.TH "__I2C_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__I2C_HandleTypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_i2c\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "I2C_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBI2C_InitTypeDef\fP \fBInit\fP"
.br
.ti -1c
.RI "uint8_t * \fBpBuffPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBXferSize\fP"
.br
.ti -1c
.RI "__IO uint16_t \fBXferCount\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBXferOptions\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBPreviousState\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmatx\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmarx\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO \fBHAL_I2C_StateTypeDef\fP \fBState\fP"
.br
.ti -1c
.RI "__IO \fBHAL_I2C_ModeTypeDef\fP \fBMode\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBErrorCode\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBDevaddress\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBMemaddress\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBMemaddSize\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBEventCount\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 stm32f4xx_hal_i2c\&.h 第 184 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "__IO uint32_t Devaddress"
I2C Target device address 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 213 行定义\&.
.SS "__IO uint32_t ErrorCode"
I2C Error code 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 211 行定义\&.
.SS "__IO uint32_t EventCount"
I2C Event counter 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 219 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmarx"
I2C Rx DMA handle parameters 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 203 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmatx"
I2C Tx DMA handle parameters 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 201 行定义\&.
.SS "\fBI2C_InitTypeDef\fP Init"
I2C communication parameters 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 188 行定义\&.
.SS "I2C_TypeDef* Instance"
I2C registers base address 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 186 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"
I2C locking object 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 205 行定义\&.
.SS "__IO uint32_t Memaddress"
I2C Target memory address 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 215 行定义\&.
.SS "__IO uint32_t MemaddSize"
I2C Target memory address size 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 217 行定义\&.
.SS "__IO \fBHAL_I2C_ModeTypeDef\fP Mode"
I2C communication mode 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 209 行定义\&.
.SS "uint8_t* pBuffPtr"
Pointer to I2C transfer buffer 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 190 行定义\&.
.SS "__IO uint32_t PreviousState"
I2C communication Previous state and mode context for internal usage 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 198 行定义\&.
.SS "__IO \fBHAL_I2C_StateTypeDef\fP State"
I2C communication state 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 207 行定义\&.
.SS "__IO uint16_t XferCount"
I2C transfer counter 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 194 行定义\&.
.SS "__IO uint32_t XferOptions"
I2C transfer options 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 196 行定义\&.
.SS "uint16_t XferSize"
I2C transfer size 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 192 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
