.TH "__SMARTCARD_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__SMARTCARD_HandleTypeDef \- SMARTCARD handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_smartcard\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "USART_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBSMARTCARD_InitTypeDef\fP \fBInit\fP"
.br
.ti -1c
.RI "uint8_t * \fBpTxBuffPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBTxXferSize\fP"
.br
.ti -1c
.RI "__IO uint16_t \fBTxXferCount\fP"
.br
.ti -1c
.RI "uint8_t * \fBpRxBuffPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBRxXferSize\fP"
.br
.ti -1c
.RI "__IO uint16_t \fBRxXferCount\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmatx\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmarx\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO \fBHAL_SMARTCARD_StateTypeDef\fP \fBgState\fP"
.br
.ti -1c
.RI "__IO \fBHAL_SMARTCARD_StateTypeDef\fP \fBRxState\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBErrorCode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
SMARTCARD handle Structure definition 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 154 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "__IO uint32_t ErrorCode"
SmartCard Error code 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 185 行定义\&.
.SS "__IO \fBHAL_SMARTCARD_StateTypeDef\fP gState"
SmartCard state information related to global Handle management and also related to Tx operations\&. This parameter can be a value of \fBHAL_SMARTCARD_StateTypeDef\fP 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 178 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmarx"
SmartCard Rx DMA Handle parameters 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 174 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmatx"
SmartCard Tx DMA Handle parameters 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 172 行定义\&.
.SS "\fBSMARTCARD_InitTypeDef\fP Init"
SmartCard communication parameters 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 158 行定义\&.
.SS "USART_TypeDef* Instance"
USART registers base address 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 156 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"
Locking object 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 176 行定义\&.
.SS "uint8_t* pRxBuffPtr"
Pointer to SmartCard Rx transfer Buffer 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 166 行定义\&.
.SS "uint8_t* pTxBuffPtr"
Pointer to SmartCard Tx transfer Buffer 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 160 行定义\&.
.SS "__IO \fBHAL_SMARTCARD_StateTypeDef\fP RxState"
SmartCard state information related to Rx operations\&. This parameter can be a value of \fBHAL_SMARTCARD_StateTypeDef\fP 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 182 行定义\&.
.SS "__IO uint16_t RxXferCount"
SmartCard Rx Transfer Counter 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 170 行定义\&.
.SS "uint16_t RxXferSize"
SmartCard Rx Transfer size 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 168 行定义\&.
.SS "__IO uint16_t TxXferCount"
SmartCard Tx Transfer Counter 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 164 行定义\&.
.SS "uint16_t TxXferSize"
SmartCard Tx Transfer size 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 162 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
