.TH "__USART_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__USART_HandleTypeDef \- USART handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_usart\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "USART_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBUSART_InitTypeDef\fP \fBInit\fP"
.br
.ti -1c
.RI "uint8_t * \fBpTxBuffPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBTxXferSize\fP"
.br
.ti -1c
.RI "__IO uint16_t \fBTxXferCount\fP"
.br
.ti -1c
.RI "uint8_t * \fBpRxBuffPtr\fP"
.br
.ti -1c
.RI "uint16_t \fBRxXferSize\fP"
.br
.ti -1c
.RI "__IO uint16_t \fBRxXferCount\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmatx\fP"
.br
.ti -1c
.RI "\fBDMA_HandleTypeDef\fP * \fBhdmarx\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO \fBHAL_USART_StateTypeDef\fP \fBState\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBErrorCode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
USART handle Structure definition 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 99 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "__IO uint32_t ErrorCode"
USART Error code 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 125 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmarx"
Usart Rx DMA Handle parameters 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 119 行定义\&.
.SS "\fBDMA_HandleTypeDef\fP* hdmatx"
Usart Tx DMA Handle parameters 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 117 行定义\&.
.SS "\fBUSART_InitTypeDef\fP Init"
Usart communication parameters 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 103 行定义\&.
.SS "USART_TypeDef* Instance"
USART registers base address 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 101 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"
Locking object 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 121 行定义\&.
.SS "uint8_t* pRxBuffPtr"
Pointer to Usart Rx transfer Buffer 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 111 行定义\&.
.SS "uint8_t* pTxBuffPtr"
Pointer to Usart Tx transfer Buffer 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 105 行定义\&.
.SS "__IO uint16_t RxXferCount"
Usart Rx Transfer Counter 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 115 行定义\&.
.SS "uint16_t RxXferSize"
Usart Rx Transfer size 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 113 行定义\&.
.SS "__IO \fBHAL_USART_StateTypeDef\fP State"
Usart communication state 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 123 行定义\&.
.SS "__IO uint16_t TxXferCount"
Usart Tx Transfer Counter 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 109 行定义\&.
.SS "uint16_t TxXferSize"
Usart Tx Transfer size 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 107 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
