.TH "src/Legacy 目录参考" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Legacy 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBstm32f4xx_hal_can\&.c\fP"
.br
.RI "This file provides firmware functions to manage the following functionalities of the Controller Area Network (CAN) peripheral: "
.in -1c
