.TH "ADC_EOCSelection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_EOCSelection
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_EOC_SEQ_CONV\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_EOC_SINGLE_CONV\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBADC_EOC_SINGLE_SEQ_CONV\fP   0x00000002U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_EOC_SEQ_CONV   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 406 行定义\&.
.SS "#define ADC_EOC_SINGLE_CONV   0x00000001U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 407 行定义\&.
.SS "#define ADC_EOC_SINGLE_SEQ_CONV   0x00000002U"
reserved for future use 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 408 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
