.TH "ADC_AnalogWDGConfTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_AnalogWDGConfTypeDef \- ADC Configuration multi-mode structure definition 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_adc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBWatchdogMode\fP"
.br
.ti -1c
.RI "uint32_t \fBHighThreshold\fP"
.br
.ti -1c
.RI "uint32_t \fBLowThreshold\fP"
.br
.ti -1c
.RI "uint32_t \fBChannel\fP"
.br
.ti -1c
.RI "FunctionalState \fBITMode\fP"
.br
.ti -1c
.RI "uint32_t \fBWatchdogNumber\fP"
.br
.in -1c
.SH "详细描述"
.PP 
ADC Configuration multi-mode structure definition 
.br
 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 136 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Channel"
Configures ADC channel for the analog watchdog\&. This parameter has an effect only if watchdog mode is configured on single channel This parameter can be a value of \fBADC Common Channels\fP 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 144 行定义\&.
.SS "uint32_t HighThreshold"
Configures the ADC analog watchdog High threshold value\&. This parameter must be a 12-bit value\&. 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 140 行定义\&.
.SS "FunctionalState ITMode"
Specifies whether the analog watchdog is configured is interrupt mode or in polling mode\&. This parameter can be set to ENABLE or DISABLE 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 147 行定义\&.
.SS "uint32_t LowThreshold"
Configures the ADC analog watchdog High threshold value\&. This parameter must be a 12-bit value\&. 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 142 行定义\&.
.SS "uint32_t WatchdogMode"
Configures the ADC analog watchdog mode\&. This parameter can be a value of \fBADC Analog Watchdog Selection\fP 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 138 行定义\&.
.SS "uint32_t WatchdogNumber"
Reserved for future use, can be set to 0 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 150 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
