.TH "ADC_InjectionConfTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_InjectionConfTypeDef \- ADC Configuration injected Channel structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_adc_ex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBInjectedChannel\fP"
.br
.ti -1c
.RI "uint32_t \fBInjectedRank\fP"
.br
.ti -1c
.RI "uint32_t \fBInjectedSamplingTime\fP"
.br
.ti -1c
.RI "uint32_t \fBInjectedOffset\fP"
.br
.ti -1c
.RI "uint32_t \fBInjectedNbrOfConversion\fP"
.br
.ti -1c
.RI "FunctionalState \fBInjectedDiscontinuousConvMode\fP"
.br
.ti -1c
.RI "FunctionalState \fBAutoInjectedConv\fP"
.br
.ti -1c
.RI "uint32_t \fBExternalTrigInjecConv\fP"
.br
.ti -1c
.RI "uint32_t \fBExternalTrigInjecConvEdge\fP"
.br
.in -1c
.SH "详细描述"
.PP 
ADC Configuration injected Channel structure definition 


.PP
\fB注解\fP
.RS 4
Parameters of this structure are shared within 2 scopes:
.IP "\(bu" 2
Scope channel: InjectedChannel, InjectedRank, InjectedSamplingTime, InjectedOffset
.IP "\(bu" 2
Scope injected group (affects all channels of injected group): InjectedNbrOfConversion, InjectedDiscontinuousConvMode, AutoInjectedConv, ExternalTrigInjecConvEdge, ExternalTrigInjecConv\&. 
.PP
.PP
The setting of these parameters with function \fBHAL_ADCEx_InjectedConfigChannel()\fP is conditioned to ADC state\&. ADC state can be either:
.IP "\(bu" 2
For all parameters: ADC disabled
.IP "\(bu" 2
For all except parameters 'InjectedDiscontinuousConvMode' and 'AutoInjectedConv': ADC enabled without conversion on going on injected group\&.
.IP "\(bu" 2
For parameters 'ExternalTrigInjecConv' and 'ExternalTrigInjecConvEdge': ADC enabled, even with conversion on going on injected group\&. 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 56 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "FunctionalState AutoInjectedConv"
Enables or disables the selected ADC automatic injected group conversion after regular one This parameter can be set to ENABLE or DISABLE\&. 
.br
 Note: To use Automatic injected conversion, discontinuous mode must be disabled ('DiscontinuousConvMode' and 'InjectedDiscontinuousConvMode' set to DISABLE) Note: To use Automatic injected conversion, injected group external triggers must be disabled ('ExternalTrigInjecConv' set to ADC_SOFTWARE_START) Note: In case of DMA used with regular group: if DMA configured in normal mode (single shot) JAUTO will be stopped upon DMA transfer complete\&. To maintain JAUTO always enabled, DMA must be configured in circular mode\&. Caution: this setting impacts the entire injected group\&. Therefore, call of \fBHAL_ADCEx_InjectedConfigChannel()\fP to configure a channel on injected group can impact the configuration of other channels previously set\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 89 行定义\&.
.SS "uint32_t ExternalTrigInjecConv"
Selects the external event used to trigger the conversion start of injected group\&. If set to ADC_INJECTED_SOFTWARE_START, external triggers are disabled\&. If set to external trigger source, triggering is on event rising edge\&. This parameter can be a value of \fBADC External Trigger Source Injected\fP Note: This parameter must be modified when ADC is disabled (before ADC start conversion or after ADC stop conversion)\&. If ADC is enabled, this parameter setting is bypassed without error reporting (as it can be the expected behaviour in case of another parameter update on the fly) Caution: this setting impacts the entire injected group\&. Therefore, call of \fBHAL_ADCEx_InjectedConfigChannel()\fP to configure a channel on injected group can impact the configuration of other channels previously set\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 97 行定义\&.
.SS "uint32_t ExternalTrigInjecConvEdge"
Selects the external trigger edge of injected group\&. This parameter can be a value of \fBADC External Trigger Edge Injected\fP\&. If trigger is set to ADC_INJECTED_SOFTWARE_START, this parameter is discarded\&. Caution: this setting impacts the entire injected group\&. Therefore, call of \fBHAL_ADCEx_InjectedConfigChannel()\fP to configure a channel on injected group can impact the configuration of other channels previously set\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 105 行定义\&.
.SS "uint32_t InjectedChannel"
Selection of ADC channel to configure This parameter can be a value of \fBADC Common Channels\fP Note: Depending on devices, some channels may not be available on package pins\&. Refer to device datasheet for channels availability\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 58 行定义\&.
.SS "FunctionalState InjectedDiscontinuousConvMode"
Specifies whether the conversions sequence of injected group is performed in Complete-sequence/Discontinuous-sequence (main sequence subdivided in successive parts)\&. Discontinuous mode is used only if sequencer is enabled (parameter 'ScanConvMode')\&. If sequencer is disabled, this parameter is discarded\&. Discontinuous mode can be enabled only if continuous mode is disabled\&. If continuous mode is enabled, this parameter setting is discarded\&. This parameter can be set to ENABLE or DISABLE\&. Note: For injected group, number of discontinuous ranks increment is fixed to one-by-one\&. Caution: this setting impacts the entire injected group\&. Therefore, call of \fBHAL_ADCEx_InjectedConfigChannel()\fP to configure a channel on injected group can impact the configuration of other channels previously set\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 82 行定义\&.
.SS "uint32_t InjectedNbrOfConversion"
Specifies the number of ranks that will be converted within the injected group sequencer\&. To use the injected group sequencer and convert several ranks, parameter 'ScanConvMode' must be enabled\&. This parameter must be a number between Min_Data = 1 and Max_Data = 4\&. Caution: this setting impacts the entire injected group\&. Therefore, call of \fBHAL_ADCEx_InjectedConfigChannel()\fP to configure a channel on injected group can impact the configuration of other channels previously set\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 77 行定义\&.
.SS "uint32_t InjectedOffset"
Defines the offset to be subtracted from the raw converted data (for channels set on injected group only)\&. Offset value must be a positive number\&. Depending of ADC resolution selected (12, 10, 8 or 6 bits), this parameter must be a number between Min_Data = 0x000 and Max_Data = 0xFFF, 0x3FF, 0xFF or 0x3F respectively\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 73 行定义\&.
.SS "uint32_t InjectedRank"
Rank in the injected group sequencer This parameter must be a value of \fBADC Injected Rank\fP Note: In case of need to disable a channel or change order of conversion sequencer, rank containing a previous channel setting can be overwritten by the new channel setting (or parameter number of conversions can be adjusted) 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 61 行定义\&.
.SS "uint32_t InjectedSamplingTime"
Sampling time value to be set for the selected channel\&. Unit: ADC clock cycles Conversion time is the addition of sampling time and processing time (12 ADC clock cycles at ADC resolution 12 bits, 11 cycles at 10 bits, 9 cycles at 8 bits, 7 cycles at 6 bits)\&. This parameter can be a value of \fBADC Sampling Times\fP Caution: This parameter updates the parameter property of the channel, that can be used into regular and/or injected groups\&. If this same channel has been previously configured in the other group (regular/injected), it will be updated to last setting\&. Note: In case of usage of internal measurement channels (VrefInt/Vbat/TempSensor), sampling time constraints must be respected (sampling time can be adjusted in function of ADC clock frequency and sampling time setting) Refer to device datasheet for timings values, parameters TS_vrefint, TS_temp (values rough order: 4us min)\&. 
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 64 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
