.TH "ADC_flags_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_flags_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_FLAG_AWD\fP   ((uint32_t)ADC_SR_AWD)"
.br
.ti -1c
.RI "#define \fBADC_FLAG_EOC\fP   ((uint32_t)ADC_SR_EOC)"
.br
.ti -1c
.RI "#define \fBADC_FLAG_JEOC\fP   ((uint32_t)ADC_SR_JEOC)"
.br
.ti -1c
.RI "#define \fBADC_FLAG_JSTRT\fP   ((uint32_t)ADC_SR_JSTRT)"
.br
.ti -1c
.RI "#define \fBADC_FLAG_STRT\fP   ((uint32_t)ADC_SR_STRT)"
.br
.ti -1c
.RI "#define \fBADC_FLAG_OVR\fP   ((uint32_t)ADC_SR_OVR)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_FLAG_AWD   ((uint32_t)ADC_SR_AWD)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 450 行定义\&.
.SS "#define ADC_FLAG_EOC   ((uint32_t)ADC_SR_EOC)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 451 行定义\&.
.SS "#define ADC_FLAG_JEOC   ((uint32_t)ADC_SR_JEOC)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 452 行定义\&.
.SS "#define ADC_FLAG_JSTRT   ((uint32_t)ADC_SR_JSTRT)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 453 行定义\&.
.SS "#define ADC_FLAG_OVR   ((uint32_t)ADC_SR_OVR)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 455 行定义\&.
.SS "#define ADC_FLAG_STRT   ((uint32_t)ADC_SR_STRT)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 454 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
