.TH "ADC_interrupts_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_interrupts_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_IT_EOC\fP   ((uint32_t)ADC_CR1_EOCIE)"
.br
.ti -1c
.RI "#define \fBADC_IT_AWD\fP   ((uint32_t)ADC_CR1_AWDIE)"
.br
.ti -1c
.RI "#define \fBADC_IT_JEOC\fP   ((uint32_t)ADC_CR1_JEOCIE)"
.br
.ti -1c
.RI "#define \fBADC_IT_OVR\fP   ((uint32_t)ADC_CR1_OVRIE)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_IT_AWD   ((uint32_t)ADC_CR1_AWDIE)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 440 行定义\&.
.SS "#define ADC_IT_EOC   ((uint32_t)ADC_CR1_EOCIE)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 439 行定义\&.
.SS "#define ADC_IT_JEOC   ((uint32_t)ADC_CR1_JEOCIE)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 441 行定义\&.
.SS "#define ADC_IT_OVR   ((uint32_t)ADC_CR1_OVRIE)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 442 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
