.TH "ADC_External_trigger_edge_Regular" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_External_trigger_edge_Regular
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONVEDGE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONVEDGE_RISING\fP   ((uint32_t)ADC_CR2_EXTEN_0)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONVEDGE_FALLING\fP   ((uint32_t)ADC_CR2_EXTEN_1)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONVEDGE_RISINGFALLING\fP   ((uint32_t)ADC_CR2_EXTEN)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_EXTERNALTRIGCONVEDGE_FALLING   ((uint32_t)ADC_CR2_EXTEN_1)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 318 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONVEDGE_NONE   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 316 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONVEDGE_RISING   ((uint32_t)ADC_CR2_EXTEN_0)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 317 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING   ((uint32_t)ADC_CR2_EXTEN)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 319 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
