.TH "ADC_External_trigger_Source_Regular" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_External_trigger_Source_Regular
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T1_CC1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T1_CC2\fP   ((uint32_t)ADC_CR2_EXTSEL_0)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T1_CC3\fP   ((uint32_t)ADC_CR2_EXTSEL_1)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T2_CC2\fP   ((uint32_t)(ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T2_CC3\fP   ((uint32_t)ADC_CR2_EXTSEL_2)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T2_CC4\fP   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T2_TRGO\fP   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T3_CC1\fP   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T3_TRGO\fP   ((uint32_t)ADC_CR2_EXTSEL_3)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T4_CC4\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T5_CC1\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_1))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T5_CC2\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T5_CC3\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T8_CC1\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_0))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_T8_TRGO\fP   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1))"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGCONV_Ext_IT11\fP   ((uint32_t)ADC_CR2_EXTSEL)"
.br
.ti -1c
.RI "#define \fBADC_SOFTWARE_START\fP   ((uint32_t)ADC_CR2_EXTSEL + 1U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_EXTERNALTRIGCONV_Ext_IT11   ((uint32_t)ADC_CR2_EXTSEL)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 344 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T1_CC1   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 329 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T1_CC2   ((uint32_t)ADC_CR2_EXTSEL_0)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 330 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T1_CC3   ((uint32_t)ADC_CR2_EXTSEL_1)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 331 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T2_CC2   ((uint32_t)(ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 332 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T2_CC3   ((uint32_t)ADC_CR2_EXTSEL_2)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 333 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T2_CC4   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 334 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T2_TRGO   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 335 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T3_CC1   ((uint32_t)(ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 336 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T3_TRGO   ((uint32_t)ADC_CR2_EXTSEL_3)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 337 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T4_CC4   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 338 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T5_CC1   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 339 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T5_CC2   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 340 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T5_CC3   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 341 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T8_CC1   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 342 行定义\&.
.SS "#define ADC_EXTERNALTRIGCONV_T8_TRGO   ((uint32_t)(ADC_CR2_EXTSEL_3 | ADC_CR2_EXTSEL_2 | ADC_CR2_EXTSEL_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 343 行定义\&.
.SS "#define ADC_SOFTWARE_START   ((uint32_t)ADC_CR2_EXTSEL + 1U)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 345 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
