.TH "ADC_sampling_times" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_sampling_times
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_SAMPLETIME_3CYCLES\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_15CYCLES\fP   ((uint32_t)ADC_SMPR1_SMP10_0)"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_28CYCLES\fP   ((uint32_t)ADC_SMPR1_SMP10_1)"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_56CYCLES\fP   ((uint32_t)(ADC_SMPR1_SMP10_1 | ADC_SMPR1_SMP10_0))"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_84CYCLES\fP   ((uint32_t)ADC_SMPR1_SMP10_2)"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_112CYCLES\fP   ((uint32_t)(ADC_SMPR1_SMP10_2 | ADC_SMPR1_SMP10_0))"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_144CYCLES\fP   ((uint32_t)(ADC_SMPR1_SMP10_2 | ADC_SMPR1_SMP10_1))"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_480CYCLES\fP   ((uint32_t)ADC_SMPR1_SMP10)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_SAMPLETIME_112CYCLES   ((uint32_t)(ADC_SMPR1_SMP10_2 | ADC_SMPR1_SMP10_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 396 行定义\&.
.SS "#define ADC_SAMPLETIME_144CYCLES   ((uint32_t)(ADC_SMPR1_SMP10_2 | ADC_SMPR1_SMP10_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 397 行定义\&.
.SS "#define ADC_SAMPLETIME_15CYCLES   ((uint32_t)ADC_SMPR1_SMP10_0)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 392 行定义\&.
.SS "#define ADC_SAMPLETIME_28CYCLES   ((uint32_t)ADC_SMPR1_SMP10_1)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 393 行定义\&.
.SS "#define ADC_SAMPLETIME_3CYCLES   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 391 行定义\&.
.SS "#define ADC_SAMPLETIME_480CYCLES   ((uint32_t)ADC_SMPR1_SMP10)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 398 行定义\&.
.SS "#define ADC_SAMPLETIME_56CYCLES   ((uint32_t)(ADC_SMPR1_SMP10_1 | ADC_SMPR1_SMP10_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 394 行定义\&.
.SS "#define ADC_SAMPLETIME_84CYCLES   ((uint32_t)ADC_SMPR1_SMP10_2)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 395 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
