.TH "ADC_Exported_Functions_Group4" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Exported_Functions_Group4
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "uint32_t \fBHAL_ADC_GetState\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_ADC_GetError\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_ADC_GetError (\fBADC_HandleTypeDef\fP * hadc)"

.SS "uint32_t HAL_ADC_GetState (\fBADC_HandleTypeDef\fP * hadc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
