.TH "ADC_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBADC_InitTypeDef\fP"
.br
.RI "Structure definition of ADC and regular group initialization "
.ti -1c
.RI "struct \fBADC_ChannelConfTypeDef\fP"
.br
.RI "Structure definition of ADC channel for regular group 
.br
 "
.ti -1c
.RI "struct \fBADC_AnalogWDGConfTypeDef\fP"
.br
.RI "ADC Configuration multi-mode structure definition 
.br
 "
.ti -1c
.RI "struct \fBADC_HandleTypeDef\fP"
.br
.RI "ADC handle Structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_ADC_STATE_RESET\fP   0x00000000U"
.br
.RI "HAL ADC state machine: ADC states definition (bitfields) "
.ti -1c
.RI "#define \fBHAL_ADC_STATE_READY\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY_INTERNAL\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_TIMEOUT\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_ERROR_INTERNAL\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_ERROR_CONFIG\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_ERROR_DMA\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_REG_BUSY\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_REG_EOC\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_REG_OVR\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_INJ_BUSY\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_INJ_EOC\fP   0x00002000U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_AWD1\fP   0x00010000U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_AWD2\fP   0x00020000U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_AWD3\fP   0x00040000U"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_MULTIMODE_SLAVE\fP   0x00100000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_ADC_STATE_AWD1   0x00010000U"
Out-of-window occurrence of analog watchdog 1 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 180 行定义\&.
.SS "#define HAL_ADC_STATE_AWD2   0x00020000U"
Not available on STM32F4 device: Out-of-window occurrence of analog watchdog 2 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 181 行定义\&.
.SS "#define HAL_ADC_STATE_AWD3   0x00040000U"
Not available on STM32F4 device: Out-of-window occurrence of analog watchdog 3 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 182 行定义\&.
.SS "#define HAL_ADC_STATE_BUSY_INTERNAL   0x00000002U"
ADC is busy to internal process (initialization, calibration) 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 160 行定义\&.
.SS "#define HAL_ADC_STATE_ERROR_CONFIG   0x00000020U"
Configuration error occurrence 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 165 行定义\&.
.SS "#define HAL_ADC_STATE_ERROR_DMA   0x00000040U"
DMA error occurrence 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 166 行定义\&.
.SS "#define HAL_ADC_STATE_ERROR_INTERNAL   0x00000010U"
Internal error occurrence 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 164 行定义\&.
.SS "#define HAL_ADC_STATE_INJ_BUSY   0x00001000U"
A conversion on group injected is ongoing or can occur (either by auto-injection mode, external trigger, low power auto power-on (if feature available), multimode ADC master control (if feature available)) 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 176 行定义\&.
.SS "#define HAL_ADC_STATE_INJ_EOC   0x00002000U"
Conversion data available on group injected 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 177 行定义\&.
.SS "#define HAL_ADC_STATE_MULTIMODE_SLAVE   0x00100000U"
Not available on STM32F4 device: ADC in multimode slave state, controlled by another ADC master ( 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 185 行定义\&.
.SS "#define HAL_ADC_STATE_READY   0x00000001U"
ADC peripheral ready for use 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 159 行定义\&.
.SS "#define HAL_ADC_STATE_REG_BUSY   0x00000100U"
A conversion on group regular is ongoing or can occur (either by continuous mode, external trigger, low power auto power-on (if feature available), multimode ADC master control (if feature available)) 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 170 行定义\&.
.SS "#define HAL_ADC_STATE_REG_EOC   0x00000200U"
Conversion data available on group regular 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 171 行定义\&.
.SS "#define HAL_ADC_STATE_REG_OVR   0x00000400U"
Overrun occurrence 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 172 行定义\&.
.SS "#define HAL_ADC_STATE_RESET   0x00000000U"

.PP
HAL ADC state machine: ADC states definition (bitfields) ADC not yet initialized or disabled 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 158 行定义\&.
.SS "#define HAL_ADC_STATE_TIMEOUT   0x00000004U"
TimeOut occurrence 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 161 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
