.TH "ADC_delay_between_2_sampling_phases" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_delay_between_2_sampling_phases
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_5CYCLES\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_6CYCLES\fP   ((uint32_t)ADC_CCR_DELAY_0)"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_7CYCLES\fP   ((uint32_t)ADC_CCR_DELAY_1)"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_8CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_9CYCLES\fP   ((uint32_t)ADC_CCR_DELAY_2)"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_10CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_11CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_12CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_13CYCLES\fP   ((uint32_t)ADC_CCR_DELAY_3)"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_14CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_15CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_1))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_16CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_17CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_18CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2 | ADC_CCR_DELAY_0))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_19CYCLES\fP   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1))"
.br
.ti -1c
.RI "#define \fBADC_TWOSAMPLINGDELAY_20CYCLES\fP   ((uint32_t)ADC_CCR_DELAY)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_TWOSAMPLINGDELAY_10CYCLES   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 287 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_11CYCLES   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 288 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_12CYCLES   ((uint32_t)(ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 289 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_13CYCLES   ((uint32_t)ADC_CCR_DELAY_3)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 290 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_14CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 291 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_15CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 292 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_16CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 293 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_17CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 294 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_18CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 295 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_19CYCLES   ((uint32_t)(ADC_CCR_DELAY_3 | ADC_CCR_DELAY_2 | ADC_CCR_DELAY_1))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 296 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_20CYCLES   ((uint32_t)ADC_CCR_DELAY)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 297 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_5CYCLES   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 282 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_6CYCLES   ((uint32_t)ADC_CCR_DELAY_0)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 283 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_7CYCLES   ((uint32_t)ADC_CCR_DELAY_1)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 284 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_8CYCLES   ((uint32_t)(ADC_CCR_DELAY_1 | ADC_CCR_DELAY_0))"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 285 行定义\&.
.SS "#define ADC_TWOSAMPLINGDELAY_9CYCLES   ((uint32_t)ADC_CCR_DELAY_2)"

.PP
在文件 stm32f4xx_hal_adc\&.h 第 286 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
