.TH "ADC_ChannelConfTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_ChannelConfTypeDef \- Structure definition of ADC channel for regular group 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_adc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBChannel\fP"
.br
.ti -1c
.RI "uint32_t \fBRank\fP"
.br
.ti -1c
.RI "uint32_t \fBSamplingTime\fP"
.br
.ti -1c
.RI "uint32_t \fBOffset\fP"
.br
.in -1c
.SH "详细描述"
.PP 
Structure definition of ADC channel for regular group 
.br
 


.PP
\fB注解\fP
.RS 4
The setting of these parameters with function \fBHAL_ADC_ConfigChannel()\fP is conditioned to ADC state\&. ADC can be either disabled or enabled without conversion on going on regular group\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_adc\&.h 第 115 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Channel"
Specifies the channel to configure into ADC regular group\&. This parameter can be a value of \fBADC Common Channels\fP 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 117 行定义\&.
.SS "uint32_t Offset"
Reserved for future use, can be set to 0 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 130 行定义\&.
.SS "uint32_t Rank"
Specifies the rank in the regular group sequencer\&. This parameter must be a number between Min_Data = 1 and Max_Data = 16 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 119 行定义\&.
.SS "uint32_t SamplingTime"
Sampling time value to be set for the selected channel\&. Unit: ADC clock cycles Conversion time is the addition of sampling time and processing time (12 ADC clock cycles at ADC resolution 12 bits, 11 cycles at 10 bits, 9 cycles at 8 bits, 7 cycles at 6 bits)\&. This parameter can be a value of \fBADC Sampling Times\fP Caution: This parameter updates the parameter property of the channel, that can be used into regular and/or injected groups\&. If this same channel has been previously configured in the other group (regular/injected), it will be updated to last setting\&. Note: In case of usage of internal measurement channels (VrefInt/Vbat/TempSensor), sampling time constraints must be respected (sampling time can be adjusted in function of ADC clock frequency and sampling time setting) Refer to device datasheet for timings values, parameters TS_vrefint, TS_temp (values rough order: 4us min)\&. 
.PP
在文件 stm32f4xx_hal_adc\&.h 第 121 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
