.TH "ADC_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBADC Error Code\fP"
.br
.ti -1c
.RI "\fBADC Clock Prescaler\fP"
.br
.ti -1c
.RI "\fBADC Delay Between 2 Sampling Phases\fP"
.br
.ti -1c
.RI "\fBADC Resolution\fP"
.br
.ti -1c
.RI "\fBADC External Trigger Edge Regular\fP"
.br
.ti -1c
.RI "\fBADC External Trigger Source Regular\fP"
.br
.ti -1c
.RI "\fBADC Data Align\fP"
.br
.ti -1c
.RI "\fBADC Common Channels\fP"
.br
.ti -1c
.RI "\fBADC Sampling Times\fP"
.br
.ti -1c
.RI "\fBADC EOC Selection\fP"
.br
.ti -1c
.RI "\fBADC Event Type\fP"
.br
.ti -1c
.RI "\fBADC Analog Watchdog Selection\fP"
.br
.ti -1c
.RI "\fBADC Interrupts Definition\fP"
.br
.ti -1c
.RI "\fBADC Flags Definition\fP"
.br
.ti -1c
.RI "\fBADC Channels Type\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
