.TH "ADCEx_External_trigger_edge_Injected" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_External_trigger_edge_Injected
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGINJECCONVEDGE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGINJECCONVEDGE_RISING\fP   ((uint32_t)ADC_CR2_JEXTEN_0)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGINJECCONVEDGE_FALLING\fP   ((uint32_t)ADC_CR2_JEXTEN_1)"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIGINJECCONVEDGE_RISINGFALLING\fP   ((uint32_t)ADC_CR2_JEXTEN)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_EXTERNALTRIGINJECCONVEDGE_FALLING   ((uint32_t)ADC_CR2_JEXTEN_1)"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 171 行定义\&.
.SS "#define ADC_EXTERNALTRIGINJECCONVEDGE_NONE   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 169 行定义\&.
.SS "#define ADC_EXTERNALTRIGINJECCONVEDGE_RISING   ((uint32_t)ADC_CR2_JEXTEN_0)"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 170 行定义\&.
.SS "#define ADC_EXTERNALTRIGINJECCONVEDGE_RISINGFALLING   ((uint32_t)ADC_CR2_JEXTEN)"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 172 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
