.TH "ADCEx" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx \- ADC Extended driver modules  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBADC Exported Types\fP"
.br
.ti -1c
.RI "\fBADC Exported Constants\fP"
.br
.ti -1c
.RI "\fBADC Exported Macros\fP"
.br
.ti -1c
.RI "\fBADC Private Constants\fP"
.br
.ti -1c
.RI "\fBADC Private Macros\fP"
.br
.ti -1c
.RI "\fBADC Private Functions\fP"
.br
.ti -1c
.RI "\fBADCEx_Exported_Functions\fP"
.br
.in -1c
.SH "详细描述"
.PP 
ADC Extended driver modules 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
