.TH "ADCEx_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBADC Common Mode\fP"
.br
.ti -1c
.RI "\fBADC Direct Memory Access Mode For Multi Mode\fP"
.br
.ti -1c
.RI "\fBADC External Trigger Edge Injected\fP"
.br
.ti -1c
.RI "\fBADC External Trigger Source Injected\fP"
.br
.ti -1c
.RI "\fBADC Injected Rank\fP"
.br
.ti -1c
.RI "\fBADC Specific Channels\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
