.TH "ADCEx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedStart\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedStop\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedPollForConversion\fP (\fBADC_HandleTypeDef\fP *hadc, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedStart_IT\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedStop_IT\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_ADCEx_InjectedGetValue\fP (\fBADC_HandleTypeDef\fP *hadc, uint32_t InjectedRank)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_MultiModeStart_DMA\fP (\fBADC_HandleTypeDef\fP *hadc, uint32_t *pData, uint32_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_MultiModeStop_DMA\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_ADCEx_MultiModeGetValue\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "void \fBHAL_ADCEx_InjectedConvCpltCallback\fP (\fBADC_HandleTypeDef\fP *hadc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_InjectedConfigChannel\fP (\fBADC_HandleTypeDef\fP *hadc, \fBADC_InjectionConfTypeDef\fP *sConfigInjected)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_ADCEx_MultiModeConfigChannel\fP (\fBADC_HandleTypeDef\fP *hadc, \fBADC_MultiModeTypeDef\fP *multimode)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedConfigChannel (\fBADC_HandleTypeDef\fP * hadc, \fBADC_InjectionConfTypeDef\fP * sConfigInjected)"

.SS "void HAL_ADCEx_InjectedConvCpltCallback (\fBADC_HandleTypeDef\fP * hadc)"

.SS "uint32_t HAL_ADCEx_InjectedGetValue (\fBADC_HandleTypeDef\fP * hadc, uint32_t InjectedRank)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedPollForConversion (\fBADC_HandleTypeDef\fP * hadc, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedStart (\fBADC_HandleTypeDef\fP * hadc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedStart_IT (\fBADC_HandleTypeDef\fP * hadc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedStop (\fBADC_HandleTypeDef\fP * hadc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_InjectedStop_IT (\fBADC_HandleTypeDef\fP * hadc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_MultiModeConfigChannel (\fBADC_HandleTypeDef\fP * hadc, \fBADC_MultiModeTypeDef\fP * multimode)"

.SS "uint32_t HAL_ADCEx_MultiModeGetValue (\fBADC_HandleTypeDef\fP * hadc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_MultiModeStart_DMA (\fBADC_HandleTypeDef\fP * hadc, uint32_t * pData, uint32_t Length)"

.SS "\fBHAL_StatusTypeDef\fP HAL_ADCEx_MultiModeStop_DMA (\fBADC_HandleTypeDef\fP * hadc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
