.TH "ADCEx_Common_mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_Common_mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_MODE_INDEPENDENT\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_REGSIMULT_INJECSIMULT\fP   ((uint32_t)ADC_CCR_MULTI_0)"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_REGSIMULT_ALTERTRIG\fP   ((uint32_t)ADC_CCR_MULTI_1)"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_INJECSIMULT\fP   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_REGSIMULT\fP   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1))"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_INTERL\fP   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_DUALMODE_ALTERTRIG\fP   ((uint32_t)(ADC_CCR_MULTI_3 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_REGSIMULT_INJECSIMULT\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_REGSIMULT_AlterTrig\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_1))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_INJECSIMULT\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_REGSIMULT\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_INTERL\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1 | ADC_CCR_MULTI_0))"
.br
.ti -1c
.RI "#define \fBADC_TRIPLEMODE_ALTERTRIG\fP   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_3 | ADC_CCR_MULTI_0))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_DUALMODE_ALTERTRIG   ((uint32_t)(ADC_CCR_MULTI_3 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 144 行定义\&.
.SS "#define ADC_DUALMODE_INJECSIMULT   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 141 行定义\&.
.SS "#define ADC_DUALMODE_INTERL   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 143 行定义\&.
.SS "#define ADC_DUALMODE_REGSIMULT   ((uint32_t)(ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 142 行定义\&.
.SS "#define ADC_DUALMODE_REGSIMULT_ALTERTRIG   ((uint32_t)ADC_CCR_MULTI_1)"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 140 行定义\&.
.SS "#define ADC_DUALMODE_REGSIMULT_INJECSIMULT   ((uint32_t)ADC_CCR_MULTI_0)"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 139 行定义\&.
.SS "#define ADC_MODE_INDEPENDENT   0x00000000U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 138 行定义\&.
.SS "#define ADC_TRIPLEMODE_ALTERTRIG   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_3 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 150 行定义\&.
.SS "#define ADC_TRIPLEMODE_INJECSIMULT   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 147 行定义\&.
.SS "#define ADC_TRIPLEMODE_INTERL   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 149 行定义\&.
.SS "#define ADC_TRIPLEMODE_REGSIMULT   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_2 | ADC_CCR_MULTI_1))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 148 行定义\&.
.SS "#define ADC_TRIPLEMODE_REGSIMULT_AlterTrig   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_1))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 146 行定义\&.
.SS "#define ADC_TRIPLEMODE_REGSIMULT_INJECSIMULT   ((uint32_t)(ADC_CCR_MULTI_4 | ADC_CCR_MULTI_0))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 145 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
