.TH "ADCEx_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_ADC_MODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_ADC_DMA_ACCESS_MODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_ADC_EXT_INJEC_TRIG_EDGE\fP(EDGE)"
.br
.ti -1c
.RI "#define \fBIS_ADC_EXT_INJEC_TRIG\fP(INJTRIG)"
.br
.ti -1c
.RI "#define \fBIS_ADC_INJECTED_LENGTH\fP(LENGTH)   (((LENGTH) >= 1U) && ((LENGTH) <= 4U))"
.br
.ti -1c
.RI "#define \fBIS_ADC_INJECTED_RANK\fP(RANK)   (((RANK) >= 1U) && ((RANK) <= 4U))"
.br
.ti -1c
.RI "#define \fBADC_JSQR\fP(_CHANNELNB_,  _RANKNB_,  _JSQR_JL_)   (((uint32_t)((uint16_t)(_CHANNELNB_))) << (5U * (uint8_t)(((_RANKNB_) + 3U) \- (_JSQR_JL_))))"
.br
.RI "Set the selected injected Channel rank\&. "
.ti -1c
.RI "#define \fBADC_COMMON_REGISTER\fP(__HANDLE__)   ADC1_COMMON"
.br
.RI "Defines if the selected ADC is within ADC common register ADC123 or ADC1 if available (ADC2, ADC3 availability depends on STM32 product) "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_COMMON_REGISTER(__HANDLE__)   ADC1_COMMON"

.PP
Defines if the selected ADC is within ADC common register ADC123 or ADC1 if available (ADC2, ADC3 availability depends on STM32 product) 
.PP
\fB参数\fP
.RS 4
\fI<strong>HANDLE</strong>\fP ADC handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fICommon\fP control register ADC123 or ADC1 
.RE
.PP

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 379 行定义\&.
.SS "#define ADC_JSQR(_CHANNELNB_, _RANKNB_, _JSQR_JL_)   (((uint32_t)((uint16_t)(_CHANNELNB_))) << (5U * (uint8_t)(((_RANKNB_) + 3U) \- (_JSQR_JL_))))"

.PP
Set the selected injected Channel rank\&. 
.PP
\fB参数\fP
.RS 4
\fI<em>CHANNELNB</em>\fP Channel number\&. 
.br
\fI<em>RANKNB</em>\fP Rank number\&. 
.br
\fI<em>JSQR_JL</em>\fP Sequence length\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 368 行定义\&.
.SS "#define IS_ADC_DMA_ACCESS_MODE(MODE)"
\fB值:\fP
.PP
.nf
                                      (((MODE) == ADC_DMAACCESSMODE_DISABLED) || \
                                      ((MODE) == ADC_DMAACCESSMODE_1)        || \
                                      ((MODE) == ADC_DMAACCESSMODE_2)        || \
                                      ((MODE) == ADC_DMAACCESSMODE_3))
.fi
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 333 行定义\&.
.SS "#define IS_ADC_EXT_INJEC_TRIG(INJTRIG)"
\fB值:\fP
.PP
.nf
                                        (((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T1_CC4)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T1_TRGO) || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T2_CC1)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T2_TRGO) || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T3_CC2)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T3_CC4)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T4_CC1)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T4_CC2)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T4_CC3)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T4_TRGO) || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T5_CC4)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T5_TRGO) || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T8_CC2)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T8_CC3)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_T8_CC4)  || \
                                        ((INJTRIG) == ADC_EXTERNALTRIGINJECCONV_EXT_IT15)|| \
                                        ((INJTRIG) == ADC_INJECTED_SOFTWARE_START))
.fi
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 341 行定义\&.
.SS "#define IS_ADC_EXT_INJEC_TRIG_EDGE(EDGE)"
\fB值:\fP
.PP
.nf
                                          (((EDGE) == ADC_EXTERNALTRIGINJECCONVEDGE_NONE)    || \
                                          ((EDGE) == ADC_EXTERNALTRIGINJECCONVEDGE_RISING)  || \
                                          ((EDGE) == ADC_EXTERNALTRIGINJECCONVEDGE_FALLING) || \
                                          ((EDGE) == ADC_EXTERNALTRIGINJECCONVEDGE_RISINGFALLING))
.fi
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 337 行定义\&.
.SS "#define IS_ADC_INJECTED_LENGTH(LENGTH)   (((LENGTH) >= 1U) && ((LENGTH) <= 4U))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 358 行定义\&.
.SS "#define IS_ADC_INJECTED_RANK(RANK)   (((RANK) >= 1U) && ((RANK) <= 4U))"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 359 行定义\&.
.SS "#define IS_ADC_MODE(MODE)"
\fB值:\fP
.PP
.nf
                           (((MODE) == ADC_MODE_INDEPENDENT)                 || \
                           ((MODE) == ADC_DUALMODE_REGSIMULT_INJECSIMULT)   || \
                           ((MODE) == ADC_DUALMODE_REGSIMULT_ALTERTRIG)     || \
                           ((MODE) == ADC_DUALMODE_INJECSIMULT)             || \
                           ((MODE) == ADC_DUALMODE_REGSIMULT)               || \
                           ((MODE) == ADC_DUALMODE_INTERL)                  || \
                           ((MODE) == ADC_DUALMODE_ALTERTRIG)               || \
                           ((MODE) == ADC_TRIPLEMODE_REGSIMULT_INJECSIMULT) || \
                           ((MODE) == ADC_TRIPLEMODE_REGSIMULT_AlterTrig)   || \
                           ((MODE) == ADC_TRIPLEMODE_INJECSIMULT)           || \
                           ((MODE) == ADC_TRIPLEMODE_REGSIMULT)             || \
                           ((MODE) == ADC_TRIPLEMODE_INTERL)                || \
                           ((MODE) == ADC_TRIPLEMODE_ALTERTRIG))
.fi
.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 320 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
