.TH "ADCEx_injected_rank" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADCEx_injected_rank
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_INJECTED_RANK_1\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBADC_INJECTED_RANK_2\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBADC_INJECTED_RANK_3\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBADC_INJECTED_RANK_4\fP   0x00000004U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_INJECTED_RANK_1   0x00000001U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 204 行定义\&.
.SS "#define ADC_INJECTED_RANK_2   0x00000002U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 205 行定义\&.
.SS "#define ADC_INJECTED_RANK_3   0x00000003U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 206 行定义\&.
.SS "#define ADC_INJECTED_RANK_4   0x00000004U"

.PP
在文件 stm32f4xx_hal_adc_ex\&.h 第 207 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
