.TH "Blocking_mode_Polling" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blocking_mode_Polling
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMBUS_IsDeviceReady\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus, uint16_t DevAddress, uint32_t Trials, uint32_t Timeout)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_SMBUS_IsDeviceReady (\fBSMBUS_HandleTypeDef\fP * hsmbus, uint16_t DevAddress, uint32_t Trials, uint32_t Timeout)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
