.TH "CORTEX_LL_EF_MCU_INFO" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_EF_MCU_INFO
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_CPUID_GetImplementer\fP (void)"
.br
.RI "Get Implementer code @rmtoll SCB_CPUID IMPLEMENTER LL_CPUID_GetImplementer "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_CPUID_GetVariant\fP (void)"
.br
.RI "Get Variant number (The r value in the rnpn product revision identifier) @rmtoll SCB_CPUID VARIANT LL_CPUID_GetVariant "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_CPUID_GetConstant\fP (void)"
.br
.RI "Get Constant number @rmtoll SCB_CPUID ARCHITECTURE LL_CPUID_GetConstant "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_CPUID_GetParNo\fP (void)"
.br
.RI "Get Part number @rmtoll SCB_CPUID PARTNO LL_CPUID_GetParNo "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_CPUID_GetRevision\fP (void)"
.br
.RI "Get Revision number (The p value in the rnpn product revision identifier, indicates patch release) @rmtoll SCB_CPUID REVISION LL_CPUID_GetRevision "
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "__STATIC_INLINE uint32_t LL_CPUID_GetConstant (void)"

.PP
Get Constant number @rmtoll SCB_CPUID ARCHITECTURE LL_CPUID_GetConstant 
.PP
\fB返回值\fP
.RS 4
\fIValue\fP should be equal to 0xF for Cortex-M4 devices 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 447 行定义\&.
.SS "__STATIC_INLINE uint32_t LL_CPUID_GetImplementer (void)"

.PP
Get Implementer code @rmtoll SCB_CPUID IMPLEMENTER LL_CPUID_GetImplementer 
.PP
\fB返回值\fP
.RS 4
\fIValue\fP should be equal to 0x41 for ARM 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 427 行定义\&.
.SS "__STATIC_INLINE uint32_t LL_CPUID_GetParNo (void)"

.PP
Get Part number @rmtoll SCB_CPUID PARTNO LL_CPUID_GetParNo 
.PP
\fB返回值\fP
.RS 4
\fIValue\fP should be equal to 0xC24 for Cortex-M4 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 457 行定义\&.
.SS "__STATIC_INLINE uint32_t LL_CPUID_GetRevision (void)"

.PP
Get Revision number (The p value in the rnpn product revision identifier, indicates patch release) @rmtoll SCB_CPUID REVISION LL_CPUID_GetRevision 
.PP
\fB返回值\fP
.RS 4
\fIValue\fP between 0 and 255 (0x1: patch 1) 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 467 行定义\&.
.SS "__STATIC_INLINE uint32_t LL_CPUID_GetVariant (void)"

.PP
Get Variant number (The r value in the rnpn product revision identifier) @rmtoll SCB_CPUID VARIANT LL_CPUID_GetVariant 
.PP
\fB返回值\fP
.RS 4
\fIValue\fP between 0 and 255 (0x0: revision 0) 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 437 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
