.TH "CORTEX_LL_EC_CLKSOURCE_HCLK" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_EC_CLKSOURCE_HCLK
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLL_SYSTICK_CLKSOURCE_HCLK_DIV8\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBLL_SYSTICK_CLKSOURCE_HCLK\fP   SysTick_CTRL_CLKSOURCE_Msk"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define LL_SYSTICK_CLKSOURCE_HCLK   SysTick_CTRL_CLKSOURCE_Msk"
AHB clock selected as SysTick clock source\&. 
.PP
在文件 stm32f4xx_ll_cortex\&.h 第 73 行定义\&.
.SS "#define LL_SYSTICK_CLKSOURCE_HCLK_DIV8   0x00000000U"
AHB clock divided by 8 selected as SysTick clock source\&. 
.PP
在文件 stm32f4xx_ll_cortex\&.h 第 72 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
