.TH "CORTEX_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_NVIC_PRIORITY_GROUP\fP(GROUP)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_PREEMPTION_PRIORITY\fP(PRIORITY)   ((PRIORITY) < 0x10U)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_SUB_PRIORITY\fP(PRIORITY)   ((PRIORITY) < 0x10U)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_DEVICE_IRQ\fP(IRQ)   ((IRQ) >= (IRQn_Type)0x00U)"
.br
.ti -1c
.RI "#define \fBIS_SYSTICK_CLK_SOURCE\fP(SOURCE)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_NVIC_DEVICE_IRQ(IRQ)   ((IRQ) >= (IRQn_Type)0x00U)"

.PP
在文件 stm32f4xx_hal_cortex\&.h 第 317 行定义\&.
.SS "#define IS_NVIC_PREEMPTION_PRIORITY(PRIORITY)   ((PRIORITY) < 0x10U)"

.PP
在文件 stm32f4xx_hal_cortex\&.h 第 313 行定义\&.
.SS "#define IS_NVIC_PRIORITY_GROUP(GROUP)"
\fB值:\fP
.PP
.nf
                                       (((GROUP) == NVIC_PRIORITYGROUP_0) || \
                                       ((GROUP) == NVIC_PRIORITYGROUP_1) || \
                                       ((GROUP) == NVIC_PRIORITYGROUP_2) || \
                                       ((GROUP) == NVIC_PRIORITYGROUP_3) || \
                                       ((GROUP) == NVIC_PRIORITYGROUP_4))
.fi
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 307 行定义\&.
.SS "#define IS_NVIC_SUB_PRIORITY(PRIORITY)   ((PRIORITY) < 0x10U)"

.PP
在文件 stm32f4xx_hal_cortex\&.h 第 315 行定义\&.
.SS "#define IS_SYSTICK_CLK_SOURCE(SOURCE)"
\fB值:\fP
.PP
.nf
                                       (((SOURCE) == SYSTICK_CLKSOURCE_HCLK) || \
                                       ((SOURCE) == SYSTICK_CLKSOURCE_HCLK_DIV8))
.fi
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 319 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
