.TH "CORTEX_LL_EF_LOW_POWER_MODE" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_EF_LOW_POWER_MODE
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_EnableSleep\fP (void)"
.br
.RI "Processor uses sleep as its low power mode @rmtoll SCB_SCR SLEEPDEEP LL_LPM_EnableSleep "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_EnableDeepSleep\fP (void)"
.br
.RI "Processor uses deep sleep as its low power mode @rmtoll SCB_SCR SLEEPDEEP LL_LPM_EnableDeepSleep "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_EnableSleepOnExit\fP (void)"
.br
.RI "Configures sleep-on-exit when returning from Handler mode to Thread mode\&. "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_DisableSleepOnExit\fP (void)"
.br
.RI "Do not sleep when returning to Thread mode\&. @rmtoll SCB_SCR SLEEPONEXIT LL_LPM_DisableSleepOnExit "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_EnableEventOnPend\fP (void)"
.br
.RI "Enabled events and all interrupts, including disabled interrupts, can wakeup the processor\&. @rmtoll SCB_SCR SEVEONPEND LL_LPM_EnableEventOnPend "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_LPM_DisableEventOnPend\fP (void)"
.br
.RI "Only enabled interrupts or events can wakeup the processor, disabled interrupts are excluded @rmtoll SCB_SCR SEVEONPEND LL_LPM_DisableEventOnPend "
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "__STATIC_INLINE void LL_LPM_DisableEventOnPend (void)"

.PP
Only enabled interrupts or events can wakeup the processor, disabled interrupts are excluded @rmtoll SCB_SCR SEVEONPEND LL_LPM_DisableEventOnPend 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 370 行定义\&.
.SS "__STATIC_INLINE void LL_LPM_DisableSleepOnExit (void)"

.PP
Do not sleep when returning to Thread mode\&. @rmtoll SCB_SCR SLEEPONEXIT LL_LPM_DisableSleepOnExit 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 346 行定义\&.
.SS "__STATIC_INLINE void LL_LPM_EnableDeepSleep (void)"

.PP
Processor uses deep sleep as its low power mode @rmtoll SCB_SCR SLEEPDEEP LL_LPM_EnableDeepSleep 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 322 行定义\&.
.SS "__STATIC_INLINE void LL_LPM_EnableEventOnPend (void)"

.PP
Enabled events and all interrupts, including disabled interrupts, can wakeup the processor\&. @rmtoll SCB_SCR SEVEONPEND LL_LPM_EnableEventOnPend 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 358 行定义\&.
.SS "__STATIC_INLINE void LL_LPM_EnableSleep (void)"

.PP
Processor uses sleep as its low power mode @rmtoll SCB_SCR SLEEPDEEP LL_LPM_EnableSleep 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 311 行定义\&.
.SS "__STATIC_INLINE void LL_LPM_EnableSleepOnExit (void)"

.PP
Configures sleep-on-exit when returning from Handler mode to Thread mode\&. 
.PP
\fB注解\fP
.RS 4
Setting this bit to 1 enables an interrupt-driven application to avoid returning to an empty main application\&. @rmtoll SCB_SCR SLEEPONEXIT LL_LPM_EnableSleepOnExit 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_ll_cortex\&.h 第 335 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
