.TH "CORTEX_Preemption_Priority_Group" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_Preemption_Priority_Group
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_0\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_1\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_2\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_3\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_4\fP   0x00000003U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define NVIC_PRIORITYGROUP_0   0x00000007U"
0 bits for pre-emption priority 4 bits for subpriority 
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 92 行定义\&.
.SS "#define NVIC_PRIORITYGROUP_1   0x00000006U"
1 bits for pre-emption priority 3 bits for subpriority 
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 94 行定义\&.
.SS "#define NVIC_PRIORITYGROUP_2   0x00000005U"
2 bits for pre-emption priority 2 bits for subpriority 
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 96 行定义\&.
.SS "#define NVIC_PRIORITYGROUP_3   0x00000004U"
3 bits for pre-emption priority 1 bits for subpriority 
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 98 行定义\&.
.SS "#define NVIC_PRIORITYGROUP_4   0x00000003U"
4 bits for pre-emption priority 0 bits for subpriority 
.PP
在文件 stm32f4xx_hal_cortex\&.h 第 100 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
