.TH "CORTEX_LL_EC_FAULT" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_EC_FAULT
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLL_HANDLER_FAULT_USG\fP   SCB_SHCSR_USGFAULTENA_Msk"
.br
.ti -1c
.RI "#define \fBLL_HANDLER_FAULT_BUS\fP   SCB_SHCSR_BUSFAULTENA_Msk"
.br
.ti -1c
.RI "#define \fBLL_HANDLER_FAULT_MEM\fP   SCB_SHCSR_MEMFAULTENA_Msk"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define LL_HANDLER_FAULT_BUS   SCB_SHCSR_BUSFAULTENA_Msk"
Bus fault 
.PP
在文件 stm32f4xx_ll_cortex\&.h 第 82 行定义\&.
.SS "#define LL_HANDLER_FAULT_MEM   SCB_SHCSR_MEMFAULTENA_Msk"
Memory management fault 
.PP
在文件 stm32f4xx_ll_cortex\&.h 第 83 行定义\&.
.SS "#define LL_HANDLER_FAULT_USG   SCB_SHCSR_USGFAULTENA_Msk"
Usage fault 
.PP
在文件 stm32f4xx_ll_cortex\&.h 第 81 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
