.TH "CORTEX_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_NVIC_SetPriorityGrouping\fP (uint32_t PriorityGroup)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SetPriority\fP (IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_EnableIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_DisableIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SystemReset\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SYSTICK_Config\fP (uint32_t TicksNumb)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_NVIC_DisableIRQ (IRQn_Type IRQn)"

.SS "void HAL_NVIC_EnableIRQ (IRQn_Type IRQn)"

.SS "void HAL_NVIC_SetPriority (IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)"

.SS "void HAL_NVIC_SetPriorityGrouping (uint32_t PriorityGroup)"

.SS "void HAL_NVIC_SystemReset (void)"

.SS "uint32_t HAL_SYSTICK_Config (uint32_t TicksNumb)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
