.TH "CRC" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC \- CRC HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBCRC Exported Types\fP"
.br
.ti -1c
.RI "\fBCRC Exported Constants\fP"
.br
.ti -1c
.RI "\fBCRC Exported Macros\fP"
.br
.ti -1c
.RI "\fBCRC Private Macros\fP"
.br
.ti -1c
.RI "\fBCRC Exported Functions\fP"
.br
.in -1c
.SH "详细描述"
.PP 
CRC HAL module driver\&. 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
