.TH "CRC_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_CRC_Init\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_CRC_DeInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "void \fBHAL_CRC_MspInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "void \fBHAL_CRC_MspDeInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_CRC_DeInit (\fBCRC_HandleTypeDef\fP * hcrc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_CRC_Init (\fBCRC_HandleTypeDef\fP * hcrc)"

.SS "void HAL_CRC_MspDeInit (\fBCRC_HandleTypeDef\fP * hcrc)"

.SS "void HAL_CRC_MspInit (\fBCRC_HandleTypeDef\fP * hcrc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
