.TH "CRC_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_CRC_StateTypeDef\fP \fBHAL_CRC_GetState\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_CRC_StateTypeDef\fP HAL_CRC_GetState (\fBCRC_HandleTypeDef\fP * hcrc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
