.TH "CRC_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_HandleTypeDef \- CRC Handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_crc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "CRC_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO \fBHAL_CRC_StateTypeDef\fP \fBState\fP"
.br
.in -1c
.SH "详细描述"
.PP 
CRC Handle Structure definition 
.PP
在文件 stm32f4xx_hal_crc\&.h 第 60 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "CRC_TypeDef* Instance"
Register base address 
.br
 
.PP
在文件 stm32f4xx_hal_crc\&.h 第 62 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"
CRC Locking object 
.br
 
.PP
在文件 stm32f4xx_hal_crc\&.h 第 64 行定义\&.
.SS "__IO \fBHAL_CRC_StateTypeDef\fP State"
CRC communication state 
.br
 
.PP
在文件 stm32f4xx_hal_crc\&.h 第 66 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
