.TH "CRC_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "uint32_t \fBHAL_CRC_Accumulate\fP (\fBCRC_HandleTypeDef\fP *hcrc, uint32_t pBuffer[], uint32_t BufferLength)"
.br
.ti -1c
.RI "uint32_t \fBHAL_CRC_Calculate\fP (\fBCRC_HandleTypeDef\fP *hcrc, uint32_t pBuffer[], uint32_t BufferLength)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_CRC_Accumulate (\fBCRC_HandleTypeDef\fP * hcrc, uint32_t pBuffer[], uint32_t BufferLength)"

.SS "uint32_t HAL_CRC_Calculate (\fBCRC_HandleTypeDef\fP * hcrc, uint32_t pBuffer[], uint32_t BufferLength)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
