.TH "DMA_Channel_selection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Channel_selection \- DMA channel selection  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDMA_CHANNEL_0\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_1\fP   0x02000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_2\fP   0x04000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_3\fP   0x06000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_4\fP   0x08000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_5\fP   0x0A000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_6\fP   0x0C000000U"
.br
.ti -1c
.RI "#define \fBDMA_CHANNEL_7\fP   0x0E000000U"
.br
.in -1c
.SH "详细描述"
.PP 
DMA channel selection 


.SH "宏定义说明"
.PP 
.SS "#define DMA_CHANNEL_0   0x00000000U"
DMA Channel 0 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 203 行定义\&.
.SS "#define DMA_CHANNEL_1   0x02000000U"
DMA Channel 1 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 204 行定义\&.
.SS "#define DMA_CHANNEL_2   0x04000000U"
DMA Channel 2 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 205 行定义\&.
.SS "#define DMA_CHANNEL_3   0x06000000U"
DMA Channel 3 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 206 行定义\&.
.SS "#define DMA_CHANNEL_4   0x08000000U"
DMA Channel 4 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 207 行定义\&.
.SS "#define DMA_CHANNEL_5   0x0A000000U"
DMA Channel 5 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 208 行定义\&.
.SS "#define DMA_CHANNEL_6   0x0C000000U"
DMA Channel 6 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 209 行定义\&.
.SS "#define DMA_CHANNEL_7   0x0E000000U"
DMA Channel 7 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 210 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
