.TH "DMA_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Functions_Group1 \- Initialization and de-initialization functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMA_Init\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMA_DeInit\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "详细描述"
.PP 
Initialization and de-initialization functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_DMA_DeInit (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "\fBHAL_StatusTypeDef\fP HAL_DMA_Init (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
