.TH "DMA_flag_definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_flag_definitions \- DMA flag definitions  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDMA_FLAG_FEIF0_4\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_DMEIF0_4\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TEIF0_4\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HTIF0_4\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TCIF0_4\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_FEIF1_5\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_DMEIF1_5\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TEIF1_5\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HTIF1_5\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TCIF1_5\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_FEIF2_6\fP   0x00010000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_DMEIF2_6\fP   0x00040000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TEIF2_6\fP   0x00080000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HTIF2_6\fP   0x00100000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TCIF2_6\fP   0x00200000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_FEIF3_7\fP   0x00400000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_DMEIF3_7\fP   0x01000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TEIF3_7\fP   0x02000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HTIF3_7\fP   0x04000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TCIF3_7\fP   0x08000000U"
.br
.in -1c
.SH "详细描述"
.PP 
DMA flag definitions 


.SH "宏定义说明"
.PP 
.SS "#define DMA_FLAG_DMEIF0_4   0x00000004U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 365 行定义\&.
.SS "#define DMA_FLAG_DMEIF1_5   0x00000100U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 370 行定义\&.
.SS "#define DMA_FLAG_DMEIF2_6   0x00040000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 375 行定义\&.
.SS "#define DMA_FLAG_DMEIF3_7   0x01000000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 380 行定义\&.
.SS "#define DMA_FLAG_FEIF0_4   0x00000001U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 364 行定义\&.
.SS "#define DMA_FLAG_FEIF1_5   0x00000040U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 369 行定义\&.
.SS "#define DMA_FLAG_FEIF2_6   0x00010000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 374 行定义\&.
.SS "#define DMA_FLAG_FEIF3_7   0x00400000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 379 行定义\&.
.SS "#define DMA_FLAG_HTIF0_4   0x00000010U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 367 行定义\&.
.SS "#define DMA_FLAG_HTIF1_5   0x00000400U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 372 行定义\&.
.SS "#define DMA_FLAG_HTIF2_6   0x00100000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 377 行定义\&.
.SS "#define DMA_FLAG_HTIF3_7   0x04000000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 382 行定义\&.
.SS "#define DMA_FLAG_TCIF0_4   0x00000020U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 368 行定义\&.
.SS "#define DMA_FLAG_TCIF1_5   0x00000800U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 373 行定义\&.
.SS "#define DMA_FLAG_TCIF2_6   0x00200000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 378 行定义\&.
.SS "#define DMA_FLAG_TCIF3_7   0x08000000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 383 行定义\&.
.SS "#define DMA_FLAG_TEIF0_4   0x00000008U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 366 行定义\&.
.SS "#define DMA_FLAG_TEIF1_5   0x00000200U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 371 行定义\&.
.SS "#define DMA_FLAG_TEIF2_6   0x00080000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 376 行定义\&.
.SS "#define DMA_FLAG_TEIF3_7   0x02000000U"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 381 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
