.TH "DMA_Handle_index" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Handle_index
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMA_ID_UPDATE\fP   ((uint16_t) 0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_CC1\fP   ((uint16_t) 0x0001)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_CC2\fP   ((uint16_t) 0x0002)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_CC3\fP   ((uint16_t) 0x0003)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_CC4\fP   ((uint16_t) 0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_COMMUTATION\fP   ((uint16_t) 0x0005)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_ID_TRIGGER\fP   ((uint16_t) 0x0006)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_DMA_ID_CC1   ((uint16_t) 0x0001)"
Index of the DMA handle used for Capture/Compare 1 DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 947 行定义\&.
.SS "#define TIM_DMA_ID_CC2   ((uint16_t) 0x0002)"
Index of the DMA handle used for Capture/Compare 2 DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 948 行定义\&.
.SS "#define TIM_DMA_ID_CC3   ((uint16_t) 0x0003)"
Index of the DMA handle used for Capture/Compare 3 DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 949 行定义\&.
.SS "#define TIM_DMA_ID_CC4   ((uint16_t) 0x0004)"
Index of the DMA handle used for Capture/Compare 4 DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 950 行定义\&.
.SS "#define TIM_DMA_ID_COMMUTATION   ((uint16_t) 0x0005)"
Index of the DMA handle used for Commutation DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 951 行定义\&.
.SS "#define TIM_DMA_ID_TRIGGER   ((uint16_t) 0x0006)"
Index of the DMA handle used for Trigger DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 952 行定义\&.
.SS "#define TIM_DMA_ID_UPDATE   ((uint16_t) 0x0000)"
Index of the DMA handle used for Update DMA requests 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 946 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
