.TH "DMA_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Functions_Group3 \- Peripheral State functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_DMA_StateTypeDef\fP \fBHAL_DMA_GetState\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "uint32_t \fBHAL_DMA_GetError\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "详细描述"
.PP 
Peripheral State functions 


.SH "函数说明"
.PP 
.SS "uint32_t HAL_DMA_GetError (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "\fBHAL_DMA_StateTypeDef\fP HAL_DMA_GetState (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
