.TH "DMA_Error_Code" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Error_Code \- DMA Error Code  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_TE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_FE\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_DME\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_TIMEOUT\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_PARAM\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_NO_XFER\fP   0x00000080U"
.br
.ti -1c
.RI "#define \fBHAL_DMA_ERROR_NOT_SUPPORTED\fP   0x00000100U"
.br
.in -1c
.SH "详细描述"
.PP 
DMA Error Code 


.SH "宏定义说明"
.PP 
.SS "#define HAL_DMA_ERROR_DME   0x00000004U"
Direct Mode error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 190 行定义\&.
.SS "#define HAL_DMA_ERROR_FE   0x00000002U"
FIFO error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 189 行定义\&.
.SS "#define HAL_DMA_ERROR_NO_XFER   0x00000080U"
Abort requested with no Xfer ongoing 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 193 行定义\&.
.SS "#define HAL_DMA_ERROR_NONE   0x00000000U"
No error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 187 行定义\&.
.SS "#define HAL_DMA_ERROR_NOT_SUPPORTED   0x00000100U"
Not supported mode 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 194 行定义\&.
.SS "#define HAL_DMA_ERROR_PARAM   0x00000040U"
Parameter error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 192 行定义\&.
.SS "#define HAL_DMA_ERROR_TE   0x00000001U"
Transfer error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 188 行定义\&.
.SS "#define HAL_DMA_ERROR_TIMEOUT   0x00000020U"
Timeout error 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 191 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
