.TH "DMA_Exported_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Functions \- DMA Exported functions  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBInitialization and de\-initialization functions\fP"
.br
.RI "Initialization and de-initialization functions "
.ti -1c
.RI "\fBI/O operation functions\fP"
.br
.RI "I/O operation functions 
.br
 "
.ti -1c
.RI "\fBPeripheral State functions\fP"
.br
.RI "Peripheral State functions "
.in -1c
.SH "详细描述"
.PP 
DMA Exported functions 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
