.TH "DMA_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Constants \- DMA Exported constants  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBDMA Error Code\fP"
.br
.RI "DMA Error Code "
.ti -1c
.RI "\fBDMA Channel selection\fP"
.br
.RI "DMA channel selection "
.ti -1c
.RI "\fBDMA Data transfer direction\fP"
.br
.RI "DMA data transfer direction "
.ti -1c
.RI "\fBDMA Peripheral incremented mode\fP"
.br
.RI "DMA peripheral incremented mode "
.ti -1c
.RI "\fBDMA Memory incremented mode\fP"
.br
.RI "DMA memory incremented mode "
.ti -1c
.RI "\fBDMA Peripheral data size\fP"
.br
.RI "DMA peripheral data size "
.ti -1c
.RI "\fBDMA Memory data size\fP"
.br
.RI "DMA memory data size "
.ti -1c
.RI "\fBDMA mode\fP"
.br
.RI "DMA mode "
.ti -1c
.RI "\fBDMA Priority level\fP"
.br
.RI "DMA priority levels "
.ti -1c
.RI "\fBDMA FIFO direct mode\fP"
.br
.RI "DMA FIFO direct mode "
.ti -1c
.RI "\fBDMA FIFO threshold level\fP"
.br
.RI "DMA FIFO level "
.ti -1c
.RI "\fBDMA Memory burst\fP"
.br
.RI "DMA memory burst "
.ti -1c
.RI "\fBDMA Peripheral burst\fP"
.br
.RI "DMA peripheral burst "
.ti -1c
.RI "\fBDMA interrupt enable definitions\fP"
.br
.RI "DMA interrupts definition "
.ti -1c
.RI "\fBDMA flag definitions\fP"
.br
.RI "DMA flag definitions "
.in -1c
.SH "详细描述"
.PP 
DMA Exported constants 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
