.TH "DMA_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Private_Macros \- DMA private macros  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_DMA_CHANNEL\fP(CHANNEL)"
.br
.ti -1c
.RI "#define \fBIS_DMA_DIRECTION\fP(DIRECTION)"
.br
.ti -1c
.RI "#define \fBIS_DMA_BUFFER_SIZE\fP(SIZE)   (((SIZE) >= 0x01U) && ((SIZE) < 0x10000U))"
.br
.ti -1c
.RI "#define \fBIS_DMA_PERIPHERAL_INC_STATE\fP(STATE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MEMORY_INC_STATE\fP(STATE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PERIPHERAL_DATA_SIZE\fP(SIZE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MEMORY_DATA_SIZE\fP(SIZE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PRIORITY\fP(PRIORITY)"
.br
.ti -1c
.RI "#define \fBIS_DMA_FIFO_MODE_STATE\fP(STATE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_FIFO_THRESHOLD\fP(THRESHOLD)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MEMORY_BURST\fP(BURST)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PERIPHERAL_BURST\fP(BURST)"
.br
.in -1c
.SH "详细描述"
.PP 
DMA private macros 


.SH "宏定义说明"
.PP 
.SS "#define IS_DMA_BUFFER_SIZE(SIZE)   (((SIZE) >= 0x01U) && ((SIZE) < 0x10000U))"

.PP
在文件 stm32f4xx_hal_dma\&.h 第 736 行定义\&.
.SS "#define IS_DMA_CHANNEL(CHANNEL)"
\fB值:\fP
.PP
.nf
                                 (((CHANNEL) == DMA_CHANNEL_0) || \
                                 ((CHANNEL) == DMA_CHANNEL_1) || \
                                 ((CHANNEL) == DMA_CHANNEL_2) || \
                                 ((CHANNEL) == DMA_CHANNEL_3) || \
                                 ((CHANNEL) == DMA_CHANNEL_4) || \
                                 ((CHANNEL) == DMA_CHANNEL_5) || \
                                 ((CHANNEL) == DMA_CHANNEL_6) || \
                                 ((CHANNEL) == DMA_CHANNEL_7))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 722 行定义\&.
.SS "#define IS_DMA_DIRECTION(DIRECTION)"
\fB值:\fP
.PP
.nf
                                     (((DIRECTION) == DMA_PERIPH_TO_MEMORY ) || \
                                     ((DIRECTION) == DMA_MEMORY_TO_PERIPH)  || \
                                     ((DIRECTION) == DMA_MEMORY_TO_MEMORY))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 732 行定义\&.
.SS "#define IS_DMA_FIFO_MODE_STATE(STATE)"
\fB值:\fP
.PP
.nf
                                       (((STATE) == DMA_FIFOMODE_DISABLE ) || \
                                       ((STATE) == DMA_FIFOMODE_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 761 行定义\&.
.SS "#define IS_DMA_FIFO_THRESHOLD(THRESHOLD)"
\fB值:\fP
.PP
.nf
                                          (((THRESHOLD) == DMA_FIFO_THRESHOLD_1QUARTERFULL ) || \
                                          ((THRESHOLD) == DMA_FIFO_THRESHOLD_HALFFULL)      || \
                                          ((THRESHOLD) == DMA_FIFO_THRESHOLD_3QUARTERSFULL) || \
                                          ((THRESHOLD) == DMA_FIFO_THRESHOLD_FULL))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 764 行定义\&.
.SS "#define IS_DMA_MEMORY_BURST(BURST)"
\fB值:\fP
.PP
.nf
                                    (((BURST) == DMA_MBURST_SINGLE) || \
                                    ((BURST) == DMA_MBURST_INC4)   || \
                                    ((BURST) == DMA_MBURST_INC8)   || \
                                    ((BURST) == DMA_MBURST_INC16))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 769 行定义\&.
.SS "#define IS_DMA_MEMORY_DATA_SIZE(SIZE)"
\fB值:\fP
.PP
.nf
                                       (((SIZE) == DMA_MDATAALIGN_BYTE)     || \
                                       ((SIZE) == DMA_MDATAALIGN_HALFWORD) || \
                                       ((SIZE) == DMA_MDATAALIGN_WORD ))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 748 行定义\&.
.SS "#define IS_DMA_MEMORY_INC_STATE(STATE)"
\fB值:\fP
.PP
.nf
                                        (((STATE) == DMA_MINC_ENABLE)  || \
                                        ((STATE) == DMA_MINC_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 741 行定义\&.
.SS "#define IS_DMA_MODE(MODE)"
\fB值:\fP
.PP
.nf
                           (((MODE) == DMA_NORMAL )  || \
                           ((MODE) == DMA_CIRCULAR) || \
                           ((MODE) == DMA_PFCTRL))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 752 行定义\&.
.SS "#define IS_DMA_PERIPHERAL_BURST(BURST)"
\fB值:\fP
.PP
.nf
                                        (((BURST) == DMA_PBURST_SINGLE) || \
                                        ((BURST) == DMA_PBURST_INC4)   || \
                                        ((BURST) == DMA_PBURST_INC8)   || \
                                        ((BURST) == DMA_PBURST_INC16))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 774 行定义\&.
.SS "#define IS_DMA_PERIPHERAL_DATA_SIZE(SIZE)"
\fB值:\fP
.PP
.nf
                                           (((SIZE) == DMA_PDATAALIGN_BYTE)     || \
                                           ((SIZE) == DMA_PDATAALIGN_HALFWORD) || \
                                           ((SIZE) == DMA_PDATAALIGN_WORD))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 744 行定义\&.
.SS "#define IS_DMA_PERIPHERAL_INC_STATE(STATE)"
\fB值:\fP
.PP
.nf
                                            (((STATE) == DMA_PINC_ENABLE) || \
                                            ((STATE) == DMA_PINC_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 738 行定义\&.
.SS "#define IS_DMA_PRIORITY(PRIORITY)"
\fB值:\fP
.PP
.nf
                                   (((PRIORITY) == DMA_PRIORITY_LOW )   || \
                                   ((PRIORITY) == DMA_PRIORITY_MEDIUM) || \
                                   ((PRIORITY) == DMA_PRIORITY_HIGH)   || \
                                   ((PRIORITY) == DMA_PRIORITY_VERY_HIGH))
.fi
.PP
在文件 stm32f4xx_hal_dma\&.h 第 756 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
