.TH "DMA_Priority_level" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Priority_level \- DMA priority levels  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDMA_PRIORITY_LOW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_MEDIUM\fP   ((uint32_t)DMA_SxCR_PL_0)"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_HIGH\fP   ((uint32_t)DMA_SxCR_PL_1)"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_VERY_HIGH\fP   ((uint32_t)DMA_SxCR_PL)"
.br
.in -1c
.SH "详细描述"
.PP 
DMA priority levels 


.SH "宏定义说明"
.PP 
.SS "#define DMA_PRIORITY_HIGH   ((uint32_t)DMA_SxCR_PL_1)"
Priority level: High 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 295 行定义\&.
.SS "#define DMA_PRIORITY_LOW   0x00000000U"
Priority level: Low 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 293 行定义\&.
.SS "#define DMA_PRIORITY_MEDIUM   ((uint32_t)DMA_SxCR_PL_0)"
Priority level: Medium 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 294 行定义\&.
.SS "#define DMA_PRIORITY_VERY_HIGH   ((uint32_t)DMA_SxCR_PL)"
Priority level: Very High 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 296 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
