.TH "DMA_Peripheral_incremented_mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Peripheral_incremented_mode \- DMA peripheral incremented mode  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDMA_PINC_ENABLE\fP   ((uint32_t)DMA_SxCR_PINC)"
.br
.ti -1c
.RI "#define \fBDMA_PINC_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 
DMA peripheral incremented mode 


.SH "宏定义说明"
.PP 
.SS "#define DMA_PINC_DISABLE   0x00000000U"
Peripheral increment mode disable 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 241 行定义\&.
.SS "#define DMA_PINC_ENABLE   ((uint32_t)DMA_SxCR_PINC)"
Peripheral increment mode enable 
.br
 
.PP
在文件 stm32f4xx_hal_dma\&.h 第 240 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
