.TH "DMAEx_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_Exported_Types \- DMAEx Exported types  

.SH SYNOPSIS
.br
.PP
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHAL_DMA_MemoryTypeDef\fP { \fBMEMORY0\fP = 0x00U, \fBMEMORY1\fP = 0x01U }"
.br
.RI "HAL DMA Memory definition 
.br
 "
.in -1c
.SH "详细描述"
.PP 
DMAEx Exported types 


.SH "枚举类型说明"
.PP 
.SS "enum \fBHAL_DMA_MemoryTypeDef\fP"

.PP
HAL DMA Memory definition 
.br
 
.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIMEMORY0 \fP\fP
Memory 0 
.br
 
.TP
\fB\fIMEMORY1 \fP\fP
Memory 1 
.br
 
.PP
在文件 stm32f4xx_hal_dma_ex\&.h 第 48 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
