.TH "DMAEx" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx \- DMA Extended HAL module driver  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBDMAEx Exported Types\fP"
.br
.RI "DMAEx Exported types "
.ti -1c
.RI "\fBDMAEx Exported Functions\fP"
.br
.RI "DMAEx Exported functions "
.ti -1c
.RI "\fBDMAEx Private Functions\fP"
.br
.RI "DMAEx Private functions "
.in -1c
.SH "详细描述"
.PP 
DMA Extended HAL module driver 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
