.TH "EXTI_ConfigTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_ConfigTypeDef \- EXTI Configuration structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_exti\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBLine\fP"
.br
.ti -1c
.RI "uint32_t \fBMode\fP"
.br
.ti -1c
.RI "uint32_t \fBTrigger\fP"
.br
.in -1c
.SH "详细描述"
.PP 
EXTI Configuration structure definition 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 65 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Line"
The Exti line to be configured\&. This parameter can be a value of \fBEXTI Line\fP 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 67 行定义\&.
.SS "uint32_t Mode"
The Exit Mode to be configured for a core\&. This parameter can be a combination of \fBEXTI Mode\fP 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 69 行定义\&.
.SS "uint32_t Trigger"
The Exti Trigger to be configured\&. This parameter can be a value of \fBEXTI Trigger\fP 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 71 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
