.TH "EXTI_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Exported_Functions_Group2 \- IO operation functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_EXTI_IRQHandler\fP (\fBEXTI_HandleTypeDef\fP *hexti)"
.br
.ti -1c
.RI "uint32_t \fBHAL_EXTI_GetPending\fP (\fBEXTI_HandleTypeDef\fP *hexti, uint32_t Edge)"
.br
.ti -1c
.RI "void \fBHAL_EXTI_ClearPending\fP (\fBEXTI_HandleTypeDef\fP *hexti, uint32_t Edge)"
.br
.ti -1c
.RI "void \fBHAL_EXTI_GenerateSWI\fP (\fBEXTI_HandleTypeDef\fP *hexti)"
.br
.in -1c
.SH "详细描述"
.PP 
IO operation functions 


.SH "函数说明"
.PP 
.SS "void HAL_EXTI_ClearPending (\fBEXTI_HandleTypeDef\fP * hexti, uint32_t Edge)"

.SS "void HAL_EXTI_GenerateSWI (\fBEXTI_HandleTypeDef\fP * hexti)"

.SS "uint32_t HAL_EXTI_GetPending (\fBEXTI_HandleTypeDef\fP * hexti, uint32_t Edge)"

.SS "void HAL_EXTI_IRQHandler (\fBEXTI_HandleTypeDef\fP * hexti)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
