.TH "EXTI_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBEXTI_HandleTypeDef\fP"
.br
.RI "EXTI Handle structure definition "
.ti -1c
.RI "struct \fBEXTI_ConfigTypeDef\fP"
.br
.RI "EXTI Configuration structure definition "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBEXTI_CallbackIDTypeDef\fP { \fBHAL_EXTI_COMMON_CB_ID\fP = 0x00U, \fBHAL_EXTI_RISING_CB_ID\fP = 0x01U, \fBHAL_EXTI_FALLING_CB_ID\fP = 0x02U }"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "枚举类型说明"
.PP 
.SS "enum \fBEXTI_CallbackIDTypeDef\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIHAL_EXTI_COMMON_CB_ID \fP\fP
.TP
\fB\fIHAL_EXTI_RISING_CB_ID \fP\fP
.TP
\fB\fIHAL_EXTI_FALLING_CB_ID \fP\fP
.PP
在文件 stm32f4xx_hal_exti\&.h 第 45 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
