.TH "EXTI_Line" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Line
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBEXTI_LINE_0\fP   EXTI_IMR_IM0"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_1\fP   EXTI_IMR_IM1"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_2\fP   EXTI_IMR_IM2"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_3\fP   EXTI_IMR_IM3"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_4\fP   EXTI_IMR_IM4"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_5\fP   EXTI_IMR_IM5"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_6\fP   EXTI_IMR_IM6"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_7\fP   EXTI_IMR_IM7"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_8\fP   EXTI_IMR_IM8"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_9\fP   EXTI_IMR_IM9"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_10\fP   EXTI_IMR_IM10"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_11\fP   EXTI_IMR_IM11"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_12\fP   EXTI_IMR_IM12"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_13\fP   EXTI_IMR_IM13"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_14\fP   EXTI_IMR_IM14"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_15\fP   EXTI_IMR_IM15"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_16\fP   EXTI_IMR_IM16"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_17\fP   EXTI_IMR_IM17"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_18\fP   EXTI_IMR_IM18"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_19\fP   EXTI_IMR_IM19"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_20\fP   EXTI_IMR_IM20"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_21\fP   EXTI_IMR_IM21"
.br
.ti -1c
.RI "#define \fBEXTI_LINE_22\fP   EXTI_IMR_IM22"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define EXTI_LINE_0   EXTI_IMR_IM0"
External interrupt line 0 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 88 行定义\&.
.SS "#define EXTI_LINE_1   EXTI_IMR_IM1"
External interrupt line 1 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 89 行定义\&.
.SS "#define EXTI_LINE_10   EXTI_IMR_IM10"
External interrupt line 10 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 98 行定义\&.
.SS "#define EXTI_LINE_11   EXTI_IMR_IM11"
External interrupt line 11 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 99 行定义\&.
.SS "#define EXTI_LINE_12   EXTI_IMR_IM12"
External interrupt line 12 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 100 行定义\&.
.SS "#define EXTI_LINE_13   EXTI_IMR_IM13"
External interrupt line 13 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 101 行定义\&.
.SS "#define EXTI_LINE_14   EXTI_IMR_IM14"
External interrupt line 14 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 102 行定义\&.
.SS "#define EXTI_LINE_15   EXTI_IMR_IM15"
External interrupt line 15 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 103 行定义\&.
.SS "#define EXTI_LINE_16   EXTI_IMR_IM16"
External interrupt line 16 Connected to the PVD Output 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 104 行定义\&.
.SS "#define EXTI_LINE_17   EXTI_IMR_IM17"
External interrupt line 17 Connected to the RTC Alarm event 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 105 行定义\&.
.SS "#define EXTI_LINE_18   EXTI_IMR_IM18"
External interrupt line 18 Connected to the USB OTG FS Wakeup from suspend event 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 106 行定义\&.
.SS "#define EXTI_LINE_19   EXTI_IMR_IM19"
External interrupt line 19 Connected to the Ethernet Wakeup event 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 107 行定义\&.
.SS "#define EXTI_LINE_2   EXTI_IMR_IM2"
External interrupt line 2 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 90 行定义\&.
.SS "#define EXTI_LINE_20   EXTI_IMR_IM20"
External interrupt line 20 Connected to the USB OTG HS (configured in FS) Wakeup event 
.br
 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 108 行定义\&.
.SS "#define EXTI_LINE_21   EXTI_IMR_IM21"
External interrupt line 21 Connected to the RTC Tamper and Time Stamp events 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 109 行定义\&.
.SS "#define EXTI_LINE_22   EXTI_IMR_IM22"
External interrupt line 22 Connected to the RTC Wakeup event 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 110 行定义\&.
.SS "#define EXTI_LINE_3   EXTI_IMR_IM3"
External interrupt line 3 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 91 行定义\&.
.SS "#define EXTI_LINE_4   EXTI_IMR_IM4"
External interrupt line 4 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 92 行定义\&.
.SS "#define EXTI_LINE_5   EXTI_IMR_IM5"
External interrupt line 5 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 93 行定义\&.
.SS "#define EXTI_LINE_6   EXTI_IMR_IM6"
External interrupt line 6 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 94 行定义\&.
.SS "#define EXTI_LINE_7   EXTI_IMR_IM7"
External interrupt line 7 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 95 行定义\&.
.SS "#define EXTI_LINE_8   EXTI_IMR_IM8"
External interrupt line 8 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 96 行定义\&.
.SS "#define EXTI_LINE_9   EXTI_IMR_IM9"
External interrupt line 9 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 97 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
