.TH "EXTI_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_HandleTypeDef \- EXTI Handle structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_exti\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBLine\fP"
.br
.ti -1c
.RI "void(* \fBRisingCallback\fP )(void)"
.br
.ti -1c
.RI "void(* \fBFallingCallback\fP )(void)"
.br
.in -1c
.SH "详细描述"
.PP 
EXTI Handle structure definition 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 55 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "void(* FallingCallback) (void)"
Exti falling callback 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 59 行定义\&.
.SS "uint32_t Line"
Exti line number 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 57 行定义\&.
.SS "void(* RisingCallback) (void)"
Exti rising callback 
.PP
在文件 stm32f4xx_hal_exti\&.h 第 58 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
