.TH "EXTI_Trigger" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Trigger
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBEXTI_TRIGGER_RISING\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBEXTI_TRIGGER_FALLING\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBEXTI_TRIGGER_RISING_FALLING\fP   0x00000010U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define EXTI_TRIGGER_FALLING   0x0000000CU"

.PP
在文件 stm32f4xx_hal_exti\&.h 第 130 行定义\&.
.SS "#define EXTI_TRIGGER_RISING   0x00000008U"

.PP
在文件 stm32f4xx_hal_exti\&.h 第 129 行定义\&.
.SS "#define EXTI_TRIGGER_RISING_FALLING   0x00000010U"

.PP
在文件 stm32f4xx_hal_exti\&.h 第 131 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
