.TH "FLASH_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBACR_BYTE0_ADDRESS\fP   0x40023C00U"
.br
.RI "ACR register byte 0 (Bits[7:0]) base address 
.br
 "
.ti -1c
.RI "#define \fBOPTCR_BYTE0_ADDRESS\fP   0x40023C14U"
.br
.RI "OPTCR register byte 0 (Bits[7:0]) base address 
.br
 "
.ti -1c
.RI "#define \fBOPTCR_BYTE1_ADDRESS\fP   0x40023C15U"
.br
.RI "OPTCR register byte 1 (Bits[15:8]) base address 
.br
 "
.ti -1c
.RI "#define \fBOPTCR_BYTE2_ADDRESS\fP   0x40023C16U"
.br
.RI "OPTCR register byte 2 (Bits[23:16]) base address 
.br
 "
.ti -1c
.RI "#define \fBOPTCR_BYTE3_ADDRESS\fP   0x40023C17U"
.br
.RI "OPTCR register byte 3 (Bits[31:24]) base address 
.br
 "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ACR_BYTE0_ADDRESS   0x40023C00U"

.PP
ACR register byte 0 (Bits[7:0]) base address 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 364 行定义\&.
.SS "#define OPTCR_BYTE0_ADDRESS   0x40023C14U"

.PP
OPTCR register byte 0 (Bits[7:0]) base address 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 368 行定义\&.
.SS "#define OPTCR_BYTE1_ADDRESS   0x40023C15U"

.PP
OPTCR register byte 1 (Bits[15:8]) base address 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 372 行定义\&.
.SS "#define OPTCR_BYTE2_ADDRESS   0x40023C16U"

.PP
OPTCR register byte 2 (Bits[23:16]) base address 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 376 行定义\&.
.SS "#define OPTCR_BYTE3_ADDRESS   0x40023C17U"

.PP
OPTCR register byte 3 (Bits[31:24]) base address 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 380 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
