.TH "FLASHEx_Option_Type" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Option_Type
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBOPTIONBYTE_WRP\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_RDP\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_USER\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_BOR\fP   0x00000008U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define OPTIONBYTE_BOR   0x00000008U"
BOR option byte configuration 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 179 行定义\&.
.SS "#define OPTIONBYTE_RDP   0x00000002U"
RDP option byte configuration 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 177 行定义\&.
.SS "#define OPTIONBYTE_USER   0x00000004U"
USER option byte configuration 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 178 行定义\&.
.SS "#define OPTIONBYTE_WRP   0x00000001U"
WRP option byte configuration 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 176 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
