.TH "FLASHEx_Voltage_Range" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Voltage_Range
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_3\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_4\fP   0x00000003U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FLASH_VOLTAGE_RANGE_1   0x00000000U"
Device operating range: 1\&.8V to 2\&.1V 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 156 行定义\&.
.SS "#define FLASH_VOLTAGE_RANGE_2   0x00000001U"
Device operating range: 2\&.1V to 2\&.7V 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 157 行定义\&.
.SS "#define FLASH_VOLTAGE_RANGE_3   0x00000002U"
Device operating range: 2\&.7V to 3\&.6V 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 158 行定义\&.
.SS "#define FLASH_VOLTAGE_RANGE_4   0x00000003U"
Device operating range: 2\&.7V to 3\&.6V + External Vpp 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 159 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
