.TH "FLASH_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBFLASH_ProcessTypeDef\fP"
.br
.RI "FLASH handle Structure definition 
.br
 "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBFLASH_ProcedureTypeDef\fP { \fBFLASH_PROC_NONE\fP = 0U, \fBFLASH_PROC_SECTERASE\fP, \fBFLASH_PROC_MASSERASE\fP, \fBFLASH_PROC_PROGRAM\fP }"
.br
.RI "FLASH Procedure structure definition "
.in -1c
.SH "详细描述"
.PP 

.SH "枚举类型说明"
.PP 
.SS "enum \fBFLASH_ProcedureTypeDef\fP"

.PP
FLASH Procedure structure definition 
.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIFLASH_PROC_NONE \fP\fP
.TP
\fB\fIFLASH_PROC_SECTERASE \fP\fP
.TP
\fB\fIFLASH_PROC_MASSERASE \fP\fP
.TP
\fB\fIFLASH_PROC_PROGRAM \fP\fP
.PP
在文件 stm32f4xx_hal_flash\&.h 第 47 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
