.TH "FLASH_ProcessTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_ProcessTypeDef \- FLASH handle Structure definition 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_flash\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "__IO \fBFLASH_ProcedureTypeDef\fP \fBProcedureOnGoing\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBNbSectorsToErase\fP"
.br
.ti -1c
.RI "__IO uint8_t \fBVoltageForErase\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBSector\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBBank\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBAddress\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO uint32_t \fBErrorCode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
FLASH handle Structure definition 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 58 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "__IO uint32_t Address"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 70 行定义\&.
.SS "__IO uint32_t Bank"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 68 行定义\&.
.SS "__IO uint32_t ErrorCode"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 74 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 72 行定义\&.
.SS "__IO uint32_t NbSectorsToErase"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 62 行定义\&.
.SS "__IO \fBFLASH_ProcedureTypeDef\fP ProcedureOnGoing"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 60 行定义\&.
.SS "__IO uint32_t Sector"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 66 行定义\&.
.SS "__IO uint8_t VoltageForErase"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 64 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
