.TH "FLASHEx_Option_Bytes_IWatchdog" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Option_Bytes_IWatchdog
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBOB_IWDG_SW\fP   ((uint8_t)0x20)"
.br
.ti -1c
.RI "#define \fBOB_IWDG_HW\fP   ((uint8_t)0x00)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define OB_IWDG_HW   ((uint8_t)0x00)"
Hardware IWDG selected 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 199 行定义\&.
.SS "#define OB_IWDG_SW   ((uint8_t)0x20)"
Software IWDG selected 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 198 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
