.TH "FLASH_OBProgramInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OBProgramInitTypeDef \- FLASH Option Bytes Program structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_flash_ex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBOptionType\fP"
.br
.ti -1c
.RI "uint32_t \fBWRPState\fP"
.br
.ti -1c
.RI "uint32_t \fBWRPSector\fP"
.br
.ti -1c
.RI "uint32_t \fBBanks\fP"
.br
.ti -1c
.RI "uint32_t \fBRDPLevel\fP"
.br
.ti -1c
.RI "uint32_t \fBBORLevel\fP"
.br
.ti -1c
.RI "uint8_t \fBUSERConfig\fP"
.br
.in -1c
.SH "详细描述"
.PP 
FLASH Option Bytes Program structure definition 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 69 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Banks"
Select banks for WRP activation/deactivation of all sectors\&. This parameter must be a value of \fBFLASH Banks\fP 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 80 行定义\&.
.SS "uint32_t BORLevel"
Set the BOR Level\&. This parameter can be a value of \fBFLASH BOR Reset Level\fP 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 86 行定义\&.
.SS "uint32_t OptionType"
Option byte to be configured\&. This parameter can be a value of \fBFLASH Option Type\fP 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 71 行定义\&.
.SS "uint32_t RDPLevel"
Set the read protection level\&. This parameter can be a value of \fBFLASH Option Bytes Read Protection\fP 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 83 行定义\&.
.SS "uint8_t USERConfig"
Program the FLASH User Option Byte: IWDG_SW / RST_STOP / RST_STDBY\&. 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 89 行定义\&.
.SS "uint32_t WRPSector"
Specifies the sector(s) to be write protected\&. The value of this parameter depend on device used within the same series 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 77 行定义\&.
.SS "uint32_t WRPState"
Write protection activation or deactivation\&. This parameter can be a value of \fBFLASH WRP State\fP 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 74 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
