.TH "FLASHEx_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBFLASH Type Erase\fP"
.br
.ti -1c
.RI "\fBFLASH Voltage Range\fP"
.br
.ti -1c
.RI "\fBFLASH WRP State\fP"
.br
.ti -1c
.RI "\fBFLASH Option Type\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes Read Protection\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes IWatchdog\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes nRST_STOP\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes nRST_STDBY\fP"
.br
.ti -1c
.RI "\fBFLASH BOR Reset Level\fP"
.br
.ti -1c
.RI "\fBFLASH Advanced Option Type\fP"
.br
.ti -1c
.RI "\fBFLASH Latency\fP"
.br
.ti -1c
.RI "\fBFLASH Banks\fP"
.br
.ti -1c
.RI "\fBFLASH Mass Erase bit\fP"
.br
.ti -1c
.RI "\fBFLASH Sectors\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes Write Protection\fP"
.br
.ti -1c
.RI "\fBFLASH Option Bytes PC ReadWrite Protection\fP"
.br
.ti -1c
.RI "\fBFLASH Dual Boot\fP"
.br
.ti -1c
.RI "\fBFLASH Selection Protection Mode\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
