.TH "FLASH_Flag_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Flag_definition \- Flag definition  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFLASH_FLAG_EOP\fP   FLASH_SR_EOP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_OPERR\fP   FLASH_SR_SOP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_WRPERR\fP   FLASH_SR_WRPERR"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_PGAERR\fP   FLASH_SR_PGAERR"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_PGPERR\fP   FLASH_SR_PGPERR"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_PGSERR\fP   FLASH_SR_PGSERR"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_BSY\fP   FLASH_SR_BSY"
.br
.in -1c
.SH "详细描述"
.PP 
Flag definition 


.SH "宏定义说明"
.PP 
.SS "#define FLASH_FLAG_BSY   FLASH_SR_BSY"
FLASH Busy flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 126 行定义\&.
.SS "#define FLASH_FLAG_EOP   FLASH_SR_EOP"
FLASH End of Operation flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 117 行定义\&.
.SS "#define FLASH_FLAG_OPERR   FLASH_SR_SOP"
FLASH operation Error flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 118 行定义\&.
.SS "#define FLASH_FLAG_PGAERR   FLASH_SR_PGAERR"
FLASH Programming Alignment error flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 120 行定义\&.
.SS "#define FLASH_FLAG_PGPERR   FLASH_SR_PGPERR"
FLASH Programming Parallelism error flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 121 行定义\&.
.SS "#define FLASH_FLAG_PGSERR   FLASH_SR_PGSERR"
FLASH Programming Sequence error flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 122 行定义\&.
.SS "#define FLASH_FLAG_WRPERR   FLASH_SR_WRPERR"
FLASH Write protected error flag 
.br
 
.PP
在文件 stm32f4xx_hal_flash\&.h 第 119 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
