.TH "FLASH_Keys" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Keys
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRDP_KEY\fP   ((uint16_t)0x00A5)"
.br
.ti -1c
.RI "#define \fBFLASH_KEY1\fP   0x45670123U"
.br
.ti -1c
.RI "#define \fBFLASH_KEY2\fP   0xCDEF89ABU"
.br
.ti -1c
.RI "#define \fBFLASH_OPT_KEY1\fP   0x08192A3BU"
.br
.ti -1c
.RI "#define \fBFLASH_OPT_KEY2\fP   0x4C5D6E7FU"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FLASH_KEY1   0x45670123U"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 157 行定义\&.
.SS "#define FLASH_KEY2   0xCDEF89ABU"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 158 行定义\&.
.SS "#define FLASH_OPT_KEY1   0x08192A3BU"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 159 行定义\&.
.SS "#define FLASH_OPT_KEY2   0x4C5D6E7FU"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 160 行定义\&.
.SS "#define RDP_KEY   ((uint16_t)0x00A5)"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 156 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
