.TH "FLASH_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASH_Program\fP (uint32_t TypeProgram, uint32_t Address, uint64_t Data)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASH_Program_IT\fP (uint32_t TypeProgram, uint32_t Address, uint64_t Data)"
.br
.ti -1c
.RI "void \fBHAL_FLASH_IRQHandler\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_FLASH_EndOfOperationCallback\fP (uint32_t ReturnValue)"
.br
.ti -1c
.RI "void \fBHAL_FLASH_OperationErrorCallback\fP (uint32_t ReturnValue)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_FLASH_EndOfOperationCallback (uint32_t ReturnValue)"

.SS "void HAL_FLASH_IRQHandler (void)"

.SS "void HAL_FLASH_OperationErrorCallback (uint32_t ReturnValue)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASH_Program (uint32_t TypeProgram, uint32_t Address, uint64_t Data)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASH_Program_IT (uint32_t TypeProgram, uint32_t Address, uint64_t Data)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
