.TH "FLASH_Program_Parallelism" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Program_Parallelism
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFLASH_PSIZE_BYTE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBFLASH_PSIZE_HALF_WORD\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBFLASH_PSIZE_WORD\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBFLASH_PSIZE_DOUBLE_WORD\fP   0x00000300U"
.br
.ti -1c
.RI "#define \fBCR_PSIZE_MASK\fP   0xFFFFFCFFU"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CR_PSIZE_MASK   0xFFFFFCFFU"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 148 行定义\&.
.SS "#define FLASH_PSIZE_BYTE   0x00000000U"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 144 行定义\&.
.SS "#define FLASH_PSIZE_DOUBLE_WORD   0x00000300U"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 147 行定义\&.
.SS "#define FLASH_PSIZE_HALF_WORD   0x00000100U"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 145 行定义\&.
.SS "#define FLASH_PSIZE_WORD   0x00000200U"

.PP
在文件 stm32f4xx_hal_flash\&.h 第 146 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
