.TH "FLASHEx_BOR_Reset_Level" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_BOR_Reset_Level
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBOB_BOR_LEVEL3\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBOB_BOR_LEVEL2\fP   ((uint8_t)0x04)"
.br
.ti -1c
.RI "#define \fBOB_BOR_LEVEL1\fP   ((uint8_t)0x08)"
.br
.ti -1c
.RI "#define \fBOB_BOR_OFF\fP   ((uint8_t)0x0C)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define OB_BOR_LEVEL1   ((uint8_t)0x08)"
Supply voltage ranges from 2\&.10 to 2\&.40 V 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 228 行定义\&.
.SS "#define OB_BOR_LEVEL2   ((uint8_t)0x04)"
Supply voltage ranges from 2\&.40 to 2\&.70 V 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 227 行定义\&.
.SS "#define OB_BOR_LEVEL3   ((uint8_t)0x00)"
Supply voltage ranges from 2\&.70 to 3\&.60 V 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 226 行定义\&.
.SS "#define OB_BOR_OFF   ((uint8_t)0x0C)"
Supply voltage ranges from 1\&.62 to 2\&.10 V 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 229 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
