.TH "FLASHEx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit, uint32_t *SectorError)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase_IT\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_OBProgram\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_OBGetConfig\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase (\fBFLASH_EraseInitTypeDef\fP * pEraseInit, uint32_t * SectorError)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase_IT (\fBFLASH_EraseInitTypeDef\fP * pEraseInit)"

.SS "void HAL_FLASHEx_OBGetConfig (\fBFLASH_OBProgramInitTypeDef\fP * pOBInit)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_OBProgram (\fBFLASH_OBProgramInitTypeDef\fP * pOBInit)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
