.TH "FLASHEx_Option_Bytes_nRST_STDBY" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Option_Bytes_nRST_STDBY
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBOB_STDBY_NO_RST\fP   ((uint8_t)0x80)"
.br
.ti -1c
.RI "#define \fBOB_STDBY_RST\fP   ((uint8_t)0x00)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define OB_STDBY_NO_RST   ((uint8_t)0x80)"
No reset generated when entering in STANDBY 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 217 行定义\&.
.SS "#define OB_STDBY_RST   ((uint8_t)0x00)"
Reset generated when entering in STANDBY 
.br
 
.PP
在文件 stm32f4xx_hal_flash_ex\&.h 第 218 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
