.TH "GPIO_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBGPIO_InitTypeDef\fP"
.br
.RI "GPIO Init structure definition 
.br
 "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBGPIO_PinState\fP { \fBGPIO_PIN_RESET\fP = 0, \fBGPIO_PIN_SET\fP }"
.br
.RI "GPIO Bit SET and Bit RESET enumeration "
.in -1c
.SH "详细描述"
.PP 

.SH "枚举类型说明"
.PP 
.SS "enum \fBGPIO_PinState\fP"

.PP
GPIO Bit SET and Bit RESET enumeration 
.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIGPIO_PIN_RESET \fP\fP
.TP
\fB\fIGPIO_PIN_SET \fP\fP
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 68 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
