.TH "GPIO_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBGPIO_PinState\fP \fBHAL_GPIO_ReadPin\fP (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_WritePin\fP (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, \fBGPIO_PinState\fP PinState)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_TogglePin\fP (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_GPIO_LockPin\fP (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_EXTI_IRQHandler\fP (uint16_t GPIO_Pin)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_EXTI_Callback\fP (uint16_t GPIO_Pin)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)"

.SS "void HAL_GPIO_EXTI_IRQHandler (uint16_t GPIO_Pin)"

.SS "\fBHAL_StatusTypeDef\fP HAL_GPIO_LockPin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)"

.SS "\fBGPIO_PinState\fP HAL_GPIO_ReadPin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)"

.SS "void HAL_GPIO_TogglePin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)"

.SS "void HAL_GPIO_WritePin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, \fBGPIO_PinState\fP PinState)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
