.TH "GPIO_Exported_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_GPIO_EXTI_GET_FLAG\fP(__EXTI_LINE__)   (EXTI\->PR & (__EXTI_LINE__))"
.br
.RI "Checks whether the specified EXTI line flag is set or not\&. "
.ti -1c
.RI "#define \fB__HAL_GPIO_EXTI_CLEAR_FLAG\fP(__EXTI_LINE__)   (EXTI\->PR = (__EXTI_LINE__))"
.br
.RI "Clears the EXTI's line pending flags\&. "
.ti -1c
.RI "#define \fB__HAL_GPIO_EXTI_GET_IT\fP(__EXTI_LINE__)   (EXTI\->PR & (__EXTI_LINE__))"
.br
.RI "Checks whether the specified EXTI line is asserted or not\&. "
.ti -1c
.RI "#define \fB__HAL_GPIO_EXTI_CLEAR_IT\fP(__EXTI_LINE__)   (EXTI\->PR = (__EXTI_LINE__))"
.br
.RI "Clears the EXTI's line pending bits\&. "
.ti -1c
.RI "#define \fB__HAL_GPIO_EXTI_GENERATE_SWIT\fP(__EXTI_LINE__)   (EXTI\->SWIER |= (__EXTI_LINE__))"
.br
.RI "Generates a Software interrupt on selected EXTI line\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_GPIO_EXTI_CLEAR_FLAG(__EXTI_LINE__)   (EXTI\->PR = (__EXTI_LINE__))"

.PP
Clears the EXTI's line pending flags\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>EXTI_LINE</strong>\fP specifies the EXTI lines flags to clear\&. This parameter can be any combination of GPIO_PIN_x where x can be (0\&.\&.15) 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 185 行定义\&.
.SS "#define __HAL_GPIO_EXTI_CLEAR_IT(__EXTI_LINE__)   (EXTI\->PR = (__EXTI_LINE__))"

.PP
Clears the EXTI's line pending bits\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>EXTI_LINE</strong>\fP specifies the EXTI lines to clear\&. This parameter can be any combination of GPIO_PIN_x where x can be (0\&.\&.15) 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 201 行定义\&.
.SS "#define __HAL_GPIO_EXTI_GENERATE_SWIT(__EXTI_LINE__)   (EXTI\->SWIER |= (__EXTI_LINE__))"

.PP
Generates a Software interrupt on selected EXTI line\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>EXTI_LINE</strong>\fP specifies the EXTI line to check\&. This parameter can be GPIO_PIN_x where x can be(0\&.\&.15) 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 209 行定义\&.
.SS "#define __HAL_GPIO_EXTI_GET_FLAG(__EXTI_LINE__)   (EXTI\->PR & (__EXTI_LINE__))"

.PP
Checks whether the specified EXTI line flag is set or not\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>EXTI_LINE</strong>\fP specifies the EXTI line flag to check\&. This parameter can be GPIO_PIN_x where x can be(0\&.\&.15) 
.RE
.PP
\fB返回值\fP
.RS 4
\fIThe\fP new state of \fBEXTI_LINE\fP (SET or RESET)\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 177 行定义\&.
.SS "#define __HAL_GPIO_EXTI_GET_IT(__EXTI_LINE__)   (EXTI\->PR & (__EXTI_LINE__))"

.PP
Checks whether the specified EXTI line is asserted or not\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>EXTI_LINE</strong>\fP specifies the EXTI line to check\&. This parameter can be GPIO_PIN_x where x can be(0\&.\&.15) 
.RE
.PP
\fB返回值\fP
.RS 4
\fIThe\fP new state of \fBEXTI_LINE\fP (SET or RESET)\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 193 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
