.TH "GPIO_pins_define" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_pins_define
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBGPIO_PIN_0\fP   ((uint16_t)0x0001)  /* Pin 0 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_1\fP   ((uint16_t)0x0002)  /* Pin 1 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_2\fP   ((uint16_t)0x0004)  /* Pin 2 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_3\fP   ((uint16_t)0x0008)  /* Pin 3 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_4\fP   ((uint16_t)0x0010)  /* Pin 4 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_5\fP   ((uint16_t)0x0020)  /* Pin 5 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_6\fP   ((uint16_t)0x0040)  /* Pin 6 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_7\fP   ((uint16_t)0x0080)  /* Pin 7 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_8\fP   ((uint16_t)0x0100)  /* Pin 8 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_9\fP   ((uint16_t)0x0200)  /* Pin 9 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_10\fP   ((uint16_t)0x0400)  /* Pin 10 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_11\fP   ((uint16_t)0x0800)  /* Pin 11 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_12\fP   ((uint16_t)0x1000)  /* Pin 12 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_13\fP   ((uint16_t)0x2000)  /* Pin 13 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_14\fP   ((uint16_t)0x4000)  /* Pin 14 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_15\fP   ((uint16_t)0x8000)  /* Pin 15 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_All\fP   ((uint16_t)0xFFFF)  /* All pins selected */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_MASK\fP   0x0000FFFFU /* PIN mask for assert test */"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define GPIO_PIN_0   ((uint16_t)0x0001)  /* Pin 0 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 87 行定义\&.
.SS "#define GPIO_PIN_1   ((uint16_t)0x0002)  /* Pin 1 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 88 行定义\&.
.SS "#define GPIO_PIN_10   ((uint16_t)0x0400)  /* Pin 10 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 97 行定义\&.
.SS "#define GPIO_PIN_11   ((uint16_t)0x0800)  /* Pin 11 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 98 行定义\&.
.SS "#define GPIO_PIN_12   ((uint16_t)0x1000)  /* Pin 12 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 99 行定义\&.
.SS "#define GPIO_PIN_13   ((uint16_t)0x2000)  /* Pin 13 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 100 行定义\&.
.SS "#define GPIO_PIN_14   ((uint16_t)0x4000)  /* Pin 14 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 101 行定义\&.
.SS "#define GPIO_PIN_15   ((uint16_t)0x8000)  /* Pin 15 selected   */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 102 行定义\&.
.SS "#define GPIO_PIN_2   ((uint16_t)0x0004)  /* Pin 2 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 89 行定义\&.
.SS "#define GPIO_PIN_3   ((uint16_t)0x0008)  /* Pin 3 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 90 行定义\&.
.SS "#define GPIO_PIN_4   ((uint16_t)0x0010)  /* Pin 4 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 91 行定义\&.
.SS "#define GPIO_PIN_5   ((uint16_t)0x0020)  /* Pin 5 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 92 行定义\&.
.SS "#define GPIO_PIN_6   ((uint16_t)0x0040)  /* Pin 6 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 93 行定义\&.
.SS "#define GPIO_PIN_7   ((uint16_t)0x0080)  /* Pin 7 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 94 行定义\&.
.SS "#define GPIO_PIN_8   ((uint16_t)0x0100)  /* Pin 8 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 95 行定义\&.
.SS "#define GPIO_PIN_9   ((uint16_t)0x0200)  /* Pin 9 selected    */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 96 行定义\&.
.SS "#define GPIO_PIN_All   ((uint16_t)0xFFFF)  /* All pins selected */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 103 行定义\&.
.SS "#define GPIO_PIN_MASK   0x0000FFFFU /* PIN mask for assert test */"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 105 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
