.TH "GPIO_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBGPIO pins define\fP"
.br
.ti -1c
.RI "\fBGPIO mode define\fP"
.br
.RI "GPIO Configuration Mode Elements values convention: 0xX0yz00YZ "
.ti -1c
.RI "\fBGPIO speed define\fP"
.br
.RI "GPIO Output Maximum frequency "
.ti -1c
.RI "\fBGPIO pull define\fP"
.br
.RI "GPIO Pull-Up or Pull-Down Activation "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
