.TH "GPIO_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_GPIO_PIN_ACTION\fP(ACTION)   (((ACTION) == \fBGPIO_PIN_RESET\fP) || ((ACTION) == \fBGPIO_PIN_SET\fP))"
.br
.ti -1c
.RI "#define \fBIS_GPIO_PIN\fP(PIN)   ((((PIN) & \fBGPIO_PIN_MASK\fP ) != 0x00U) && (((PIN) & ~\fBGPIO_PIN_MASK\fP) == 0x00U))"
.br
.ti -1c
.RI "#define \fBIS_GPIO_MODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_SPEED\fP(SPEED)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_PULL\fP(PULL)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_GPIO_MODE(MODE)"
\fB值:\fP
.PP
.nf
                            (((MODE) == GPIO_MODE_INPUT)              ||\
                            ((MODE) == GPIO_MODE_OUTPUT_PP)          ||\
                            ((MODE) == GPIO_MODE_OUTPUT_OD)          ||\
                            ((MODE) == GPIO_MODE_AF_PP)              ||\
                            ((MODE) == GPIO_MODE_AF_OD)              ||\
                            ((MODE) == GPIO_MODE_IT_RISING)          ||\
                            ((MODE) == GPIO_MODE_IT_FALLING)         ||\
                            ((MODE) == GPIO_MODE_IT_RISING_FALLING)  ||\
                            ((MODE) == GPIO_MODE_EVT_RISING)         ||\
                            ((MODE) == GPIO_MODE_EVT_FALLING)        ||\
                            ((MODE) == GPIO_MODE_EVT_RISING_FALLING) ||\
                            ((MODE) == GPIO_MODE_ANALOG))
.fi
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 267 行定义\&.
.SS "#define IS_GPIO_PIN(PIN)   ((((PIN) & \fBGPIO_PIN_MASK\fP ) != 0x00U) && (((PIN) & ~\fBGPIO_PIN_MASK\fP) == 0x00U))"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 266 行定义\&.
.SS "#define IS_GPIO_PIN_ACTION(ACTION)   (((ACTION) == \fBGPIO_PIN_RESET\fP) || ((ACTION) == \fBGPIO_PIN_SET\fP))"

.PP
在文件 stm32f4xx_hal_gpio\&.h 第 265 行定义\&.
.SS "#define IS_GPIO_PULL(PULL)"
\fB值:\fP
.PP
.nf
                            (((PULL) == GPIO_NOPULL) || ((PULL) == GPIO_PULLUP) || \
                            ((PULL) == GPIO_PULLDOWN))
.fi
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 281 行定义\&.
.SS "#define IS_GPIO_SPEED(SPEED)"
\fB值:\fP
.PP
.nf
                              (((SPEED) == GPIO_SPEED_FREQ_LOW)  || ((SPEED) == GPIO_SPEED_FREQ_MEDIUM) || \
                              ((SPEED) == GPIO_SPEED_FREQ_HIGH) || ((SPEED) == GPIO_SPEED_FREQ_VERY_HIGH))
.fi
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 279 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
