.TH "GPIO_speed_define" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_speed_define \- GPIO Output Maximum frequency  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_LOW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_MEDIUM\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_HIGH\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_VERY_HIGH\fP   0x00000003U"
.br
.in -1c
.SH "详细描述"
.PP 
GPIO Output Maximum frequency 


.SH "宏定义说明"
.PP 
.SS "#define GPIO_SPEED_FREQ_HIGH   0x00000002U"
range 25 MHz to 100 MHz, please refer to the product datasheet 
.br
 
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 145 行定义\&.
.SS "#define GPIO_SPEED_FREQ_LOW   0x00000000U"
IO works at 2 MHz, please refer to the product datasheet 
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 143 行定义\&.
.SS "#define GPIO_SPEED_FREQ_MEDIUM   0x00000001U"
range 12,5 MHz to 50 MHz, please refer to the product datasheet 
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 144 行定义\&.
.SS "#define GPIO_SPEED_FREQ_VERY_HIGH   0x00000003U"
range 50 MHz to 200 MHz, please refer to the product datasheet 
.br
 
.PP
在文件 stm32f4xx_hal_gpio\&.h 第 146 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
