.TH "HAL" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL \- HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBHAL Exported Constants\fP"
.br
.ti -1c
.RI "\fBHAL Exported Macros\fP"
.br
.ti -1c
.RI "\fBHAL Private Macros\fP"
.br
.ti -1c
.RI "\fBHAL Private Variables\fP"
.br
.ti -1c
.RI "\fBHAL Private Constants\fP"
.br
.ti -1c
.RI "\fBHAL Exported Functions\fP"
.br
.in -1c
.SH "详细描述"
.PP 
HAL module driver\&. 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
