.TH "HAL_TSC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TSC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTSC_SYNC_POL_FALL\fP   TSC_SYNC_POLARITY_FALLING"
.br
.ti -1c
.RI "#define \fBTSC_SYNC_POL_RISE_HIGH\fP   TSC_SYNC_POLARITY_RISING"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TSC_SYNC_POL_FALL   TSC_SYNC_POLARITY_FALLING"

.PP
在文件 stm32_hal_legacy\&.h 第 982 行定义\&.
.SS "#define TSC_SYNC_POL_RISE_HIGH   TSC_SYNC_POLARITY_RISING"

.PP
在文件 stm32_hal_legacy\&.h 第 983 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
