.TH "HAL_I2S_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE\fP   IS_I2S_ALL_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE_EXT\fP   IS_I2S_ALL_INSTANCE_EXT"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_I2S_INSTANCE   IS_I2S_ALL_INSTANCE"

.PP
在文件 stm32_hal_legacy\&.h 第 1848 行定义\&.
.SS "#define IS_I2S_INSTANCE_EXT   IS_I2S_ALL_INSTANCE_EXT"

.PP
在文件 stm32_hal_legacy\&.h 第 1849 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
