.TH "HAL_LPTIM_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_LPTIM_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_CLOCKSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_2TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_4TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_8TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_RISINGEDGE\fP   LPTIM_CLOCKPOLARITY_RISING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_FALLINGEDGE\fP   LPTIM_CLOCKPOLARITY_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_BOTHEDGES\fP   LPTIM_CLOCKPOLARITY_RISING_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_TRIGSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSITION\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSITION\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSITION\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define LPTIM_CLOCKPOLARITY_BOTHEDGES   LPTIM_CLOCKPOLARITY_RISING_FALLING"

.PP
在文件 stm32_hal_legacy\&.h 第 662 行定义\&.
.SS "#define LPTIM_CLOCKPOLARITY_FALLINGEDGE   LPTIM_CLOCKPOLARITY_FALLING"

.PP
在文件 stm32_hal_legacy\&.h 第 661 行定义\&.
.SS "#define LPTIM_CLOCKPOLARITY_RISINGEDGE   LPTIM_CLOCKPOLARITY_RISING"

.PP
在文件 stm32_hal_legacy\&.h 第 660 行定义\&.
.SS "#define LPTIM_CLOCKSAMPLETIME_2TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_2TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 656 行定义\&.
.SS "#define LPTIM_CLOCKSAMPLETIME_4TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_4TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 657 行定义\&.
.SS "#define LPTIM_CLOCKSAMPLETIME_8TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_8TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 658 行定义\&.
.SS "#define LPTIM_CLOCKSAMPLETIME_DIRECTTRANSISTION   LPTIM_CLOCKSAMPLETIME_DIRECTTRANSITION"

.PP
在文件 stm32_hal_legacy\&.h 第 655 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_2TRANSISTIONS   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 665 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_2TRANSITION   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 671 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_4TRANSISTIONS   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 666 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_4TRANSITION   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 672 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_8TRANSISTIONS   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 667 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_8TRANSITION   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"

.PP
在文件 stm32_hal_legacy\&.h 第 673 行定义\&.
.SS "#define LPTIM_TRIGSAMPLETIME_DIRECTTRANSISTION   LPTIM_TRIGSAMPLETIME_DIRECTTRANSITION"

.PP
在文件 stm32_hal_legacy\&.h 第 664 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
