.TH "HAL_SMBUS_Aliased_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_SMBUS_Slave_Listen_IT\fP   \fBHAL_SMBUS_EnableListen_IT\fP"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_SlaveAddrCallback\fP   \fBHAL_SMBUS_AddrCallback\fP"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_SlaveListenCpltCallback\fP   \fBHAL_SMBUS_ListenCpltCallback\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_SMBUS_Slave_Listen_IT   \fBHAL_SMBUS_EnableListen_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1332 行定义\&.
.SS "#define HAL_SMBUS_SlaveAddrCallback   \fBHAL_SMBUS_AddrCallback\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1333 行定义\&.
.SS "#define HAL_SMBUS_SlaveListenCpltCallback   \fBHAL_SMBUS_ListenCpltCallback\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1334 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
