.TH "HAL_AES_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_AES_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBAES_IT_CC\fP   CRYP_IT_CC"
.br
.ti -1c
.RI "#define \fBAES_IT_ERR\fP   CRYP_IT_ERR"
.br
.ti -1c
.RI "#define \fBAES_FLAG_CCF\fP   CRYP_FLAG_CCF"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define AES_FLAG_CCF   CRYP_FLAG_CCF"

.PP
在文件 stm32_hal_legacy\&.h 第 1401 行定义\&.
.SS "#define AES_IT_CC   CRYP_IT_CC"

.PP
在文件 stm32_hal_legacy\&.h 第 1399 行定义\&.
.SS "#define AES_IT_ERR   CRYP_IT_ERR"

.PP
在文件 stm32_hal_legacy\&.h 第 1400 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
