.TH "HAL_TICK_FREQ" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TICK_FREQ
.SH SYNOPSIS
.br
.PP
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHAL_TickFreqTypeDef\fP { \fBHAL_TICK_FREQ_10HZ\fP = 100U, \fBHAL_TICK_FREQ_100HZ\fP = 10U, \fBHAL_TICK_FREQ_1KHZ\fP = 1U, \fBHAL_TICK_FREQ_DEFAULT\fP = HAL_TICK_FREQ_1KHZ }"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "枚举类型说明"
.PP 
.SS "enum \fBHAL_TickFreqTypeDef\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIHAL_TICK_FREQ_10HZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_100HZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_1KHZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_DEFAULT \fP\fP
.PP
在文件 stm32f4xx_hal\&.h 第 50 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
