.TH "HAL_SPI_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_SPI_1LINE_TX\fP   \fBSPI_1LINE_TX\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SPI_1LINE_RX\fP   \fBSPI_1LINE_RX\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SPI_RESET_CRC\fP   \fBSPI_RESET_CRC\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_SPI_1LINE_RX   \fBSPI_1LINE_RX\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3240 行定义\&.
.SS "#define __HAL_SPI_1LINE_TX   \fBSPI_1LINE_TX\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3239 行定义\&.
.SS "#define __HAL_SPI_RESET_CRC   \fBSPI_RESET_CRC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3241 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
