.TH "HAL_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__STM32F4xx_HAL_VERSION_MAIN\fP   (0x01U)"
.br
.RI "STM32F4xx HAL Driver version number V1\&.7\&.5 "
.ti -1c
.RI "#define \fB__STM32F4xx_HAL_VERSION_SUB1\fP   (0x07U)"
.br
.ti -1c
.RI "#define \fB__STM32F4xx_HAL_VERSION_SUB2\fP   (0x05U)"
.br
.ti -1c
.RI "#define \fB__STM32F4xx_HAL_VERSION_RC\fP   (0x00U)"
.br
.ti -1c
.RI "#define \fB__STM32F4xx_HAL_VERSION\fP"
.br
.ti -1c
.RI "#define \fBIDCODE_DEVID_MASK\fP   0x00000FFFU"
.br
.ti -1c
.RI "#define \fBSYSCFG_OFFSET\fP   (SYSCFG_BASE \- PERIPH_BASE)"
.br
.ti -1c
.RI "#define \fBMEMRMP_OFFSET\fP   \fBSYSCFG_OFFSET\fP"
.br
.ti -1c
.RI "#define \fBUFB_MODE_BIT_NUMBER\fP   SYSCFG_MEMRMP_UFB_MODE_Pos"
.br
.ti -1c
.RI "#define \fBUFB_MODE_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBMEMRMP_OFFSET\fP * 32U) + (\fBUFB_MODE_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBCMPCR_OFFSET\fP   (\fBSYSCFG_OFFSET\fP + 0x20U)"
.br
.ti -1c
.RI "#define \fBCMP_PD_BIT_NUMBER\fP   SYSCFG_CMPCR_CMP_PD_Pos"
.br
.ti -1c
.RI "#define \fBCMPCR_CMP_PD_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBCMPCR_OFFSET\fP * 32U) + (\fBCMP_PD_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBMCHDLYCR_OFFSET\fP   (\fBSYSCFG_OFFSET\fP + 0x30U)"
.br
.ti -1c
.RI "#define \fBBSCKSEL_BIT_NUMBER\fP   SYSCFG_MCHDLYCR_BSCKSEL_Pos"
.br
.ti -1c
.RI "#define \fBMCHDLYCR_BSCKSEL_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBMCHDLYCR_OFFSET\fP * 32U) + (\fBBSCKSEL_BIT_NUMBER\fP * 4U))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __STM32F4xx_HAL_VERSION"
\fB值:\fP
.PP
.nf
                                        ((__STM32F4xx_HAL_VERSION_MAIN << 24U)\
                                        |(__STM32F4xx_HAL_VERSION_SUB1 << 16U)\
                                        |(__STM32F4xx_HAL_VERSION_SUB2 << 8U )\
                                        |(__STM32F4xx_HAL_VERSION_RC))
.fi
.PP
在文件 stm32f4xx_hal\&.c 第 60 行定义\&.
.SS "#define __STM32F4xx_HAL_VERSION_MAIN   (0x01U)"

.PP
STM32F4xx HAL Driver version number V1\&.7\&.5 [31:24] main version 
.PP
在文件 stm32f4xx_hal\&.c 第 56 行定义\&.
.SS "#define __STM32F4xx_HAL_VERSION_RC   (0x00U)"
[7:0] release candidate 
.PP
在文件 stm32f4xx_hal\&.c 第 59 行定义\&.
.SS "#define __STM32F4xx_HAL_VERSION_SUB1   (0x07U)"
[23:16] sub1 version 
.PP
在文件 stm32f4xx_hal\&.c 第 57 行定义\&.
.SS "#define __STM32F4xx_HAL_VERSION_SUB2   (0x05U)"
[15:8] sub2 version 
.PP
在文件 stm32f4xx_hal\&.c 第 58 行定义\&.
.SS "#define BSCKSEL_BIT_NUMBER   SYSCFG_MCHDLYCR_BSCKSEL_Pos"

.PP
在文件 stm32f4xx_hal\&.c 第 84 行定义\&.
.SS "#define CMP_PD_BIT_NUMBER   SYSCFG_CMPCR_CMP_PD_Pos"

.PP
在文件 stm32f4xx_hal\&.c 第 78 行定义\&.
.SS "#define CMPCR_CMP_PD_BB   (uint32_t)(PERIPH_BB_BASE + (\fBCMPCR_OFFSET\fP * 32U) + (\fBCMP_PD_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal\&.c 第 79 行定义\&.
.SS "#define CMPCR_OFFSET   (\fBSYSCFG_OFFSET\fP + 0x20U)"

.PP
在文件 stm32f4xx_hal\&.c 第 77 行定义\&.
.SS "#define IDCODE_DEVID_MASK   0x00000FFFU"

.PP
在文件 stm32f4xx_hal\&.c 第 65 行定义\&.
.SS "#define MCHDLYCR_BSCKSEL_BB   (uint32_t)(PERIPH_BB_BASE + (\fBMCHDLYCR_OFFSET\fP * 32U) + (\fBBSCKSEL_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal\&.c 第 85 行定义\&.
.SS "#define MCHDLYCR_OFFSET   (\fBSYSCFG_OFFSET\fP + 0x30U)"

.PP
在文件 stm32f4xx_hal\&.c 第 83 行定义\&.
.SS "#define MEMRMP_OFFSET   \fBSYSCFG_OFFSET\fP"

.PP
在文件 stm32f4xx_hal\&.c 第 71 行定义\&.
.SS "#define SYSCFG_OFFSET   (SYSCFG_BASE \- PERIPH_BASE)"

.PP
在文件 stm32f4xx_hal\&.c 第 68 行定义\&.
.SS "#define UFB_MODE_BB   (uint32_t)(PERIPH_BB_BASE + (\fBMEMRMP_OFFSET\fP * 32U) + (\fBUFB_MODE_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal\&.c 第 73 行定义\&.
.SS "#define UFB_MODE_BIT_NUMBER   SYSCFG_MEMRMP_UFB_MODE_Pos"

.PP
在文件 stm32f4xx_hal\&.c 第 72 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
