.TH "HAL_SMBUS_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_DUALADDRESS_DISABLED\fP   \fBSMBUS_DUALADDRESS_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_DUALADDRESS_ENABLED\fP   \fBSMBUS_DUALADDRESS_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_GENERALCALL_DISABLED\fP   \fBSMBUS_GENERALCALL_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_GENERALCALL_ENABLED\fP   \fBSMBUS_GENERALCALL_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_NOSTRETCH_DISABLED\fP   \fBSMBUS_NOSTRETCH_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_NOSTRETCH_ENABLED\fP   \fBSMBUS_NOSTRETCH_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_ENABLED\fP   \fBSMBUS_ANALOGFILTER_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_DISABLED\fP   \fBSMBUS_ANALOGFILTER_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_PEC_DISABLED\fP   \fBSMBUS_PEC_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMBUS_PEC_ENABLED\fP   \fBSMBUS_PEC_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_STATE_SLAVE_LISTEN\fP   \fBHAL_SMBUS_STATE_LISTEN\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_SMBUS_STATE_SLAVE_LISTEN   \fBHAL_SMBUS_STATE_LISTEN\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 867 行定义\&.
.SS "#define SMBUS_ANALOGFILTER_DISABLED   \fBSMBUS_ANALOGFILTER_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 864 行定义\&.
.SS "#define SMBUS_ANALOGFILTER_ENABLED   \fBSMBUS_ANALOGFILTER_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 863 行定义\&.
.SS "#define SMBUS_DUALADDRESS_DISABLED   \fBSMBUS_DUALADDRESS_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 857 行定义\&.
.SS "#define SMBUS_DUALADDRESS_ENABLED   \fBSMBUS_DUALADDRESS_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 858 行定义\&.
.SS "#define SMBUS_GENERALCALL_DISABLED   \fBSMBUS_GENERALCALL_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 859 行定义\&.
.SS "#define SMBUS_GENERALCALL_ENABLED   \fBSMBUS_GENERALCALL_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 860 行定义\&.
.SS "#define SMBUS_NOSTRETCH_DISABLED   \fBSMBUS_NOSTRETCH_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 861 行定义\&.
.SS "#define SMBUS_NOSTRETCH_ENABLED   \fBSMBUS_NOSTRETCH_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 862 行定义\&.
.SS "#define SMBUS_PEC_DISABLED   \fBSMBUS_PEC_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 865 行定义\&.
.SS "#define SMBUS_PEC_ENABLED   \fBSMBUS_PEC_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 866 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
