.TH "HAL_Exported_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM2\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM2_STOP))"
.br
.RI "Freeze/Unfreeze Peripherals in Debug mode "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM3\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM3_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM4\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM4_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM5\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM5_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM6\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM6_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM7\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM7_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM12\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM12_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM13\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM13_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM14\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM14_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_RTC\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_RTC_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_WWDG\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_WWDG_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_IWDG\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_IWDG_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C1_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_I2C2_TIMEOUT\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C2_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_I2C3_TIMEOUT\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C3_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_CAN1\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_CAN1_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_CAN2\fP()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_CAN2_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM1\fP()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM1_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM8\fP()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM8_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM9\fP()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM9_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM10\fP()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM10_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM11\fP()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM11_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM2_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM3_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM4\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM4_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM5\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM5_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM6\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM6_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM7\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM7_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM12\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM12_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM13\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM13_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM14\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM14_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_RTC\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_RTC_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_WWDG_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_IWDG_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C1_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C2_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C3_SMBUS_TIMEOUT))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_CAN1\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_CAN1_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_CAN2\fP()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_CAN2_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM1\fP()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM1_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM8\fP()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM8_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM9\fP()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM9_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM10\fP()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM10_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM11\fP()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM11_STOP))"
.br
.ti -1c
.RI "#define \fB__HAL_SYSCFG_REMAPMEMORY_FLASH\fP()   (SYSCFG\->MEMRMP &= ~(SYSCFG_MEMRMP_MEM_MODE))"
.br
.RI "Main Flash memory mapped at 0x00000000 "
.ti -1c
.RI "#define \fB__HAL_SYSCFG_REMAPMEMORY_SYSTEMFLASH\fP()"
.br
.RI "System Flash memory mapped at 0x00000000 "
.ti -1c
.RI "#define \fB__HAL_SYSCFG_REMAPMEMORY_SRAM\fP()"
.br
.RI "Embedded SRAM mapped at 0x00000000 "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_DBGMCU_FREEZE_CAN1()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_CAN1_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 88 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_CAN2()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_CAN2_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 89 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_I2C1_TIMEOUT()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C1_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 85 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_I2C2_TIMEOUT()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C2_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 86 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_I2C3_TIMEOUT()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_I2C3_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 87 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_IWDG()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_IWDG_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 84 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_RTC()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_RTC_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 82 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM1()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM1_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 90 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM10()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM10_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 93 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM11()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM11_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 94 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM12()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM12_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 79 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM13()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM13_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 80 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM14()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM14_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 81 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM2()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM2_STOP))"

.PP
Freeze/Unfreeze Peripherals in Debug mode 
.PP
在文件 stm32f4xx_hal\&.h 第 73 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM3()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM3_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 74 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM4()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM4_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 75 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM5()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM5_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 76 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM6()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM6_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 77 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM7()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_TIM7_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 78 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM8()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM8_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 91 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_TIM9()   (DBGMCU\->APB2FZ |= (DBGMCU_APB2_FZ_DBG_TIM9_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 92 行定义\&.
.SS "#define __HAL_DBGMCU_FREEZE_WWDG()   (DBGMCU\->APB1FZ |= (DBGMCU_APB1_FZ_DBG_WWDG_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 83 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_CAN1()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_CAN1_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 111 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_CAN2()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_CAN2_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 112 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C1_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 108 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C2_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 109 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_I2C3_SMBUS_TIMEOUT))"

.PP
在文件 stm32f4xx_hal\&.h 第 110 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_IWDG()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_IWDG_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 107 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_RTC()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_RTC_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 105 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM1()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM1_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 113 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM10()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM10_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 116 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM11()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM11_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 117 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM12()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM12_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 102 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM13()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM13_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 103 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM14()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM14_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 104 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM2()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM2_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 96 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM3()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM3_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 97 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM4()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM4_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 98 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM5()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM5_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 99 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM6()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM6_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 100 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM7()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_TIM7_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 101 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM8()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM8_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 114 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_TIM9()   (DBGMCU\->APB2FZ &= ~(DBGMCU_APB2_FZ_DBG_TIM9_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 115 行定义\&.
.SS "#define __HAL_DBGMCU_UNFREEZE_WWDG()   (DBGMCU\->APB1FZ &= ~(DBGMCU_APB1_FZ_DBG_WWDG_STOP))"

.PP
在文件 stm32f4xx_hal\&.h 第 106 行定义\&.
.SS "#define __HAL_SYSCFG_REMAPMEMORY_FLASH()   (SYSCFG\->MEMRMP &= ~(SYSCFG_MEMRMP_MEM_MODE))"

.PP
Main Flash memory mapped at 0x00000000 
.PP
在文件 stm32f4xx_hal\&.h 第 121 行定义\&.
.SS "#define __HAL_SYSCFG_REMAPMEMORY_SRAM()"
\fB值:\fP
.PP
.nf
                                                  do {SYSCFG->MEMRMP &= ~(SYSCFG_MEMRMP_MEM_MODE);\
                                                  SYSCFG->MEMRMP |= (SYSCFG_MEMRMP_MEM_MODE_0 | SYSCFG_MEMRMP_MEM_MODE_1);\
                                                 }while(0);
.fi
.PP
Embedded SRAM mapped at 0x00000000 
.PP
在文件 stm32f4xx_hal\&.h 第 131 行定义\&.
.SS "#define __HAL_SYSCFG_REMAPMEMORY_SYSTEMFLASH()"
\fB值:\fP
.PP
.nf
                                                         do {SYSCFG->MEMRMP &= ~(SYSCFG_MEMRMP_MEM_MODE);\
                                                         SYSCFG->MEMRMP |= SYSCFG_MEMRMP_MEM_MODE_0;\
                                                        }while(0);
.fi
.PP
System Flash memory mapped at 0x00000000 
.PP
在文件 stm32f4xx_hal\&.h 第 125 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
