.TH "HAL_Aliased_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_EnableDBGSleepMode\fP   \fBHAL_DBGMCU_EnableDBGSleepMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGSleepMode\fP   \fBHAL_DBGMCU_DisableDBGSleepMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_EnableDBGStopMode\fP   \fBHAL_DBGMCU_EnableDBGStopMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGStopMode\fP   \fBHAL_DBGMCU_DisableDBGStopMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_EnableDBGStandbyMode\fP   \fBHAL_DBGMCU_EnableDBGStandbyMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_DisableDBGStandbyMode\fP   \fBHAL_DBGMCU_DisableDBGStandbyMode\fP"
.br
.ti -1c
.RI "#define \fBHAL_DBG_LowPowerConfig\fP(Periph,  cmd)   (((cmd)==ENABLE)? HAL_DBGMCU_DBG_EnableLowPowerConfig(Periph) : HAL_DBGMCU_DBG_DisableLowPowerConfig(Periph))"
.br
.ti -1c
.RI "#define \fBHAL_VREFINT_OutputSelect\fP   HAL_SYSCFG_VREFINT_OutputSelect"
.br
.ti -1c
.RI "#define \fBHAL_Lock_Cmd\fP(cmd)   (((cmd)==ENABLE) ? HAL_SYSCFG_Enable_Lock_VREFINT() : HAL_SYSCFG_Disable_Lock_VREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_VREFINT_Cmd\fP(cmd)   (((cmd)==ENABLE)? HAL_SYSCFG_EnableVREFINT() : HAL_SYSCFG_DisableVREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_ADC_EnableBuffer_Cmd\fP(cmd)   (((cmd)==ENABLE) ? HAL_ADCEx_EnableVREFINT() : HAL_ADCEx_DisableVREFINT())"
.br
.ti -1c
.RI "#define \fBHAL_ADC_EnableBufferSensor_Cmd\fP(cmd)   (((cmd)==ENABLE) ?  HAL_ADCEx_EnableVREFINTTempSensor() : HAL_ADCEx_DisableVREFINTTempSensor())"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_ADC_EnableBuffer_Cmd(cmd)   (((cmd)==ENABLE) ? HAL_ADCEx_EnableVREFINT() : HAL_ADCEx_DisableVREFINT())"

.PP
在文件 stm32_hal_legacy\&.h 第 1223 行定义\&.
.SS "#define HAL_ADC_EnableBufferSensor_Cmd(cmd)   (((cmd)==ENABLE) ?  HAL_ADCEx_EnableVREFINTTempSensor() : HAL_ADCEx_DisableVREFINTTempSensor())"

.PP
在文件 stm32_hal_legacy\&.h 第 1224 行定义\&.
.SS "#define HAL_DBG_LowPowerConfig(Periph, cmd)   (((cmd)==ENABLE)? HAL_DBGMCU_DBG_EnableLowPowerConfig(Periph) : HAL_DBGMCU_DBG_DisableLowPowerConfig(Periph))"

.PP
在文件 stm32_hal_legacy\&.h 第 1216 行定义\&.
.SS "#define HAL_DisableDBGSleepMode   \fBHAL_DBGMCU_DisableDBGSleepMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1211 行定义\&.
.SS "#define HAL_DisableDBGStandbyMode   \fBHAL_DBGMCU_DisableDBGStandbyMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1215 行定义\&.
.SS "#define HAL_DisableDBGStopMode   \fBHAL_DBGMCU_DisableDBGStopMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1213 行定义\&.
.SS "#define HAL_EnableDBGSleepMode   \fBHAL_DBGMCU_EnableDBGSleepMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1210 行定义\&.
.SS "#define HAL_EnableDBGStandbyMode   \fBHAL_DBGMCU_EnableDBGStandbyMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1214 行定义\&.
.SS "#define HAL_EnableDBGStopMode   \fBHAL_DBGMCU_EnableDBGStopMode\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1212 行定义\&.
.SS "#define HAL_Lock_Cmd(cmd)   (((cmd)==ENABLE) ? HAL_SYSCFG_Enable_Lock_VREFINT() : HAL_SYSCFG_Disable_Lock_VREFINT())"

.PP
在文件 stm32_hal_legacy\&.h 第 1218 行定义\&.
.SS "#define HAL_VREFINT_Cmd(cmd)   (((cmd)==ENABLE)? HAL_SYSCFG_EnableVREFINT() : HAL_SYSCFG_DisableVREFINT())"

.PP
在文件 stm32_hal_legacy\&.h 第 1221 行定义\&.
.SS "#define HAL_VREFINT_OutputSelect   HAL_SYSCFG_VREFINT_OutputSelect"

.PP
在文件 stm32_hal_legacy\&.h 第 1217 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
