.TH "HAL_SYSCFG_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SYSCFG_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PA9\fP   I2C_FASTMODEPLUS_PA9"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PA10\fP   I2C_FASTMODEPLUS_PA10"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB6\fP   I2C_FASTMODEPLUS_PB6"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB7\fP   I2C_FASTMODEPLUS_PB7"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB8\fP   I2C_FASTMODEPLUS_PB8"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C_PB9\fP   I2C_FASTMODEPLUS_PB9"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C1\fP   I2C_FASTMODEPLUS_I2C1"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C2\fP   I2C_FASTMODEPLUS_I2C2"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_FASTMODEPLUS_I2C3\fP   I2C_FASTMODEPLUS_I2C3"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C1   I2C_FASTMODEPLUS_I2C1"

.PP
在文件 stm32_hal_legacy\&.h 第 487 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C2   I2C_FASTMODEPLUS_I2C2"

.PP
在文件 stm32_hal_legacy\&.h 第 488 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C3   I2C_FASTMODEPLUS_I2C3"

.PP
在文件 stm32_hal_legacy\&.h 第 489 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PA10   I2C_FASTMODEPLUS_PA10"

.PP
在文件 stm32_hal_legacy\&.h 第 482 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PA9   I2C_FASTMODEPLUS_PA9"

.PP
在文件 stm32_hal_legacy\&.h 第 481 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PB6   I2C_FASTMODEPLUS_PB6"

.PP
在文件 stm32_hal_legacy\&.h 第 483 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PB7   I2C_FASTMODEPLUS_PB7"

.PP
在文件 stm32_hal_legacy\&.h 第 484 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PB8   I2C_FASTMODEPLUS_PB8"

.PP
在文件 stm32_hal_legacy\&.h 第 485 行定义\&.
.SS "#define HAL_SYSCFG_FASTMODEPLUS_I2C_PB9   I2C_FASTMODEPLUS_PB9"

.PP
在文件 stm32_hal_legacy\&.h 第 486 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
