.TH "HAL_CEC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_CEC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_CEC_GET_IT\fP   __HAL_CEC_GET_FLAG"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_CEC_GET_IT   __HAL_CEC_GET_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 110 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
