.TH "HAL_NAND_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_NAND_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_NAND_Read_Page\fP   HAL_NAND_Read_Page_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Write_Page\fP   HAL_NAND_Write_Page_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Read_SpareArea\fP   HAL_NAND_Read_SpareArea_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Write_SpareArea\fP   HAL_NAND_Write_SpareArea_8b"
.br
.ti -1c
.RI "#define \fBNAND_AddressTypedef\fP   NAND_AddressTypeDef"
.br
.ti -1c
.RI "#define \fB__ARRAY_ADDRESS\fP   ARRAY_ADDRESS"
.br
.ti -1c
.RI "#define \fB__ADDR_1st_CYCLE\fP   ADDR_1ST_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_2nd_CYCLE\fP   ADDR_2ND_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_3rd_CYCLE\fP   ADDR_3RD_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_4th_CYCLE\fP   ADDR_4TH_CYCLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __ADDR_1st_CYCLE   ADDR_1ST_CYCLE"

.PP
在文件 stm32_hal_legacy\&.h 第 690 行定义\&.
.SS "#define __ADDR_2nd_CYCLE   ADDR_2ND_CYCLE"

.PP
在文件 stm32_hal_legacy\&.h 第 691 行定义\&.
.SS "#define __ADDR_3rd_CYCLE   ADDR_3RD_CYCLE"

.PP
在文件 stm32_hal_legacy\&.h 第 692 行定义\&.
.SS "#define __ADDR_4th_CYCLE   ADDR_4TH_CYCLE"

.PP
在文件 stm32_hal_legacy\&.h 第 693 行定义\&.
.SS "#define __ARRAY_ADDRESS   ARRAY_ADDRESS"

.PP
在文件 stm32_hal_legacy\&.h 第 689 行定义\&.
.SS "#define HAL_NAND_Read_Page   HAL_NAND_Read_Page_8b"

.PP
在文件 stm32_hal_legacy\&.h 第 682 行定义\&.
.SS "#define HAL_NAND_Read_SpareArea   HAL_NAND_Read_SpareArea_8b"

.PP
在文件 stm32_hal_legacy\&.h 第 684 行定义\&.
.SS "#define HAL_NAND_Write_Page   HAL_NAND_Write_Page_8b"

.PP
在文件 stm32_hal_legacy\&.h 第 683 行定义\&.
.SS "#define HAL_NAND_Write_SpareArea   HAL_NAND_Write_SpareArea_8b"

.PP
在文件 stm32_hal_legacy\&.h 第 685 行定义\&.
.SS "#define NAND_AddressTypedef   NAND_AddressTypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 687 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
