.TH "HAL_USART_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_USART_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUSART_CLOCK_DISABLED\fP   \fBUSART_CLOCK_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBUSART_CLOCK_ENABLED\fP   \fBUSART_CLOCK_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBUSARTNACK_ENABLED\fP   \fBUSART_NACK_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBUSARTNACK_DISABLED\fP   \fBUSART_NACK_DISABLE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define USART_CLOCK_DISABLED   \fBUSART_CLOCK_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1023 行定义\&.
.SS "#define USART_CLOCK_ENABLED   \fBUSART_CLOCK_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1024 行定义\&.
.SS "#define USARTNACK_DISABLED   \fBUSART_NACK_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1027 行定义\&.
.SS "#define USARTNACK_ENABLED   \fBUSART_NACK_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1026 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
