.TH "HAL_DMA_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DMA_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_REMAPDMA_ADC_DMA_CH2\fP   DMA_REMAP_ADC_DMA_CH2"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART1_TX_DMA_CH4\fP   DMA_REMAP_USART1_TX_DMA_CH4"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART1_RX_DMA_CH5\fP   DMA_REMAP_USART1_RX_DMA_CH5"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM16_DMA_CH4\fP   DMA_REMAP_TIM16_DMA_CH4"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM17_DMA_CH2\fP   DMA_REMAP_TIM17_DMA_CH2"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART3_DMA_CH32\fP   DMA_REMAP_USART3_DMA_CH32"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM16_DMA_CH6\fP   DMA_REMAP_TIM16_DMA_CH6"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM17_DMA_CH7\fP   DMA_REMAP_TIM17_DMA_CH7"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_SPI2_DMA_CH67\fP   DMA_REMAP_SPI2_DMA_CH67"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART2_DMA_CH67\fP   DMA_REMAP_USART2_DMA_CH67"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_I2C1_DMA_CH76\fP   DMA_REMAP_I2C1_DMA_CH76"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM1_DMA_CH6\fP   DMA_REMAP_TIM1_DMA_CH6"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM2_DMA_CH7\fP   DMA_REMAP_TIM2_DMA_CH7"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM3_DMA_CH6\fP   DMA_REMAP_TIM3_DMA_CH6"
.br
.ti -1c
.RI "#define \fBIS_HAL_REMAPDMA\fP   IS_DMA_REMAP"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPDMA_CHANNEL_ENABLE\fP   __HAL_DMA_REMAP_CHANNEL_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPDMA_CHANNEL_DISABLE\fP   __HAL_DMA_REMAP_CHANNEL_DISABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_REMAPDMA_CHANNEL_DISABLE   __HAL_DMA_REMAP_CHANNEL_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 264 行定义\&.
.SS "#define __HAL_REMAPDMA_CHANNEL_ENABLE   __HAL_DMA_REMAP_CHANNEL_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 263 行定义\&.
.SS "#define HAL_REMAPDMA_ADC_DMA_CH2   DMA_REMAP_ADC_DMA_CH2"

.PP
在文件 stm32_hal_legacy\&.h 第 247 行定义\&.
.SS "#define HAL_REMAPDMA_I2C1_DMA_CH76   DMA_REMAP_I2C1_DMA_CH76"

.PP
在文件 stm32_hal_legacy\&.h 第 257 行定义\&.
.SS "#define HAL_REMAPDMA_SPI2_DMA_CH67   DMA_REMAP_SPI2_DMA_CH67"

.PP
在文件 stm32_hal_legacy\&.h 第 255 行定义\&.
.SS "#define HAL_REMAPDMA_TIM16_DMA_CH4   DMA_REMAP_TIM16_DMA_CH4"

.PP
在文件 stm32_hal_legacy\&.h 第 250 行定义\&.
.SS "#define HAL_REMAPDMA_TIM16_DMA_CH6   DMA_REMAP_TIM16_DMA_CH6"

.PP
在文件 stm32_hal_legacy\&.h 第 253 行定义\&.
.SS "#define HAL_REMAPDMA_TIM17_DMA_CH2   DMA_REMAP_TIM17_DMA_CH2"

.PP
在文件 stm32_hal_legacy\&.h 第 251 行定义\&.
.SS "#define HAL_REMAPDMA_TIM17_DMA_CH7   DMA_REMAP_TIM17_DMA_CH7"

.PP
在文件 stm32_hal_legacy\&.h 第 254 行定义\&.
.SS "#define HAL_REMAPDMA_TIM1_DMA_CH6   DMA_REMAP_TIM1_DMA_CH6"

.PP
在文件 stm32_hal_legacy\&.h 第 258 行定义\&.
.SS "#define HAL_REMAPDMA_TIM2_DMA_CH7   DMA_REMAP_TIM2_DMA_CH7"

.PP
在文件 stm32_hal_legacy\&.h 第 259 行定义\&.
.SS "#define HAL_REMAPDMA_TIM3_DMA_CH6   DMA_REMAP_TIM3_DMA_CH6"

.PP
在文件 stm32_hal_legacy\&.h 第 260 行定义\&.
.SS "#define HAL_REMAPDMA_USART1_RX_DMA_CH5   DMA_REMAP_USART1_RX_DMA_CH5"

.PP
在文件 stm32_hal_legacy\&.h 第 249 行定义\&.
.SS "#define HAL_REMAPDMA_USART1_TX_DMA_CH4   DMA_REMAP_USART1_TX_DMA_CH4"

.PP
在文件 stm32_hal_legacy\&.h 第 248 行定义\&.
.SS "#define HAL_REMAPDMA_USART2_DMA_CH67   DMA_REMAP_USART2_DMA_CH67"

.PP
在文件 stm32_hal_legacy\&.h 第 256 行定义\&.
.SS "#define HAL_REMAPDMA_USART3_DMA_CH32   DMA_REMAP_USART3_DMA_CH32"

.PP
在文件 stm32_hal_legacy\&.h 第 252 行定义\&.
.SS "#define IS_HAL_REMAPDMA   IS_DMA_REMAP"

.PP
在文件 stm32_hal_legacy\&.h 第 262 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
