.TH "HAL_DBGMCU_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DBGMCU_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM1_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM1\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM1_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM1\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM2_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM2_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM3_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM3\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM3_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM4_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM4\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM4_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM4\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM5_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM5\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM5_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM5\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM6_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM6\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM6_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM6\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM7_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM7\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM7_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM7\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM8_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM8\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM8_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM8\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM9_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM9\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM9_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM9\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM10_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM10\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM10_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM10\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM11_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM11\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM11_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM11\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM12_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM12\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM12_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM12\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM13_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM13\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM13_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM13\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM14_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM14\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM14_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM14\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_CAN2_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_CAN2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_CAN2_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_CAN2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM15_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM15"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM15_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM15"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM16_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM16"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM16_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM16"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM17_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM17"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM17_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM17"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_RTC_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_RTC\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_RTC_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_RTC\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_WWDG_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_WWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_WWDG_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_IWDG_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_IWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_IWDG_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C1_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C1_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C2_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_I2C2_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C2_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C3_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_I2C3_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C3_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_CAN1_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_CAN1\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_CAN1_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_CAN1\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_LPTIM1_DBGMCU\fP   __HAL_DBGMCU_FREEZE_LPTIM1"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_LPTIM1_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_LPTIM1"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_LPTIM2_DBGMCU\fP   __HAL_DBGMCU_FREEZE_LPTIM2"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_LPTIM2_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_LPTIM2"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_FREEZE_CAN1_DBGMCU   \fB__HAL_DBGMCU_FREEZE_CAN1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1592 行定义\&.
.SS "#define __HAL_FREEZE_CAN2_DBGMCU   \fB__HAL_DBGMCU_FREEZE_CAN2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1563 行定义\&.
.SS "#define __HAL_FREEZE_I2C1_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1586 行定义\&.
.SS "#define __HAL_FREEZE_I2C2_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_FREEZE_I2C2_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1588 行定义\&.
.SS "#define __HAL_FREEZE_I2C3_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_FREEZE_I2C3_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1590 行定义\&.
.SS "#define __HAL_FREEZE_IWDG_DBGMCU   \fB__HAL_DBGMCU_FREEZE_IWDG\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1583 行定义\&.
.SS "#define __HAL_FREEZE_LPTIM1_DBGMCU   __HAL_DBGMCU_FREEZE_LPTIM1"

.PP
在文件 stm32_hal_legacy\&.h 第 1594 行定义\&.
.SS "#define __HAL_FREEZE_LPTIM2_DBGMCU   __HAL_DBGMCU_FREEZE_LPTIM2"

.PP
在文件 stm32_hal_legacy\&.h 第 1596 行定义\&.
.SS "#define __HAL_FREEZE_RTC_DBGMCU   \fB__HAL_DBGMCU_FREEZE_RTC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1573 行定义\&.
.SS "#define __HAL_FREEZE_TIM10_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM10\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1553 行定义\&.
.SS "#define __HAL_FREEZE_TIM11_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM11\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1555 行定义\&.
.SS "#define __HAL_FREEZE_TIM12_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM12\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1557 行定义\&.
.SS "#define __HAL_FREEZE_TIM13_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM13\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1559 行定义\&.
.SS "#define __HAL_FREEZE_TIM14_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM14\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1561 行定义\&.
.SS "#define __HAL_FREEZE_TIM15_DBGMCU   __HAL_DBGMCU_FREEZE_TIM15"

.PP
在文件 stm32_hal_legacy\&.h 第 1567 行定义\&.
.SS "#define __HAL_FREEZE_TIM16_DBGMCU   __HAL_DBGMCU_FREEZE_TIM16"

.PP
在文件 stm32_hal_legacy\&.h 第 1569 行定义\&.
.SS "#define __HAL_FREEZE_TIM17_DBGMCU   __HAL_DBGMCU_FREEZE_TIM17"

.PP
在文件 stm32_hal_legacy\&.h 第 1571 行定义\&.
.SS "#define __HAL_FREEZE_TIM1_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1534 行定义\&.
.SS "#define __HAL_FREEZE_TIM2_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1536 行定义\&.
.SS "#define __HAL_FREEZE_TIM3_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM3\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1538 行定义\&.
.SS "#define __HAL_FREEZE_TIM4_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1540 行定义\&.
.SS "#define __HAL_FREEZE_TIM5_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM5\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1542 行定义\&.
.SS "#define __HAL_FREEZE_TIM6_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM6\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1544 行定义\&.
.SS "#define __HAL_FREEZE_TIM7_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM7\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1546 行定义\&.
.SS "#define __HAL_FREEZE_TIM8_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1548 行定义\&.
.SS "#define __HAL_FREEZE_TIM9_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM9\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1551 行定义\&.
.SS "#define __HAL_FREEZE_WWDG_DBGMCU   \fB__HAL_DBGMCU_FREEZE_WWDG\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1581 行定义\&.
.SS "#define __HAL_UNFREEZE_CAN1_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_CAN1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1593 行定义\&.
.SS "#define __HAL_UNFREEZE_CAN2_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_CAN2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1564 行定义\&.
.SS "#define __HAL_UNFREEZE_I2C1_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1587 行定义\&.
.SS "#define __HAL_UNFREEZE_I2C2_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1589 行定义\&.
.SS "#define __HAL_UNFREEZE_I2C3_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1591 行定义\&.
.SS "#define __HAL_UNFREEZE_IWDG_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1584 行定义\&.
.SS "#define __HAL_UNFREEZE_LPTIM1_DBGMCU   __HAL_DBGMCU_UNFREEZE_LPTIM1"

.PP
在文件 stm32_hal_legacy\&.h 第 1595 行定义\&.
.SS "#define __HAL_UNFREEZE_LPTIM2_DBGMCU   __HAL_DBGMCU_UNFREEZE_LPTIM2"

.PP
在文件 stm32_hal_legacy\&.h 第 1597 行定义\&.
.SS "#define __HAL_UNFREEZE_RTC_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_RTC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1574 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM10_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM10\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1554 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM11_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM11\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1556 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM12_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM12\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1558 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM13_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM13\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1560 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM14_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM14\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1562 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM15_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM15"

.PP
在文件 stm32_hal_legacy\&.h 第 1568 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM16_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM16"

.PP
在文件 stm32_hal_legacy\&.h 第 1570 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM17_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM17"

.PP
在文件 stm32_hal_legacy\&.h 第 1572 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM1_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1535 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM2_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1537 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM3_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1539 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM4_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1541 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM5_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM5\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1543 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM6_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM6\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1545 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM7_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM7\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1547 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM8_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1549 行定义\&.
.SS "#define __HAL_UNFREEZE_TIM9_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM9\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1552 行定义\&.
.SS "#define __HAL_UNFREEZE_WWDG_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1582 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
