.TH "HAL_UART_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_DISABLED\fP   UART_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_ENABLED\fP   UART_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_DISABLED\fP   UART_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_ENABLED\fP   UART_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_ENABLE\fP   \fB__HAL_UART_ONE_BIT_SAMPLE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_DISABLE\fP   \fB__HAL_UART_ONE_BIT_SAMPLE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING16\fP   \fBUART_DIV_SAMPLING16\fP"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING16\fP   \fBUART_DIVMANT_SAMPLING16\fP"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING16\fP   \fBUART_DIVFRAQ_SAMPLING16\fP"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING16\fP   \fBUART_BRR_SAMPLING16\fP"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING8\fP   \fBUART_DIV_SAMPLING8\fP"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING8\fP   \fBUART_DIVMANT_SAMPLING8\fP"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING8\fP   \fBUART_DIVFRAQ_SAMPLING8\fP"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING8\fP   \fBUART_BRR_SAMPLING8\fP"
.br
.ti -1c
.RI "#define \fB__DIV_LPUART\fP   UART_DIV_LPUART"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_IDLELINE\fP   \fBUART_WAKEUPMETHOD_IDLELINE\fP"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_ADDRESSMARK\fP   \fBUART_WAKEUPMETHOD_ADDRESSMARK\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __DIV_LPUART   UART_DIV_LPUART"

.PP
在文件 stm32_hal_legacy\&.h 第 1009 行定义\&.
.SS "#define __DIV_SAMPLING16   \fBUART_DIV_SAMPLING16\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 999 行定义\&.
.SS "#define __DIV_SAMPLING8   \fBUART_DIV_SAMPLING8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1004 行定义\&.
.SS "#define __DIVFRAQ_SAMPLING16   \fBUART_DIVFRAQ_SAMPLING16\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1001 行定义\&.
.SS "#define __DIVFRAQ_SAMPLING8   \fBUART_DIVFRAQ_SAMPLING8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1006 行定义\&.
.SS "#define __DIVMANT_SAMPLING16   \fBUART_DIVMANT_SAMPLING16\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1000 行定义\&.
.SS "#define __DIVMANT_SAMPLING8   \fBUART_DIVMANT_SAMPLING8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1005 行定义\&.
.SS "#define __HAL_UART_ONEBIT_DISABLE   \fB__HAL_UART_ONE_BIT_SAMPLE_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 997 行定义\&.
.SS "#define __HAL_UART_ONEBIT_ENABLE   \fB__HAL_UART_ONE_BIT_SAMPLE_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 996 行定义\&.
.SS "#define __UART_BRR_SAMPLING16   \fBUART_BRR_SAMPLING16\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1002 行定义\&.
.SS "#define __UART_BRR_SAMPLING8   \fBUART_BRR_SAMPLING8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1007 行定义\&.
.SS "#define UART_ONE_BIT_SAMPLE_DISABLED   UART_ONE_BIT_SAMPLE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 993 行定义\&.
.SS "#define UART_ONE_BIT_SAMPLE_ENABLED   UART_ONE_BIT_SAMPLE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 994 行定义\&.
.SS "#define UART_ONEBIT_SAMPLING_DISABLED   UART_ONE_BIT_SAMPLE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 991 行定义\&.
.SS "#define UART_ONEBIT_SAMPLING_ENABLED   UART_ONE_BIT_SAMPLE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 992 行定义\&.
.SS "#define UART_WAKEUPMETHODE_ADDRESSMARK   \fBUART_WAKEUPMETHOD_ADDRESSMARK\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1012 行定义\&.
.SS "#define UART_WAKEUPMETHODE_IDLELINE   \fBUART_WAKEUPMETHOD_IDLELINE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1011 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
