.TH "HAL_SD_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SD_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSD_OCR_CID_CSD_OVERWRIETE\fP   SD_OCR_CID_CSD_OVERWRITE"
.br
.ti -1c
.RI "#define \fBSD_CMD_SD_APP_STAUS\fP   SD_CMD_SD_APP_STATUS"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SD_CMD_SD_APP_STAUS   SD_CMD_SD_APP_STATUS"

.PP
在文件 stm32_hal_legacy\&.h 第 3124 行定义\&.
.SS "#define SD_OCR_CID_CSD_OVERWRIETE   SD_OCR_CID_CSD_OVERWRITE"

.PP
在文件 stm32_hal_legacy\&.h 第 3123 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
