.TH "HAL_TIM_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TIM_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_TIM_SetICPrescalerValue\fP   \fBTIM_SET_ICPRESCALERVALUE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_ResetICPrescalerValue\fP   \fBTIM_RESET_ICPRESCALERVALUE\fP"
.br
.ti -1c
.RI "#define \fBTIM_GET_ITSTATUS\fP   \fB__HAL_TIM_GET_IT_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBTIM_GET_CLEAR_IT\fP   \fB__HAL_TIM_CLEAR_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GET_ITSTATUS\fP   \fB__HAL_TIM_GET_IT_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_DIRECTION_STATUS\fP   \fB__HAL_TIM_IS_TIM_COUNTING_DOWN\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_PRESCALER\fP   \fB__HAL_TIM_SET_PRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetCounter\fP   \fB__HAL_TIM_SET_COUNTER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetCounter\fP   \fB__HAL_TIM_GET_COUNTER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetAutoreload\fP   \fB__HAL_TIM_SET_AUTORELOAD\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetAutoreload\fP   \fB__HAL_TIM_GET_AUTORELOAD\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetClockDivision\fP   \fB__HAL_TIM_SET_CLOCKDIVISION\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetClockDivision\fP   \fB__HAL_TIM_GET_CLOCKDIVISION\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetICPrescaler\fP   \fB__HAL_TIM_SET_ICPRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetICPrescaler\fP   \fB__HAL_TIM_GET_ICPRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetCompare\fP   \fB__HAL_TIM_SET_COMPARE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetCompare\fP   \fB__HAL_TIM_GET_COMPARE\fP"
.br
.ti -1c
.RI "#define \fBTIM_BREAKINPUTSOURCE_DFSDM\fP   TIM_BREAKINPUTSOURCE_DFSDM1"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_TIM_DIRECTION_STATUS   \fB__HAL_TIM_IS_TIM_COUNTING_DOWN\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3343 行定义\&.
.SS "#define __HAL_TIM_GET_ITSTATUS   \fB__HAL_TIM_GET_IT_SOURCE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3341 行定义\&.
.SS "#define __HAL_TIM_GetAutoreload   \fB__HAL_TIM_GET_AUTORELOAD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3348 行定义\&.
.SS "#define __HAL_TIM_GetClockDivision   \fB__HAL_TIM_GET_CLOCKDIVISION\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3350 行定义\&.
.SS "#define __HAL_TIM_GetCompare   \fB__HAL_TIM_GET_COMPARE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3354 行定义\&.
.SS "#define __HAL_TIM_GetCounter   \fB__HAL_TIM_GET_COUNTER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3346 行定义\&.
.SS "#define __HAL_TIM_GetICPrescaler   \fB__HAL_TIM_GET_ICPRESCALER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3352 行定义\&.
.SS "#define __HAL_TIM_PRESCALER   \fB__HAL_TIM_SET_PRESCALER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3344 行定义\&.
.SS "#define __HAL_TIM_ResetICPrescalerValue   \fBTIM_RESET_ICPRESCALERVALUE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3336 行定义\&.
.SS "#define __HAL_TIM_SetAutoreload   \fB__HAL_TIM_SET_AUTORELOAD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3347 行定义\&.
.SS "#define __HAL_TIM_SetClockDivision   \fB__HAL_TIM_SET_CLOCKDIVISION\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3349 行定义\&.
.SS "#define __HAL_TIM_SetCompare   \fB__HAL_TIM_SET_COMPARE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3353 行定义\&.
.SS "#define __HAL_TIM_SetCounter   \fB__HAL_TIM_SET_COUNTER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3345 行定义\&.
.SS "#define __HAL_TIM_SetICPrescaler   \fB__HAL_TIM_SET_ICPRESCALER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3351 行定义\&.
.SS "#define __HAL_TIM_SetICPrescalerValue   \fBTIM_SET_ICPRESCALERVALUE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3335 行定义\&.
.SS "#define TIM_BREAKINPUTSOURCE_DFSDM   TIM_BREAKINPUTSOURCE_DFSDM1"

.PP
在文件 stm32_hal_legacy\&.h 第 3356 行定义\&.
.SS "#define TIM_GET_CLEAR_IT   \fB__HAL_TIM_CLEAR_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3339 行定义\&.
.SS "#define TIM_GET_ITSTATUS   \fB__HAL_TIM_GET_IT_SOURCE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3338 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
