.TH "HAL_CORTEX_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_CORTEX_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_CORTEX_SYSTICKCLK_CONFIG\fP   \fBHAL_SYSTICK_CLKSourceConfig\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_CORTEX_SYSTICKCLK_CONFIG   \fBHAL_SYSTICK_CLKSourceConfig\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 210 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
