.TH "HAL_GPIO_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_GPIO_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBGET_GPIO_SOURCE\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGET_GPIO_INDEX\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGPIO_AF0_LPTIM\fP   GPIO_AF0_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF1_LPTIM\fP   GPIO_AF1_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF2_LPTIM\fP   GPIO_AF2_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF6_DFSDM\fP   GPIO_AF6_DFSDM1"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define GET_GPIO_INDEX   GPIO_GET_INDEX"

.PP
在文件 stm32_hal_legacy\&.h 第 527 行定义\&.
.SS "#define GET_GPIO_SOURCE   GPIO_GET_INDEX"

.PP
在文件 stm32_hal_legacy\&.h 第 526 行定义\&.
.SS "#define GPIO_AF0_LPTIM   GPIO_AF0_LPTIM1"

.PP
在文件 stm32_hal_legacy\&.h 第 553 行定义\&.
.SS "#define GPIO_AF1_LPTIM   GPIO_AF1_LPTIM1"

.PP
在文件 stm32_hal_legacy\&.h 第 554 行定义\&.
.SS "#define GPIO_AF2_LPTIM   GPIO_AF2_LPTIM1"

.PP
在文件 stm32_hal_legacy\&.h 第 555 行定义\&.
.SS "#define GPIO_AF6_DFSDM   GPIO_AF6_DFSDM1"

.PP
在文件 stm32_hal_legacy\&.h 第 577 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
