.TH "HAL_PCCARD_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PCCARD_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBCF_DATA\fP   ATA_DATA"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_COUNT\fP   ATA_SECTOR_COUNT"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_NUMBER\fP   ATA_SECTOR_NUMBER"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_LOW\fP   ATA_CYLINDER_LOW"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_HIGH\fP   ATA_CYLINDER_HIGH"
.br
.ti -1c
.RI "#define \fBCF_CARD_HEAD\fP   ATA_CARD_HEAD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD\fP   ATA_STATUS_CMD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD_ALTERNATE\fP   ATA_STATUS_CMD_ALTERNATE"
.br
.ti -1c
.RI "#define \fBCF_COMMON_DATA_AREA\fP   ATA_COMMON_DATA_AREA"
.br
.ti -1c
.RI "#define \fBCF_READ_SECTOR_CMD\fP   ATA_READ_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_WRITE_SECTOR_CMD\fP   ATA_WRITE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_ERASE_SECTOR_CMD\fP   ATA_ERASE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_IDENTIFY_CMD\fP   ATA_IDENTIFY_CMD"
.br
.ti -1c
.RI "#define \fBPCCARD_StatusTypedef\fP   HAL_PCCARD_StatusTypeDef"
.br
.ti -1c
.RI "#define \fBPCCARD_SUCCESS\fP   HAL_PCCARD_STATUS_SUCCESS"
.br
.ti -1c
.RI "#define \fBPCCARD_ONGOING\fP   HAL_PCCARD_STATUS_ONGOING"
.br
.ti -1c
.RI "#define \fBPCCARD_ERROR\fP   HAL_PCCARD_STATUS_ERROR"
.br
.ti -1c
.RI "#define \fBPCCARD_TIMEOUT\fP   HAL_PCCARD_STATUS_TIMEOUT"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CF_CARD_HEAD   ATA_CARD_HEAD"

.PP
在文件 stm32_hal_legacy\&.h 第 777 行定义\&.
.SS "#define CF_COMMON_DATA_AREA   ATA_COMMON_DATA_AREA"

.PP
在文件 stm32_hal_legacy\&.h 第 780 行定义\&.
.SS "#define CF_CYLINDER_HIGH   ATA_CYLINDER_HIGH"

.PP
在文件 stm32_hal_legacy\&.h 第 776 行定义\&.
.SS "#define CF_CYLINDER_LOW   ATA_CYLINDER_LOW"

.PP
在文件 stm32_hal_legacy\&.h 第 775 行定义\&.
.SS "#define CF_DATA   ATA_DATA"

.PP
在文件 stm32_hal_legacy\&.h 第 772 行定义\&.
.SS "#define CF_ERASE_SECTOR_CMD   ATA_ERASE_SECTOR_CMD"

.PP
在文件 stm32_hal_legacy\&.h 第 785 行定义\&.
.SS "#define CF_IDENTIFY_CMD   ATA_IDENTIFY_CMD"

.PP
在文件 stm32_hal_legacy\&.h 第 786 行定义\&.
.SS "#define CF_READ_SECTOR_CMD   ATA_READ_SECTOR_CMD"

.PP
在文件 stm32_hal_legacy\&.h 第 783 行定义\&.
.SS "#define CF_SECTOR_COUNT   ATA_SECTOR_COUNT"

.PP
在文件 stm32_hal_legacy\&.h 第 773 行定义\&.
.SS "#define CF_SECTOR_NUMBER   ATA_SECTOR_NUMBER"

.PP
在文件 stm32_hal_legacy\&.h 第 774 行定义\&.
.SS "#define CF_STATUS_CMD   ATA_STATUS_CMD"

.PP
在文件 stm32_hal_legacy\&.h 第 778 行定义\&.
.SS "#define CF_STATUS_CMD_ALTERNATE   ATA_STATUS_CMD_ALTERNATE"

.PP
在文件 stm32_hal_legacy\&.h 第 779 行定义\&.
.SS "#define CF_WRITE_SECTOR_CMD   ATA_WRITE_SECTOR_CMD"

.PP
在文件 stm32_hal_legacy\&.h 第 784 行定义\&.
.SS "#define PCCARD_ERROR   HAL_PCCARD_STATUS_ERROR"

.PP
在文件 stm32_hal_legacy\&.h 第 791 行定义\&.
.SS "#define PCCARD_ONGOING   HAL_PCCARD_STATUS_ONGOING"

.PP
在文件 stm32_hal_legacy\&.h 第 790 行定义\&.
.SS "#define PCCARD_StatusTypedef   HAL_PCCARD_StatusTypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 788 行定义\&.
.SS "#define PCCARD_SUCCESS   HAL_PCCARD_STATUS_SUCCESS"

.PP
在文件 stm32_hal_legacy\&.h 第 789 行定义\&.
.SS "#define PCCARD_TIMEOUT   HAL_PCCARD_STATUS_TIMEOUT"

.PP
在文件 stm32_hal_legacy\&.h 第 792 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
