.TH "HAL_RTC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_RTC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFORMAT_BIN\fP   \fBRTC_FORMAT_BIN\fP"
.br
.ti -1c
.RI "#define \fBFORMAT_BCD\fP   \fBRTC_FORMAT_BCD\fP"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_None\fP   \fBRTC_ALARMSUBSECONDMASK_NONE\fP"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERERASEBACKUP_DISABLED\fP   RTC_TAMPER_ERASE_BACKUP_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERMASK_FLAG_DISABLED\fP   RTC_TAMPERMASK_FLAG_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERMASK_FLAG_ENABLED\fP   RTC_TAMPERMASK_FLAG_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_MASKTAMPERFLAG_DISABLED\fP   RTC_TAMPERMASK_FLAG_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_MASKTAMPERFLAG_ENABLED\fP   RTC_TAMPERMASK_FLAG_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERERASEBACKUP_ENABLED\fP   RTC_TAMPER_ERASE_BACKUP_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPER1_2_INTERRUPT\fP   RTC_ALL_TAMPER_INTERRUPT"
.br
.ti -1c
.RI "#define \fBRTC_TAMPER1_2_3_INTERRUPT\fP   RTC_ALL_TAMPER_INTERRUPT"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PC13\fP   \fBRTC_TIMESTAMPPIN_DEFAULT\fP"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PA0\fP   \fBRTC_TIMESTAMPPIN_POS1\fP"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PI8\fP   \fBRTC_TIMESTAMPPIN_POS1\fP"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PC1\fP   RTC_TIMESTAMPPIN_POS2"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PC13\fP   RTC_OUTPUT_REMAP_NONE"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PB14\fP   RTC_OUTPUT_REMAP_POS1"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PB2\fP   RTC_OUTPUT_REMAP_POS1"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PC13\fP   \fBRTC_TAMPERPIN_DEFAULT\fP"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PA0\fP   \fBRTC_TAMPERPIN_POS1\fP"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PI8\fP   \fBRTC_TAMPERPIN_POS1\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FORMAT_BCD   \fBRTC_FORMAT_BCD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 802 行定义\&.
.SS "#define FORMAT_BIN   \fBRTC_FORMAT_BIN\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 801 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_None   \fBRTC_ALARMSUBSECONDMASK_NONE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 804 行定义\&.
.SS "#define RTC_MASKTAMPERFLAG_DISABLED   RTC_TAMPERMASK_FLAG_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 809 行定义\&.
.SS "#define RTC_MASKTAMPERFLAG_ENABLED   RTC_TAMPERMASK_FLAG_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 810 行定义\&.
.SS "#define RTC_OUTPUT_REMAP_PB14   RTC_OUTPUT_REMAP_POS1"

.PP
在文件 stm32_hal_legacy\&.h 第 821 行定义\&.
.SS "#define RTC_OUTPUT_REMAP_PB2   RTC_OUTPUT_REMAP_POS1"

.PP
在文件 stm32_hal_legacy\&.h 第 822 行定义\&.
.SS "#define RTC_OUTPUT_REMAP_PC13   RTC_OUTPUT_REMAP_NONE"

.PP
在文件 stm32_hal_legacy\&.h 第 820 行定义\&.
.SS "#define RTC_TAMPER1_2_3_INTERRUPT   RTC_ALL_TAMPER_INTERRUPT"

.PP
在文件 stm32_hal_legacy\&.h 第 813 行定义\&.
.SS "#define RTC_TAMPER1_2_INTERRUPT   RTC_ALL_TAMPER_INTERRUPT"

.PP
在文件 stm32_hal_legacy\&.h 第 812 行定义\&.
.SS "#define RTC_TAMPERERASEBACKUP_DISABLED   RTC_TAMPER_ERASE_BACKUP_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 805 行定义\&.
.SS "#define RTC_TAMPERERASEBACKUP_ENABLED   RTC_TAMPER_ERASE_BACKUP_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 811 行定义\&.
.SS "#define RTC_TAMPERMASK_FLAG_DISABLED   RTC_TAMPERMASK_FLAG_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 806 行定义\&.
.SS "#define RTC_TAMPERMASK_FLAG_ENABLED   RTC_TAMPERMASK_FLAG_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 807 行定义\&.
.SS "#define RTC_TAMPERPIN_PA0   \fBRTC_TAMPERPIN_POS1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 825 行定义\&.
.SS "#define RTC_TAMPERPIN_PC13   \fBRTC_TAMPERPIN_DEFAULT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 824 行定义\&.
.SS "#define RTC_TAMPERPIN_PI8   \fBRTC_TAMPERPIN_POS1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 826 行定义\&.
.SS "#define RTC_TIMESTAMPPIN_PA0   \fBRTC_TIMESTAMPPIN_POS1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 816 行定义\&.
.SS "#define RTC_TIMESTAMPPIN_PC1   RTC_TIMESTAMPPIN_POS2"

.PP
在文件 stm32_hal_legacy\&.h 第 818 行定义\&.
.SS "#define RTC_TIMESTAMPPIN_PC13   \fBRTC_TIMESTAMPPIN_DEFAULT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 815 行定义\&.
.SS "#define RTC_TIMESTAMPPIN_PI8   \fBRTC_TIMESTAMPPIN_POS1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 817 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
