.TH "HAL_I2C_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2C_DUALADDRESS_DISABLED\fP   \fBI2C_DUALADDRESS_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_DUALADDRESS_ENABLED\fP   \fBI2C_DUALADDRESS_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_GENERALCALL_DISABLED\fP   \fBI2C_GENERALCALL_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_GENERALCALL_ENABLED\fP   \fBI2C_GENERALCALL_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_DISABLED\fP   \fBI2C_NOSTRETCH_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_ENABLED\fP   \fBI2C_NOSTRETCH_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBI2C_ANALOGFILTER_ENABLED\fP   I2C_ANALOGFILTER_ENABLE"
.br
.ti -1c
.RI "#define \fBI2C_ANALOGFILTER_DISABLED\fP   I2C_ANALOGFILTER_DISABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2C_ANALOGFILTER_DISABLED   I2C_ANALOGFILTER_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 617 行定义\&.
.SS "#define I2C_ANALOGFILTER_ENABLED   I2C_ANALOGFILTER_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 616 行定义\&.
.SS "#define I2C_DUALADDRESS_DISABLED   \fBI2C_DUALADDRESS_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 610 行定义\&.
.SS "#define I2C_DUALADDRESS_ENABLED   \fBI2C_DUALADDRESS_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 611 行定义\&.
.SS "#define I2C_GENERALCALL_DISABLED   \fBI2C_GENERALCALL_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 612 行定义\&.
.SS "#define I2C_GENERALCALL_ENABLED   \fBI2C_GENERALCALL_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 613 行定义\&.
.SS "#define I2C_NOSTRETCH_DISABLED   \fBI2C_NOSTRETCH_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 614 行定义\&.
.SS "#define I2C_NOSTRETCH_ENABLED   \fBI2C_NOSTRETCH_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 615 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
