.TH "HAL_FLASH_Aliased_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFLASH_HalfPageProgram\fP   HAL_FLASHEx_HalfPageProgram"
.br
.ti -1c
.RI "#define \fBFLASH_EnableRunPowerDown\fP   HAL_FLASHEx_EnableRunPowerDown"
.br
.ti -1c
.RI "#define \fBFLASH_DisableRunPowerDown\fP   HAL_FLASHEx_DisableRunPowerDown"
.br
.ti -1c
.RI "#define \fBHAL_DATA_EEPROMEx_Unlock\fP   HAL_FLASHEx_DATAEEPROM_Unlock"
.br
.ti -1c
.RI "#define \fBHAL_DATA_EEPROMEx_Lock\fP   HAL_FLASHEx_DATAEEPROM_Lock"
.br
.ti -1c
.RI "#define \fBHAL_DATA_EEPROMEx_Erase\fP   HAL_FLASHEx_DATAEEPROM_Erase"
.br
.ti -1c
.RI "#define \fBHAL_DATA_EEPROMEx_Program\fP   HAL_FLASHEx_DATAEEPROM_Program"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FLASH_DisableRunPowerDown   HAL_FLASHEx_DisableRunPowerDown"

.PP
在文件 stm32_hal_legacy\&.h 第 1234 行定义\&.
.SS "#define FLASH_EnableRunPowerDown   HAL_FLASHEx_EnableRunPowerDown"

.PP
在文件 stm32_hal_legacy\&.h 第 1233 行定义\&.
.SS "#define FLASH_HalfPageProgram   HAL_FLASHEx_HalfPageProgram"

.PP
在文件 stm32_hal_legacy\&.h 第 1232 行定义\&.
.SS "#define HAL_DATA_EEPROMEx_Erase   HAL_FLASHEx_DATAEEPROM_Erase"

.PP
在文件 stm32_hal_legacy\&.h 第 1237 行定义\&.
.SS "#define HAL_DATA_EEPROMEx_Lock   HAL_FLASHEx_DATAEEPROM_Lock"

.PP
在文件 stm32_hal_legacy\&.h 第 1236 行定义\&.
.SS "#define HAL_DATA_EEPROMEx_Program   HAL_FLASHEx_DATAEEPROM_Program"

.PP
在文件 stm32_hal_legacy\&.h 第 1238 行定义\&.
.SS "#define HAL_DATA_EEPROMEx_Unlock   HAL_FLASHEx_DATAEEPROM_Unlock"

.PP
在文件 stm32_hal_legacy\&.h 第 1235 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
