.TH "HAL_ETH_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ETH_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_ENABLE_IT\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_DISABLE_IT\fP   __HAL_ETH_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_GET_FLAG\fP   __HAL_ETH_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_CLEAR_FLAG\fP   __HAL_ETH_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_RISING_EDGE_TRIGGER"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLING_EDGE_TRIGGER"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLINGRISING_TRIGGER"
.br
.ti -1c
.RI "#define \fBETH_PROMISCIOUSMODE_ENABLE\fP   ETH_PROMISCUOUS_MODE_ENABLE"
.br
.ti -1c
.RI "#define \fBETH_PROMISCIOUSMODE_DISABLE\fP   ETH_PROMISCUOUS_MODE_DISABLE"
.br
.ti -1c
.RI "#define \fBIS_ETH_PROMISCIOUS_MODE\fP   IS_ETH_PROMISCUOUS_MODE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_ETH_EXTI_CLEAR_FLAG   __HAL_ETH_WAKEUP_EXTI_CLEAR_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3368 行定义\&.
.SS "#define __HAL_ETH_EXTI_DISABLE_IT   __HAL_ETH_WAKEUP_EXTI_DISABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3366 行定义\&.
.SS "#define __HAL_ETH_EXTI_ENABLE_IT   __HAL_ETH_WAKEUP_EXTI_ENABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3365 行定义\&.
.SS "#define __HAL_ETH_EXTI_GET_FLAG   __HAL_ETH_WAKEUP_EXTI_GET_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3367 行定义\&.
.SS "#define __HAL_ETH_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLING_EDGE_TRIGGER"

.PP
在文件 stm32_hal_legacy\&.h 第 3370 行定义\&.
.SS "#define __HAL_ETH_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLINGRISING_TRIGGER"

.PP
在文件 stm32_hal_legacy\&.h 第 3371 行定义\&.
.SS "#define __HAL_ETH_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_RISING_EDGE_TRIGGER"

.PP
在文件 stm32_hal_legacy\&.h 第 3369 行定义\&.
.SS "#define ETH_PROMISCIOUSMODE_DISABLE   ETH_PROMISCUOUS_MODE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3374 行定义\&.
.SS "#define ETH_PROMISCIOUSMODE_ENABLE   ETH_PROMISCUOUS_MODE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3373 行定义\&.
.SS "#define IS_ETH_PROMISCIOUS_MODE   IS_ETH_PROMISCUOUS_MODE"

.PP
在文件 stm32_hal_legacy\&.h 第 3375 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
