.TH "HAL_AES_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_AES_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBAES_FLAG_RDERR\fP   CRYP_FLAG_RDERR"
.br
.ti -1c
.RI "#define \fBAES_FLAG_WRERR\fP   CRYP_FLAG_WRERR"
.br
.ti -1c
.RI "#define \fBAES_CLEARFLAG_CCF\fP   CRYP_CLEARFLAG_CCF"
.br
.ti -1c
.RI "#define \fBAES_CLEARFLAG_RDERR\fP   CRYP_CLEARFLAG_RDERR"
.br
.ti -1c
.RI "#define \fBAES_CLEARFLAG_WRERR\fP   CRYP_CLEARFLAG_WRERR"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define AES_CLEARFLAG_CCF   CRYP_CLEARFLAG_CCF"

.PP
在文件 stm32_hal_legacy\&.h 第 39 行定义\&.
.SS "#define AES_CLEARFLAG_RDERR   CRYP_CLEARFLAG_RDERR"

.PP
在文件 stm32_hal_legacy\&.h 第 40 行定义\&.
.SS "#define AES_CLEARFLAG_WRERR   CRYP_CLEARFLAG_WRERR"

.PP
在文件 stm32_hal_legacy\&.h 第 41 行定义\&.
.SS "#define AES_FLAG_RDERR   CRYP_FLAG_RDERR"

.PP
在文件 stm32_hal_legacy\&.h 第 37 行定义\&.
.SS "#define AES_FLAG_WRERR   CRYP_FLAG_WRERR"

.PP
在文件 stm32_hal_legacy\&.h 第 38 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
