.TH "HAL_I2S_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2S_STANDARD_PHILLIPS\fP   \fBI2S_STANDARD_PHILIPS\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2S_STANDARD_PHILLIPS   \fBI2S_STANDARD_PHILIPS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 749 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
