.TH "HAL_SPI_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSPI_TIMODE_DISABLED\fP   \fBSPI_TIMODE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_TIMODE_ENABLED\fP   \fBSPI_TIMODE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_DISABLED\fP   \fBSPI_CRCCALCULATION_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_ENABLED\fP   \fBSPI_CRCCALCULATION_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_DISABLED\fP   SPI_NSS_PULSE_DISABLE"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_ENABLED\fP   SPI_NSS_PULSE_ENABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SPI_CRCCALCULATION_DISABLED   \fBSPI_CRCCALCULATION_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 878 行定义\&.
.SS "#define SPI_CRCCALCULATION_ENABLED   \fBSPI_CRCCALCULATION_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 879 行定义\&.
.SS "#define SPI_NSS_PULSE_DISABLED   SPI_NSS_PULSE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 881 行定义\&.
.SS "#define SPI_NSS_PULSE_ENABLED   SPI_NSS_PULSE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 882 行定义\&.
.SS "#define SPI_TIMODE_DISABLED   \fBSPI_TIMODE_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 875 行定义\&.
.SS "#define SPI_TIMODE_ENABLED   \fBSPI_TIMODE_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 876 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
