.TH "HAL_I2C_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_I2C_RESET_CR2\fP   I2C_RESET_CR2"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_GENERATE_START\fP   I2C_GENERATE_START"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_FREQ_RANGE\fP   I2C_FREQ_RANGE"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_RISE_TIME\fP   \fBI2C_RISE_TIME\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED_STANDARD\fP   \fBI2C_SPEED_STANDARD\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED_FAST\fP   \fBI2C_SPEED_FAST\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED\fP   \fBI2C_SPEED\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_7BIT_ADD_WRITE\fP   \fBI2C_7BIT_ADD_WRITE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_7BIT_ADD_READ\fP   \fBI2C_7BIT_ADD_READ\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_ADDRESS\fP   \fBI2C_10BIT_ADDRESS\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_HEADER_WRITE\fP   \fBI2C_10BIT_HEADER_WRITE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_HEADER_READ\fP   \fBI2C_10BIT_HEADER_READ\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_MEM_ADD_MSB\fP   \fBI2C_MEM_ADD_MSB\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_MEM_ADD_LSB\fP   \fBI2C_MEM_ADD_LSB\fP"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_FREQRANGE\fP   \fBI2C_FREQRANGE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_I2C_10BIT_ADDRESS   \fBI2C_10BIT_ADDRESS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1834 行定义\&.
.SS "#define __HAL_I2C_10BIT_HEADER_READ   \fBI2C_10BIT_HEADER_READ\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1836 行定义\&.
.SS "#define __HAL_I2C_10BIT_HEADER_WRITE   \fBI2C_10BIT_HEADER_WRITE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1835 行定义\&.
.SS "#define __HAL_I2C_7BIT_ADD_READ   \fBI2C_7BIT_ADD_READ\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1833 行定义\&.
.SS "#define __HAL_I2C_7BIT_ADD_WRITE   \fBI2C_7BIT_ADD_WRITE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1832 行定义\&.
.SS "#define __HAL_I2C_FREQ_RANGE   I2C_FREQ_RANGE"

.PP
在文件 stm32_hal_legacy\&.h 第 1826 行定义\&.
.SS "#define __HAL_I2C_FREQRANGE   \fBI2C_FREQRANGE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1839 行定义\&.
.SS "#define __HAL_I2C_GENERATE_START   I2C_GENERATE_START"

.PP
在文件 stm32_hal_legacy\&.h 第 1822 行定义\&.
.SS "#define __HAL_I2C_MEM_ADD_LSB   \fBI2C_MEM_ADD_LSB\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1838 行定义\&.
.SS "#define __HAL_I2C_MEM_ADD_MSB   \fBI2C_MEM_ADD_MSB\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1837 行定义\&.
.SS "#define __HAL_I2C_RESET_CR2   I2C_RESET_CR2"

.PP
在文件 stm32_hal_legacy\&.h 第 1821 行定义\&.
.SS "#define __HAL_I2C_RISE_TIME   \fBI2C_RISE_TIME\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1828 行定义\&.
.SS "#define __HAL_I2C_SPEED   \fBI2C_SPEED\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1831 行定义\&.
.SS "#define __HAL_I2C_SPEED_FAST   \fBI2C_SPEED_FAST\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1830 行定义\&.
.SS "#define __HAL_I2C_SPEED_STANDARD   \fBI2C_SPEED_STANDARD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1829 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
