.TH "HAL_USB_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_USB_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUSB_EXTI_LINE_WAKEUP\fP   USB_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_RISING_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_RISING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_FALLING_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_BOTH_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_LINE_WAKEUP\fP   USB_OTG_FS_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_RISING_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_RISING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_FALLING_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_BOTH_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_LINE_WAKEUP\fP   USB_OTG_HS_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_ENABLE_IT\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_DISABLE_IT\fP   __HAL_USB_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_GET_FLAG\fP   __HAL_USB_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_CLEAR_FLAG\fP   __HAL_USB_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_RISING_EDGE_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_FALLING_EDGE_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_ENABLE_IT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_DISABLE_IT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_GET_FLAG\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_CLEAR_FLAG\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_GENERATE_SWIT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_GENERATE_SWIT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_ENABLE_IT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_DISABLE_IT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_GET_FLAG\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_CLEAR_FLAG\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_GENERATE_SWIT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_GENERATE_SWIT"
.br
.ti -1c
.RI "#define \fBHAL_PCD_ActiveRemoteWakeup\fP   HAL_PCD_ActivateRemoteWakeup"
.br
.ti -1c
.RI "#define \fBHAL_PCD_DeActiveRemoteWakeup\fP   HAL_PCD_DeActivateRemoteWakeup"
.br
.ti -1c
.RI "#define \fBHAL_PCD_SetTxFiFo\fP   HAL_PCDEx_SetTxFiFo"
.br
.ti -1c
.RI "#define \fBHAL_PCD_SetRxFiFo\fP   HAL_PCDEx_SetRxFiFo"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_USB_EXTI_CLEAR_FLAG   __HAL_USB_WAKEUP_EXTI_CLEAR_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3300 行定义\&.
.SS "#define __HAL_USB_EXTI_DISABLE_IT   __HAL_USB_WAKEUP_EXTI_DISABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3298 行定义\&.
.SS "#define __HAL_USB_EXTI_ENABLE_IT   __HAL_USB_WAKEUP_EXTI_ENABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3297 行定义\&.
.SS "#define __HAL_USB_EXTI_GET_FLAG   __HAL_USB_WAKEUP_EXTI_GET_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3299 行定义\&.
.SS "#define __HAL_USB_EXTI_SET_FALLING_EDGE_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3302 行定义\&.
.SS "#define __HAL_USB_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3303 行定义\&.
.SS "#define __HAL_USB_EXTI_SET_RISING_EDGE_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3301 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_CLEAR_FLAG   __HAL_USB_OTG_FS_WAKEUP_EXTI_CLEAR_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3308 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_DISABLE_IT   __HAL_USB_OTG_FS_WAKEUP_EXTI_DISABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3306 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_ENABLE_IT   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3305 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_GENERATE_SWIT   __HAL_USB_OTG_FS_WAKEUP_EXTI_GENERATE_SWIT"

.PP
在文件 stm32_hal_legacy\&.h 第 3312 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_GET_FLAG   __HAL_USB_OTG_FS_WAKEUP_EXTI_GET_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3307 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3310 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3311 行定义\&.
.SS "#define __HAL_USB_FS_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3309 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_CLEAR_FLAG   __HAL_USB_OTG_HS_WAKEUP_EXTI_CLEAR_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3317 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_DISABLE_IT   __HAL_USB_OTG_HS_WAKEUP_EXTI_DISABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3315 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_ENABLE_IT   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_IT"

.PP
在文件 stm32_hal_legacy\&.h 第 3314 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_GENERATE_SWIT   __HAL_USB_OTG_HS_WAKEUP_EXTI_GENERATE_SWIT"

.PP
在文件 stm32_hal_legacy\&.h 第 3321 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_GET_FLAG   __HAL_USB_OTG_HS_WAKEUP_EXTI_GET_FLAG"

.PP
在文件 stm32_hal_legacy\&.h 第 3316 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3319 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3320 行定义\&.
.SS "#define __HAL_USB_HS_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3318 行定义\&.
.SS "#define HAL_PCD_ActiveRemoteWakeup   HAL_PCD_ActivateRemoteWakeup"

.PP
在文件 stm32_hal_legacy\&.h 第 3323 行定义\&.
.SS "#define HAL_PCD_DeActiveRemoteWakeup   HAL_PCD_DeActivateRemoteWakeup"

.PP
在文件 stm32_hal_legacy\&.h 第 3324 行定义\&.
.SS "#define HAL_PCD_SetRxFiFo   HAL_PCDEx_SetRxFiFo"

.PP
在文件 stm32_hal_legacy\&.h 第 3327 行定义\&.
.SS "#define HAL_PCD_SetTxFiFo   HAL_PCDEx_SetTxFiFo"

.PP
在文件 stm32_hal_legacy\&.h 第 3326 行定义\&.
.SS "#define USB_EXTI_LINE_WAKEUP   USB_WAKEUP_EXTI_LINE"

.PP
在文件 stm32_hal_legacy\&.h 第 3285 行定义\&.
.SS "#define USB_FS_EXTI_LINE_WAKEUP   USB_OTG_FS_WAKEUP_EXTI_LINE"

.PP
在文件 stm32_hal_legacy\&.h 第 3290 行定义\&.
.SS "#define USB_FS_EXTI_TRIGGER_BOTH_EDGE   USB_OTG_FS_WAKEUP_EXTI_RISING_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3289 行定义\&.
.SS "#define USB_FS_EXTI_TRIGGER_FALLING_EDGE   USB_OTG_FS_WAKEUP_EXTI_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3288 行定义\&.
.SS "#define USB_FS_EXTI_TRIGGER_RISING_EDGE   USB_OTG_FS_WAKEUP_EXTI_RISING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3287 行定义\&.
.SS "#define USB_HS_EXTI_LINE_WAKEUP   USB_OTG_HS_WAKEUP_EXTI_LINE"

.PP
在文件 stm32_hal_legacy\&.h 第 3295 行定义\&.
.SS "#define USB_HS_EXTI_TRIGGER_BOTH_EDGE   USB_OTG_HS_WAKEUP_EXTI_RISING_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3294 行定义\&.
.SS "#define USB_HS_EXTI_TRIGGER_FALLING_EDGE   USB_OTG_HS_WAKEUP_EXTI_FALLING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3293 行定义\&.
.SS "#define USB_HS_EXTI_TRIGGER_RISING_EDGE   USB_OTG_HS_WAKEUP_EXTI_RISING_EDGE"

.PP
在文件 stm32_hal_legacy\&.h 第 3292 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
