.TH "HAL_mode_structure_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_mode_structure_definition \- HAL Mode structure definition  

.SH SYNOPSIS
.br
.PP
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHAL_I2C_ModeTypeDef\fP { \fBHAL_I2C_MODE_NONE\fP = 0x00U, \fBHAL_I2C_MODE_MASTER\fP = 0x10U, \fBHAL_I2C_MODE_SLAVE\fP = 0x20U, \fBHAL_I2C_MODE_MEM\fP = 0x40U }"
.br
.in -1c
.SH "详细描述"
.PP 
HAL Mode structure definition 


.PP
\fB注解\fP
.RS 4
HAL I2C Mode value coding follow below described bitmap :
.br
 b7 (not used)
.br
 x : Should be set to 0
.br
 b6
.br
 0 : None
.br
 1 : Memory (HAL I2C communication is in Memory Mode)
.br
 b5
.br
 0 : None
.br
 1 : Slave (HAL I2C communication is in Slave Mode)
.br
 b4
.br
 0 : None
.br
 1 : Master (HAL I2C communication is in Master Mode)
.br
 b3-b2-b1-b0 (not used)
.br
 xxxx : Should be set to 0000 
.RE
.PP

.SH "枚举类型说明"
.PP 
.SS "enum \fBHAL_I2C_ModeTypeDef\fP"

.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIHAL_I2C_MODE_NONE \fP\fP
No I2C communication on going 
.br
 
.TP
\fB\fIHAL_I2C_MODE_MASTER \fP\fP
I2C communication is in Master Mode 
.br
 
.TP
\fB\fIHAL_I2C_MODE_SLAVE \fP\fP
I2C communication is in Slave Mode 
.br
 
.TP
\fB\fIHAL_I2C_MODE_MEM \fP\fP
I2C communication is in Memory Mode 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 147 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
