.TH "HAL_HRTIM_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_HRTIM_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DISABLED\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DISABLED"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_DEEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_DEEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_DEEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_DEEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV7"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetCounter\fP   __HAL_HRTIM_SETCOUNTER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetCounter\fP   __HAL_HRTIM_GETCOUNTER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetPeriod\fP   __HAL_HRTIM_SETPERIOD"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetPeriod\fP   __HAL_HRTIM_GETPERIOD"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetClockPrescaler\fP   __HAL_HRTIM_SETCLOCKPRESCALER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetClockPrescaler\fP   __HAL_HRTIM_GETCLOCKPRESCALER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetCompare\fP   __HAL_HRTIM_SETCOMPARE"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetCompare\fP   __HAL_HRTIM_GETCOMPARE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_HRTIM_GetClockPrescaler   __HAL_HRTIM_GETCLOCKPRESCALER"

.PP
在文件 stm32_hal_legacy\&.h 第 600 行定义\&.
.SS "#define __HAL_HRTIM_GetCompare   __HAL_HRTIM_GETCOMPARE"

.PP
在文件 stm32_hal_legacy\&.h 第 602 行定义\&.
.SS "#define __HAL_HRTIM_GetCounter   __HAL_HRTIM_GETCOUNTER"

.PP
在文件 stm32_hal_legacy\&.h 第 596 行定义\&.
.SS "#define __HAL_HRTIM_GetPeriod   __HAL_HRTIM_GETPERIOD"

.PP
在文件 stm32_hal_legacy\&.h 第 598 行定义\&.
.SS "#define __HAL_HRTIM_SetClockPrescaler   __HAL_HRTIM_SETCLOCKPRESCALER"

.PP
在文件 stm32_hal_legacy\&.h 第 599 行定义\&.
.SS "#define __HAL_HRTIM_SetCompare   __HAL_HRTIM_SETCOMPARE"

.PP
在文件 stm32_hal_legacy\&.h 第 601 行定义\&.
.SS "#define __HAL_HRTIM_SetCounter   __HAL_HRTIM_SETCOUNTER"

.PP
在文件 stm32_hal_legacy\&.h 第 595 行定义\&.
.SS "#define __HAL_HRTIM_SetPeriod   __HAL_HRTIM_SETPERIOD"

.PP
在文件 stm32_hal_legacy\&.h 第 597 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV6"

.PP
在文件 stm32_hal_legacy\&.h 第 589 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV7"

.PP
在文件 stm32_hal_legacy\&.h 第 593 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV6"

.PP
在文件 stm32_hal_legacy\&.h 第 588 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV7"

.PP
在文件 stm32_hal_legacy\&.h 第 592 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_DEEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_DEEV7"

.PP
在文件 stm32_hal_legacy\&.h 第 590 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_EEV6"

.PP
在文件 stm32_hal_legacy\&.h 第 586 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_DEEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_DEEV7"

.PP
在文件 stm32_hal_legacy\&.h 第 591 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_EEV6"

.PP
在文件 stm32_hal_legacy\&.h 第 587 行定义\&.
.SS "#define HRTIM_TIMDELAYEDPROTECTION_DISABLED   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DISABLED"

.PP
在文件 stm32_hal_legacy\&.h 第 585 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
