.TH "HAL_DCMI_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DCMI_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_DCMI_ERROR_OVF\fP   HAL_DCMI_ERROR_OVR"
.br
.ti -1c
.RI "#define \fBDCMI_IT_OVF\fP   DCMI_IT_OVR"
.br
.ti -1c
.RI "#define \fBDCMI_FLAG_OVFRI\fP   DCMI_FLAG_OVRRI"
.br
.ti -1c
.RI "#define \fBDCMI_FLAG_OVFMI\fP   DCMI_FLAG_OVRMI"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_ConfigCROP\fP   HAL_DCMI_ConfigCrop"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_EnableCROP\fP   HAL_DCMI_EnableCrop"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_DisableCROP\fP   HAL_DCMI_DisableCrop"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define DCMI_FLAG_OVFMI   DCMI_FLAG_OVRMI"

.PP
在文件 stm32_hal_legacy\&.h 第 1125 行定义\&.
.SS "#define DCMI_FLAG_OVFRI   DCMI_FLAG_OVRRI"

.PP
在文件 stm32_hal_legacy\&.h 第 1124 行定义\&.
.SS "#define DCMI_IT_OVF   DCMI_IT_OVR"

.PP
在文件 stm32_hal_legacy\&.h 第 1123 行定义\&.
.SS "#define HAL_DCMI_ConfigCROP   HAL_DCMI_ConfigCrop"

.PP
在文件 stm32_hal_legacy\&.h 第 1127 行定义\&.
.SS "#define HAL_DCMI_DisableCROP   HAL_DCMI_DisableCrop"

.PP
在文件 stm32_hal_legacy\&.h 第 1129 行定义\&.
.SS "#define HAL_DCMI_EnableCROP   HAL_DCMI_EnableCrop"

.PP
在文件 stm32_hal_legacy\&.h 第 1128 行定义\&.
.SS "#define HAL_DCMI_ERROR_OVF   HAL_DCMI_ERROR_OVR"

.PP
在文件 stm32_hal_legacy\&.h 第 1122 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
