.TH "HAL_SMBUS_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_SMBUS_RESET_CR1\fP   SMBUS_RESET_CR1"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_RESET_CR2\fP   SMBUS_RESET_CR2"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GENERATE_START\fP   SMBUS_GENERATE_START"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_ADDR_MATCH\fP   SMBUS_GET_ADDR_MATCH"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_DIR\fP   SMBUS_GET_DIR"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_STOP_MODE\fP   SMBUS_GET_STOP_MODE"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_PEC_MODE\fP   \fBSMBUS_GET_PEC_MODE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_ALERT_ENABLED\fP   SMBUS_GET_ALERT_ENABLED"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_SMBUS_GENERATE_START   SMBUS_GENERATE_START"

.PP
在文件 stm32_hal_legacy\&.h 第 3225 行定义\&.
.SS "#define __HAL_SMBUS_GET_ADDR_MATCH   SMBUS_GET_ADDR_MATCH"

.PP
在文件 stm32_hal_legacy\&.h 第 3226 行定义\&.
.SS "#define __HAL_SMBUS_GET_ALERT_ENABLED   SMBUS_GET_ALERT_ENABLED"

.PP
在文件 stm32_hal_legacy\&.h 第 3230 行定义\&.
.SS "#define __HAL_SMBUS_GET_DIR   SMBUS_GET_DIR"

.PP
在文件 stm32_hal_legacy\&.h 第 3227 行定义\&.
.SS "#define __HAL_SMBUS_GET_PEC_MODE   \fBSMBUS_GET_PEC_MODE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3229 行定义\&.
.SS "#define __HAL_SMBUS_GET_STOP_MODE   SMBUS_GET_STOP_MODE"

.PP
在文件 stm32_hal_legacy\&.h 第 3228 行定义\&.
.SS "#define __HAL_SMBUS_RESET_CR1   SMBUS_RESET_CR1"

.PP
在文件 stm32_hal_legacy\&.h 第 3223 行定义\&.
.SS "#define __HAL_SMBUS_RESET_CR2   SMBUS_RESET_CR2"

.PP
在文件 stm32_hal_legacy\&.h 第 3224 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
