.TH "HAL_OPAMP_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_OPAMP_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXPD\fP   OPAMP_CSR_OPAXPD"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S3SELX\fP   OPAMP_CSR_S3SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S4SELX\fP   OPAMP_CSR_S4SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S5SELX\fP   OPAMP_CSR_S5SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S6SELX\fP   OPAMP_CSR_S6SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCAL_L\fP   OPAMP_CSR_OPAXCAL_L"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCAL_H\fP   OPAMP_CSR_OPAXCAL_H"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXLPM\fP   OPAMP_CSR_OPAXLPM"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_ALL_SWITCHES\fP   OPAMP_CSR_ALL_SWITCHES"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_ANAWSELX\fP   OPAMP_CSR_ANAWSELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCALOUT\fP   OPAMP_CSR_OPAXCALOUT"
.br
.ti -1c
.RI "#define \fB__OPAMP_OFFSET_TRIM_BITSPOSITION\fP   OPAMP_OFFSET_TRIM_BITSPOSITION"
.br
.ti -1c
.RI "#define \fB__OPAMP_OFFSET_TRIM_SET\fP   OPAMP_OFFSET_TRIM_SET"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __OPAMP_CSR_ALL_SWITCHES   OPAMP_CSR_ALL_SWITCHES"

.PP
在文件 stm32_hal_legacy\&.h 第 1913 行定义\&.
.SS "#define __OPAMP_CSR_ANAWSELX   OPAMP_CSR_ANAWSELX"

.PP
在文件 stm32_hal_legacy\&.h 第 1914 行定义\&.
.SS "#define __OPAMP_CSR_OPAXCAL_H   OPAMP_CSR_OPAXCAL_H"

.PP
在文件 stm32_hal_legacy\&.h 第 1911 行定义\&.
.SS "#define __OPAMP_CSR_OPAXCAL_L   OPAMP_CSR_OPAXCAL_L"

.PP
在文件 stm32_hal_legacy\&.h 第 1910 行定义\&.
.SS "#define __OPAMP_CSR_OPAXCALOUT   OPAMP_CSR_OPAXCALOUT"

.PP
在文件 stm32_hal_legacy\&.h 第 1915 行定义\&.
.SS "#define __OPAMP_CSR_OPAXLPM   OPAMP_CSR_OPAXLPM"

.PP
在文件 stm32_hal_legacy\&.h 第 1912 行定义\&.
.SS "#define __OPAMP_CSR_OPAXPD   OPAMP_CSR_OPAXPD"

.PP
在文件 stm32_hal_legacy\&.h 第 1905 行定义\&.
.SS "#define __OPAMP_CSR_S3SELX   OPAMP_CSR_S3SELX"

.PP
在文件 stm32_hal_legacy\&.h 第 1906 行定义\&.
.SS "#define __OPAMP_CSR_S4SELX   OPAMP_CSR_S4SELX"

.PP
在文件 stm32_hal_legacy\&.h 第 1907 行定义\&.
.SS "#define __OPAMP_CSR_S5SELX   OPAMP_CSR_S5SELX"

.PP
在文件 stm32_hal_legacy\&.h 第 1908 行定义\&.
.SS "#define __OPAMP_CSR_S6SELX   OPAMP_CSR_S6SELX"

.PP
在文件 stm32_hal_legacy\&.h 第 1909 行定义\&.
.SS "#define __OPAMP_OFFSET_TRIM_BITSPOSITION   OPAMP_OFFSET_TRIM_BITSPOSITION"

.PP
在文件 stm32_hal_legacy\&.h 第 1916 行定义\&.
.SS "#define __OPAMP_OFFSET_TRIM_SET   OPAMP_OFFSET_TRIM_SET"

.PP
在文件 stm32_hal_legacy\&.h 第 1917 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
