.TH "HAL_TimeBase_TIM" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TimeBase_TIM
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBTIM6_DAC_IRQHandler\fP (void)"
.br
.RI "This function handles TIM interrupt request\&. "
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_InitTick\fP (uint32_t TickPriority)"
.br
.RI "This function configures the TIM6 as a time base source\&. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority\&. "
.ti -1c
.RI "void \fBHAL_SuspendTick\fP (void)"
.br
.RI "Suspend Tick increment\&. "
.ti -1c
.RI "void \fBHAL_ResumeTick\fP (void)"
.br
.RI "Resume Tick increment\&. "
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.RI "Period elapsed callback in non blocking mode "
.in -1c
.SS "变量"

.in +1c
.ti -1c
.RI "\fBTIM_HandleTypeDef\fP \fBTimHandle\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_InitTick (uint32_t TickPriority)"

.PP
This function configures the TIM6 as a time base source\&. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority\&. 
.PP
\fB注解\fP
.RS 4
This function is called automatically at the beginning of program after reset by \fBHAL_Init()\fP or at any time when clock is configured, by \fBHAL_RCC_ClockConfig()\fP\&. 
.RE
.PP
\fB参数\fP
.RS 4
\fITickPriority\fP Tick interrupt priority\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fIHAL\fP status 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 55 行定义\&.
.SS "void HAL_ResumeTick (void)"

.PP
Resume Tick increment\&. 
.PP
\fB注解\fP
.RS 4
Enable the tick increment by Enabling TIM6 update interrupt\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 130 行定义\&.
.SS "void HAL_SuspendTick (void)"

.PP
Suspend Tick increment\&. 
.PP
\fB注解\fP
.RS 4
Disable the tick increment by disabling TIM6 update interrupt\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 119 行定义\&.
.SS "void HAL_TIM_PeriodElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.PP
Period elapsed callback in non blocking mode 
.PP
\fB注解\fP
.RS 4
This function is called when TIM6 interrupt took place, inside \fBHAL_TIM_IRQHandler()\fP\&. It makes a direct call to \fBHAL_IncTick()\fP to increment a global variable 'uwTick' used as application time base\&. 
.RE
.PP
\fB参数\fP
.RS 4
\fIhtim\fP TIM handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 144 行定义\&.
.SS "void TIM6_DAC_IRQHandler (void)"

.PP
This function handles TIM interrupt request\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 153 行定义\&.
.SH "变量说明"
.PP 
.SS "\fBTIM_HandleTypeDef\fP TimHandle"

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 41 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
