.TH "HAL_ADC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ADC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBADC_RESOLUTION12b\fP   \fBADC_RESOLUTION_12B\fP"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION10b\fP   \fBADC_RESOLUTION_10B\fP"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION8b\fP   \fBADC_RESOLUTION_8B\fP"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION6b\fP   \fBADC_RESOLUTION_6B\fP"
.br
.ti -1c
.RI "#define \fBOVR_DATA_OVERWRITTEN\fP   ADC_OVR_DATA_OVERWRITTEN"
.br
.ti -1c
.RI "#define \fBOVR_DATA_PRESERVED\fP   ADC_OVR_DATA_PRESERVED"
.br
.ti -1c
.RI "#define \fBEOC_SINGLE_CONV\fP   \fBADC_EOC_SINGLE_CONV\fP"
.br
.ti -1c
.RI "#define \fBEOC_SEQ_CONV\fP   \fBADC_EOC_SEQ_CONV\fP"
.br
.ti -1c
.RI "#define \fBEOC_SINGLE_SEQ_CONV\fP   \fBADC_EOC_SINGLE_SEQ_CONV\fP"
.br
.ti -1c
.RI "#define \fBREGULAR_GROUP\fP   ADC_REGULAR_GROUP"
.br
.ti -1c
.RI "#define \fBINJECTED_GROUP\fP   ADC_INJECTED_GROUP"
.br
.ti -1c
.RI "#define \fBREGULAR_INJECTED_GROUP\fP   ADC_REGULAR_INJECTED_GROUP"
.br
.ti -1c
.RI "#define \fBAWD_EVENT\fP   \fBADC_AWD_EVENT\fP"
.br
.ti -1c
.RI "#define \fBAWD1_EVENT\fP   ADC_AWD1_EVENT"
.br
.ti -1c
.RI "#define \fBAWD2_EVENT\fP   ADC_AWD2_EVENT"
.br
.ti -1c
.RI "#define \fBAWD3_EVENT\fP   ADC_AWD3_EVENT"
.br
.ti -1c
.RI "#define \fBOVR_EVENT\fP   \fBADC_OVR_EVENT\fP"
.br
.ti -1c
.RI "#define \fBJQOVF_EVENT\fP   ADC_JQOVF_EVENT"
.br
.ti -1c
.RI "#define \fBALL_CHANNELS\fP   \fBADC_ALL_CHANNELS\fP"
.br
.ti -1c
.RI "#define \fBREGULAR_CHANNELS\fP   \fBADC_REGULAR_CHANNELS\fP"
.br
.ti -1c
.RI "#define \fBINJECTED_CHANNELS\fP   \fBADC_INJECTED_CHANNELS\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_SENSOR_ADC\fP   ADC_FLAG_SENSOR"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_VREF_ADC\fP   ADC_FLAG_VREFINT"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV1\fP   ADC_CLOCK_SYNC_PCLK_DIV1"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV2\fP   \fBADC_CLOCK_SYNC_PCLK_DIV2\fP"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV4\fP   \fBADC_CLOCK_SYNC_PCLK_DIV4\fP"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV6\fP   \fBADC_CLOCK_SYNC_PCLK_DIV6\fP"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV8\fP   \fBADC_CLOCK_SYNC_PCLK_DIV8\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG0_T6_TRGO\fP   ADC_EXTERNALTRIGCONV_T6_TRGO"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG1_T21_CC2\fP   ADC_EXTERNALTRIGCONV_T21_CC2"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG2_T2_TRGO\fP   \fBADC_EXTERNALTRIGCONV_T2_TRGO\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG3_T2_CC4\fP   \fBADC_EXTERNALTRIGCONV_T2_CC4\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG4_T22_TRGO\fP   ADC_EXTERNALTRIGCONV_T22_TRGO"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG7_EXT_IT11\fP   ADC_EXTERNALTRIGCONV_EXT_IT11"
.br
.ti -1c
.RI "#define \fBADC_CLOCK_ASYNC\fP   ADC_CLOCK_ASYNC_DIV1"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_NONE\fP   \fBADC_EXTERNALTRIGCONVEDGE_NONE\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_RISING\fP   \fBADC_EXTERNALTRIGCONVEDGE_RISING\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_FALLING\fP   \fBADC_EXTERNALTRIGCONVEDGE_FALLING\fP"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_RISINGFALLING\fP   \fBADC_EXTERNALTRIGCONVEDGE_RISINGFALLING\fP"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_2CYCLE_5\fP   ADC_SAMPLETIME_2CYCLES_5"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY_REG\fP   \fBHAL_ADC_STATE_REG_BUSY\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY_INJ\fP   \fBHAL_ADC_STATE_INJ_BUSY\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_EOC_REG\fP   \fBHAL_ADC_STATE_REG_EOC\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_EOC_INJ\fP   \fBHAL_ADC_STATE_INJ_EOC\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_ERROR\fP   \fBHAL_ADC_STATE_ERROR_INTERNAL\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY\fP   \fBHAL_ADC_STATE_BUSY_INTERNAL\fP"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_AWD\fP   \fBHAL_ADC_STATE_AWD1\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define ADC_CLOCK_ASYNC   ADC_CLOCK_ASYNC_DIV1"

.PP
在文件 stm32_hal_legacy\&.h 第 84 行定义\&.
.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV1   ADC_CLOCK_SYNC_PCLK_DIV1"

.PP
在文件 stm32_hal_legacy\&.h 第 73 行定义\&.
.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV2   \fBADC_CLOCK_SYNC_PCLK_DIV2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 74 行定义\&.
.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV4   \fBADC_CLOCK_SYNC_PCLK_DIV4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 75 行定义\&.
.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV6   \fBADC_CLOCK_SYNC_PCLK_DIV6\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 76 行定义\&.
.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV8   \fBADC_CLOCK_SYNC_PCLK_DIV8\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 77 行定义\&.
.SS "#define ADC_EXTERNALTRIG0_T6_TRGO   ADC_EXTERNALTRIGCONV_T6_TRGO"

.PP
在文件 stm32_hal_legacy\&.h 第 78 行定义\&.
.SS "#define ADC_EXTERNALTRIG1_T21_CC2   ADC_EXTERNALTRIGCONV_T21_CC2"

.PP
在文件 stm32_hal_legacy\&.h 第 79 行定义\&.
.SS "#define ADC_EXTERNALTRIG2_T2_TRGO   \fBADC_EXTERNALTRIGCONV_T2_TRGO\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 80 行定义\&.
.SS "#define ADC_EXTERNALTRIG3_T2_CC4   \fBADC_EXTERNALTRIGCONV_T2_CC4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 81 行定义\&.
.SS "#define ADC_EXTERNALTRIG4_T22_TRGO   ADC_EXTERNALTRIGCONV_T22_TRGO"

.PP
在文件 stm32_hal_legacy\&.h 第 82 行定义\&.
.SS "#define ADC_EXTERNALTRIG7_EXT_IT11   ADC_EXTERNALTRIGCONV_EXT_IT11"

.PP
在文件 stm32_hal_legacy\&.h 第 83 行定义\&.
.SS "#define ADC_EXTERNALTRIG_EDGE_FALLING   \fBADC_EXTERNALTRIGCONVEDGE_FALLING\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 87 行定义\&.
.SS "#define ADC_EXTERNALTRIG_EDGE_NONE   \fBADC_EXTERNALTRIGCONVEDGE_NONE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 85 行定义\&.
.SS "#define ADC_EXTERNALTRIG_EDGE_RISING   \fBADC_EXTERNALTRIGCONVEDGE_RISING\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 86 行定义\&.
.SS "#define ADC_EXTERNALTRIG_EDGE_RISINGFALLING   \fBADC_EXTERNALTRIGCONVEDGE_RISINGFALLING\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 88 行定义\&.
.SS "#define ADC_RESOLUTION10b   \fBADC_RESOLUTION_10B\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 51 行定义\&.
.SS "#define ADC_RESOLUTION12b   \fBADC_RESOLUTION_12B\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 50 行定义\&.
.SS "#define ADC_RESOLUTION6b   \fBADC_RESOLUTION_6B\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 53 行定义\&.
.SS "#define ADC_RESOLUTION8b   \fBADC_RESOLUTION_8B\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 52 行定义\&.
.SS "#define ADC_SAMPLETIME_2CYCLE_5   ADC_SAMPLETIME_2CYCLES_5"

.PP
在文件 stm32_hal_legacy\&.h 第 89 行定义\&.
.SS "#define ALL_CHANNELS   \fBADC_ALL_CHANNELS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 68 行定义\&.
.SS "#define AWD1_EVENT   ADC_AWD1_EVENT"

.PP
在文件 stm32_hal_legacy\&.h 第 63 行定义\&.
.SS "#define AWD2_EVENT   ADC_AWD2_EVENT"

.PP
在文件 stm32_hal_legacy\&.h 第 64 行定义\&.
.SS "#define AWD3_EVENT   ADC_AWD3_EVENT"

.PP
在文件 stm32_hal_legacy\&.h 第 65 行定义\&.
.SS "#define AWD_EVENT   \fBADC_AWD_EVENT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 62 行定义\&.
.SS "#define EOC_SEQ_CONV   \fBADC_EOC_SEQ_CONV\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 57 行定义\&.
.SS "#define EOC_SINGLE_CONV   \fBADC_EOC_SINGLE_CONV\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 56 行定义\&.
.SS "#define EOC_SINGLE_SEQ_CONV   \fBADC_EOC_SINGLE_SEQ_CONV\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 58 行定义\&.
.SS "#define HAL_ADC_STATE_AWD   \fBHAL_ADC_STATE_AWD1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 97 行定义\&.
.SS "#define HAL_ADC_STATE_BUSY   \fBHAL_ADC_STATE_BUSY_INTERNAL\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 96 行定义\&.
.SS "#define HAL_ADC_STATE_BUSY_INJ   \fBHAL_ADC_STATE_INJ_BUSY\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 92 行定义\&.
.SS "#define HAL_ADC_STATE_BUSY_REG   \fBHAL_ADC_STATE_REG_BUSY\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 91 行定义\&.
.SS "#define HAL_ADC_STATE_EOC_INJ   \fBHAL_ADC_STATE_INJ_EOC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 94 行定义\&.
.SS "#define HAL_ADC_STATE_EOC_REG   \fBHAL_ADC_STATE_REG_EOC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 93 行定义\&.
.SS "#define HAL_ADC_STATE_ERROR   \fBHAL_ADC_STATE_ERROR_INTERNAL\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 95 行定义\&.
.SS "#define INJECTED_CHANNELS   \fBADC_INJECTED_CHANNELS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 70 行定义\&.
.SS "#define INJECTED_GROUP   ADC_INJECTED_GROUP"

.PP
在文件 stm32_hal_legacy\&.h 第 60 行定义\&.
.SS "#define JQOVF_EVENT   ADC_JQOVF_EVENT"

.PP
在文件 stm32_hal_legacy\&.h 第 67 行定义\&.
.SS "#define OVR_DATA_OVERWRITTEN   ADC_OVR_DATA_OVERWRITTEN"

.PP
在文件 stm32_hal_legacy\&.h 第 54 行定义\&.
.SS "#define OVR_DATA_PRESERVED   ADC_OVR_DATA_PRESERVED"

.PP
在文件 stm32_hal_legacy\&.h 第 55 行定义\&.
.SS "#define OVR_EVENT   \fBADC_OVR_EVENT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 66 行定义\&.
.SS "#define REGULAR_CHANNELS   \fBADC_REGULAR_CHANNELS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 69 行定义\&.
.SS "#define REGULAR_GROUP   ADC_REGULAR_GROUP"

.PP
在文件 stm32_hal_legacy\&.h 第 59 行定义\&.
.SS "#define REGULAR_INJECTED_GROUP   ADC_REGULAR_INJECTED_GROUP"

.PP
在文件 stm32_hal_legacy\&.h 第 61 行定义\&.
.SS "#define SYSCFG_FLAG_SENSOR_ADC   ADC_FLAG_SENSOR"

.PP
在文件 stm32_hal_legacy\&.h 第 71 行定义\&.
.SS "#define SYSCFG_FLAG_VREF_ADC   ADC_FLAG_VREFINT"

.PP
在文件 stm32_hal_legacy\&.h 第 72 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
