.TH "HAL_HASH_Aliased_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_HASH_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_HASH_STATETypeDef\fP   HAL_HASH_StateTypeDef"
.br
.ti -1c
.RI "#define \fBHAL_HASHPhaseTypeDef\fP   HAL_HASH_PhaseTypeDef"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_MD5_Finish\fP   HAL_HASH_MD5_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA1_Finish\fP   HAL_HASH_SHA1_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA224_Finish\fP   HAL_HASH_SHA224_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA256_Finish\fP   HAL_HASH_SHA256_Finish"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA1\fP   HASH_ALGOSELECTION_SHA1"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA224\fP   HASH_ALGOSELECTION_SHA224"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA256\fP   HASH_ALGOSELECTION_SHA256"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_MD5\fP   HASH_ALGOSELECTION_MD5"
.br
.ti -1c
.RI "#define \fBHASH_AlgoMode_HASH\fP   HASH_ALGOMODE_HASH"
.br
.ti -1c
.RI "#define \fBHASH_AlgoMode_HMAC\fP   HASH_ALGOMODE_HMAC"
.br
.ti -1c
.RI "#define \fBHASH_HMACKeyType_ShortKey\fP   HASH_HMAC_KEYTYPE_SHORTKEY"
.br
.ti -1c
.RI "#define \fBHASH_HMACKeyType_LongKey\fP   HASH_HMAC_KEYTYPE_LONGKEY"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_HASH_STATETypeDef   HAL_HASH_StateTypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 1184 行定义\&.
.SS "#define HAL_HASHPhaseTypeDef   HAL_HASH_PhaseTypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 1185 行定义\&.
.SS "#define HAL_HMAC_MD5_Finish   HAL_HASH_MD5_Finish"

.PP
在文件 stm32_hal_legacy\&.h 第 1186 行定义\&.
.SS "#define HAL_HMAC_SHA1_Finish   HAL_HASH_SHA1_Finish"

.PP
在文件 stm32_hal_legacy\&.h 第 1187 行定义\&.
.SS "#define HAL_HMAC_SHA224_Finish   HAL_HASH_SHA224_Finish"

.PP
在文件 stm32_hal_legacy\&.h 第 1188 行定义\&.
.SS "#define HAL_HMAC_SHA256_Finish   HAL_HASH_SHA256_Finish"

.PP
在文件 stm32_hal_legacy\&.h 第 1189 行定义\&.
.SS "#define HASH_AlgoMode_HASH   HASH_ALGOMODE_HASH"

.PP
在文件 stm32_hal_legacy\&.h 第 1198 行定义\&.
.SS "#define HASH_AlgoMode_HMAC   HASH_ALGOMODE_HMAC"

.PP
在文件 stm32_hal_legacy\&.h 第 1199 行定义\&.
.SS "#define HASH_AlgoSelection_MD5   HASH_ALGOSELECTION_MD5"

.PP
在文件 stm32_hal_legacy\&.h 第 1196 行定义\&.
.SS "#define HASH_AlgoSelection_SHA1   HASH_ALGOSELECTION_SHA1"

.PP
在文件 stm32_hal_legacy\&.h 第 1193 行定义\&.
.SS "#define HASH_AlgoSelection_SHA224   HASH_ALGOSELECTION_SHA224"

.PP
在文件 stm32_hal_legacy\&.h 第 1194 行定义\&.
.SS "#define HASH_AlgoSelection_SHA256   HASH_ALGOSELECTION_SHA256"

.PP
在文件 stm32_hal_legacy\&.h 第 1195 行定义\&.
.SS "#define HASH_HMACKeyType_LongKey   HASH_HMAC_KEYTYPE_LONGKEY"

.PP
在文件 stm32_hal_legacy\&.h 第 1202 行定义\&.
.SS "#define HASH_HMACKeyType_ShortKey   HASH_HMAC_KEYTYPE_SHORTKEY"

.PP
在文件 stm32_hal_legacy\&.h 第 1201 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
