.TH "HAL_CRC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_CRC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBCRC_OUTPUTDATA_INVERSION_DISABLED\fP   CRC_OUTPUTDATA_INVERSION_DISABLE"
.br
.ti -1c
.RI "#define \fBCRC_OUTPUTDATA_INVERSION_ENABLED\fP   CRC_OUTPUTDATA_INVERSION_ENABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CRC_OUTPUTDATA_INVERSION_DISABLED   CRC_OUTPUTDATA_INVERSION_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 219 行定义\&.
.SS "#define CRC_OUTPUTDATA_INVERSION_ENABLED   CRC_OUTPUTDATA_INVERSION_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 220 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
