.TH "HAL_IWDG_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IWDG_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBKR_KEY_RELOAD\fP   \fBIWDG_KEY_RELOAD\fP"
.br
.ti -1c
.RI "#define \fBKR_KEY_ENABLE\fP   \fBIWDG_KEY_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBKR_KEY_EWA\fP   \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBKR_KEY_DWA\fP   \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define KR_KEY_DWA   \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 646 行定义\&.
.SS "#define KR_KEY_ENABLE   \fBIWDG_KEY_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 644 行定义\&.
.SS "#define KR_KEY_EWA   \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 645 行定义\&.
.SS "#define KR_KEY_RELOAD   \fBIWDG_KEY_RELOAD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 643 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
