.TH "HAL_NOR_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_NOR_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBNOR_StatusTypedef\fP   HAL_NOR_StatusTypeDef"
.br
.ti -1c
.RI "#define \fBNOR_SUCCESS\fP   HAL_NOR_STATUS_SUCCESS"
.br
.ti -1c
.RI "#define \fBNOR_ONGOING\fP   HAL_NOR_STATUS_ONGOING"
.br
.ti -1c
.RI "#define \fBNOR_ERROR\fP   HAL_NOR_STATUS_ERROR"
.br
.ti -1c
.RI "#define \fBNOR_TIMEOUT\fP   HAL_NOR_STATUS_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__NOR_WRITE\fP   NOR_WRITE"
.br
.ti -1c
.RI "#define \fB__NOR_ADDR_SHIFT\fP   NOR_ADDR_SHIFT"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __NOR_ADDR_SHIFT   NOR_ADDR_SHIFT"

.PP
在文件 stm32_hal_legacy\&.h 第 708 行定义\&.
.SS "#define __NOR_WRITE   NOR_WRITE"

.PP
在文件 stm32_hal_legacy\&.h 第 707 行定义\&.
.SS "#define NOR_ERROR   HAL_NOR_STATUS_ERROR"

.PP
在文件 stm32_hal_legacy\&.h 第 704 行定义\&.
.SS "#define NOR_ONGOING   HAL_NOR_STATUS_ONGOING"

.PP
在文件 stm32_hal_legacy\&.h 第 703 行定义\&.
.SS "#define NOR_StatusTypedef   HAL_NOR_StatusTypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 701 行定义\&.
.SS "#define NOR_SUCCESS   HAL_NOR_STATUS_SUCCESS"

.PP
在文件 stm32_hal_legacy\&.h 第 702 行定义\&.
.SS "#define NOR_TIMEOUT   HAL_NOR_STATUS_TIMEOUT"

.PP
在文件 stm32_hal_legacy\&.h 第 705 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
