.TH "HAL_COMP_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_COMP_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBCOMP_WINDOWMODE_DISABLED\fP   COMP_WINDOWMODE_DISABLE"
.br
.ti -1c
.RI "#define \fBCOMP_WINDOWMODE_ENABLED\fP   COMP_WINDOWMODE_ENABLE"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP1_EVENT\fP   COMP_EXTI_LINE_COMP1"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP2_EVENT\fP   COMP_EXTI_LINE_COMP2"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP3_EVENT\fP   COMP_EXTI_LINE_COMP3"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP4_EVENT\fP   COMP_EXTI_LINE_COMP4"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP5_EVENT\fP   COMP_EXTI_LINE_COMP5"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP6_EVENT\fP   COMP_EXTI_LINE_COMP6"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP7_EVENT\fP   COMP_EXTI_LINE_COMP7"
.br
.ti -1c
.RI "#define \fBCOMP_OUTPUT_COMP6TIM2OCREFCLR\fP   COMP_OUTPUT_COMP6_TIM2OCREFCLR"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define COMP_EXTI_LINE_COMP1_EVENT   COMP_EXTI_LINE_COMP1"

.PP
在文件 stm32_hal_legacy\&.h 第 121 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP2_EVENT   COMP_EXTI_LINE_COMP2"

.PP
在文件 stm32_hal_legacy\&.h 第 122 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP3_EVENT   COMP_EXTI_LINE_COMP3"

.PP
在文件 stm32_hal_legacy\&.h 第 123 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP4_EVENT   COMP_EXTI_LINE_COMP4"

.PP
在文件 stm32_hal_legacy\&.h 第 124 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP5_EVENT   COMP_EXTI_LINE_COMP5"

.PP
在文件 stm32_hal_legacy\&.h 第 125 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP6_EVENT   COMP_EXTI_LINE_COMP6"

.PP
在文件 stm32_hal_legacy\&.h 第 126 行定义\&.
.SS "#define COMP_EXTI_LINE_COMP7_EVENT   COMP_EXTI_LINE_COMP7"

.PP
在文件 stm32_hal_legacy\&.h 第 127 行定义\&.
.SS "#define COMP_OUTPUT_COMP6TIM2OCREFCLR   COMP_OUTPUT_COMP6_TIM2OCREFCLR"

.PP
在文件 stm32_hal_legacy\&.h 第 131 行定义\&.
.SS "#define COMP_WINDOWMODE_DISABLED   COMP_WINDOWMODE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 119 行定义\&.
.SS "#define COMP_WINDOWMODE_ENABLED   COMP_WINDOWMODE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 120 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
