.TH "HAL_IRDA_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IRDA_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__IRDA_DISABLE\fP   \fB__HAL_IRDA_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__IRDA_ENABLE\fP   \fB__HAL_IRDA_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_IRDA_GETCLOCKSOURCE\fP   IRDA_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__HAL_IRDA_MASK_COMPUTATION\fP   IRDA_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fB__IRDA_GETCLOCKSOURCE\fP   IRDA_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__IRDA_MASK_COMPUTATION\fP   IRDA_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fBIS_IRDA_ONEBIT_SAMPLE\fP   IS_IRDA_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_IRDA_GETCLOCKSOURCE   IRDA_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 1866 行定义\&.
.SS "#define __HAL_IRDA_MASK_COMPUTATION   IRDA_MASK_COMPUTATION"

.PP
在文件 stm32_hal_legacy\&.h 第 1867 行定义\&.
.SS "#define __IRDA_DISABLE   \fB__HAL_IRDA_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1863 行定义\&.
.SS "#define __IRDA_ENABLE   \fB__HAL_IRDA_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1864 行定义\&.
.SS "#define __IRDA_GETCLOCKSOURCE   IRDA_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 1868 行定义\&.
.SS "#define __IRDA_MASK_COMPUTATION   IRDA_MASK_COMPUTATION"

.PP
在文件 stm32_hal_legacy\&.h 第 1869 行定义\&.
.SS "#define IS_IRDA_ONEBIT_SAMPLE   IS_IRDA_ONE_BIT_SAMPLE"

.PP
在文件 stm32_hal_legacy\&.h 第 1871 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
