.TH "HAL_I2C_Aliased_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_I2CEx_AnalogFilter_Config\fP   HAL_I2CEx_ConfigAnalogFilter"
.br
.ti -1c
.RI "#define \fBHAL_I2CEx_DigitalFilter_Config\fP   HAL_I2CEx_ConfigDigitalFilter"
.br
.ti -1c
.RI "#define \fBHAL_FMPI2CEx_AnalogFilter_Config\fP   HAL_FMPI2CEx_ConfigAnalogFilter"
.br
.ti -1c
.RI "#define \fBHAL_FMPI2CEx_DigitalFilter_Config\fP   HAL_FMPI2CEx_ConfigDigitalFilter"
.br
.ti -1c
.RI "#define \fBHAL_I2CFastModePlusConfig\fP(SYSCFG_I2CFastModePlus,  cmd)   (((cmd)==ENABLE)? HAL_I2CEx_EnableFastModePlus(SYSCFG_I2CFastModePlus): HAL_I2CEx_DisableFastModePlus(SYSCFG_I2CFastModePlus))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_FMPI2CEx_AnalogFilter_Config   HAL_FMPI2CEx_ConfigAnalogFilter"

.PP
在文件 stm32_hal_legacy\&.h 第 1249 行定义\&.
.SS "#define HAL_FMPI2CEx_DigitalFilter_Config   HAL_FMPI2CEx_ConfigDigitalFilter"

.PP
在文件 stm32_hal_legacy\&.h 第 1250 行定义\&.
.SS "#define HAL_I2CEx_AnalogFilter_Config   HAL_I2CEx_ConfigAnalogFilter"

.PP
在文件 stm32_hal_legacy\&.h 第 1247 行定义\&.
.SS "#define HAL_I2CEx_DigitalFilter_Config   HAL_I2CEx_ConfigDigitalFilter"

.PP
在文件 stm32_hal_legacy\&.h 第 1248 行定义\&.
.SS "#define HAL_I2CFastModePlusConfig(SYSCFG_I2CFastModePlus, cmd)   (((cmd)==ENABLE)? HAL_I2CEx_EnableFastModePlus(SYSCFG_I2CFastModePlus): HAL_I2CEx_DisableFastModePlus(SYSCFG_I2CFastModePlus))"

.PP
在文件 stm32_hal_legacy\&.h 第 1252 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
