.TH "HAL_SAI_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SAI_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSAI_OUTPUTDRIVE_DISABLED\fP   SAI_OUTPUTDRIVE_DISABLE"
.br
.ti -1c
.RI "#define \fBSAI_OUTPUTDRIVE_ENABLED\fP   SAI_OUTPUTDRIVE_ENABLE"
.br
.ti -1c
.RI "#define \fBSAI_MASTERDIVIDER_ENABLED\fP   SAI_MASTERDIVIDER_ENABLE"
.br
.ti -1c
.RI "#define \fBSAI_MASTERDIVIDER_DISABLED\fP   SAI_MASTERDIVIDER_DISABLE"
.br
.ti -1c
.RI "#define \fBSAI_STREOMODE\fP   SAI_STEREOMODE"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Empty\fP   SAI_FIFOSTATUS_EMPTY"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Less1QuarterFull\fP   SAI_FIFOSTATUS_LESS1QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_1QuarterFull\fP   SAI_FIFOSTATUS_1QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_HalfFull\fP   SAI_FIFOSTATUS_HALFFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_3QuartersFull\fP   SAI_FIFOSTATUS_3QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Full\fP   SAI_FIFOSTATUS_FULL"
.br
.ti -1c
.RI "#define \fBIS_SAI_BLOCK_MONO_STREO_MODE\fP   IS_SAI_BLOCK_MONO_STEREO_MODE"
.br
.ti -1c
.RI "#define \fBSAI_SYNCHRONOUS_EXT\fP   SAI_SYNCHRONOUS_EXT_SAI1"
.br
.ti -1c
.RI "#define \fBSAI_SYNCEXT_IN_ENABLE\fP   SAI_SYNCEXT_OUTBLOCKA_ENABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_SAI_BLOCK_MONO_STREO_MODE   IS_SAI_BLOCK_MONO_STEREO_MODE"

.PP
在文件 stm32_hal_legacy\&.h 第 3403 行定义\&.
.SS "#define SAI_FIFOStatus_1QuarterFull   SAI_FIFOSTATUS_1QUARTERFULL"

.PP
在文件 stm32_hal_legacy\&.h 第 3399 行定义\&.
.SS "#define SAI_FIFOStatus_3QuartersFull   SAI_FIFOSTATUS_3QUARTERFULL"

.PP
在文件 stm32_hal_legacy\&.h 第 3401 行定义\&.
.SS "#define SAI_FIFOStatus_Empty   SAI_FIFOSTATUS_EMPTY"

.PP
在文件 stm32_hal_legacy\&.h 第 3397 行定义\&.
.SS "#define SAI_FIFOStatus_Full   SAI_FIFOSTATUS_FULL"

.PP
在文件 stm32_hal_legacy\&.h 第 3402 行定义\&.
.SS "#define SAI_FIFOStatus_HalfFull   SAI_FIFOSTATUS_HALFFULL"

.PP
在文件 stm32_hal_legacy\&.h 第 3400 行定义\&.
.SS "#define SAI_FIFOStatus_Less1QuarterFull   SAI_FIFOSTATUS_LESS1QUARTERFULL"

.PP
在文件 stm32_hal_legacy\&.h 第 3398 行定义\&.
.SS "#define SAI_MASTERDIVIDER_DISABLED   SAI_MASTERDIVIDER_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3395 行定义\&.
.SS "#define SAI_MASTERDIVIDER_ENABLED   SAI_MASTERDIVIDER_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3394 行定义\&.
.SS "#define SAI_OUTPUTDRIVE_DISABLED   SAI_OUTPUTDRIVE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3392 行定义\&.
.SS "#define SAI_OUTPUTDRIVE_ENABLED   SAI_OUTPUTDRIVE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3393 行定义\&.
.SS "#define SAI_STREOMODE   SAI_STEREOMODE"

.PP
在文件 stm32_hal_legacy\&.h 第 3396 行定义\&.
.SS "#define SAI_SYNCEXT_IN_ENABLE   SAI_SYNCEXT_OUTBLOCKA_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3405 行定义\&.
.SS "#define SAI_SYNCHRONOUS_EXT   SAI_SYNCHRONOUS_EXT_SAI1"

.PP
在文件 stm32_hal_legacy\&.h 第 3404 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
