.TH "HAL_FLASH_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTYPEPROGRAM_BYTE\fP   \fBFLASH_TYPEPROGRAM_BYTE\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_HALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_WORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_DOUBLEWORD\fP   \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_SECTORS\fP   \fBFLASH_TYPEERASE_SECTORS\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGES\fP   FLASH_TYPEERASE_PAGES"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGEERASE\fP   FLASH_TYPEERASE_PAGES"
.br
.ti -1c
.RI "#define \fBTYPEERASE_MASSERASE\fP   \fBFLASH_TYPEERASE_MASSERASE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_DISABLE\fP   \fBOB_WRPSTATE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_ENABLE\fP   \fBOB_WRPSTATE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_TIMEOUT_VALUE\fP   FLASH_TIMEOUT_VALUE"
.br
.ti -1c
.RI "#define \fBOBEX_PCROP\fP   OPTIONBYTE_PCROP"
.br
.ti -1c
.RI "#define \fBOBEX_BOOTCONFIG\fP   OPTIONBYTE_BOOTCONFIG"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_DISABLE\fP   OB_PCROP_STATE_DISABLE"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_ENABLE\fP   OB_PCROP_STATE_ENABLE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_BYTE\fP   FLASH_TYPEERASEDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_HALFWORD\fP   FLASH_TYPEERASEDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_WORD\fP   FLASH_TYPEERASEDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_BYTE\fP   FLASH_TYPEPROGRAMDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_HALFWORD\fP   FLASH_TYPEPROGRAMDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_WORD\fP   FLASH_TYPEPROGRAMDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTBYTE\fP   FLASH_TYPEPROGRAMDATA_FASTBYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTHALFWORD\fP   FLASH_TYPEPROGRAMDATA_FASTHALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTWORD\fP   FLASH_TYPEPROGRAMDATA_FASTWORD"
.br
.ti -1c
.RI "#define \fBPAGESIZE\fP   FLASH_PAGE_SIZE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTBYTE\fP   \fBFLASH_TYPEPROGRAM_BYTE\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTHALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTWORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_1\fP   \fBFLASH_VOLTAGE_RANGE_1\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_2\fP   \fBFLASH_VOLTAGE_RANGE_2\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_3\fP   \fBFLASH_VOLTAGE_RANGE_3\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_4\fP   \fBFLASH_VOLTAGE_RANGE_4\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST\fP   FLASH_TYPEPROGRAM_FAST"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST_AND_LAST\fP   FLASH_TYPEPROGRAM_FAST_AND_LAST"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAA\fP   OB_WRPAREA_BANK1_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAB\fP   OB_WRPAREA_BANK1_AREAB"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAA\fP   OB_WRPAREA_BANK2_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAB\fP   OB_WRPAREA_BANK2_AREAB"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_FREEZE\fP   OB_IWDG_STDBY_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_ACTIVE\fP   OB_IWDG_STDBY_RUN"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_FREEZE\fP   OB_IWDG_STOP_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_ACTIVE\fP   OB_IWDG_STOP_RUN"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NONE\fP   \fBHAL_FLASH_ERROR_NONE\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_RD\fP   \fBHAL_FLASH_ERROR_RD\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PG\fP   HAL_FLASH_ERROR_PROG"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGP\fP   \fBHAL_FLASH_ERROR_PGS\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_WRP\fP   \fBHAL_FLASH_ERROR_WRP\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTV\fP   HAL_FLASH_ERROR_OPTV"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTVUSR\fP   HAL_FLASH_ERROR_OPTVUSR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PROG\fP   HAL_FLASH_ERROR_PROG"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OP\fP   \fBHAL_FLASH_ERROR_OPERATION\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGA\fP   \fBHAL_FLASH_ERROR_PGA\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZE\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZ\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGS\fP   \fBHAL_FLASH_ERROR_PGS\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_MIS\fP   HAL_FLASH_ERROR_MIS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FAST\fP   HAL_FLASH_ERROR_FAST"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FWWERR\fP   HAL_FLASH_ERROR_FWWERR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NOTZERO\fP   HAL_FLASH_ERROR_NOTZERO"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPERATION\fP   \fBHAL_FLASH_ERROR_OPERATION\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_ERS\fP   HAL_FLASH_ERROR_ERS"
.br
.ti -1c
.RI "#define \fBOB_WDG_SW\fP   \fBOB_IWDG_SW\fP"
.br
.ti -1c
.RI "#define \fBOB_WDG_HW\fP   \fBOB_IWDG_HW\fP"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_SET\fP   OB_SDACD_VDD_MONITOR_SET"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_RESET\fP   OB_SDACD_VDD_MONITOR_RESET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_SET\fP   OB_SRAM_PARITY_SET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_RESET\fP   OB_SRAM_PARITY_RESET"
.br
.ti -1c
.RI "#define \fBIS_OB_SDADC12_VDD_MONITOR\fP   IS_OB_SDACD_VDD_MONITOR"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL0\fP   \fBOB_RDP_LEVEL_0\fP"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL1\fP   \fBOB_RDP_LEVEL_1\fP"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL2\fP   \fBOB_RDP_LEVEL_2\fP"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_NONE\fP   OB_BOOT_LOCK_DISABLE"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_FLASH\fP   OB_BOOT_LOCK_ENABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FLASH_ERROR_ERS   HAL_FLASH_ERROR_ERS"

.PP
在文件 stm32_hal_legacy\&.h 第 429 行定义\&.
.SS "#define FLASH_ERROR_FAST   HAL_FLASH_ERROR_FAST"

.PP
在文件 stm32_hal_legacy\&.h 第 425 行定义\&.
.SS "#define FLASH_ERROR_FWWERR   HAL_FLASH_ERROR_FWWERR"

.PP
在文件 stm32_hal_legacy\&.h 第 426 行定义\&.
.SS "#define FLASH_ERROR_MIS   HAL_FLASH_ERROR_MIS"

.PP
在文件 stm32_hal_legacy\&.h 第 424 行定义\&.
.SS "#define FLASH_ERROR_NONE   \fBHAL_FLASH_ERROR_NONE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 411 行定义\&.
.SS "#define FLASH_ERROR_NOTZERO   HAL_FLASH_ERROR_NOTZERO"

.PP
在文件 stm32_hal_legacy\&.h 第 427 行定义\&.
.SS "#define FLASH_ERROR_OP   \fBHAL_FLASH_ERROR_OPERATION\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 419 行定义\&.
.SS "#define FLASH_ERROR_OPERATION   \fBHAL_FLASH_ERROR_OPERATION\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 428 行定义\&.
.SS "#define FLASH_ERROR_OPTV   HAL_FLASH_ERROR_OPTV"

.PP
在文件 stm32_hal_legacy\&.h 第 416 行定义\&.
.SS "#define FLASH_ERROR_OPTVUSR   HAL_FLASH_ERROR_OPTVUSR"

.PP
在文件 stm32_hal_legacy\&.h 第 417 行定义\&.
.SS "#define FLASH_ERROR_PG   HAL_FLASH_ERROR_PROG"

.PP
在文件 stm32_hal_legacy\&.h 第 413 行定义\&.
.SS "#define FLASH_ERROR_PGA   \fBHAL_FLASH_ERROR_PGA\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 420 行定义\&.
.SS "#define FLASH_ERROR_PGP   \fBHAL_FLASH_ERROR_PGS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 414 行定义\&.
.SS "#define FLASH_ERROR_PGS   \fBHAL_FLASH_ERROR_PGS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 423 行定义\&.
.SS "#define FLASH_ERROR_PROG   HAL_FLASH_ERROR_PROG"

.PP
在文件 stm32_hal_legacy\&.h 第 418 行定义\&.
.SS "#define FLASH_ERROR_RD   \fBHAL_FLASH_ERROR_RD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 412 行定义\&.
.SS "#define FLASH_ERROR_SIZ   HAL_FLASH_ERROR_SIZE"

.PP
在文件 stm32_hal_legacy\&.h 第 422 行定义\&.
.SS "#define FLASH_ERROR_SIZE   HAL_FLASH_ERROR_SIZE"

.PP
在文件 stm32_hal_legacy\&.h 第 421 行定义\&.
.SS "#define FLASH_ERROR_WRP   \fBHAL_FLASH_ERROR_WRP\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 415 行定义\&.
.SS "#define HAL_FLASH_TIMEOUT_VALUE   FLASH_TIMEOUT_VALUE"

.PP
在文件 stm32_hal_legacy\&.h 第 379 行定义\&.
.SS "#define IS_OB_SDADC12_VDD_MONITOR   IS_OB_SDACD_VDD_MONITOR"

.PP
在文件 stm32_hal_legacy\&.h 第 436 行定义\&.
.SS "#define IWDG_STDBY_ACTIVE   OB_IWDG_STDBY_RUN"

.PP
在文件 stm32_hal_legacy\&.h 第 408 行定义\&.
.SS "#define IWDG_STDBY_FREEZE   OB_IWDG_STDBY_FREEZE"

.PP
在文件 stm32_hal_legacy\&.h 第 407 行定义\&.
.SS "#define IWDG_STOP_ACTIVE   OB_IWDG_STOP_RUN"

.PP
在文件 stm32_hal_legacy\&.h 第 410 行定义\&.
.SS "#define IWDG_STOP_FREEZE   OB_IWDG_STOP_FREEZE"

.PP
在文件 stm32_hal_legacy\&.h 第 409 行定义\&.
.SS "#define OB_BOOT_ENTRY_FORCED_FLASH   OB_BOOT_LOCK_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 445 行定义\&.
.SS "#define OB_BOOT_ENTRY_FORCED_NONE   OB_BOOT_LOCK_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 444 行定义\&.
.SS "#define OB_RAM_PARITY_CHECK_RESET   OB_SRAM_PARITY_RESET"

.PP
在文件 stm32_hal_legacy\&.h 第 435 行定义\&.
.SS "#define OB_RAM_PARITY_CHECK_SET   OB_SRAM_PARITY_SET"

.PP
在文件 stm32_hal_legacy\&.h 第 434 行定义\&.
.SS "#define OB_RDP_LEVEL0   \fBOB_RDP_LEVEL_0\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 437 行定义\&.
.SS "#define OB_RDP_LEVEL1   \fBOB_RDP_LEVEL_1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 438 行定义\&.
.SS "#define OB_RDP_LEVEL2   \fBOB_RDP_LEVEL_2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 439 行定义\&.
.SS "#define OB_SDADC12_VDD_MONITOR_RESET   OB_SDACD_VDD_MONITOR_RESET"

.PP
在文件 stm32_hal_legacy\&.h 第 433 行定义\&.
.SS "#define OB_SDADC12_VDD_MONITOR_SET   OB_SDACD_VDD_MONITOR_SET"

.PP
在文件 stm32_hal_legacy\&.h 第 432 行定义\&.
.SS "#define OB_WDG_HW   \fBOB_IWDG_HW\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 431 行定义\&.
.SS "#define OB_WDG_SW   \fBOB_IWDG_SW\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 430 行定义\&.
.SS "#define OBEX_BOOTCONFIG   OPTIONBYTE_BOOTCONFIG"

.PP
在文件 stm32_hal_legacy\&.h 第 381 行定义\&.
.SS "#define OBEX_PCROP   OPTIONBYTE_PCROP"

.PP
在文件 stm32_hal_legacy\&.h 第 380 行定义\&.
.SS "#define PAGESIZE   FLASH_PAGE_SIZE"

.PP
在文件 stm32_hal_legacy\&.h 第 393 行定义\&.
.SS "#define PCROPSTATE_DISABLE   OB_PCROP_STATE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 382 行定义\&.
.SS "#define PCROPSTATE_ENABLE   OB_PCROP_STATE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 383 行定义\&.
.SS "#define TYPEERASE_MASSERASE   \fBFLASH_TYPEERASE_MASSERASE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 376 行定义\&.
.SS "#define TYPEERASE_PAGEERASE   FLASH_TYPEERASE_PAGES"

.PP
在文件 stm32_hal_legacy\&.h 第 375 行定义\&.
.SS "#define TYPEERASE_PAGES   FLASH_TYPEERASE_PAGES"

.PP
在文件 stm32_hal_legacy\&.h 第 374 行定义\&.
.SS "#define TYPEERASE_SECTORS   \fBFLASH_TYPEERASE_SECTORS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 373 行定义\&.
.SS "#define TYPEERASEDATA_BYTE   FLASH_TYPEERASEDATA_BYTE"

.PP
在文件 stm32_hal_legacy\&.h 第 384 行定义\&.
.SS "#define TYPEERASEDATA_HALFWORD   FLASH_TYPEERASEDATA_HALFWORD"

.PP
在文件 stm32_hal_legacy\&.h 第 385 行定义\&.
.SS "#define TYPEERASEDATA_WORD   FLASH_TYPEERASEDATA_WORD"

.PP
在文件 stm32_hal_legacy\&.h 第 386 行定义\&.
.SS "#define TYPEPROGRAM_BYTE   \fBFLASH_TYPEPROGRAM_BYTE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 369 行定义\&.
.SS "#define TYPEPROGRAM_DOUBLEWORD   \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 372 行定义\&.
.SS "#define TYPEPROGRAM_FAST   FLASH_TYPEPROGRAM_FAST"

.PP
在文件 stm32_hal_legacy\&.h 第 401 行定义\&.
.SS "#define TYPEPROGRAM_FAST_AND_LAST   FLASH_TYPEPROGRAM_FAST_AND_LAST"

.PP
在文件 stm32_hal_legacy\&.h 第 402 行定义\&.
.SS "#define TYPEPROGRAM_FASTBYTE   \fBFLASH_TYPEPROGRAM_BYTE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 394 行定义\&.
.SS "#define TYPEPROGRAM_FASTHALFWORD   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 395 行定义\&.
.SS "#define TYPEPROGRAM_FASTWORD   \fBFLASH_TYPEPROGRAM_WORD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 396 行定义\&.
.SS "#define TYPEPROGRAM_HALFWORD   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 370 行定义\&.
.SS "#define TYPEPROGRAM_WORD   \fBFLASH_TYPEPROGRAM_WORD\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 371 行定义\&.
.SS "#define TYPEPROGRAMDATA_BYTE   FLASH_TYPEPROGRAMDATA_BYTE"

.PP
在文件 stm32_hal_legacy\&.h 第 387 行定义\&.
.SS "#define TYPEPROGRAMDATA_FASTBYTE   FLASH_TYPEPROGRAMDATA_FASTBYTE"

.PP
在文件 stm32_hal_legacy\&.h 第 390 行定义\&.
.SS "#define TYPEPROGRAMDATA_FASTHALFWORD   FLASH_TYPEPROGRAMDATA_FASTHALFWORD"

.PP
在文件 stm32_hal_legacy\&.h 第 391 行定义\&.
.SS "#define TYPEPROGRAMDATA_FASTWORD   FLASH_TYPEPROGRAMDATA_FASTWORD"

.PP
在文件 stm32_hal_legacy\&.h 第 392 行定义\&.
.SS "#define TYPEPROGRAMDATA_HALFWORD   FLASH_TYPEPROGRAMDATA_HALFWORD"

.PP
在文件 stm32_hal_legacy\&.h 第 388 行定义\&.
.SS "#define TYPEPROGRAMDATA_WORD   FLASH_TYPEPROGRAMDATA_WORD"

.PP
在文件 stm32_hal_legacy\&.h 第 389 行定义\&.
.SS "#define VOLTAGE_RANGE_1   \fBFLASH_VOLTAGE_RANGE_1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 397 行定义\&.
.SS "#define VOLTAGE_RANGE_2   \fBFLASH_VOLTAGE_RANGE_2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 398 行定义\&.
.SS "#define VOLTAGE_RANGE_3   \fBFLASH_VOLTAGE_RANGE_3\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 399 行定义\&.
.SS "#define VOLTAGE_RANGE_4   \fBFLASH_VOLTAGE_RANGE_4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 400 行定义\&.
.SS "#define WRPAREA_BANK1_AREAA   OB_WRPAREA_BANK1_AREAA"

.PP
在文件 stm32_hal_legacy\&.h 第 403 行定义\&.
.SS "#define WRPAREA_BANK1_AREAB   OB_WRPAREA_BANK1_AREAB"

.PP
在文件 stm32_hal_legacy\&.h 第 404 行定义\&.
.SS "#define WRPAREA_BANK2_AREAA   OB_WRPAREA_BANK2_AREAA"

.PP
在文件 stm32_hal_legacy\&.h 第 405 行定义\&.
.SS "#define WRPAREA_BANK2_AREAB   OB_WRPAREA_BANK2_AREAB"

.PP
在文件 stm32_hal_legacy\&.h 第 406 行定义\&.
.SS "#define WRPSTATE_DISABLE   \fBOB_WRPSTATE_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 377 行定义\&.
.SS "#define WRPSTATE_ENABLE   \fBOB_WRPSTATE_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 378 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
