.TH "HAL_DAC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DAC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDAC1_CHANNEL_1\fP   DAC_CHANNEL_1"
.br
.ti -1c
.RI "#define \fBDAC1_CHANNEL_2\fP   DAC_CHANNEL_2"
.br
.ti -1c
.RI "#define \fBDAC2_CHANNEL_1\fP   DAC_CHANNEL_1"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_NOISE\fP   DAC_CR_WAVE1_0"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_TRIANGLE\fP   DAC_CR_WAVE1_1"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_NONE\fP   \fBDAC_WAVE_NONE\fP"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_NOISE\fP   \fBDAC_WAVE_NOISE\fP"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_TRIANGLE\fP   \fBDAC_WAVE_TRIANGLE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define DAC1_CHANNEL_1   DAC_CHANNEL_1"

.PP
在文件 stm32_hal_legacy\&.h 第 230 行定义\&.
.SS "#define DAC1_CHANNEL_2   DAC_CHANNEL_2"

.PP
在文件 stm32_hal_legacy\&.h 第 231 行定义\&.
.SS "#define DAC2_CHANNEL_1   DAC_CHANNEL_1"

.PP
在文件 stm32_hal_legacy\&.h 第 232 行定义\&.
.SS "#define DAC_WAVE_NOISE   DAC_CR_WAVE1_0"

.PP
在文件 stm32_hal_legacy\&.h 第 234 行定义\&.
.SS "#define DAC_WAVE_NONE   0x00000000U"

.PP
在文件 stm32_hal_legacy\&.h 第 233 行定义\&.
.SS "#define DAC_WAVE_TRIANGLE   DAC_CR_WAVE1_1"

.PP
在文件 stm32_hal_legacy\&.h 第 235 行定义\&.
.SS "#define DAC_WAVEGENERATION_NOISE   \fBDAC_WAVE_NOISE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 237 行定义\&.
.SS "#define DAC_WAVEGENERATION_NONE   \fBDAC_WAVE_NONE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 236 行定义\&.
.SS "#define DAC_WAVEGENERATION_TRIANGLE   \fBDAC_WAVE_TRIANGLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 238 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
