.TH "HAL_USART_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_USART_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__USART_ENABLE_IT\fP   \fB__HAL_USART_ENABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__USART_DISABLE_IT\fP   \fB__HAL_USART_DISABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__USART_ENABLE\fP   \fB__HAL_USART_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__USART_DISABLE\fP   \fB__HAL_USART_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_USART_GETCLOCKSOURCE\fP   USART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__USART_GETCLOCKSOURCE\fP   USART_GETCLOCKSOURCE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_USART_GETCLOCKSOURCE   USART_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 3275 行定义\&.
.SS "#define __USART_DISABLE   \fB__HAL_USART_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3273 行定义\&.
.SS "#define __USART_DISABLE_IT   \fB__HAL_USART_DISABLE_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3271 行定义\&.
.SS "#define __USART_ENABLE   \fB__HAL_USART_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3272 行定义\&.
.SS "#define __USART_ENABLE_IT   \fB__HAL_USART_ENABLE_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3270 行定义\&.
.SS "#define __USART_GETCLOCKSOURCE   USART_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 3276 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
