.TH "HAL_SMARTCARD_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMARTCARD_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__SMARTCARD_ENABLE_IT\fP   \fB__HAL_SMARTCARD_ENABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DISABLE_IT\fP   \fB__HAL_SMARTCARD_DISABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_ENABLE\fP   \fB__HAL_SMARTCARD_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DISABLE\fP   \fB__HAL_SMARTCARD_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DMA_REQUEST_ENABLE\fP   \fB__HAL_SMARTCARD_DMA_REQUEST_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DMA_REQUEST_DISABLE\fP   \fB__HAL_SMARTCARD_DMA_REQUEST_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_GETCLOCKSOURCE\fP   SMARTCARD_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_GETCLOCKSOURCE\fP   SMARTCARD_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_ONEBIT_SAMPLING\fP   IS_SMARTCARD_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_SMARTCARD_GETCLOCKSOURCE   SMARTCARD_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 3211 行定义\&.
.SS "#define __SMARTCARD_DISABLE   \fB__HAL_SMARTCARD_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3207 行定义\&.
.SS "#define __SMARTCARD_DISABLE_IT   \fB__HAL_SMARTCARD_DISABLE_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3205 行定义\&.
.SS "#define __SMARTCARD_DMA_REQUEST_DISABLE   \fB__HAL_SMARTCARD_DMA_REQUEST_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3209 行定义\&.
.SS "#define __SMARTCARD_DMA_REQUEST_ENABLE   \fB__HAL_SMARTCARD_DMA_REQUEST_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3208 行定义\&.
.SS "#define __SMARTCARD_ENABLE   \fB__HAL_SMARTCARD_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3206 行定义\&.
.SS "#define __SMARTCARD_ENABLE_IT   \fB__HAL_SMARTCARD_ENABLE_IT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 3204 行定义\&.
.SS "#define __SMARTCARD_GETCLOCKSOURCE   SMARTCARD_GETCLOCKSOURCE"

.PP
在文件 stm32_hal_legacy\&.h 第 3212 行定义\&.
.SS "#define IS_SMARTCARD_ONEBIT_SAMPLING   IS_SMARTCARD_ONE_BIT_SAMPLE"

.PP
在文件 stm32_hal_legacy\&.h 第 3214 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
