.TH "HAL_IRDA_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IRDA_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIRDA_ONE_BIT_SAMPLE_DISABLED\fP   IRDA_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBIRDA_ONE_BIT_SAMPLE_ENABLED\fP   IRDA_ONE_BIT_SAMPLE_ENABLE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IRDA_ONE_BIT_SAMPLE_DISABLED   IRDA_ONE_BIT_SAMPLE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 633 行定义\&.
.SS "#define IRDA_ONE_BIT_SAMPLE_ENABLED   IRDA_ONE_BIT_SAMPLE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 634 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
