.TH "HAL_FLASH_Aliased_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_WRPAREA\fP   IS_OB_WRPAREA"
.br
.ti -1c
.RI "#define \fBIS_TYPEPROGRAM\fP   \fBIS_FLASH_TYPEPROGRAM\fP"
.br
.ti -1c
.RI "#define \fBIS_TYPEPROGRAMFLASH\fP   \fBIS_FLASH_TYPEPROGRAM\fP"
.br
.ti -1c
.RI "#define \fBIS_TYPEERASE\fP   \fBIS_FLASH_TYPEERASE\fP"
.br
.ti -1c
.RI "#define \fBIS_NBSECTORS\fP   \fBIS_FLASH_NBSECTORS\fP"
.br
.ti -1c
.RI "#define \fBIS_OB_WDG_SOURCE\fP   \fBIS_OB_IWDG_SOURCE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_NBSECTORS   \fBIS_FLASH_NBSECTORS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1810 行定义\&.
.SS "#define IS_OB_WDG_SOURCE   \fBIS_OB_IWDG_SOURCE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1811 行定义\&.
.SS "#define IS_TYPEERASE   \fBIS_FLASH_TYPEERASE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1809 行定义\&.
.SS "#define IS_TYPEPROGRAM   \fBIS_FLASH_TYPEPROGRAM\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1807 行定义\&.
.SS "#define IS_TYPEPROGRAMFLASH   \fBIS_FLASH_TYPEPROGRAM\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 1808 行定义\&.
.SS "#define IS_WRPAREA   IS_OB_WRPAREA"

.PP
在文件 stm32_hal_legacy\&.h 第 1806 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
