.TH "HAL_TIM_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TIM_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBCCER_CCxE_MASK\fP   \fBTIM_CCER_CCxE_MASK\fP"
.br
.ti -1c
.RI "#define \fBCCER_CCxNE_MASK\fP   \fBTIM_CCER_CCxNE_MASK\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CR1\fP   \fBTIM_DMABASE_CR1\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CR2\fP   \fBTIM_DMABASE_CR2\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SMCR\fP   \fBTIM_DMABASE_SMCR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DIER\fP   \fBTIM_DMABASE_DIER\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SR\fP   \fBTIM_DMABASE_SR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_EGR\fP   \fBTIM_DMABASE_EGR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR1\fP   \fBTIM_DMABASE_CCMR1\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR2\fP   \fBTIM_DMABASE_CCMR2\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCER\fP   \fBTIM_DMABASE_CCER\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CNT\fP   \fBTIM_DMABASE_CNT\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_PSC\fP   \fBTIM_DMABASE_PSC\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_ARR\fP   \fBTIM_DMABASE_ARR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_RCR\fP   \fBTIM_DMABASE_RCR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR1\fP   \fBTIM_DMABASE_CCR1\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR2\fP   \fBTIM_DMABASE_CCR2\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR3\fP   \fBTIM_DMABASE_CCR3\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR4\fP   \fBTIM_DMABASE_CCR4\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_BDTR\fP   \fBTIM_DMABASE_BDTR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DCR\fP   \fBTIM_DMABASE_DCR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DMAR\fP   \fBTIM_DMABASE_DMAR\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR1\fP   TIM_DMABASE_OR1"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR3\fP   TIM_DMABASE_CCMR3"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR5\fP   TIM_DMABASE_CCR5"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR6\fP   TIM_DMABASE_CCR6"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR2\fP   TIM_DMABASE_OR2"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR3\fP   TIM_DMABASE_OR3"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_OR\fP   TIM_DMABASE_OR"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Update\fP   \fBTIM_EVENTSOURCE_UPDATE\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC1\fP   \fBTIM_EVENTSOURCE_CC1\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC2\fP   \fBTIM_EVENTSOURCE_CC2\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC3\fP   \fBTIM_EVENTSOURCE_CC3\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_CC4\fP   \fBTIM_EVENTSOURCE_CC4\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_COM\fP   \fBTIM_EVENTSOURCE_COM\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Trigger\fP   \fBTIM_EVENTSOURCE_TRIGGER\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Break\fP   \fBTIM_EVENTSOURCE_BREAK\fP"
.br
.ti -1c
.RI "#define \fBTIM_EventSource_Break2\fP   TIM_EVENTSOURCE_BREAK2"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_1Transfer\fP   \fBTIM_DMABURSTLENGTH_1TRANSFER\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_2Transfers\fP   \fBTIM_DMABURSTLENGTH_2TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_3Transfers\fP   \fBTIM_DMABURSTLENGTH_3TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_4Transfers\fP   \fBTIM_DMABURSTLENGTH_4TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_5Transfers\fP   \fBTIM_DMABURSTLENGTH_5TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_6Transfers\fP   \fBTIM_DMABURSTLENGTH_6TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_7Transfers\fP   \fBTIM_DMABURSTLENGTH_7TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_8Transfers\fP   \fBTIM_DMABURSTLENGTH_8TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_9Transfers\fP   \fBTIM_DMABURSTLENGTH_9TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_10Transfers\fP   \fBTIM_DMABURSTLENGTH_10TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_11Transfers\fP   \fBTIM_DMABURSTLENGTH_11TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_12Transfers\fP   \fBTIM_DMABURSTLENGTH_12TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_13Transfers\fP   \fBTIM_DMABURSTLENGTH_13TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_14Transfers\fP   \fBTIM_DMABURSTLENGTH_14TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_15Transfers\fP   \fBTIM_DMABURSTLENGTH_15TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_16Transfers\fP   \fBTIM_DMABURSTLENGTH_16TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_17Transfers\fP   \fBTIM_DMABURSTLENGTH_17TRANSFERS\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_18Transfers\fP   \fBTIM_DMABURSTLENGTH_18TRANSFERS\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CCER_CCxE_MASK   \fBTIM_CCER_CCxE_MASK\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 906 行定义\&.
.SS "#define CCER_CCxNE_MASK   \fBTIM_CCER_CCxNE_MASK\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 907 行定义\&.
.SS "#define TIM_DMABase_ARR   \fBTIM_DMABASE_ARR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 920 行定义\&.
.SS "#define TIM_DMABase_BDTR   \fBTIM_DMABASE_BDTR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 926 行定义\&.
.SS "#define TIM_DMABase_CCER   \fBTIM_DMABASE_CCER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 917 行定义\&.
.SS "#define TIM_DMABase_CCMR1   \fBTIM_DMABASE_CCMR1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 915 行定义\&.
.SS "#define TIM_DMABase_CCMR2   \fBTIM_DMABASE_CCMR2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 916 行定义\&.
.SS "#define TIM_DMABase_CCMR3   TIM_DMABASE_CCMR3"

.PP
在文件 stm32_hal_legacy\&.h 第 930 行定义\&.
.SS "#define TIM_DMABase_CCR1   \fBTIM_DMABASE_CCR1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 922 行定义\&.
.SS "#define TIM_DMABase_CCR2   \fBTIM_DMABASE_CCR2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 923 行定义\&.
.SS "#define TIM_DMABase_CCR3   \fBTIM_DMABASE_CCR3\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 924 行定义\&.
.SS "#define TIM_DMABase_CCR4   \fBTIM_DMABASE_CCR4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 925 行定义\&.
.SS "#define TIM_DMABase_CCR5   TIM_DMABASE_CCR5"

.PP
在文件 stm32_hal_legacy\&.h 第 931 行定义\&.
.SS "#define TIM_DMABase_CCR6   TIM_DMABASE_CCR6"

.PP
在文件 stm32_hal_legacy\&.h 第 932 行定义\&.
.SS "#define TIM_DMABase_CNT   \fBTIM_DMABASE_CNT\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 918 行定义\&.
.SS "#define TIM_DMABase_CR1   \fBTIM_DMABASE_CR1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 909 行定义\&.
.SS "#define TIM_DMABase_CR2   \fBTIM_DMABASE_CR2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 910 行定义\&.
.SS "#define TIM_DMABase_DCR   \fBTIM_DMABASE_DCR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 927 行定义\&.
.SS "#define TIM_DMABase_DIER   \fBTIM_DMABASE_DIER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 912 行定义\&.
.SS "#define TIM_DMABase_DMAR   \fBTIM_DMABASE_DMAR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 928 行定义\&.
.SS "#define TIM_DMABase_EGR   \fBTIM_DMABASE_EGR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 914 行定义\&.
.SS "#define TIM_DMABase_OR   TIM_DMABASE_OR"

.PP
在文件 stm32_hal_legacy\&.h 第 935 行定义\&.
.SS "#define TIM_DMABase_OR1   TIM_DMABASE_OR1"

.PP
在文件 stm32_hal_legacy\&.h 第 929 行定义\&.
.SS "#define TIM_DMABase_OR2   TIM_DMABASE_OR2"

.PP
在文件 stm32_hal_legacy\&.h 第 933 行定义\&.
.SS "#define TIM_DMABase_OR3   TIM_DMABASE_OR3"

.PP
在文件 stm32_hal_legacy\&.h 第 934 行定义\&.
.SS "#define TIM_DMABase_PSC   \fBTIM_DMABASE_PSC\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 919 行定义\&.
.SS "#define TIM_DMABase_RCR   \fBTIM_DMABASE_RCR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 921 行定义\&.
.SS "#define TIM_DMABase_SMCR   \fBTIM_DMABASE_SMCR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 911 行定义\&.
.SS "#define TIM_DMABase_SR   \fBTIM_DMABASE_SR\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 913 行定义\&.
.SS "#define TIM_DMABurstLength_10Transfers   \fBTIM_DMABURSTLENGTH_10TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 956 行定义\&.
.SS "#define TIM_DMABurstLength_11Transfers   \fBTIM_DMABURSTLENGTH_11TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 957 行定义\&.
.SS "#define TIM_DMABurstLength_12Transfers   \fBTIM_DMABURSTLENGTH_12TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 958 行定义\&.
.SS "#define TIM_DMABurstLength_13Transfers   \fBTIM_DMABURSTLENGTH_13TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 959 行定义\&.
.SS "#define TIM_DMABurstLength_14Transfers   \fBTIM_DMABURSTLENGTH_14TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 960 行定义\&.
.SS "#define TIM_DMABurstLength_15Transfers   \fBTIM_DMABURSTLENGTH_15TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 961 行定义\&.
.SS "#define TIM_DMABurstLength_16Transfers   \fBTIM_DMABURSTLENGTH_16TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 962 行定义\&.
.SS "#define TIM_DMABurstLength_17Transfers   \fBTIM_DMABURSTLENGTH_17TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 963 行定义\&.
.SS "#define TIM_DMABurstLength_18Transfers   \fBTIM_DMABURSTLENGTH_18TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 964 行定义\&.
.SS "#define TIM_DMABurstLength_1Transfer   \fBTIM_DMABURSTLENGTH_1TRANSFER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 947 行定义\&.
.SS "#define TIM_DMABurstLength_2Transfers   \fBTIM_DMABURSTLENGTH_2TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 948 行定义\&.
.SS "#define TIM_DMABurstLength_3Transfers   \fBTIM_DMABURSTLENGTH_3TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 949 行定义\&.
.SS "#define TIM_DMABurstLength_4Transfers   \fBTIM_DMABURSTLENGTH_4TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 950 行定义\&.
.SS "#define TIM_DMABurstLength_5Transfers   \fBTIM_DMABURSTLENGTH_5TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 951 行定义\&.
.SS "#define TIM_DMABurstLength_6Transfers   \fBTIM_DMABURSTLENGTH_6TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 952 行定义\&.
.SS "#define TIM_DMABurstLength_7Transfers   \fBTIM_DMABURSTLENGTH_7TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 953 行定义\&.
.SS "#define TIM_DMABurstLength_8Transfers   \fBTIM_DMABURSTLENGTH_8TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 954 行定义\&.
.SS "#define TIM_DMABurstLength_9Transfers   \fBTIM_DMABURSTLENGTH_9TRANSFERS\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 955 行定义\&.
.SS "#define TIM_EventSource_Break   \fBTIM_EVENTSOURCE_BREAK\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 944 行定义\&.
.SS "#define TIM_EventSource_Break2   TIM_EVENTSOURCE_BREAK2"

.PP
在文件 stm32_hal_legacy\&.h 第 945 行定义\&.
.SS "#define TIM_EventSource_CC1   \fBTIM_EVENTSOURCE_CC1\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 938 行定义\&.
.SS "#define TIM_EventSource_CC2   \fBTIM_EVENTSOURCE_CC2\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 939 行定义\&.
.SS "#define TIM_EventSource_CC3   \fBTIM_EVENTSOURCE_CC3\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 940 行定义\&.
.SS "#define TIM_EventSource_CC4   \fBTIM_EVENTSOURCE_CC4\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 941 行定义\&.
.SS "#define TIM_EventSource_COM   \fBTIM_EVENTSOURCE_COM\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 942 行定义\&.
.SS "#define TIM_EventSource_Trigger   \fBTIM_EVENTSOURCE_TRIGGER\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 943 行定义\&.
.SS "#define TIM_EventSource_Update   \fBTIM_EVENTSOURCE_UPDATE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 937 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
