.TH "HAL_OPAMP_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_OPAMP_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBOPAMP_NONINVERTINGINPUT_VP0\fP   OPAMP_NONINVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBOPAMP_NONINVERTINGINPUT_VP1\fP   OPAMP_NONINVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBOPAMP_NONINVERTINGINPUT_VP2\fP   OPAMP_NONINVERTINGINPUT_IO2"
.br
.ti -1c
.RI "#define \fBOPAMP_NONINVERTINGINPUT_VP3\fP   OPAMP_NONINVERTINGINPUT_IO3"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_NONINVERTINGINPUT_VP0\fP   OPAMP_SEC_NONINVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_NONINVERTINGINPUT_VP1\fP   OPAMP_SEC_NONINVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_NONINVERTINGINPUT_VP2\fP   OPAMP_SEC_NONINVERTINGINPUT_IO2"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_NONINVERTINGINPUT_VP3\fP   OPAMP_SEC_NONINVERTINGINPUT_IO3"
.br
.ti -1c
.RI "#define \fBOPAMP_INVERTINGINPUT_VM0\fP   OPAMP_INVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBOPAMP_INVERTINGINPUT_VM1\fP   OPAMP_INVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBIOPAMP_INVERTINGINPUT_VM0\fP   OPAMP_INVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBIOPAMP_INVERTINGINPUT_VM1\fP   OPAMP_INVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_INVERTINGINPUT_VM0\fP   OPAMP_SEC_INVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBOPAMP_SEC_INVERTINGINPUT_VM1\fP   OPAMP_SEC_INVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBOPAMP_INVERTINGINPUT_VINM\fP   OPAMP_SEC_INVERTINGINPUT_IO1"
.br
.ti -1c
.RI "#define \fBOPAMP_PGACONNECT_NO\fP   OPAMP_PGA_CONNECT_INVERTINGINPUT_NO"
.br
.ti -1c
.RI "#define \fBOPAMP_PGACONNECT_VM0\fP   OPAMP_PGA_CONNECT_INVERTINGINPUT_IO0"
.br
.ti -1c
.RI "#define \fBOPAMP_PGACONNECT_VM1\fP   OPAMP_PGA_CONNECT_INVERTINGINPUT_IO1"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IOPAMP_INVERTINGINPUT_VM0   OPAMP_INVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 730 行定义\&.
.SS "#define IOPAMP_INVERTINGINPUT_VM1   OPAMP_INVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 731 行定义\&.
.SS "#define OPAMP_INVERTINGINPUT_VINM   OPAMP_SEC_INVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 736 行定义\&.
.SS "#define OPAMP_INVERTINGINPUT_VM0   OPAMP_INVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 727 行定义\&.
.SS "#define OPAMP_INVERTINGINPUT_VM1   OPAMP_INVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 728 行定义\&.
.SS "#define OPAMP_NONINVERTINGINPUT_VP0   OPAMP_NONINVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 717 行定义\&.
.SS "#define OPAMP_NONINVERTINGINPUT_VP1   OPAMP_NONINVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 718 行定义\&.
.SS "#define OPAMP_NONINVERTINGINPUT_VP2   OPAMP_NONINVERTINGINPUT_IO2"

.PP
在文件 stm32_hal_legacy\&.h 第 719 行定义\&.
.SS "#define OPAMP_NONINVERTINGINPUT_VP3   OPAMP_NONINVERTINGINPUT_IO3"

.PP
在文件 stm32_hal_legacy\&.h 第 720 行定义\&.
.SS "#define OPAMP_PGACONNECT_NO   OPAMP_PGA_CONNECT_INVERTINGINPUT_NO"

.PP
在文件 stm32_hal_legacy\&.h 第 738 行定义\&.
.SS "#define OPAMP_PGACONNECT_VM0   OPAMP_PGA_CONNECT_INVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 739 行定义\&.
.SS "#define OPAMP_PGACONNECT_VM1   OPAMP_PGA_CONNECT_INVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 740 行定义\&.
.SS "#define OPAMP_SEC_INVERTINGINPUT_VM0   OPAMP_SEC_INVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 733 行定义\&.
.SS "#define OPAMP_SEC_INVERTINGINPUT_VM1   OPAMP_SEC_INVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 734 行定义\&.
.SS "#define OPAMP_SEC_NONINVERTINGINPUT_VP0   OPAMP_SEC_NONINVERTINGINPUT_IO0"

.PP
在文件 stm32_hal_legacy\&.h 第 722 行定义\&.
.SS "#define OPAMP_SEC_NONINVERTINGINPUT_VP1   OPAMP_SEC_NONINVERTINGINPUT_IO1"

.PP
在文件 stm32_hal_legacy\&.h 第 723 行定义\&.
.SS "#define OPAMP_SEC_NONINVERTINGINPUT_VP2   OPAMP_SEC_NONINVERTINGINPUT_IO2"

.PP
在文件 stm32_hal_legacy\&.h 第 724 行定义\&.
.SS "#define OPAMP_SEC_NONINVERTINGINPUT_VP3   OPAMP_SEC_NONINVERTINGINPUT_IO3"

.PP
在文件 stm32_hal_legacy\&.h 第 725 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
