.TH "HAL_SMARTCARD_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMARTCARD_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMARTCARD_NACK_ENABLED\fP   \fBSMARTCARD_NACK_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSMARTCARD_NACK_DISABLED\fP   \fBSMARTCARD_NACK_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_DISABLED\fP   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_ENABLED\fP   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_DISABLE\fP   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_ENABLE\fP   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_TIMEOUT_DISABLED\fP   SMARTCARD_TIMEOUT_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_TIMEOUT_ENABLED\fP   SMARTCARD_TIMEOUT_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_DISABLED\fP   \fBSMARTCARD_LASTBIT_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_ENABLED\fP   \fBSMARTCARD_LASTBIT_ENABLE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMARTCARD_LASTBIT_DISABLED   \fBSMARTCARD_LASTBIT_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 847 行定义\&.
.SS "#define SMARTCARD_LASTBIT_ENABLED   \fBSMARTCARD_LASTBIT_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 848 行定义\&.
.SS "#define SMARTCARD_NACK_DISABLED   \fBSMARTCARD_NACK_DISABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 837 行定义\&.
.SS "#define SMARTCARD_NACK_ENABLED   \fBSMARTCARD_NACK_ENABLE\fP"

.PP
在文件 stm32_hal_legacy\&.h 第 836 行定义\&.
.SS "#define SMARTCARD_ONEBIT_SAMPLING_DISABLE   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 841 行定义\&.
.SS "#define SMARTCARD_ONEBIT_SAMPLING_DISABLED   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 839 行定义\&.
.SS "#define SMARTCARD_ONEBIT_SAMPLING_ENABLE   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 842 行定义\&.
.SS "#define SMARTCARD_ONEBIT_SAMPLING_ENABLED   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 840 行定义\&.
.SS "#define SMARTCARD_TIMEOUT_DISABLED   SMARTCARD_TIMEOUT_DISABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 844 行定义\&.
.SS "#define SMARTCARD_TIMEOUT_ENABLED   SMARTCARD_TIMEOUT_ENABLE"

.PP
在文件 stm32_hal_legacy\&.h 第 845 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
