.TH "I2C_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Transmit\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Receive\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Transmit\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Receive\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Write\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Read\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_IsDeviceReady\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint32_t Trials, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Transmit_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Receive_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Transmit_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Receive_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Write_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Read_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Seq_Transmit_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Seq_Receive_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Seq_Transmit_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Seq_Receive_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_EnableListen_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_DisableListen_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Abort_IT\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Transmit_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Receive_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Transmit_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Receive_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Write_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Mem_Read_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Seq_Transmit_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Master_Seq_Receive_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Seq_Transmit_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Slave_Seq_Receive_DMA\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t *pData, uint16_t Size, uint32_t XferOptions)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_DisableListen_IT (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_EnableListen_IT (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_IsDeviceReady (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint32_t Trials, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Abort_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Receive (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Receive_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Receive_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Seq_Receive_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Seq_Receive_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Seq_Transmit_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Seq_Transmit_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Transmit (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Transmit_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Master_Transmit_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Read (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Read_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Read_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Write (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Write_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Mem_Write_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Receive (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Receive_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Receive_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Seq_Receive_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Seq_Receive_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Seq_Transmit_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Seq_Transmit_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t XferOptions)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Transmit (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Transmit_DMA (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Slave_Transmit_IT (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t * pData, uint16_t Size)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
