.TH "I2C_nostretch_mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_nostretch_mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_ENABLE\fP   I2C_CR1_NOSTRETCH"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2C_NOSTRETCH_DISABLE   0x00000000U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 322 行定义\&.
.SS "#define I2C_NOSTRETCH_ENABLE   I2C_CR1_NOSTRETCH"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 323 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
