.TH "I2C_handle_Structure_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_handle_Structure_definition \- I2C handle Structure definition  

.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fB__I2C_HandleTypeDef\fP"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "typedef struct \fB__I2C_HandleTypeDef\fP \fBI2C_HandleTypeDef\fP"
.br
.in -1c
.SH "详细描述"
.PP 
I2C handle Structure definition 


.SH "类型定义说明"
.PP 
.SS "typedef struct \fB__I2C_HandleTypeDef\fP \fBI2C_HandleTypeDef\fP"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
