.TH "I2C_XferOptions_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_XferOptions_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2C_FIRST_FRAME\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBI2C_FIRST_AND_NEXT_FRAME\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBI2C_NEXT_FRAME\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBI2C_FIRST_AND_LAST_FRAME\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBI2C_LAST_FRAME_NO_STOP\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBI2C_LAST_FRAME\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBI2C_OTHER_FRAME\fP   (0x00AA0000U)"
.br
.ti -1c
.RI "#define \fBI2C_OTHER_AND_LAST_FRAME\fP   (0xAA000000U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2C_FIRST_AND_LAST_FRAME   0x00000008U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 352 行定义\&.
.SS "#define I2C_FIRST_AND_NEXT_FRAME   0x00000002U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 350 行定义\&.
.SS "#define I2C_FIRST_FRAME   0x00000001U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 349 行定义\&.
.SS "#define I2C_LAST_FRAME   0x00000020U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 354 行定义\&.
.SS "#define I2C_LAST_FRAME_NO_STOP   0x00000010U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 353 行定义\&.
.SS "#define I2C_NEXT_FRAME   0x00000004U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 351 行定义\&.
.SS "#define I2C_OTHER_AND_LAST_FRAME   (0xAA000000U)"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 360 行定义\&.
.SS "#define I2C_OTHER_FRAME   (0x00AA0000U)"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 359 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
