.TH "I2C_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBI2C Configuration Structure definition\fP"
.br
.RI "I2C Configuration Structure definition "
.ti -1c
.RI "\fBHAL state structure definition\fP"
.br
.RI "HAL State structure definition "
.ti -1c
.RI "\fBHAL mode structure definition\fP"
.br
.RI "HAL Mode structure definition "
.ti -1c
.RI "\fBI2C Error Code definition\fP"
.br
.RI "I2C Error Code definition "
.ti -1c
.RI "\fBI2C handle Structure definition\fP"
.br
.RI "I2C handle Structure definition "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
