.TH "I2C_IRQ_Handler_and_Callbacks" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_IRQ_Handler_and_Callbacks
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_I2C_EV_IRQHandler\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_ER_IRQHandler\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MasterTxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MasterRxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_SlaveTxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_SlaveRxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_AddrCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)"
.br
.ti -1c
.RI "void \fBHAL_I2C_ListenCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MemTxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MemRxCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_ErrorCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_AbortCpltCallback\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_I2C_AbortCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_AddrCallback (\fBI2C_HandleTypeDef\fP * hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode)"

.SS "void HAL_I2C_ER_IRQHandler (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_ErrorCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_EV_IRQHandler (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_ListenCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MasterRxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MasterTxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MemRxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MemTxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_SlaveRxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_SlaveTxCpltCallback (\fBI2C_HandleTypeDef\fP * hi2c)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
