.TH "I2C_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBI2C duty cycle in fast mode\fP"
.br
.ti -1c
.RI "\fBI2C addressing mode\fP"
.br
.ti -1c
.RI "\fBI2C dual addressing mode\fP"
.br
.ti -1c
.RI "\fBI2C general call addressing mode\fP"
.br
.ti -1c
.RI "\fBI2C nostretch mode\fP"
.br
.ti -1c
.RI "\fBI2C Memory Address Size\fP"
.br
.ti -1c
.RI "\fBI2C XferDirection definition\fP"
.br
.ti -1c
.RI "\fBI2C XferOptions definition\fP"
.br
.ti -1c
.RI "\fBI2C Interrupt configuration definition\fP"
.br
.RI "I2C Interrupt definition Elements values convention: 0xXXXXXXXX "
.ti -1c
.RI "\fBI2C Flag definition\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
