.TH "I2C_Error_Code_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Error_Code_definition \- I2C Error Code definition  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_BERR\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_ARLO\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_AF\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_OVR\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_DMA\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_TIMEOUT\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_SIZE\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBHAL_I2C_ERROR_DMA_PARAM\fP   0x00000080U"
.br
.in -1c
.SH "详细描述"
.PP 
I2C Error Code definition 


.SH "宏定义说明"
.PP 
.SS "#define HAL_I2C_ERROR_AF   0x00000004U"
AF error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 168 行定义\&.
.SS "#define HAL_I2C_ERROR_ARLO   0x00000002U"
ARLO error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 167 行定义\&.
.SS "#define HAL_I2C_ERROR_BERR   0x00000001U"
BERR error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 166 行定义\&.
.SS "#define HAL_I2C_ERROR_DMA   0x00000010U"
DMA transfer error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 170 行定义\&.
.SS "#define HAL_I2C_ERROR_DMA_PARAM   0x00000080U"
DMA Parameter Error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 173 行定义\&.
.SS "#define HAL_I2C_ERROR_NONE   0x00000000U"
No error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 165 行定义\&.
.SS "#define HAL_I2C_ERROR_OVR   0x00000008U"
OVR error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 169 行定义\&.
.SS "#define HAL_I2C_ERROR_SIZE   0x00000040U"
Size Management error 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 172 行定义\&.
.SS "#define HAL_I2C_ERROR_TIMEOUT   0x00000020U"
Timeout Error 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 171 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
