.TH "I2C_Flag_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Flag_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2C_FLAG_OVR\fP   0x00010800U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_AF\fP   0x00010400U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_ARLO\fP   0x00010200U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_BERR\fP   0x00010100U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_TXE\fP   0x00010080U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_RXNE\fP   0x00010040U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_STOPF\fP   0x00010010U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_ADD10\fP   0x00010008U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_BTF\fP   0x00010004U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_ADDR\fP   0x00010002U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_SB\fP   0x00010001U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_DUALF\fP   0x00100080U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_GENCALL\fP   0x00100010U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_TRA\fP   0x00100004U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_BUSY\fP   0x00100002U"
.br
.ti -1c
.RI "#define \fBI2C_FLAG_MSL\fP   0x00100001U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2C_FLAG_ADD10   0x00010008U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 389 行定义\&.
.SS "#define I2C_FLAG_ADDR   0x00010002U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 391 行定义\&.
.SS "#define I2C_FLAG_AF   0x00010400U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 383 行定义\&.
.SS "#define I2C_FLAG_ARLO   0x00010200U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 384 行定义\&.
.SS "#define I2C_FLAG_BERR   0x00010100U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 385 行定义\&.
.SS "#define I2C_FLAG_BTF   0x00010004U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 390 行定义\&.
.SS "#define I2C_FLAG_BUSY   0x00100002U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 396 行定义\&.
.SS "#define I2C_FLAG_DUALF   0x00100080U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 393 行定义\&.
.SS "#define I2C_FLAG_GENCALL   0x00100010U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 394 行定义\&.
.SS "#define I2C_FLAG_MSL   0x00100001U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 397 行定义\&.
.SS "#define I2C_FLAG_OVR   0x00010800U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 382 行定义\&.
.SS "#define I2C_FLAG_RXNE   0x00010040U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 387 行定义\&.
.SS "#define I2C_FLAG_SB   0x00010001U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 392 行定义\&.
.SS "#define I2C_FLAG_STOPF   0x00010010U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 388 行定义\&.
.SS "#define I2C_FLAG_TRA   0x00100004U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 395 行定义\&.
.SS "#define I2C_FLAG_TXE   0x00010080U"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 386 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
