.TH "I2C_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_Init\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2C_DeInit\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MspInit\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.ti -1c
.RI "void \fBHAL_I2C_MspDeInit\fP (\fBI2C_HandleTypeDef\fP *hi2c)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_DeInit (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2C_Init (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MspDeInit (\fBI2C_HandleTypeDef\fP * hi2c)"

.SS "void HAL_I2C_MspInit (\fBI2C_HandleTypeDef\fP * hi2c)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
