.TH "I2C_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2C_FLAG_MASK\fP   0x0000FFFFU"
.br
.ti -1c
.RI "#define \fBI2C_MIN_PCLK_FREQ_STANDARD\fP   2000000U"
.br
.ti -1c
.RI "#define \fBI2C_MIN_PCLK_FREQ_FAST\fP   4000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2C_FLAG_MASK   0x0000FFFFU"

.PP
在文件 stm32f4xx_hal_i2c\&.h 第 644 行定义\&.
.SS "#define I2C_MIN_PCLK_FREQ_FAST   4000000U"
4 MHz 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 646 行定义\&.
.SS "#define I2C_MIN_PCLK_FREQ_STANDARD   2000000U"
2 MHz 
.br
 
.PP
在文件 stm32f4xx_hal_i2c\&.h 第 645 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
