.TH "I2S_Standard" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Standard
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2S_STANDARD_PHILIPS\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBI2S_STANDARD_MSB\fP   (SPI_I2SCFGR_I2SSTD_0)"
.br
.ti -1c
.RI "#define \fBI2S_STANDARD_LSB\fP   (SPI_I2SCFGR_I2SSTD_1)"
.br
.ti -1c
.RI "#define \fBI2S_STANDARD_PCM_SHORT\fP   ((SPI_I2SCFGR_I2SSTD_0 | SPI_I2SCFGR_I2SSTD_1))"
.br
.ti -1c
.RI "#define \fBI2S_STANDARD_PCM_LONG\fP   ((SPI_I2SCFGR_I2SSTD_0 | SPI_I2SCFGR_I2SSTD_1 | SPI_I2SCFGR_PCMSYNC))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2S_STANDARD_LSB   (SPI_I2SCFGR_I2SSTD_1)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 205 行定义\&.
.SS "#define I2S_STANDARD_MSB   (SPI_I2SCFGR_I2SSTD_0)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 204 行定义\&.
.SS "#define I2S_STANDARD_PCM_LONG   ((SPI_I2SCFGR_I2SSTD_0 | SPI_I2SCFGR_I2SSTD_1 | SPI_I2SCFGR_PCMSYNC))"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 207 行定义\&.
.SS "#define I2S_STANDARD_PCM_SHORT   ((SPI_I2SCFGR_I2SSTD_0 | SPI_I2SCFGR_I2SSTD_1))"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 206 行定义\&.
.SS "#define I2S_STANDARD_PHILIPS   (0x00000000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 203 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
