.TH "I2S_Data_Format" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Data_Format
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2S_DATAFORMAT_16B\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBI2S_DATAFORMAT_16B_EXTENDED\fP   (SPI_I2SCFGR_CHLEN)"
.br
.ti -1c
.RI "#define \fBI2S_DATAFORMAT_24B\fP   ((SPI_I2SCFGR_CHLEN | SPI_I2SCFGR_DATLEN_0))"
.br
.ti -1c
.RI "#define \fBI2S_DATAFORMAT_32B\fP   ((SPI_I2SCFGR_CHLEN | SPI_I2SCFGR_DATLEN_1))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2S_DATAFORMAT_16B   (0x00000000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 215 行定义\&.
.SS "#define I2S_DATAFORMAT_16B_EXTENDED   (SPI_I2SCFGR_CHLEN)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 216 行定义\&.
.SS "#define I2S_DATAFORMAT_24B   ((SPI_I2SCFGR_CHLEN | SPI_I2SCFGR_DATLEN_0))"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 217 行定义\&.
.SS "#define I2S_DATAFORMAT_32B   ((SPI_I2SCFGR_CHLEN | SPI_I2SCFGR_DATLEN_1))"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 218 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
