.TH "I2S_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Transmit\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Receive\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Transmit_IT\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Receive_IT\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "void \fBHAL_I2S_IRQHandler\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Transmit_DMA\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Receive_DMA\fP (\fBI2S_HandleTypeDef\fP *hi2s, uint16_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_DMAPause\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_DMAResume\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_DMAStop\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_TxHalfCpltCallback\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_TxCpltCallback\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_RxHalfCpltCallback\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_RxCpltCallback\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_ErrorCallback\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_DMAPause (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_DMAResume (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_DMAStop (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_ErrorCallback (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_IRQHandler (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Receive (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Receive_DMA (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Receive_IT (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size)"

.SS "void HAL_I2S_RxCpltCallback (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_RxHalfCpltCallback (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Transmit (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Transmit_DMA (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Transmit_IT (\fBI2S_HandleTypeDef\fP * hi2s, uint16_t * pData, uint16_t Size)"

.SS "void HAL_I2S_TxCpltCallback (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_TxHalfCpltCallback (\fBI2S_HandleTypeDef\fP * hi2s)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
