.TH "I2S_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_Init\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_I2S_DeInit\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_MspInit\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.ti -1c
.RI "void \fBHAL_I2S_MspDeInit\fP (\fBI2S_HandleTypeDef\fP *hi2s)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_DeInit (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "\fBHAL_StatusTypeDef\fP HAL_I2S_Init (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_MspDeInit (\fBI2S_HandleTypeDef\fP * hi2s)"

.SS "void HAL_I2S_MspInit (\fBI2S_HandleTypeDef\fP * hi2s)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
