.TH "I2S_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_InitTypeDef \- I2S Init structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_i2s\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBMode\fP"
.br
.ti -1c
.RI "uint32_t \fBStandard\fP"
.br
.ti -1c
.RI "uint32_t \fBDataFormat\fP"
.br
.ti -1c
.RI "uint32_t \fBMCLKOutput\fP"
.br
.ti -1c
.RI "uint32_t \fBAudioFreq\fP"
.br
.ti -1c
.RI "uint32_t \fBCPOL\fP"
.br
.ti -1c
.RI "uint32_t \fBClockSource\fP"
.br
.ti -1c
.RI "uint32_t \fBFullDuplexMode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
I2S Init structure definition 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AudioFreq"
Specifies the frequency selected for the I2S communication\&. This parameter can be a value of \fBI2S Audio Frequency\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 61 行定义\&.
.SS "uint32_t ClockSource"
Specifies the I2S Clock Source\&. This parameter can be a value of \fBI2S Clock Source Definition\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 67 行定义\&.
.SS "uint32_t CPOL"
Specifies the idle state of the I2S clock\&. This parameter can be a value of \fBI2S Clock Polarity\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 64 行定义\&.
.SS "uint32_t DataFormat"
Specifies the data format for the I2S communication\&. This parameter can be a value of \fBI2S Data Format\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 55 行定义\&.
.SS "uint32_t FullDuplexMode"
Specifies the I2S FullDuplex mode\&. This parameter can be a value of \fBI2S FullDuplex Mode\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 69 行定义\&.
.SS "uint32_t MCLKOutput"
Specifies whether the I2S MCLK output is enabled or not\&. This parameter can be a value of \fBI2S MCLK Output\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 58 行定义\&.
.SS "uint32_t Mode"
Specifies the I2S operating mode\&. This parameter can be a value of \fBI2S Mode\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 49 行定义\&.
.SS "uint32_t Standard"
Specifies the standard used for the I2S communication\&. This parameter can be a value of \fBI2S Standard\fP 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 52 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
