.TH "I2S_Interrupts_Definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Interrupts_Definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2S_IT_TXE\fP   SPI_CR2_TXEIE"
.br
.ti -1c
.RI "#define \fBI2S_IT_RXNE\fP   SPI_CR2_RXNEIE"
.br
.ti -1c
.RI "#define \fBI2S_IT_ERR\fP   SPI_CR2_ERRIE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2S_IT_ERR   SPI_CR2_ERRIE"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 272 行定义\&.
.SS "#define I2S_IT_RXNE   SPI_CR2_RXNEIE"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 271 行定义\&.
.SS "#define I2S_IT_TXE   SPI_CR2_TXEIE"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 270 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
