.TH "I2S_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBI2S Error\fP"
.br
.ti -1c
.RI "\fBI2S Mode\fP"
.br
.ti -1c
.RI "\fBI2S Standard\fP"
.br
.ti -1c
.RI "\fBI2S Data Format\fP"
.br
.ti -1c
.RI "\fBI2S MCLK Output\fP"
.br
.ti -1c
.RI "\fBI2S Audio Frequency\fP"
.br
.ti -1c
.RI "\fBI2S FullDuplex Mode\fP"
.br
.ti -1c
.RI "\fBI2S Clock Polarity\fP"
.br
.ti -1c
.RI "\fBI2S Interrupts Definition\fP"
.br
.ti -1c
.RI "\fBI2S Flags Definition\fP"
.br
.ti -1c
.RI "\fBI2S Clock Source Definition\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
