.TH "I2S_Audio_Frequency" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Audio_Frequency
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_192K\fP   (192000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_96K\fP   (96000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_48K\fP   (48000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_44K\fP   (44100U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_32K\fP   (32000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_22K\fP   (22050U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_16K\fP   (16000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_11K\fP   (11025U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_8K\fP   (8000U)"
.br
.ti -1c
.RI "#define \fBI2S_AUDIOFREQ_DEFAULT\fP   (2U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define I2S_AUDIOFREQ_11K   (11025U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 242 行定义\&.
.SS "#define I2S_AUDIOFREQ_16K   (16000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 241 行定义\&.
.SS "#define I2S_AUDIOFREQ_192K   (192000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 235 行定义\&.
.SS "#define I2S_AUDIOFREQ_22K   (22050U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 240 行定义\&.
.SS "#define I2S_AUDIOFREQ_32K   (32000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 239 行定义\&.
.SS "#define I2S_AUDIOFREQ_44K   (44100U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 238 行定义\&.
.SS "#define I2S_AUDIOFREQ_48K   (48000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 237 行定义\&.
.SS "#define I2S_AUDIOFREQ_8K   (8000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 243 行定义\&.
.SS "#define I2S_AUDIOFREQ_96K   (96000U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 236 行定义\&.
.SS "#define I2S_AUDIOFREQ_DEFAULT   (2U)"

.PP
在文件 stm32f4xx_hal_i2s\&.h 第 244 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
