.TH "I2S_Error" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_Error
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_NONE\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_TIMEOUT\fP   (0x00000001U)"
.br
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_OVR\fP   (0x00000002U)"
.br
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_UDR\fP   (0x00000004U)"
.br
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_DMA\fP   (0x00000008U)"
.br
.ti -1c
.RI "#define \fBHAL_I2S_ERROR_PRESCALER\fP   (0x00000010U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_I2S_ERROR_DMA   (0x00000008U)"
DMA transfer error 
.br
 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 180 行定义\&.
.SS "#define HAL_I2S_ERROR_NONE   (0x00000000U)"
No error 
.br
 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 176 行定义\&.
.SS "#define HAL_I2S_ERROR_OVR   (0x00000002U)"
OVR error 
.br
 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 178 行定义\&.
.SS "#define HAL_I2S_ERROR_PRESCALER   (0x00000010U)"
Prescaler Calculation error 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 181 行定义\&.
.SS "#define HAL_I2S_ERROR_TIMEOUT   (0x00000001U)"
Timeout error 
.br
 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 177 行定义\&.
.SS "#define HAL_I2S_ERROR_UDR   (0x00000004U)"
UDR error 
.br
 
.PP
在文件 stm32f4xx_hal_i2s\&.h 第 179 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
