.TH "IRDA_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRDA_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_IRDA_WORD_LENGTH\fP(LENGTH)"
.br
.ti -1c
.RI "#define \fBIS_IRDA_PARITY\fP(PARITY)"
.br
.ti -1c
.RI "#define \fBIS_IRDA_MODE\fP(MODE)   ((((MODE) & 0x0000FFF3U) == 0x00U) && ((MODE) != 0x00000000U))"
.br
.ti -1c
.RI "#define \fBIS_IRDA_POWERMODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_IRDA_BAUDRATE\fP(BAUDRATE)   ((BAUDRATE) < 115201U)"
.br
.ti -1c
.RI "#define \fBIRDA_DIV\fP(_PCLK_,  _BAUD_)   (((_PCLK_)*25U)/(4U*(_BAUD_)))"
.br
.ti -1c
.RI "#define \fBIRDA_DIVMANT\fP(_PCLK_,  _BAUD_)   (\fBIRDA_DIV\fP((_PCLK_), (_BAUD_))/100U)"
.br
.ti -1c
.RI "#define \fBIRDA_DIVFRAQ\fP(_PCLK_,  _BAUD_)   (((\fBIRDA_DIV\fP((_PCLK_), (_BAUD_)) \- (\fBIRDA_DIVMANT\fP((_PCLK_), (_BAUD_)) * 100U)) * 16U + 50U) / 100U)"
.br
.ti -1c
.RI "#define \fBIRDA_BRR\fP(_PCLK_,  _BAUD_)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IRDA_BRR(_PCLK_, _BAUD_)"
\fB值:\fP
.PP
.nf
                                        (((IRDA_DIVMANT((_PCLK_), (_BAUD_)) << 4U) + \
                                        (IRDA_DIVFRAQ((_PCLK_), (_BAUD_)) & 0xF0U)) + \
                                        (IRDA_DIVFRAQ((_PCLK_), (_BAUD_)) & 0x0FU))
.fi
.PP
在文件 stm32f4xx_hal_irda\&.h 第 654 行定义\&.
.SS "#define IRDA_DIV(_PCLK_, _BAUD_)   (((_PCLK_)*25U)/(4U*(_BAUD_)))"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 646 行定义\&.
.SS "#define IRDA_DIVFRAQ(_PCLK_, _BAUD_)   (((\fBIRDA_DIV\fP((_PCLK_), (_BAUD_)) \- (\fBIRDA_DIVMANT\fP((_PCLK_), (_BAUD_)) * 100U)) * 16U + 50U) / 100U)"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 650 行定义\&.
.SS "#define IRDA_DIVMANT(_PCLK_, _BAUD_)   (\fBIRDA_DIV\fP((_PCLK_), (_BAUD_))/100U)"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 648 行定义\&.
.SS "#define IS_IRDA_BAUDRATE(BAUDRATE)   ((BAUDRATE) < 115201U)"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 644 行定义\&.
.SS "#define IS_IRDA_MODE(MODE)   ((((MODE) & 0x0000FFF3U) == 0x00U) && ((MODE) != 0x00000000U))"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 639 行定义\&.
.SS "#define IS_IRDA_PARITY(PARITY)"
\fB值:\fP
.PP
.nf
                                       (((PARITY) == IRDA_PARITY_NONE) || \
                                       ((PARITY) == IRDA_PARITY_EVEN) || \
                                       ((PARITY) == IRDA_PARITY_ODD))
.fi
.PP
在文件 stm32f4xx_hal_irda\&.h 第 635 行定义\&.
.SS "#define IS_IRDA_POWERMODE(MODE)"
\fB值:\fP
.PP
.nf
                                       (((MODE) == IRDA_POWERMODE_LOWPOWER) || \
                                       ((MODE) == IRDA_POWERMODE_NORMAL))
.fi
.PP
在文件 stm32f4xx_hal_irda\&.h 第 641 行定义\&.
.SS "#define IS_IRDA_WORD_LENGTH(LENGTH)"
\fB值:\fP
.PP
.nf
                                       (((LENGTH) == IRDA_WORDLENGTH_8B) || \
                                       ((LENGTH) == IRDA_WORDLENGTH_9B))
.fi
.PP
在文件 stm32f4xx_hal_irda\&.h 第 632 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
