.TH "IRDA_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRDA_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIRDA_IT_MASK\fP"
.br
.RI "IRDA interruptions flag mask "
.ti -1c
.RI "#define \fBIRDA_CR1_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBIRDA_CR2_REG_INDEX\fP   2U"
.br
.ti -1c
.RI "#define \fBIRDA_CR3_REG_INDEX\fP   3U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IRDA_CR1_REG_INDEX   1U"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 621 行定义\&.
.SS "#define IRDA_CR2_REG_INDEX   2U"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 622 行定义\&.
.SS "#define IRDA_CR3_REG_INDEX   3U"

.PP
在文件 stm32f4xx_hal_irda\&.h 第 623 行定义\&.
.SS "#define IRDA_IT_MASK"
\fB值:\fP
.PP
.nf
                                  ((uint32_t) USART_CR1_PEIE | USART_CR1_TXEIE | USART_CR1_TCIE | USART_CR1_RXNEIE | \
                                  USART_CR1_IDLEIE | USART_CR2_LBDIE | USART_CR3_CTSIE | USART_CR3_EIE )
.fi
.PP
IRDA interruptions flag mask 
.PP
在文件 stm32f4xx_hal_irda\&.h 第 618 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
