.TH "IRDA_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRDA_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_IRDA_StateTypeDef\fP \fBHAL_IRDA_GetState\fP (\fBIRDA_HandleTypeDef\fP *hirda)"
.br
.ti -1c
.RI "uint32_t \fBHAL_IRDA_GetError\fP (\fBIRDA_HandleTypeDef\fP *hirda)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_IRDA_GetError (\fBIRDA_HandleTypeDef\fP * hirda)"

.SS "\fBHAL_IRDA_StateTypeDef\fP HAL_IRDA_GetState (\fBIRDA_HandleTypeDef\fP * hirda)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
