.TH "IRDA_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRDA_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBIRDA Error Code\fP"
.br
.ti -1c
.RI "\fBIRDA Word Length\fP"
.br
.ti -1c
.RI "\fBIRDA Parity\fP"
.br
.ti -1c
.RI "\fBIRDA Transfer Mode\fP"
.br
.ti -1c
.RI "\fBIRDA Low Power\fP"
.br
.ti -1c
.RI "\fBIRDA Flags\fP"
.br
.RI "Elements values convention: 0xXXXX "
.ti -1c
.RI "\fBIRDA Interrupt Definitions\fP"
.br
.RI "Elements values convention: 0xY000XXXX "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
