.TH "IWDG_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIWDG_KEY_RELOAD\fP   0x0000AAAAu"
.br
.RI "IWDG Key Register BitMask "
.ti -1c
.RI "#define \fBIWDG_KEY_ENABLE\fP   0x0000CCCCu"
.br
.ti -1c
.RI "#define \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP   0x00005555u"
.br
.ti -1c
.RI "#define \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP   0x00000000u"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IWDG_KEY_ENABLE   0x0000CCCCu"
IWDG Peripheral Enable 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 159 行定义\&.
.SS "#define IWDG_KEY_RELOAD   0x0000AAAAu"

.PP
IWDG Key Register BitMask IWDG Reload Counter Enable 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 158 行定义\&.
.SS "#define IWDG_KEY_WRITE_ACCESS_DISABLE   0x00000000u"
IWDG KR Write Access Disable 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 161 行定义\&.
.SS "#define IWDG_KEY_WRITE_ACCESS_ENABLE   0x00005555u"
IWDG KR Write Access Enable 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 160 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
