.TH "IWDG_Prescaler" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIWDG_PRESCALER_4\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_8\fP   IWDG_PR_PR_0"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_16\fP   IWDG_PR_PR_1"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_32\fP   (IWDG_PR_PR_1 | IWDG_PR_PR_0)"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_64\fP   IWDG_PR_PR_2"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_128\fP   (IWDG_PR_PR_2 | IWDG_PR_PR_0)"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_256\fP   (IWDG_PR_PR_2 | IWDG_PR_PR_1)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IWDG_PRESCALER_128   (IWDG_PR_PR_2 | IWDG_PR_PR_0)"
IWDG prescaler set to 128 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 86 行定义\&.
.SS "#define IWDG_PRESCALER_16   IWDG_PR_PR_1"
IWDG prescaler set to 16 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 83 行定义\&.
.SS "#define IWDG_PRESCALER_256   (IWDG_PR_PR_2 | IWDG_PR_PR_1)"
IWDG prescaler set to 256 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 87 行定义\&.
.SS "#define IWDG_PRESCALER_32   (IWDG_PR_PR_1 | IWDG_PR_PR_0)"
IWDG prescaler set to 32 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 84 行定义\&.
.SS "#define IWDG_PRESCALER_4   0x00000000u"
IWDG prescaler set to 4 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 81 行定义\&.
.SS "#define IWDG_PRESCALER_64   IWDG_PR_PR_2"
IWDG prescaler set to 64 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 85 行定义\&.
.SS "#define IWDG_PRESCALER_8   IWDG_PR_PR_0"
IWDG prescaler set to 8 
.br
 
.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 82 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
