.TH "IWDG_Exported_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_Exported_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_IWDG_START\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_ENABLE\fP)"
.br
.RI "Enable the IWDG peripheral\&. "
.ti -1c
.RI "#define \fB__HAL_IWDG_RELOAD_COUNTER\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_RELOAD\fP)"
.br
.RI "Reload IWDG counter with value defined in the reload register (write access to IWDG_PR and IWDG_RLR registers disabled)\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_IWDG_RELOAD_COUNTER(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_RELOAD\fP)"

.PP
Reload IWDG counter with value defined in the reload register (write access to IWDG_PR and IWDG_RLR registers disabled)\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>HANDLE</strong>\fP IWDG handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 117 行定义\&.
.SS "#define __HAL_IWDG_START(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_ENABLE\fP)"

.PP
Enable the IWDG peripheral\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>HANDLE</strong>\fP IWDG handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 109 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
