.TH "IWDG_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIWDG_ENABLE_WRITE_ACCESS\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP)"
.br
.RI "Enable write access to IWDG_PR and IWDG_RLR registers\&. "
.ti -1c
.RI "#define \fBIWDG_DISABLE_WRITE_ACCESS\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP)"
.br
.RI "Disable write access to IWDG_PR and IWDG_RLR registers\&. "
.ti -1c
.RI "#define \fBIS_IWDG_PRESCALER\fP(__PRESCALER__)"
.br
.RI "Check IWDG prescaler value\&. "
.ti -1c
.RI "#define \fBIS_IWDG_RELOAD\fP(__RELOAD__)   ((__RELOAD__) <= IWDG_RLR_RL)"
.br
.RI "Check IWDG reload value\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_IWDG_PRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                               (((__PRESCALER__) == IWDG_PRESCALER_4)  || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_8)  || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_16) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_32) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_64) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_128)|| \
                                               ((__PRESCALER__) == IWDG_PRESCALER_256))
.fi
.PP
Check IWDG prescaler value\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>PRESCALER</strong>\fP IWDG prescaler value 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 191 行定义\&.
.SS "#define IS_IWDG_RELOAD(__RELOAD__)   ((__RELOAD__) <= IWDG_RLR_RL)"

.PP
Check IWDG reload value\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>RELOAD</strong>\fP IWDG reload value 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 204 行定义\&.
.SS "#define IWDG_DISABLE_WRITE_ACCESS(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP)"

.PP
Disable write access to IWDG_PR and IWDG_RLR registers\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>HANDLE</strong>\fP IWDG handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 184 行定义\&.
.SS "#define IWDG_ENABLE_WRITE_ACCESS(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP)"

.PP
Enable write access to IWDG_PR and IWDG_RLR registers\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>HANDLE</strong>\fP IWDG handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_iwdg\&.h 第 177 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
