.TH "LL_FSMC_Aliased_Defines" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LL_FSMC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFSMC_NORSRAM_TYPEDEF\fP   FSMC_NORSRAM_TypeDef"
.br
.ti -1c
.RI "#define \fBFSMC_NORSRAM_EXTENDED_TYPEDEF\fP   FSMC_NORSRAM_EXTENDED_TypeDef"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define FSMC_NORSRAM_EXTENDED_TYPEDEF   FSMC_NORSRAM_EXTENDED_TypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 518 行定义\&.
.SS "#define FSMC_NORSRAM_TYPEDEF   FSMC_NORSRAM_TypeDef"

.PP
在文件 stm32_hal_legacy\&.h 第 517 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
