.TH "LL_UTILS_ClkInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LL_UTILS_ClkInitTypeDef \- UTILS System, AHB and APB buses clock configuration structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_ll_utils\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBAHBCLKDivider\fP"
.br
.ti -1c
.RI "uint32_t \fBAPB1CLKDivider\fP"
.br
.ti -1c
.RI "uint32_t \fBAPB2CLKDivider\fP"
.br
.in -1c
.SH "详细描述"
.PP 
UTILS System, AHB and APB buses clock configuration structure definition 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 120 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AHBCLKDivider"
The AHB clock (HCLK) divider\&. This clock is derived from the system clock (SYSCLK)\&. This parameter can be a value of \fBRCC_LL_EC_SYSCLK_DIV\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_SetAHBPrescaler()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 122 行定义\&.
.SS "uint32_t APB1CLKDivider"
The APB1 clock (PCLK1) divider\&. This clock is derived from the AHB clock (HCLK)\&. This parameter can be a value of \fBRCC_LL_EC_APB1_DIV\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_SetAPB1Prescaler()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 128 行定义\&.
.SS "uint32_t APB2CLKDivider"
The APB2 clock (PCLK2) divider\&. This clock is derived from the AHB clock (HCLK)\&. This parameter can be a value of \fBRCC_LL_EC_APB2_DIV\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_SetAPB2Prescaler()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 134 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
