.TH "LL_UTILS_PLLInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LL_UTILS_PLLInitTypeDef \- UTILS PLL structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_ll_utils\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBPLLM\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLN\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLP\fP"
.br
.in -1c
.SH "详细描述"
.PP 
UTILS PLL structure definition 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 95 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t PLLM"
Division factor for PLL VCO input clock\&. This parameter can be a value of \fBRCC_LL_EC_PLLM_DIV\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_PLL_ConfigDomain_SYS()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 97 行定义\&.
.SS "uint32_t PLLN"
Multiplication factor for PLL VCO output clock\&. This parameter must be a number between Min_Data = \fBRCC_PLLN_MIN_VALUE\fP and Max_Data = \fBRCC_PLLN_MIN_VALUE\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_PLL_ConfigDomain_SYS()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 103 行定义\&.
.SS "uint32_t PLLP"
Division for the main system clock\&. This parameter can be a value of \fBRCC_LL_EC_PLLP_DIV\fP
.PP
This feature can be modified afterwards using unitary function \fBLL_RCC_PLL_ConfigDomain_SYS()\fP\&. 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 110 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
