.TH "PWR_SLEEP_mode_entry" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_SLEEP_mode_entry
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFI\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFE\fP   ((uint8_t)0x02)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_SLEEPENTRY_WFE   ((uint8_t)0x02)"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 118 行定义\&.
.SS "#define PWR_SLEEPENTRY_WFI   ((uint8_t)0x01)"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 117 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
