.TH "PWR_PVD_EXTI_Line" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_PVD_EXTI_Line
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_EXTI_LINE_PVD\fP   ((uint32_t)EXTI_IMR_MR16)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_EXTI_LINE_PVD   ((uint32_t)EXTI_IMR_MR16)"
External interrupt line 16 Connected to the PVD EXTI Line 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 337 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
