.TH "PWR_Regulator_state_in_STOP_mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Regulator_state_in_STOP_mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_MAINREGULATOR_ON\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBPWR_LOWPOWERREGULATOR_ON\fP   PWR_CR_LPDS"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_LOWPOWERREGULATOR_ON   PWR_CR_LPDS"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 109 行定义\&.
.SS "#define PWR_MAINREGULATOR_ON   0x00000000U"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 108 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
