.TH "PWR_CSR_register_alias" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_CSR_register_alias
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBEWUP_BIT_NUMBER\fP   PWR_CSR_EWUP_Pos"
.br
.ti -1c
.RI "#define \fBCSR_EWUP_BB\fP   (PERIPH_BB_BASE + (\fBPWR_CSR_OFFSET_BB\fP * 32U) + (\fBEWUP_BIT_NUMBER\fP * 4U))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CSR_EWUP_BB   (PERIPH_BB_BASE + (\fBPWR_CSR_OFFSET_BB\fP * 32U) + (\fBEWUP_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 380 行定义\&.
.SS "#define EWUP_BIT_NUMBER   PWR_CSR_EWUP_Pos"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 379 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
