.TH "PWR_CR_register_alias" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_CR_register_alias
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDBP_BIT_NUMBER\fP   PWR_CR_DBP_Pos"
.br
.ti -1c
.RI "#define \fBCR_DBP_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBDBP_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBPVDE_BIT_NUMBER\fP   PWR_CR_PVDE_Pos"
.br
.ti -1c
.RI "#define \fBCR_PVDE_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBPVDE_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBVOS_BIT_NUMBER\fP   PWR_CR_VOS_Pos"
.br
.ti -1c
.RI "#define \fBCR_VOS_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBVOS_BIT_NUMBER\fP * 4U))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CR_DBP_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBDBP_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 361 行定义\&.
.SS "#define CR_PVDE_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBPVDE_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 365 行定义\&.
.SS "#define CR_VOS_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBVOS_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 369 行定义\&.
.SS "#define DBP_BIT_NUMBER   PWR_CR_DBP_Pos"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 360 行定义\&.
.SS "#define PVDE_BIT_NUMBER   PWR_CR_PVDE_Pos"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 364 行定义\&.
.SS "#define VOS_BIT_NUMBER   PWR_CR_VOS_Pos"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 368 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
