.TH "PWR_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_PWR_ConfigPVD\fP (\fBPWR_PVDTypeDef\fP *sConfigPVD)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnablePVD\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisablePVD\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableWakeUpPin\fP (uint32_t WakeUpPinx)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableWakeUpPin\fP (uint32_t WakeUpPinx)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTOPMode\fP (uint32_t Regulator, uint8_t STOPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSLEEPMode\fP (uint32_t Regulator, uint8_t SLEEPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTANDBYMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_PVD_IRQHandler\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_PVDCallback\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSEVOnPend\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSEVOnPend\fP (void)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_PWR_ConfigPVD (\fBPWR_PVDTypeDef\fP * sConfigPVD)"

.SS "void HAL_PWR_DisablePVD (void)"

.SS "void HAL_PWR_DisableSEVOnPend (void)"

.SS "void HAL_PWR_DisableSleepOnExit (void)"

.SS "void HAL_PWR_DisableWakeUpPin (uint32_t WakeUpPinx)"

.SS "void HAL_PWR_EnablePVD (void)"

.SS "void HAL_PWR_EnableSEVOnPend (void)"

.SS "void HAL_PWR_EnableSleepOnExit (void)"

.SS "void HAL_PWR_EnableWakeUpPin (uint32_t WakeUpPinx)"

.SS "void HAL_PWR_EnterSLEEPMode (uint32_t Regulator, uint8_t SLEEPEntry)"

.SS "void HAL_PWR_EnterSTANDBYMode (void)"

.SS "void HAL_PWR_EnterSTOPMode (uint32_t Regulator, uint8_t STOPEntry)"

.SS "void HAL_PWR_PVD_IRQHandler (void)"

.SS "void HAL_PWR_PVDCallback (void)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
