.TH "PWR_PVD_Mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_PVD_Mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_PVD_MODE_NORMAL\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_IT_RISING\fP   0x00010001U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_IT_FALLING\fP   0x00010002U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_IT_RISING_FALLING\fP   0x00010003U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_EVENT_RISING\fP   0x00020001U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_EVENT_FALLING\fP   0x00020002U"
.br
.ti -1c
.RI "#define \fBPWR_PVD_MODE_EVENT_RISING_FALLING\fP   0x00020003U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_PVD_MODE_EVENT_FALLING   0x00020002U"
Event Mode with Falling edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 98 行定义\&.
.SS "#define PWR_PVD_MODE_EVENT_RISING   0x00020001U"
Event Mode with Rising edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 97 行定义\&.
.SS "#define PWR_PVD_MODE_EVENT_RISING_FALLING   0x00020003U"
Event Mode with Rising/Falling edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 99 行定义\&.
.SS "#define PWR_PVD_MODE_IT_FALLING   0x00010002U"
External Interrupt Mode with Falling edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 95 行定义\&.
.SS "#define PWR_PVD_MODE_IT_RISING   0x00010001U"
External Interrupt Mode with Rising edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 94 行定义\&.
.SS "#define PWR_PVD_MODE_IT_RISING_FALLING   0x00010003U"
External Interrupt Mode with Rising/Falling edge trigger detection 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 96 行定义\&.
.SS "#define PWR_PVD_MODE_NORMAL   0x00000000U"
basic mode is used 
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 93 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
