.TH "PWR_PVD_detection_level" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_PVD_detection_level
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_0\fP   PWR_CR_PLS_LEV0"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_1\fP   PWR_CR_PLS_LEV1"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_2\fP   PWR_CR_PLS_LEV2"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_3\fP   PWR_CR_PLS_LEV3"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_4\fP   PWR_CR_PLS_LEV4"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_5\fP   PWR_CR_PLS_LEV5"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_6\fP   PWR_CR_PLS_LEV6"
.br
.ti -1c
.RI "#define \fBPWR_PVDLEVEL_7\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_PVDLEVEL_0   PWR_CR_PLS_LEV0"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 78 行定义\&.
.SS "#define PWR_PVDLEVEL_1   PWR_CR_PLS_LEV1"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 79 行定义\&.
.SS "#define PWR_PVDLEVEL_2   PWR_CR_PLS_LEV2"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 80 行定义\&.
.SS "#define PWR_PVDLEVEL_3   PWR_CR_PLS_LEV3"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 81 行定义\&.
.SS "#define PWR_PVDLEVEL_4   PWR_CR_PLS_LEV4"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 82 行定义\&.
.SS "#define PWR_PVDLEVEL_5   PWR_CR_PLS_LEV5"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 83 行定义\&.
.SS "#define PWR_PVDLEVEL_6   PWR_CR_PLS_LEV6"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 84 行定义\&.
.SS "#define PWR_PVDLEVEL_7"
\fB值:\fP
.PP
.nf
                                                          PWR_CR_PLS_LEV7/* External input analog voltage 
                                                          (Compare internally to VREFINT) */
.fi
.PP
在文件 stm32f4xx_hal_pwr\&.h 第 85 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
