.TH "PWR_Flag" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Flag
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_FLAG_WU\fP   PWR_CSR_WUF"
.br
.ti -1c
.RI "#define \fBPWR_FLAG_SB\fP   PWR_CSR_SBF"
.br
.ti -1c
.RI "#define \fBPWR_FLAG_PVDO\fP   PWR_CSR_PVDO"
.br
.ti -1c
.RI "#define \fBPWR_FLAG_BRR\fP   PWR_CSR_BRR"
.br
.ti -1c
.RI "#define \fBPWR_FLAG_VOSRDY\fP   PWR_CSR_VOSRDY"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_FLAG_BRR   PWR_CSR_BRR"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 138 行定义\&.
.SS "#define PWR_FLAG_PVDO   PWR_CSR_PVDO"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 137 行定义\&.
.SS "#define PWR_FLAG_SB   PWR_CSR_SBF"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 136 行定义\&.
.SS "#define PWR_FLAG_VOSRDY   PWR_CSR_VOSRDY"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 139 行定义\&.
.SS "#define PWR_FLAG_WU   PWR_CSR_WUF"

.PP
在文件 stm32f4xx_hal_pwr\&.h 第 135 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
