.TH "PWREx_Regulator_Voltage_Scale" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Regulator_Voltage_Scale
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBPWR_REGULATOR_VOLTAGE_SCALE1\fP"
.br
.ti -1c
.RI "#define \fBPWR_REGULATOR_VOLTAGE_SCALE2\fP"
.br
.ti -1c
.RI "#define \fBPWR_REGULATOR_VOLTAGE_SCALE3\fP   PWR_CR_VOS_0           /* Scale 3 mode: the maximum value of fHCLK is 120 MHz\&. */"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define PWR_REGULATOR_VOLTAGE_SCALE1"
\fB值:\fP
.PP
.nf
                                                                       PWR_CR_VOS             /* Scale 1 mode(default value at reset): the maximum value of fHCLK is 168 MHz\&. It can be extended to
                                                                       180 MHz by activating the over-drive mode\&. */
.fi
.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 75 行定义\&.
.SS "#define PWR_REGULATOR_VOLTAGE_SCALE2"
\fB值:\fP
.PP
.nf
                                                                       PWR_CR_VOS_1           /* Scale 2 mode: the maximum value of fHCLK is 144 MHz\&. It can be extended to
                                                                       168 MHz by activating the over-drive mode\&. */
.fi
.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 76 行定义\&.
.SS "#define PWR_REGULATOR_VOLTAGE_SCALE3   PWR_CR_VOS_0           /* Scale 3 mode: the maximum value of fHCLK is 120 MHz\&. */"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 77 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
