.TH "PWREx_IS_PWR_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_IS_PWR_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_PWR_VOLTAGE_SCALING_RANGE\fP(VOLTAGE)"
.br
.ti -1c
.RI "#define \fBIS_PWR_WAKEUP_PIN\fP(PIN)   ((PIN) == \fBPWR_WAKEUP_PIN1\fP)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_PWR_VOLTAGE_SCALING_RANGE(VOLTAGE)"
\fB值:\fP
.PP
.nf
                                               (((VOLTAGE) == PWR_REGULATOR_VOLTAGE_SCALE1) || \
                                               ((VOLTAGE) == PWR_REGULATOR_VOLTAGE_SCALE2) || \
                                               ((VOLTAGE) == PWR_REGULATOR_VOLTAGE_SCALE3))
.fi
.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 305 行定义\&.
.SS "#define IS_PWR_WAKEUP_PIN(PIN)   ((PIN) == \fBPWR_WAKEUP_PIN1\fP)"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 318 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
