.TH "PWREx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_PWREx_EnableFlashPowerDown\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_DisableFlashPowerDown\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_EnableBkUpReg\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_DisableBkUpReg\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_PWREx_GetVoltageRange\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_ControlVoltageScaling\fP (uint32_t VoltageScaling)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_ControlVoltageScaling (uint32_t VoltageScaling)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_DisableBkUpReg (void)"

.SS "void HAL_PWREx_DisableFlashPowerDown (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_EnableBkUpReg (void)"

.SS "void HAL_PWREx_EnableFlashPowerDown (void)"

.SS "uint32_t HAL_PWREx_GetVoltageRange (void)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
