.TH "PWREx_register_alias_address" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_register_alias_address
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFPDS_BIT_NUMBER\fP   PWR_CR_FPDS_Pos"
.br
.ti -1c
.RI "#define \fBCR_FPDS_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBFPDS_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBODEN_BIT_NUMBER\fP   PWR_CR_ODEN_Pos"
.br
.ti -1c
.RI "#define \fBCR_ODEN_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBODEN_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBODSWEN_BIT_NUMBER\fP   PWR_CR_ODSWEN_Pos"
.br
.ti -1c
.RI "#define \fBCR_ODSWEN_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBODSWEN_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBMRLVDS_BIT_NUMBER\fP   PWR_CR_MRLVDS_Pos"
.br
.ti -1c
.RI "#define \fBCR_MRLVDS_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBMRLVDS_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBLPLVDS_BIT_NUMBER\fP   PWR_CR_LPLVDS_Pos"
.br
.ti -1c
.RI "#define \fBCR_LPLVDS_BB\fP   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBLPLVDS_BIT_NUMBER\fP * 4U))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define CR_FPDS_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBFPDS_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 249 行定义\&.
.SS "#define CR_LPLVDS_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBLPLVDS_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 265 行定义\&.
.SS "#define CR_MRLVDS_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBMRLVDS_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 261 行定义\&.
.SS "#define CR_ODEN_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBODEN_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 253 行定义\&.
.SS "#define CR_ODSWEN_BB   (uint32_t)(PERIPH_BB_BASE + (\fBPWR_CR_OFFSET_BB\fP * 32U) + (\fBODSWEN_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 257 行定义\&.
.SS "#define FPDS_BIT_NUMBER   PWR_CR_FPDS_Pos"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 248 行定义\&.
.SS "#define LPLVDS_BIT_NUMBER   PWR_CR_LPLVDS_Pos"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 264 行定义\&.
.SS "#define MRLVDS_BIT_NUMBER   PWR_CR_MRLVDS_Pos"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 260 行定义\&.
.SS "#define ODEN_BIT_NUMBER   PWR_CR_ODEN_Pos"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 252 行定义\&.
.SS "#define ODSWEN_BIT_NUMBER   PWR_CR_ODSWEN_Pos"

.PP
在文件 stm32f4xx_hal_pwr_ex\&.h 第 256 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
