.TH "RCC_AHB_Clock_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_AHB_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV1\fP   RCC_CFGR_HPRE_DIV1"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV2\fP   RCC_CFGR_HPRE_DIV2"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV4\fP   RCC_CFGR_HPRE_DIV4"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV8\fP   RCC_CFGR_HPRE_DIV8"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV16\fP   RCC_CFGR_HPRE_DIV16"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV64\fP   RCC_CFGR_HPRE_DIV64"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV128\fP   RCC_CFGR_HPRE_DIV128"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV256\fP   RCC_CFGR_HPRE_DIV256"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV512\fP   RCC_CFGR_HPRE_DIV512"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_SYSCLK_DIV1   RCC_CFGR_HPRE_DIV1"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 228 行定义\&.
.SS "#define RCC_SYSCLK_DIV128   RCC_CFGR_HPRE_DIV128"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 234 行定义\&.
.SS "#define RCC_SYSCLK_DIV16   RCC_CFGR_HPRE_DIV16"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 232 行定义\&.
.SS "#define RCC_SYSCLK_DIV2   RCC_CFGR_HPRE_DIV2"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 229 行定义\&.
.SS "#define RCC_SYSCLK_DIV256   RCC_CFGR_HPRE_DIV256"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 235 行定义\&.
.SS "#define RCC_SYSCLK_DIV4   RCC_CFGR_HPRE_DIV4"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 230 行定义\&.
.SS "#define RCC_SYSCLK_DIV512   RCC_CFGR_HPRE_DIV512"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 236 行定义\&.
.SS "#define RCC_SYSCLK_DIV64   RCC_CFGR_HPRE_DIV64"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 233 行定义\&.
.SS "#define RCC_SYSCLK_DIV8   RCC_CFGR_HPRE_DIV8"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 231 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
