.TH "RCC_APB1_APB2_Clock_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB1_APB2_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_HCLK_DIV1\fP   RCC_CFGR_PPRE1_DIV1"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV2\fP   RCC_CFGR_PPRE1_DIV2"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV4\fP   RCC_CFGR_PPRE1_DIV4"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV8\fP   RCC_CFGR_PPRE1_DIV8"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV16\fP   RCC_CFGR_PPRE1_DIV16"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_HCLK_DIV1   RCC_CFGR_PPRE1_DIV1"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 244 行定义\&.
.SS "#define RCC_HCLK_DIV16   RCC_CFGR_PPRE1_DIV16"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 248 行定义\&.
.SS "#define RCC_HCLK_DIV2   RCC_CFGR_PPRE1_DIV2"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 245 行定义\&.
.SS "#define RCC_HCLK_DIV4   RCC_CFGR_PPRE1_DIV4"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 246 行定义\&.
.SS "#define RCC_HCLK_DIV8   RCC_CFGR_PPRE1_DIV8"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 247 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
