.TH "RCC_PLLP_Clock_Divider" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLLP_Clock_Divider
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLLP_DIV2\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRCC_PLLP_DIV4\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRCC_PLLP_DIV6\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBRCC_PLLP_DIV8\fP   0x00000008U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_PLLP_DIV2   0x00000002U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 171 行定义\&.
.SS "#define RCC_PLLP_DIV4   0x00000004U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 172 行定义\&.
.SS "#define RCC_PLLP_DIV6   0x00000006U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 173 行定义\&.
.SS "#define RCC_PLLP_DIV8   0x00000008U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 174 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
