.TH "RCC_PLL_Clock_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLL_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLLSOURCE_HSI\fP   RCC_PLLCFGR_PLLSRC_HSI"
.br
.ti -1c
.RI "#define \fBRCC_PLLSOURCE_HSE\fP   RCC_PLLCFGR_PLLSRC_HSE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_PLLSOURCE_HSE   RCC_PLLCFGR_PLLSRC_HSE"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 183 行定义\&.
.SS "#define RCC_PLLSOURCE_HSI   RCC_PLLCFGR_PLLSRC_HSI"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 182 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
