.TH "RCC_PLLInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLLInitTypeDef \- RCC PLL configuration structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rcc_ex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBPLLState\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLSource\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLM\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLN\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLP\fP"
.br
.ti -1c
.RI "uint32_t \fBPLLQ\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RCC PLL configuration structure definition 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t PLLM"
PLLM: Division factor for PLL VCO input clock\&. This parameter must be a number between Min_Data = 0 and Max_Data = 63 
.br
 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 55 行定义\&.
.SS "uint32_t PLLN"
PLLN: Multiplication factor for PLL VCO output clock\&. This parameter must be a number between Min_Data = 50 and Max_Data = 432 except for STM32F411xE devices where the Min_Data = 192 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 58 行定义\&.
.SS "uint32_t PLLP"
PLLP: Division factor for main system clock (SYSCLK)\&. This parameter must be a value of \fBPLLP Clock Divider\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 62 行定义\&.
.SS "uint32_t PLLQ"
PLLQ: Division factor for OTG FS, SDIO and RNG clocks\&. This parameter must be a number between Min_Data = 2 and Max_Data = 15 
.br
 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 65 行定义\&.
.SS "uint32_t PLLSource"
RCC_PLLSource: PLL entry clock source\&. This parameter must be a value of \fBPLL Clock Source\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 52 行定义\&.
.SS "uint32_t PLLState"
The new state of the PLL\&. This parameter can be a value of \fBPLL Config\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 49 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
