.TH "RCC_Exported_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Exported_Macros
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBAHB1 Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the AHB1 peripheral clock\&. "
.ti -1c
.RI "\fBAHB1 Peripheral Clock Enable Disable Status\fP"
.br
.RI "Get the enable or disable status of the AHB1 peripheral clock\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the Low Speed APB (APB1) peripheral clock\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Enable Disable Status\fP"
.br
.RI "Get the enable or disable status of the APB1 peripheral clock\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the High Speed APB (APB2) peripheral clock\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Enable Disable Status\fP"
.br
.RI "Get the enable or disable status of the APB2 peripheral clock\&. "
.ti -1c
.RI "\fBAHB1 Force Release Reset\fP"
.br
.RI "Force or release AHB1 peripheral reset\&. "
.ti -1c
.RI "\fBAPB1 Force Release Reset\fP"
.br
.RI "Force or release APB1 peripheral reset\&. "
.ti -1c
.RI "\fBAPB2 Force Release Reset\fP"
.br
.RI "Force or release APB2 peripheral reset\&. "
.ti -1c
.RI "\fBAHB1 Peripheral Low Power Enable Disable\fP"
.br
.RI "Enable or disable the AHB1 peripheral clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Low Power Enable Disable\fP"
.br
.RI "Enable or disable the APB1 peripheral clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Low Power Enable Disable\fP"
.br
.RI "Enable or disable the APB2 peripheral clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBHSI Configuration\fP"
.br
.ti -1c
.RI "\fBLSI Configuration\fP"
.br
.ti -1c
.RI "\fBHSE Configuration\fP"
.br
.ti -1c
.RI "\fBLSE Configuration\fP"
.br
.ti -1c
.RI "\fBRTC Clock Configuration\fP"
.br
.ti -1c
.RI "\fBPLL Configuration\fP"
.br
.ti -1c
.RI "\fBGet Clock source\fP"
.br
.ti -1c
.RI "\fBRCC Extended MCOx Clock Config\fP"
.br
.ti -1c
.RI "\fBFlags Interrupts Management\fP"
.br
.RI "macros to manage the specified RCC Flags and interrupts\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
