.TH "RCC_RTC_Clock_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_RTC_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_NO_CLK\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_LSE\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_LSI\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIVX\fP   0x00000300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV2\fP   0x00020300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV3\fP   0x00030300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV4\fP   0x00040300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV5\fP   0x00050300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV6\fP   0x00060300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV7\fP   0x00070300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV8\fP   0x00080300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV9\fP   0x00090300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV10\fP   0x000A0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV11\fP   0x000B0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV12\fP   0x000C0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV13\fP   0x000D0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV14\fP   0x000E0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV15\fP   0x000F0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV16\fP   0x00100300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV17\fP   0x00110300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV18\fP   0x00120300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV19\fP   0x00130300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV20\fP   0x00140300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV21\fP   0x00150300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV22\fP   0x00160300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV23\fP   0x00170300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV24\fP   0x00180300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV25\fP   0x00190300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV26\fP   0x001A0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV27\fP   0x001B0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV28\fP   0x001C0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV29\fP   0x001D0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV30\fP   0x001E0300U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV31\fP   0x001F0300U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV10   0x000A0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 268 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV11   0x000B0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 269 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV12   0x000C0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 270 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV13   0x000D0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 271 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV14   0x000E0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 272 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV15   0x000F0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 273 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV16   0x00100300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 274 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV17   0x00110300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 275 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV18   0x00120300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 276 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV19   0x00130300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 277 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV2   0x00020300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 260 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV20   0x00140300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 278 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV21   0x00150300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 279 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV22   0x00160300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 280 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV23   0x00170300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 281 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV24   0x00180300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 282 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV25   0x00190300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 283 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV26   0x001A0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 284 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV27   0x001B0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 285 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV28   0x001C0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 286 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV29   0x001D0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 287 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV3   0x00030300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 261 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV30   0x001E0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 288 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV31   0x001F0300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 289 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV4   0x00040300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 262 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV5   0x00050300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 263 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV6   0x00060300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 264 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV7   0x00070300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 265 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV8   0x00080300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 266 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV9   0x00090300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 267 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_HSE_DIVX   0x00000300U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 259 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_LSE   0x00000100U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 257 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_LSI   0x00000200U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 258 行定义\&.
.SS "#define RCC_RTCCLKSOURCE_NO_CLK   0x00000000U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 256 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
