.TH "RCC_LSI_Configuration" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_LSI_Configuration
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_LSI_ENABLE\fP()   (*(__IO uint32_t *) \fBRCC_CSR_LSION_BB\fP = ENABLE)"
.br
.RI "Macros to enable or disable the Internal Low Speed oscillator (LSI)\&. "
.ti -1c
.RI "#define \fB__HAL_RCC_LSI_DISABLE\fP()   (*(__IO uint32_t *) \fBRCC_CSR_LSION_BB\fP = DISABLE)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RCC_LSI_DISABLE()   (*(__IO uint32_t *) \fBRCC_CSR_LSION_BB\fP = DISABLE)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 866 行定义\&.
.SS "#define __HAL_RCC_LSI_ENABLE()   (*(__IO uint32_t *) \fBRCC_CSR_LSION_BB\fP = ENABLE)"

.PP
Macros to enable or disable the Internal Low Speed oscillator (LSI)\&. 
.PP
\fB注解\fP
.RS 4
After enabling the LSI, the application software should wait on LSIRDY flag to be set indicating that LSI clock is stable and can be used to clock the IWDG and/or the RTC\&. 
.PP
LSI can not be disabled if the IWDG is running\&. 
.PP
When the LSI is stopped, LSIRDY flag goes low after 6 LSI oscillator clock cycles\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 865 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
