.TH "RCC_APB1_LowPower_Enable_Disable" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB1_LowPower_Enable_Disable \- Enable or disable the APB1 peripheral clock during Low Power (Sleep) mode\&.  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_TIM5_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_TIM5LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_WWDG_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_WWDGLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI2_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_SPI2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART2_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_USART2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C1_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_I2C1LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C2_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_I2C2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_PWR_CLK_SLEEP_ENABLE\fP()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_PWRLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM5_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_TIM5LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_WWDG_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_WWDGLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI2_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_SPI2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART2_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_USART2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C1_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_I2C1LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C2_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_I2C2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_PWR_CLK_SLEEP_DISABLE\fP()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_PWRLPEN))"
.br
.in -1c
.SH "详细描述"
.PP 
Enable or disable the APB1 peripheral clock during Low Power (Sleep) mode\&. 


.PP
\fB注解\fP
.RS 4
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption\&. 
.PP
After wake-up from SLEEP mode, the peripheral clock is enabled again\&. 
.PP
By default, all peripheral clocks are enabled during SLEEP mode\&. 
.RE
.PP

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RCC_I2C1_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_I2C1LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 782 行定义\&.
.SS "#define __HAL_RCC_I2C1_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_I2C1LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 774 行定义\&.
.SS "#define __HAL_RCC_I2C2_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_I2C2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 783 行定义\&.
.SS "#define __HAL_RCC_I2C2_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_I2C2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 775 行定义\&.
.SS "#define __HAL_RCC_PWR_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_PWRLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 784 行定义\&.
.SS "#define __HAL_RCC_PWR_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_PWRLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 776 行定义\&.
.SS "#define __HAL_RCC_SPI2_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_SPI2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 780 行定义\&.
.SS "#define __HAL_RCC_SPI2_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_SPI2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 772 行定义\&.
.SS "#define __HAL_RCC_TIM5_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_TIM5LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 778 行定义\&.
.SS "#define __HAL_RCC_TIM5_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_TIM5LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 770 行定义\&.
.SS "#define __HAL_RCC_USART2_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_USART2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 781 行定义\&.
.SS "#define __HAL_RCC_USART2_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_USART2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 773 行定义\&.
.SS "#define __HAL_RCC_WWDG_CLK_SLEEP_DISABLE()   (RCC\->APB1LPENR &= ~(RCC_APB1LPENR_WWDGLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 779 行定义\&.
.SS "#define __HAL_RCC_WWDG_CLK_SLEEP_ENABLE()   (RCC\->APB1LPENR |= (RCC_APB1LPENR_WWDGLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 771 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
