.TH "RCC_Get_Clock_source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Get_Clock_source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCLK_CONFIG\fP(__RCC_SYSCLKSOURCE__)   MODIFY_REG(RCC\->CFGR, RCC_CFGR_SW, (__RCC_SYSCLKSOURCE__))"
.br
.RI "Macro to configure the system clock source\&. "
.ti -1c
.RI "#define \fB__HAL_RCC_GET_SYSCLK_SOURCE\fP()   (RCC\->CFGR & RCC_CFGR_SWS)"
.br
.RI "Macro to get the clock source used as system clock\&. "
.ti -1c
.RI "#define \fB__HAL_RCC_GET_PLL_OSCSOURCE\fP()   ((uint32_t)(RCC\->PLLCFGR & RCC_PLLCFGR_PLLSRC))"
.br
.RI "Macro to get the oscillator used as PLL clock source\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RCC_GET_PLL_OSCSOURCE()   ((uint32_t)(RCC\->PLLCFGR & RCC_PLLCFGR_PLLSRC))"

.PP
Macro to get the oscillator used as PLL clock source\&. 
.PP
\fB返回值\fP
.RS 4
\fIThe\fP oscillator used as PLL clock source\&. The returned value can be one of the following:
.IP "\(bu" 2
RCC_PLLSOURCE_HSI: HSI oscillator is used as PLL clock source\&.
.IP "\(bu" 2
RCC_PLLSOURCE_HSE: HSE oscillator is used as PLL clock source\&. 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1097 行定义\&.
.SS "#define __HAL_RCC_GET_SYSCLK_SOURCE()   (RCC\->CFGR & RCC_CFGR_SWS)"

.PP
Macro to get the clock source used as system clock\&. 
.PP
\fB返回值\fP
.RS 4
\fIThe\fP clock source used as system clock\&. The returned value can be one of the following:
.IP "\(bu" 2
RCC_SYSCLKSOURCE_STATUS_HSI: HSI used as system clock\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_STATUS_HSE: HSE used as system clock\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_STATUS_PLLCLK: PLL used as system clock\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_STATUS_PLLRCLK: PLLR used as system clock\&. This parameter is available only for STM32F446xx devices\&. 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1089 行定义\&.
.SS "#define __HAL_RCC_SYSCLK_CONFIG(__RCC_SYSCLKSOURCE__)   MODIFY_REG(RCC\->CFGR, RCC_CFGR_SW, (__RCC_SYSCLKSOURCE__))"

.PP
Macro to configure the system clock source\&. 
.PP
\fB参数\fP
.RS 4
\fI<strong>RCC_SYSCLKSOURCE</strong>\fP specifies the system clock source\&. This parameter can be one of the following values:
.IP "\(bu" 2
RCC_SYSCLKSOURCE_HSI: HSI oscillator is used as system clock source\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_HSE: HSE oscillator is used as system clock source\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_PLLCLK: PLL output is used as system clock source\&.
.IP "\(bu" 2
RCC_SYSCLKSOURCE_PLLRCLK: PLLR output is used as system clock source\&. This parameter is available only for STM32F446xx devices\&. 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1078 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
