.TH "RCC_Oscillator_Type" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Oscillator_Type
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_HSE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_HSI\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_LSE\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_LSI\fP   0x00000008U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RCC_OSCILLATORTYPE_HSE   0x00000001U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 110 行定义\&.
.SS "#define RCC_OSCILLATORTYPE_HSI   0x00000002U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 111 行定义\&.
.SS "#define RCC_OSCILLATORTYPE_LSE   0x00000004U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 112 行定义\&.
.SS "#define RCC_OSCILLATORTYPE_LSI   0x00000008U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 113 行定义\&.
.SS "#define RCC_OSCILLATORTYPE_NONE   0x00000000U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 109 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
