.TH "RCC_System_Clock_Source_Status" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_System_Clock_Source_Status
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_SYSCLKSOURCE_STATUS_HSI\fP   RCC_CFGR_SWS_HSI"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLKSOURCE_STATUS_HSE\fP   RCC_CFGR_SWS_HSE"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLKSOURCE_STATUS_PLLCLK\fP   RCC_CFGR_SWS_PLL"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLKSOURCE_STATUS_PLLRCLK\fP   ((uint32_t)(RCC_CFGR_SWS_0 | RCC_CFGR_SWS_1))"
.br
.in -1c
.SH "详细描述"
.PP 

.PP
\fB注解\fP
.RS 4
The RCC_SYSCLKSOURCE_STATUS_PLLRCLK parameter is available only for STM32F446xx devices\&. 
.RE
.PP

.SH "宏定义说明"
.PP 
.SS "#define RCC_SYSCLKSOURCE_STATUS_HSE   RCC_CFGR_SWS_HSE"
HSE used as system clock 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 218 行定义\&.
.SS "#define RCC_SYSCLKSOURCE_STATUS_HSI   RCC_CFGR_SWS_HSI"
HSI used as system clock 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 217 行定义\&.
.SS "#define RCC_SYSCLKSOURCE_STATUS_PLLCLK   RCC_CFGR_SWS_PLL"
PLL used as system clock 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 219 行定义\&.
.SS "#define RCC_SYSCLKSOURCE_STATUS_PLLRCLK   ((uint32_t)(RCC_CFGR_SWS_0 | RCC_CFGR_SWS_1))"
PLLR used as system clock 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 220 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
