.TH "RCC_ClkInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_ClkInitTypeDef \- RCC System, AHB and APB busses clock configuration structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rcc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBClockType\fP"
.br
.ti -1c
.RI "uint32_t \fBSYSCLKSource\fP"
.br
.ti -1c
.RI "uint32_t \fBAHBCLKDivider\fP"
.br
.ti -1c
.RI "uint32_t \fBAPB1CLKDivider\fP"
.br
.ti -1c
.RI "uint32_t \fBAPB2CLKDivider\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RCC System, AHB and APB busses clock configuration structure definition 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 77 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AHBCLKDivider"
The AHB clock (HCLK) divider\&. This clock is derived from the system clock (SYSCLK)\&. This parameter can be a value of \fBAHB Clock Source\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 85 行定义\&.
.SS "uint32_t APB1CLKDivider"
The APB1 clock (PCLK1) divider\&. This clock is derived from the AHB clock (HCLK)\&. This parameter can be a value of \fBAPB1/APB2 Clock Source\fP 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 88 行定义\&.
.SS "uint32_t APB2CLKDivider"
The APB2 clock (PCLK2) divider\&. This clock is derived from the AHB clock (HCLK)\&. This parameter can be a value of \fBAPB1/APB2 Clock Source\fP 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 91 行定义\&.
.SS "uint32_t ClockType"
The clock to be configured\&. This parameter can be a value of \fBSystem Clock Type\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 79 行定义\&.
.SS "uint32_t SYSCLKSource"
The clock source (SYSCLKS) used as system clock\&. This parameter can be a value of \fBSystem Clock Source\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 82 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
