.TH "RCC_OscInitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_OscInitTypeDef \- RCC Internal/External Oscillator (HSE, HSI, LSE and LSI) configuration structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rcc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBOscillatorType\fP"
.br
.ti -1c
.RI "uint32_t \fBHSEState\fP"
.br
.ti -1c
.RI "uint32_t \fBLSEState\fP"
.br
.ti -1c
.RI "uint32_t \fBHSIState\fP"
.br
.ti -1c
.RI "uint32_t \fBHSICalibrationValue\fP"
.br
.ti -1c
.RI "uint32_t \fBLSIState\fP"
.br
.ti -1c
.RI "\fBRCC_PLLInitTypeDef\fP \fBPLL\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RCC Internal/External Oscillator (HSE, HSI, LSE and LSI) configuration structure definition 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 51 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t HSEState"
The new state of the HSE\&. This parameter can be a value of \fBHSE Config\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 56 行定义\&.
.SS "uint32_t HSICalibrationValue"
The HSI calibration trimming value (default is RCC_HSICALIBRATION_DEFAULT)\&. This parameter must be a number between Min_Data = 0x00 and Max_Data = 0x1F 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 65 行定义\&.
.SS "uint32_t HSIState"
The new state of the HSI\&. This parameter can be a value of \fBHSI Config\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 62 行定义\&.
.SS "uint32_t LSEState"
The new state of the LSE\&. This parameter can be a value of \fBLSE Config\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 59 行定义\&.
.SS "uint32_t LSIState"
The new state of the LSI\&. This parameter can be a value of \fBLSI Config\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 68 行定义\&.
.SS "uint32_t OscillatorType"
The oscillators to be configured\&. This parameter can be a value of \fBOscillator Type\fP 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 53 行定义\&.
.SS "\fBRCC_PLLInitTypeDef\fP PLL"
PLL structure parameters 
.br
 
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 71 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
