.TH "RCC_AHB1_LowPower_Enable_Disable" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_AHB1_LowPower_Enable_Disable \- Enable or disable the AHB1 peripheral clock during Low Power (Sleep) mode\&.  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOALPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOBLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOCLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOH_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOHLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_DMA1_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_DMA1LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_DMA2_CLK_SLEEP_ENABLE\fP()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_DMA2LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOALPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOBLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOCLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOH_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOHLPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_DMA1_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_DMA1LPEN))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_DMA2_CLK_SLEEP_DISABLE\fP()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_DMA2LPEN))"
.br
.in -1c
.SH "详细描述"
.PP 
Enable or disable the AHB1 peripheral clock during Low Power (Sleep) mode\&. 


.PP
\fB注解\fP
.RS 4
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption\&. 
.PP
After wake-up from SLEEP mode, the peripheral clock is enabled again\&. 
.PP
By default, all peripheral clocks are enabled during SLEEP mode\&. 
.RE
.PP

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RCC_DMA1_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_DMA1LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 756 行定义\&.
.SS "#define __HAL_RCC_DMA1_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_DMA1LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 749 行定义\&.
.SS "#define __HAL_RCC_DMA2_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_DMA2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 757 行定义\&.
.SS "#define __HAL_RCC_DMA2_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_DMA2LPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 750 行定义\&.
.SS "#define __HAL_RCC_GPIOA_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOALPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 752 行定义\&.
.SS "#define __HAL_RCC_GPIOA_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOALPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 745 行定义\&.
.SS "#define __HAL_RCC_GPIOB_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOBLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 753 行定义\&.
.SS "#define __HAL_RCC_GPIOB_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOBLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 746 行定义\&.
.SS "#define __HAL_RCC_GPIOC_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOCLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 754 行定义\&.
.SS "#define __HAL_RCC_GPIOC_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOCLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 747 行定义\&.
.SS "#define __HAL_RCC_GPIOH_CLK_SLEEP_DISABLE()   (RCC\->AHB1LPENR &= ~(RCC_AHB1LPENR_GPIOHLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 755 行定义\&.
.SS "#define __HAL_RCC_GPIOH_CLK_SLEEP_ENABLE()   (RCC\->AHB1LPENR |= (RCC_AHB1LPENR_GPIOHLPEN))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 748 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
