.TH "RCC_LSE_Configuration" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_LSE_Configuration
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_LSE_CONFIG\fP(__STATE__)"
.br
.RI "Macro to configure the External Low Speed oscillator (LSE)\&. "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RCC_LSE_CONFIG(__STATE__)"
\fB值:\fP
.PP
.nf
                    do {                                       \
                      if((__STATE__) == RCC_LSE_ON)            \
                      {                                        \
                        SET_BIT(RCC->BDCR, RCC_BDCR_LSEON);    \
                      }                                        \
                      else if((__STATE__) == RCC_LSE_BYPASS)   \
                      {                                        \
                        SET_BIT(RCC->BDCR, RCC_BDCR_LSEBYP);   \
                        SET_BIT(RCC->BDCR, RCC_BDCR_LSEON);    \
                      }                                        \
                      else                                     \
                      {                                        \
                        CLEAR_BIT(RCC->BDCR, RCC_BDCR_LSEON);  \
                        CLEAR_BIT(RCC->BDCR, RCC_BDCR_LSEBYP); \
                      }                                        \
                    } while(0U)
.fi
.PP
Macro to configure the External Low Speed oscillator (LSE)\&. 
.PP
\fB注解\fP
.RS 4
Transition LSE Bypass to LSE On and LSE On to LSE Bypass are not supported by this macro\&. User should request a transition to LSE Off first and then LSE On or LSE Bypass\&. 
.PP
As the LSE is in the Backup domain and write access is denied to this domain after reset, you have to enable write access using \fBHAL_PWR_EnableBkUpAccess()\fP function before to configure the LSE (to be done once after reset)\&. 
.PP
After enabling the LSE (RCC_LSE_ON or RCC_LSE_BYPASS), the application software should wait on LSERDY flag to be set indicating that LSE clock is stable and can be used to clock the RTC\&. 
.RE
.PP
\fB参数\fP
.RS 4
\fI<strong>STATE</strong>\fP specifies the new state of the LSE\&. This parameter can be one of the following values: 
.PD 0

.IP "\(bu" 2
RCC_LSE_OFF: turn OFF the LSE oscillator, LSERDY flag goes low after 6 LSE oscillator clock cycles\&. 
.IP "\(bu" 2
RCC_LSE_ON: turn ON the LSE oscillator\&. 
.IP "\(bu" 2
RCC_LSE_BYPASS: LSE oscillator bypassed with external clock\&. 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 939 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
