.TH "RCC_BitAddress_AliasRegion" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_BitAddress_AliasRegion \- RCC registers bit address in the alias region  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_OFFSET\fP   (RCC_BASE \- PERIPH_BASE)"
.br
.ti -1c
.RI "#define \fBRCC_CR_OFFSET\fP   (\fBRCC_OFFSET\fP + 0x00U)"
.br
.ti -1c
.RI "#define \fBRCC_HSION_BIT_NUMBER\fP   0x00U"
.br
.ti -1c
.RI "#define \fBRCC_CR_HSION_BB\fP   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_HSION_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_CSSON_BIT_NUMBER\fP   0x13U"
.br
.ti -1c
.RI "#define \fBRCC_CR_CSSON_BB\fP   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_CSSON_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_PLLON_BIT_NUMBER\fP   0x18U"
.br
.ti -1c
.RI "#define \fBRCC_CR_PLLON_BB\fP   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_PLLON_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_BDCR_OFFSET\fP   (\fBRCC_OFFSET\fP + 0x70U)"
.br
.ti -1c
.RI "#define \fBRCC_RTCEN_BIT_NUMBER\fP   0x0FU"
.br
.ti -1c
.RI "#define \fBRCC_BDCR_RTCEN_BB\fP   (PERIPH_BB_BASE + (\fBRCC_BDCR_OFFSET\fP * 32U) + (\fBRCC_RTCEN_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_BDRST_BIT_NUMBER\fP   0x10U"
.br
.ti -1c
.RI "#define \fBRCC_BDCR_BDRST_BB\fP   (PERIPH_BB_BASE + (\fBRCC_BDCR_OFFSET\fP * 32U) + (\fBRCC_BDRST_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_CSR_OFFSET\fP   (\fBRCC_OFFSET\fP + 0x74U)"
.br
.ti -1c
.RI "#define \fBRCC_LSION_BIT_NUMBER\fP   0x00U"
.br
.ti -1c
.RI "#define \fBRCC_CSR_LSION_BB\fP   (PERIPH_BB_BASE + (\fBRCC_CSR_OFFSET\fP * 32U) + (\fBRCC_LSION_BIT_NUMBER\fP * 4U))"
.br
.ti -1c
.RI "#define \fBRCC_CR_BYTE2_ADDRESS\fP   0x40023802U"
.br
.ti -1c
.RI "#define \fBRCC_CIR_BYTE1_ADDRESS\fP   ((uint32_t)(RCC_BASE + 0x0CU + 0x01U))"
.br
.ti -1c
.RI "#define \fBRCC_CIR_BYTE2_ADDRESS\fP   ((uint32_t)(RCC_BASE + 0x0CU + 0x02U))"
.br
.ti -1c
.RI "#define \fBRCC_BDCR_BYTE0_ADDRESS\fP   (PERIPH_BASE + \fBRCC_BDCR_OFFSET\fP)"
.br
.ti -1c
.RI "#define \fBRCC_DBP_TIMEOUT_VALUE\fP   2U"
.br
.ti -1c
.RI "#define \fBRCC_LSE_TIMEOUT_VALUE\fP   \fBLSE_STARTUP_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fBHSE_TIMEOUT_VALUE\fP   \fBHSE_STARTUP_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fBHSI_TIMEOUT_VALUE\fP   2U  /* 2 ms */"
.br
.ti -1c
.RI "#define \fBLSI_TIMEOUT_VALUE\fP   2U  /* 2 ms */"
.br
.ti -1c
.RI "#define \fBCLOCKSWITCH_TIMEOUT_VALUE\fP   5000U /* 5 s */"
.br
.in -1c
.SH "详细描述"
.PP 
RCC registers bit address in the alias region 


.SH "宏定义说明"
.PP 
.SS "#define CLOCKSWITCH_TIMEOUT_VALUE   5000U /* 5 s */"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1342 行定义\&.
.SS "#define HSE_TIMEOUT_VALUE   \fBHSE_STARTUP_TIMEOUT\fP"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1339 行定义\&.
.SS "#define HSI_TIMEOUT_VALUE   2U  /* 2 ms */"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1340 行定义\&.
.SS "#define LSI_TIMEOUT_VALUE   2U  /* 2 ms */"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1341 行定义\&.
.SS "#define RCC_BDCR_BDRST_BB   (PERIPH_BB_BASE + (\fBRCC_BDCR_OFFSET\fP * 32U) + (\fBRCC_BDRST_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1316 行定义\&.
.SS "#define RCC_BDCR_BYTE0_ADDRESS   (PERIPH_BASE + \fBRCC_BDCR_OFFSET\fP)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1334 行定义\&.
.SS "#define RCC_BDCR_OFFSET   (\fBRCC_OFFSET\fP + 0x70U)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1311 行定义\&.
.SS "#define RCC_BDCR_RTCEN_BB   (PERIPH_BB_BASE + (\fBRCC_BDCR_OFFSET\fP * 32U) + (\fBRCC_RTCEN_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1313 行定义\&.
.SS "#define RCC_BDRST_BIT_NUMBER   0x10U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1315 行定义\&.
.SS "#define RCC_CIR_BYTE1_ADDRESS   ((uint32_t)(RCC_BASE + 0x0CU + 0x01U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1328 行定义\&.
.SS "#define RCC_CIR_BYTE2_ADDRESS   ((uint32_t)(RCC_BASE + 0x0CU + 0x02U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1331 行定义\&.
.SS "#define RCC_CR_BYTE2_ADDRESS   0x40023802U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1325 行定义\&.
.SS "#define RCC_CR_CSSON_BB   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_CSSON_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1304 行定义\&.
.SS "#define RCC_CR_HSION_BB   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_HSION_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1301 行定义\&.
.SS "#define RCC_CR_OFFSET   (\fBRCC_OFFSET\fP + 0x00U)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1299 行定义\&.
.SS "#define RCC_CR_PLLON_BB   (PERIPH_BB_BASE + (\fBRCC_CR_OFFSET\fP * 32U) + (\fBRCC_PLLON_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1307 行定义\&.
.SS "#define RCC_CSR_LSION_BB   (PERIPH_BB_BASE + (\fBRCC_CSR_OFFSET\fP * 32U) + (\fBRCC_LSION_BIT_NUMBER\fP * 4U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1322 行定义\&.
.SS "#define RCC_CSR_OFFSET   (\fBRCC_OFFSET\fP + 0x74U)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1320 行定义\&.
.SS "#define RCC_CSSON_BIT_NUMBER   0x13U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1303 行定义\&.
.SS "#define RCC_DBP_TIMEOUT_VALUE   2U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1336 行定义\&.
.SS "#define RCC_HSION_BIT_NUMBER   0x00U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1300 行定义\&.
.SS "#define RCC_LSE_TIMEOUT_VALUE   \fBLSE_STARTUP_TIMEOUT\fP"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1337 行定义\&.
.SS "#define RCC_LSION_BIT_NUMBER   0x00U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1321 行定义\&.
.SS "#define RCC_OFFSET   (RCC_BASE \- PERIPH_BASE)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1296 行定义\&.
.SS "#define RCC_PLLON_BIT_NUMBER   0x18U"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1306 行定义\&.
.SS "#define RCC_RTCEN_BIT_NUMBER   0x0FU"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1312 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
