.TH "RCC_IS_RCC_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_IS_RCC_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_RCC_OSCILLATORTYPE\fP(OSCILLATOR)   ((OSCILLATOR) <= 15U)"
.br
.ti -1c
.RI "#define \fBIS_RCC_HSE\fP(HSE)"
.br
.ti -1c
.RI "#define \fBIS_RCC_LSE\fP(LSE)"
.br
.ti -1c
.RI "#define \fBIS_RCC_HSI\fP(HSI)   (((HSI) == \fBRCC_HSI_OFF\fP) || ((HSI) == \fBRCC_HSI_ON\fP))"
.br
.ti -1c
.RI "#define \fBIS_RCC_LSI\fP(LSI)   (((LSI) == \fBRCC_LSI_OFF\fP) || ((LSI) == \fBRCC_LSI_ON\fP))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLL\fP(PLL)   (((PLL) == \fBRCC_PLL_NONE\fP) ||((PLL) == \fBRCC_PLL_OFF\fP) || ((PLL) == \fBRCC_PLL_ON\fP))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLSOURCE\fP(SOURCE)"
.br
.ti -1c
.RI "#define \fBIS_RCC_SYSCLKSOURCE\fP(SOURCE)"
.br
.ti -1c
.RI "#define \fBIS_RCC_RTCCLKSOURCE\fP(__SOURCE__)"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLM_VALUE\fP(VALUE)   ((VALUE) <= 63U)"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLP_VALUE\fP(VALUE)   (((VALUE) == 2U) || ((VALUE) == 4U) || ((VALUE) == 6U) || ((VALUE) == 8U))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLQ_VALUE\fP(VALUE)   ((2U <= (VALUE)) && ((VALUE) <= 15U))"
.br
.ti -1c
.RI "#define \fBIS_RCC_HCLK\fP(HCLK)"
.br
.ti -1c
.RI "#define \fBIS_RCC_CLOCKTYPE\fP(CLK)   ((1U <= (CLK)) && ((CLK) <= 15U))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PCLK\fP(PCLK)"
.br
.ti -1c
.RI "#define \fBIS_RCC_MCO\fP(MCOx)   (((MCOx) == \fBRCC_MCO1\fP) || ((MCOx) == \fBRCC_MCO2\fP))"
.br
.ti -1c
.RI "#define \fBIS_RCC_MCO1SOURCE\fP(SOURCE)"
.br
.ti -1c
.RI "#define \fBIS_RCC_MCODIV\fP(DIV)"
.br
.ti -1c
.RI "#define \fBIS_RCC_CALIBRATION_VALUE\fP(VALUE)   ((VALUE) <= 0x1FU)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_RCC_CALIBRATION_VALUE(VALUE)   ((VALUE) <= 0x1FU)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1441 行定义\&.
.SS "#define IS_RCC_CLOCKTYPE(CLK)   ((1U <= (CLK)) && ((CLK) <= 15U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1427 行定义\&.
.SS "#define IS_RCC_HCLK(HCLK)"
\fB值:\fP
.PP
.nf
                           (((HCLK) == RCC_SYSCLK_DIV1)   || ((HCLK) == RCC_SYSCLK_DIV2)   || \
                           ((HCLK) == RCC_SYSCLK_DIV4)   || ((HCLK) == RCC_SYSCLK_DIV8)   || \
                           ((HCLK) == RCC_SYSCLK_DIV16)  || ((HCLK) == RCC_SYSCLK_DIV64)  || \
                           ((HCLK) == RCC_SYSCLK_DIV128) || ((HCLK) == RCC_SYSCLK_DIV256) || \
                           ((HCLK) == RCC_SYSCLK_DIV512))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1421 行定义\&.
.SS "#define IS_RCC_HSE(HSE)"
\fB值:\fP
.PP
.nf
                         (((HSE) == RCC_HSE_OFF) || ((HSE) == RCC_HSE_ON) || \
                         ((HSE) == RCC_HSE_BYPASS))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1362 行定义\&.
.SS "#define IS_RCC_HSI(HSI)   (((HSI) == \fBRCC_HSI_OFF\fP) || ((HSI) == \fBRCC_HSI_ON\fP))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1368 行定义\&.
.SS "#define IS_RCC_LSE(LSE)"
\fB值:\fP
.PP
.nf
                         (((LSE) == RCC_LSE_OFF) || ((LSE) == RCC_LSE_ON) || \
                         ((LSE) == RCC_LSE_BYPASS))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1365 行定义\&.
.SS "#define IS_RCC_LSI(LSI)   (((LSI) == \fBRCC_LSI_OFF\fP) || ((LSI) == \fBRCC_LSI_ON\fP))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1370 行定义\&.
.SS "#define IS_RCC_MCO(MCOx)   (((MCOx) == \fBRCC_MCO1\fP) || ((MCOx) == \fBRCC_MCO2\fP))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1433 行定义\&.
.SS "#define IS_RCC_MCO1SOURCE(SOURCE)"
\fB值:\fP
.PP
.nf
                                   (((SOURCE) == RCC_MCO1SOURCE_HSI) || ((SOURCE) == RCC_MCO1SOURCE_LSE) || \
                                   ((SOURCE) == RCC_MCO1SOURCE_HSE) || ((SOURCE) == RCC_MCO1SOURCE_PLLCLK))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1435 行定义\&.
.SS "#define IS_RCC_MCODIV(DIV)"
\fB值:\fP
.PP
.nf
                             (((DIV) == RCC_MCODIV_1)  || ((DIV) == RCC_MCODIV_2) || \
                             ((DIV) == RCC_MCODIV_3) || ((DIV) == RCC_MCODIV_4) || \
                             ((DIV) == RCC_MCODIV_5))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1438 行定义\&.
.SS "#define IS_RCC_OSCILLATORTYPE(OSCILLATOR)   ((OSCILLATOR) <= 15U)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1360 行定义\&.
.SS "#define IS_RCC_PCLK(PCLK)"
\fB值:\fP
.PP
.nf
                           (((PCLK) == RCC_HCLK_DIV1) || ((PCLK) == RCC_HCLK_DIV2) || \
                           ((PCLK) == RCC_HCLK_DIV4) || ((PCLK) == RCC_HCLK_DIV8) || \
                           ((PCLK) == RCC_HCLK_DIV16))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1429 行定义\&.
.SS "#define IS_RCC_PLL(PLL)   (((PLL) == \fBRCC_PLL_NONE\fP) ||((PLL) == \fBRCC_PLL_OFF\fP) || ((PLL) == \fBRCC_PLL_ON\fP))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1372 行定义\&.
.SS "#define IS_RCC_PLLM_VALUE(VALUE)   ((VALUE) <= 63U)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1415 行定义\&.
.SS "#define IS_RCC_PLLP_VALUE(VALUE)   (((VALUE) == 2U) || ((VALUE) == 4U) || ((VALUE) == 6U) || ((VALUE) == 8U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1417 行定义\&.
.SS "#define IS_RCC_PLLQ_VALUE(VALUE)   ((2U <= (VALUE)) && ((VALUE) <= 15U))"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1419 行定义\&.
.SS "#define IS_RCC_PLLSOURCE(SOURCE)"
\fB值:\fP
.PP
.nf
                                  (((SOURCE) == RCC_PLLSOURCE_HSI) || \
                                  ((SOURCE) == RCC_PLLSOURCE_HSE))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1374 行定义\&.
.SS "#define IS_RCC_RTCCLKSOURCE(__SOURCE__)"

.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1382 行定义\&.
.SS "#define IS_RCC_SYSCLKSOURCE(SOURCE)"
\fB值:\fP
.PP
.nf
                                     (((SOURCE) == RCC_SYSCLKSOURCE_HSI) || \
                                     ((SOURCE) == RCC_SYSCLKSOURCE_HSE) || \
                                     ((SOURCE) == RCC_SYSCLKSOURCE_PLLCLK) || \
                                     ((SOURCE) == RCC_SYSCLKSOURCE_PLLRCLK))
.fi
.PP
在文件 stm32f4xx_hal_rcc\&.h 第 1377 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
