.TH "RCC_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_RCC_MCOConfig\fP (uint32_t RCC_MCOx, uint32_t RCC_MCOSource, uint32_t RCC_MCODiv)"
.br
.ti -1c
.RI "void \fBHAL_RCC_EnableCSS\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_RCC_DisableCSS\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_RCC_GetSysClockFreq\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_RCC_GetHCLKFreq\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_RCC_GetPCLK1Freq\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_RCC_GetPCLK2Freq\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_RCC_GetOscConfig\fP (\fBRCC_OscInitTypeDef\fP *RCC_OscInitStruct)"
.br
.ti -1c
.RI "void \fBHAL_RCC_GetClockConfig\fP (\fBRCC_ClkInitTypeDef\fP *RCC_ClkInitStruct, uint32_t *pFLatency)"
.br
.ti -1c
.RI "void \fBHAL_RCC_NMI_IRQHandler\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_RCC_CSSCallback\fP (void)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_RCC_CSSCallback (void)"

.SS "void HAL_RCC_DisableCSS (void)"

.SS "void HAL_RCC_EnableCSS (void)"

.SS "void HAL_RCC_GetClockConfig (\fBRCC_ClkInitTypeDef\fP * RCC_ClkInitStruct, uint32_t * pFLatency)"

.SS "uint32_t HAL_RCC_GetHCLKFreq (void)"

.SS "void HAL_RCC_GetOscConfig (\fBRCC_OscInitTypeDef\fP * RCC_OscInitStruct)"

.SS "uint32_t HAL_RCC_GetPCLK1Freq (void)"

.SS "uint32_t HAL_RCC_GetPCLK2Freq (void)"

.SS "uint32_t HAL_RCC_GetSysClockFreq (void)"

.SS "void HAL_RCC_MCOConfig (uint32_t RCC_MCOx, uint32_t RCC_MCOSource, uint32_t RCC_MCODiv)"

.SS "void HAL_RCC_NMI_IRQHandler (void)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
