.TH "RCC_Exported_Types" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBRCC_OscInitTypeDef\fP"
.br
.RI "RCC Internal/External Oscillator (HSE, HSI, LSE and LSI) configuration structure definition "
.ti -1c
.RI "struct \fBRCC_ClkInitTypeDef\fP"
.br
.RI "RCC System, AHB and APB busses clock configuration structure definition "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
