.TH "RCCEx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RCCEx_PeriphCLKConfig\fP (RCC_PeriphCLKInitTypeDef *PeriphClkInit)"
.br
.ti -1c
.RI "void \fBHAL_RCCEx_GetPeriphCLKConfig\fP (RCC_PeriphCLKInitTypeDef *PeriphClkInit)"
.br
.ti -1c
.RI "uint32_t \fBHAL_RCCEx_GetPeriphCLKFreq\fP (uint32_t PeriphClk)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_RCCEx_GetPeriphCLKConfig (RCC_PeriphCLKInitTypeDef * PeriphClkInit)"

.SS "uint32_t HAL_RCCEx_GetPeriphCLKFreq (uint32_t PeriphClk)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RCCEx_PeriphCLKConfig (RCC_PeriphCLKInitTypeDef * PeriphClkInit)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
