.TH "RCCEx_IS_RCC_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_IS_RCC_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_RCC_PLLN_VALUE\fP(VALUE)   ((50U <= (VALUE)) && ((VALUE) <= 432U))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLI2SN_VALUE\fP(VALUE)   ((50U <= (VALUE)) && ((VALUE) <= 432U))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLLI2SR_VALUE\fP(VALUE)   ((2U <= (VALUE)) && ((VALUE) <= 7U))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_RCC_PLLI2SN_VALUE(VALUE)   ((50U <= (VALUE)) && ((VALUE) <= 432U))"

.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 6879 行定义\&.
.SS "#define IS_RCC_PLLI2SR_VALUE(VALUE)   ((2U <= (VALUE)) && ((VALUE) <= 7U))"

.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 6914 行定义\&.
.SS "#define IS_RCC_PLLN_VALUE(VALUE)   ((50U <= (VALUE)) && ((VALUE) <= 432U))"

.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 6878 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
