.TH "RCCEx_BitAddress_AliasRegion" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_BitAddress_AliasRegion \- RCC registers bit address in the alias region  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRCC_CFGR_OFFSET\fP   (\fBRCC_OFFSET\fP + 0x08U)"
.br
.ti -1c
.RI "#define \fBPLL_TIMEOUT_VALUE\fP   2U  /* 2 ms */"
.br
.in -1c
.SH "详细描述"
.PP 
RCC registers bit address in the alias region 


.SH "宏定义说明"
.PP 
.SS "#define PLL_TIMEOUT_VALUE   2U  /* 2 ms */"

.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 6855 行定义\&.
.SS "#define RCC_CFGR_OFFSET   (\fBRCC_OFFSET\fP + 0x08U)"

.PP
在文件 stm32f4xx_hal_rcc_ex\&.h 第 6821 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
