.TH "RTC_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_InitTypeDef \- RTC Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rtc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBHourFormat\fP"
.br
.ti -1c
.RI "uint32_t \fBAsynchPrediv\fP"
.br
.ti -1c
.RI "uint32_t \fBSynchPrediv\fP"
.br
.ti -1c
.RI "uint32_t \fBOutPut\fP"
.br
.ti -1c
.RI "uint32_t \fBOutPutPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBOutPutType\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RTC Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 59 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AsynchPrediv"
Specifies the RTC Asynchronous Predivider value\&. This parameter must be a number between Min_Data = 0x00 and Max_Data = 0x7F 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 64 行定义\&.
.SS "uint32_t HourFormat"
Specifies the RTC Hour Format\&. This parameter can be a value of \fBRTC Hour Formats\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 61 行定义\&.
.SS "uint32_t OutPut"
Specifies which signal will be routed to the RTC output\&. This parameter can be a value of \fBRTC Output Selection Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 70 行定义\&.
.SS "uint32_t OutPutPolarity"
Specifies the polarity of the output signal\&. This parameter can be a value of \fBRTC Output Polarity Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 73 行定义\&.
.SS "uint32_t OutPutType"
Specifies the RTC Output Pin mode\&. This parameter can be a value of \fBRTC Output Type ALARM OUT\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 76 行定义\&.
.SS "uint32_t SynchPrediv"
Specifies the RTC Synchronous Predivider value\&. This parameter must be a number between Min_Data = 0x00 and Max_Data = 0x7FFFU 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 67 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
