.TH "RTC_Interrupts_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Interrupts_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_IT_TS\fP   0x00008000U"
.br
.ti -1c
.RI "#define \fBRTC_IT_WUT\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBRTC_IT_ALRB\fP   0x00002000U"
.br
.ti -1c
.RI "#define \fBRTC_IT_ALRA\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBRTC_IT_TAMP\fP   0x00000004U /* Used only to Enable the Tamper Interrupt */"
.br
.ti -1c
.RI "#define \fBRTC_IT_TAMP1\fP   0x00020000U"
.br
.ti -1c
.RI "#define \fBRTC_IT_TAMP2\fP   0x00040000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_IT_ALRA   0x00001000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 415 行定义\&.
.SS "#define RTC_IT_ALRB   0x00002000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 414 行定义\&.
.SS "#define RTC_IT_TAMP   0x00000004U /* Used only to Enable the Tamper Interrupt */"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 416 行定义\&.
.SS "#define RTC_IT_TAMP1   0x00020000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 417 行定义\&.
.SS "#define RTC_IT_TAMP2   0x00040000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 418 行定义\&.
.SS "#define RTC_IT_TS   0x00008000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 412 行定义\&.
.SS "#define RTC_IT_WUT   0x00004000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 413 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
