.TH "RTC_Alarms_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Alarms_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_ALARM_A\fP   RTC_CR_ALRAE"
.br
.ti -1c
.RI "#define \fBRTC_ALARM_B\fP   RTC_CR_ALRBE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_ALARM_A   RTC_CR_ALRAE"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 363 行定义\&.
.SS "#define RTC_ALARM_B   RTC_CR_ALRBE"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 364 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
