.TH "RTC_Flags_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Flags_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_FLAG_RECALPF\fP   0x00010000U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_TAMP2F\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_TAMP1F\fP   0x00002000U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_TSOVF\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_TSF\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_WUTF\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_ALRBF\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_ALRAF\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_INITF\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_RSF\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_INITS\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_SHPF\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_WUTWF\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_ALRBWF\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRTC_FLAG_ALRAWF\fP   0x00000001U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_FLAG_ALRAF   0x00000100U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 433 行定义\&.
.SS "#define RTC_FLAG_ALRAWF   0x00000001U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 440 行定义\&.
.SS "#define RTC_FLAG_ALRBF   0x00000200U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 432 行定义\&.
.SS "#define RTC_FLAG_ALRBWF   0x00000002U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 439 行定义\&.
.SS "#define RTC_FLAG_INITF   0x00000040U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 434 行定义\&.
.SS "#define RTC_FLAG_INITS   0x00000010U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 436 行定义\&.
.SS "#define RTC_FLAG_RECALPF   0x00010000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 426 行定义\&.
.SS "#define RTC_FLAG_RSF   0x00000020U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 435 行定义\&.
.SS "#define RTC_FLAG_SHPF   0x00000008U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 437 行定义\&.
.SS "#define RTC_FLAG_TAMP1F   0x00002000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 428 行定义\&.
.SS "#define RTC_FLAG_TAMP2F   0x00004000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 427 行定义\&.
.SS "#define RTC_FLAG_TSF   0x00000800U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 430 行定义\&.
.SS "#define RTC_FLAG_TSOVF   0x00001000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 429 行定义\&.
.SS "#define RTC_FLAG_WUTF   0x00000400U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 431 行定义\&.
.SS "#define RTC_FLAG_WUTWF   0x00000004U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 438 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
