.TH "RTC_TamperTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_TamperTypeDef \- RTC Tamper structure definition 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rtc_ex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBTamper\fP"
.br
.ti -1c
.RI "uint32_t \fBPinSelection\fP"
.br
.ti -1c
.RI "uint32_t \fBTrigger\fP"
.br
.ti -1c
.RI "uint32_t \fBFilter\fP"
.br
.ti -1c
.RI "uint32_t \fBSamplingFrequency\fP"
.br
.ti -1c
.RI "uint32_t \fBPrechargeDuration\fP"
.br
.ti -1c
.RI "uint32_t \fBTamperPullUp\fP"
.br
.ti -1c
.RI "uint32_t \fBTimeStampOnTamperDetection\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RTC Tamper structure definition 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Filter"
Specifies the RTC Filter Tamper\&. This parameter can be a value of \fBRTC Tamper Filter Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 58 行定义\&.
.SS "uint32_t PinSelection"
Specifies the Tamper Pin\&. This parameter can be a value of \fBRTC tamper Pins Selection\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 52 行定义\&.
.SS "uint32_t PrechargeDuration"
Specifies the Precharge Duration \&. This parameter can be a value of \fBRTC Tamper Pin Precharge Duration Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 64 行定义\&.
.SS "uint32_t SamplingFrequency"
Specifies the sampling frequency\&. This parameter can be a value of \fBRTC Tamper Sampling Frequencies Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 61 行定义\&.
.SS "uint32_t Tamper"
Specifies the Tamper Pin\&. This parameter can be a value of \fBRTC Tamper Pins Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 49 行定义\&.
.SS "uint32_t TamperPullUp"
Specifies the Tamper PullUp \&. This parameter can be a value of \fBRTC Tamper Pull Up Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 67 行定义\&.
.SS "uint32_t TimeStampOnTamperDetection"
Specifies the TimeStampOnTamperDetection\&. This parameter can be a value of \fBRTC Tamper TimeStamp On Tamper Detection Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 70 行定义\&.
.SS "uint32_t Trigger"
Specifies the Tamper Trigger\&. This parameter can be a value of \fBRTC Tamper Triggers Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 55 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
