.TH "RTC_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TR_RESERVED_MASK\fP   0x007F7F7FU"
.br
.ti -1c
.RI "#define \fBRTC_DR_RESERVED_MASK\fP   0x00FFFF3FU"
.br
.ti -1c
.RI "#define \fBRTC_INIT_MASK\fP   0xFFFFFFFFU"
.br
.ti -1c
.RI "#define \fBRTC_RSF_MASK\fP   0xFFFFFF5FU"
.br
.ti -1c
.RI "#define \fBRTC_FLAGS_MASK\fP"
.br
.ti -1c
.RI "#define \fBRTC_TIMEOUT_VALUE\fP   1000"
.br
.ti -1c
.RI "#define \fBRTC_EXTI_LINE_ALARM_EVENT\fP   ((uint32_t)EXTI_IMR_MR17)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_DR_RESERVED_MASK   0x00FFFF3FU"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 754 行定义\&.
.SS "#define RTC_EXTI_LINE_ALARM_EVENT   ((uint32_t)EXTI_IMR_MR17)"
External interrupt line 17 Connected to the RTC Alarm event 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 765 行定义\&.
.SS "#define RTC_FLAGS_MASK"
\fB值:\fP
.PP
.nf
                                            ((uint32_t)(RTC_FLAG_TSOVF | RTC_FLAG_TSF | RTC_FLAG_WUTF | \
                                            RTC_FLAG_ALRBF | RTC_FLAG_ALRAF | RTC_FLAG_INITF | \
                                            RTC_FLAG_RSF | RTC_FLAG_INITS | RTC_FLAG_WUTWF | \
                                            RTC_FLAG_ALRBWF | RTC_FLAG_ALRAWF | RTC_FLAG_TAMP1F | \
                                            RTC_FLAG_RECALPF | RTC_FLAG_SHPF))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 757 行定义\&.
.SS "#define RTC_INIT_MASK   0xFFFFFFFFU"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 755 行定义\&.
.SS "#define RTC_RSF_MASK   0xFFFFFF5FU"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 756 行定义\&.
.SS "#define RTC_TIMEOUT_VALUE   1000"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 763 行定义\&.
.SS "#define RTC_TR_RESERVED_MASK   0x007F7F7FU"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 753 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
