.TH "RTC_Hour_Formats" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Hour_Formats
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_HOURFORMAT_24\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_HOURFORMAT_12\fP   0x00000040U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_HOURFORMAT_12   0x00000040U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 233 行定义\&.
.SS "#define RTC_HOURFORMAT_24   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 232 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
