.TH "RTC_DayLightSaving_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_DayLightSaving_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_DAYLIGHTSAVING_SUB1H\fP   0x00020000U"
.br
.ti -1c
.RI "#define \fBRTC_DAYLIGHTSAVING_ADD1H\fP   0x00010000U"
.br
.ti -1c
.RI "#define \fBRTC_DAYLIGHTSAVING_NONE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_DAYLIGHTSAVING_ADD1H   0x00010000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 280 行定义\&.
.SS "#define RTC_DAYLIGHTSAVING_NONE   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 281 行定义\&.
.SS "#define RTC_DAYLIGHTSAVING_SUB1H   0x00020000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 279 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
