.TH "RTC_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_Init\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_DeInit\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "void \fBHAL_RTC_MspInit\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "void \fBHAL_RTC_MspDeInit\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_DeInit (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_Init (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "void HAL_RTC_MspDeInit (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "void HAL_RTC_MspInit (\fBRTC_HandleTypeDef\fP * hrtc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
