.TH "RTC_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_SetAlarm\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_AlarmTypeDef\fP *sAlarm, uint32_t Format)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_SetAlarm_IT\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_AlarmTypeDef\fP *sAlarm, uint32_t Format)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_DeactivateAlarm\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Alarm)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_GetAlarm\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_AlarmTypeDef\fP *sAlarm, uint32_t Alarm, uint32_t Format)"
.br
.ti -1c
.RI "void \fBHAL_RTC_AlarmIRQHandler\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTC_PollForAlarmAEvent\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Timeout)"
.br
.ti -1c
.RI "void \fBHAL_RTC_AlarmAEventCallback\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.RI "ALARM A Event Callback in non blocking mode "
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_RTC_AlarmAEventCallback (\fBRTC_HandleTypeDef\fP * hrtc)"

.PP
ALARM A Event Callback in non blocking mode 
.PP
\fB注解\fP
.RS 4
This function is called when RTC_ALARM interrupt took place, inside RTC_ALARM_IRQHandler()\&. It makes a direct call to \fBHAL_IncTick()\fP to increment a global variable 'uwTick' used as application time base\&. 
.RE
.PP
\fB参数\fP
.RS 4
\fIhrtc\fP RTC handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_rtc_alarm_template\&.c 第 251 行定义\&.
.SS "void HAL_RTC_AlarmIRQHandler (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_DeactivateAlarm (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Alarm)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_GetAlarm (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_AlarmTypeDef\fP * sAlarm, uint32_t Alarm, uint32_t Format)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_PollForAlarmAEvent (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_SetAlarm (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_AlarmTypeDef\fP * sAlarm, uint32_t Format)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTC_SetAlarm_IT (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_AlarmTypeDef\fP * sAlarm, uint32_t Format)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
