.TH "RTC_AlarmTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_AlarmTypeDef \- RTC Alarm structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rtc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBRTC_TimeTypeDef\fP \fBAlarmTime\fP"
.br
.ti -1c
.RI "uint32_t \fBAlarmMask\fP"
.br
.ti -1c
.RI "uint32_t \fBAlarmSubSecondMask\fP"
.br
.ti -1c
.RI "uint32_t \fBAlarmDateWeekDaySel\fP"
.br
.ti -1c
.RI "uint8_t \fBAlarmDateWeekDay\fP"
.br
.ti -1c
.RI "uint32_t \fBAlarm\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RTC Alarm structure definition 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 138 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Alarm"
Specifies the alarm \&. This parameter can be a value of \fBRTC Alarms Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 155 行定义\&.
.SS "uint8_t AlarmDateWeekDay"
Specifies the RTC Alarm Date/WeekDay\&. If the Alarm Date is selected, this parameter must be set to a value in the 1-31 range\&. If the Alarm WeekDay is selected, this parameter can be a value of \fBRTC WeekDay Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 151 行定义\&.
.SS "uint32_t AlarmDateWeekDaySel"
Specifies the RTC Alarm is on Date or WeekDay\&. This parameter can be a value of \fBRTC Alarm Date WeekDay Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 148 行定义\&.
.SS "uint32_t AlarmMask"
Specifies the RTC Alarm Masks\&. This parameter can be a value of \fBRTC Alarm Mask Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 142 行定义\&.
.SS "uint32_t AlarmSubSecondMask"
Specifies the RTC Alarm SubSeconds Masks\&. This parameter can be a value of \fBRTC Alarm Sub Seconds Masks Definitions\fP 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 145 行定义\&.
.SS "\fBRTC_TimeTypeDef\fP AlarmTime"
Specifies the RTC Alarm Time members 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 140 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
