.TH "RTC_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_HandleTypeDef \- RTC Handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_rtc\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "RTC_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBRTC_InitTypeDef\fP \fBInit\fP"
.br
.ti -1c
.RI "\fBHAL_LockTypeDef\fP \fBLock\fP"
.br
.ti -1c
.RI "__IO \fBHAL_RTCStateTypeDef\fP \fBState\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RTC Handle Structure definition 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 165 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBRTC_InitTypeDef\fP Init"
RTC required parameters 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 170 行定义\&.
.SS "RTC_TypeDef* Instance"
Register base address 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 168 行定义\&.
.SS "\fBHAL_LockTypeDef\fP Lock"
RTC locking object 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 172 行定义\&.
.SS "__IO \fBHAL_RTCStateTypeDef\fP State"
Time communication state 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 174 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
