.TH "RTC_Alarm_Sub_Seconds_Masks_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Alarm_Sub_Seconds_Masks_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_ALL\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_1\fP   0x01000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_2\fP   0x02000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_3\fP   0x03000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_4\fP   0x04000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_5\fP   0x05000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_6\fP   0x06000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_7\fP   0x07000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_8\fP   0x08000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_9\fP   0x09000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_10\fP   0x0A000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_11\fP   0x0B000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_12\fP   0x0C000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14_13\fP   0x0D000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_SS14\fP   0x0E000000U"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_NONE\fP   0x0F000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_ALARMSUBSECONDMASK_ALL   0x00000000U"
All Alarm SS fields are masked\&. There is no comparison on sub seconds for Alarm 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 374 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_NONE   0x0F000000U"
SS[14:0] are compared and must match to activate alarm\&. 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 404 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14   0x0E000000U"
SS[14] is don't care in Alarm comparison\&.Only SS[13:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 402 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_1   0x01000000U"
SS[14:1] are don't care in Alarm comparison\&. Only SS[0] is compared\&. 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 376 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_10   0x0A000000U"
SS[14:10] are don't care in Alarm comparison\&. Only SS[9:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 394 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_11   0x0B000000U"
SS[14:11] are don't care in Alarm comparison\&. Only SS[10:0] are compared 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 396 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_12   0x0C000000U"
SS[14:12] are don't care in Alarm comparison\&.Only SS[11:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 398 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_13   0x0D000000U"
SS[14:13] are don't care in Alarm comparison\&. Only SS[12:0] are compared 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 400 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_2   0x02000000U"
SS[14:2] are don't care in Alarm comparison\&. Only SS[1:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 378 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_3   0x03000000U"
SS[14:3] are don't care in Alarm comparison\&. Only SS[2:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 380 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_4   0x04000000U"
SS[14:4] are don't care in Alarm comparison\&. Only SS[3:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 382 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_5   0x05000000U"
SS[14:5] are don't care in Alarm comparison\&. Only SS[4:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 384 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_6   0x06000000U"
SS[14:6] are don't care in Alarm comparison\&. Only SS[5:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 386 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_7   0x07000000U"
SS[14:7] are don't care in Alarm comparison\&. Only SS[6:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 388 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_8   0x08000000U"
SS[14:8] are don't care in Alarm comparison\&. Only SS[7:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 390 行定义\&.
.SS "#define RTC_ALARMSUBSECONDMASK_SS14_9   0x09000000U"
SS[14:9] are don't care in Alarm comparison\&. Only SS[8:0] are compared 
.br
 
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 392 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
