.TH "RTC_Output_selection_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Output_selection_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_OUTPUT_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_ALARMA\fP   0x00200000U"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_ALARMB\fP   0x00400000U"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_WAKEUP\fP   0x00600000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_OUTPUT_ALARMA   0x00200000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 242 行定义\&.
.SS "#define RTC_OUTPUT_ALARMB   0x00400000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 243 行定义\&.
.SS "#define RTC_OUTPUT_DISABLE   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 241 行定义\&.
.SS "#define RTC_OUTPUT_WAKEUP   0x00600000U"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 244 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
