.TH "RTC_IS_RTC_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_IS_RTC_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_RTC_HOUR_FORMAT\fP(FORMAT)"
.br
.ti -1c
.RI "#define \fBIS_RTC_OUTPUT\fP(OUTPUT)"
.br
.ti -1c
.RI "#define \fBIS_RTC_OUTPUT_POL\fP(POL)"
.br
.ti -1c
.RI "#define \fBIS_RTC_OUTPUT_TYPE\fP(TYPE)"
.br
.ti -1c
.RI "#define \fBIS_RTC_HOUR12\fP(HOUR)   (((HOUR) > 0U) && ((HOUR) <= 12U))"
.br
.ti -1c
.RI "#define \fBIS_RTC_HOUR24\fP(HOUR)   ((HOUR) <= 23U)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ASYNCH_PREDIV\fP(PREDIV)   ((PREDIV) <= 0x7FU)"
.br
.ti -1c
.RI "#define \fBIS_RTC_SYNCH_PREDIV\fP(PREDIV)   ((PREDIV) <= 0x7FFFU)"
.br
.ti -1c
.RI "#define \fBIS_RTC_MINUTES\fP(MINUTES)   ((MINUTES) <= 59U)"
.br
.ti -1c
.RI "#define \fBIS_RTC_SECONDS\fP(SECONDS)   ((SECONDS) <= 59U)"
.br
.ti -1c
.RI "#define \fBIS_RTC_HOURFORMAT12\fP(PM)   (((PM) == \fBRTC_HOURFORMAT12_AM\fP) || ((PM) == \fBRTC_HOURFORMAT12_PM\fP))"
.br
.ti -1c
.RI "#define \fBIS_RTC_DAYLIGHT_SAVING\fP(SAVE)"
.br
.ti -1c
.RI "#define \fBIS_RTC_STORE_OPERATION\fP(OPERATION)"
.br
.ti -1c
.RI "#define \fBIS_RTC_FORMAT\fP(FORMAT)   (((FORMAT) == \fBRTC_FORMAT_BIN\fP) || ((FORMAT) == \fBRTC_FORMAT_BCD\fP))"
.br
.ti -1c
.RI "#define \fBIS_RTC_YEAR\fP(YEAR)   ((YEAR) <= 99U)"
.br
.ti -1c
.RI "#define \fBIS_RTC_MONTH\fP(MONTH)   (((MONTH) >= 1U) && ((MONTH) <= 12U))"
.br
.ti -1c
.RI "#define \fBIS_RTC_DATE\fP(DATE)   (((DATE) >= 1U) && ((DATE) <= 31U))"
.br
.ti -1c
.RI "#define \fBIS_RTC_WEEKDAY\fP(WEEKDAY)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_DATE_WEEKDAY_DATE\fP(DATE)   (((DATE) > 0U) && ((DATE) <= 31U))"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY\fP(WEEKDAY)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_DATE_WEEKDAY_SEL\fP(SEL)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_MASK\fP(MASK)   (((MASK) & 0x7F7F7F7FU) == (uint32_t)RESET)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM\fP(ALARM)   (((ALARM) == \fBRTC_ALARM_A\fP) || ((ALARM) == \fBRTC_ALARM_B\fP))"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_SUB_SECOND_VALUE\fP(VALUE)   ((VALUE) <= 0x00007FFFU)"
.br
.ti -1c
.RI "#define \fBIS_RTC_ALARM_SUB_SECOND_MASK\fP(MASK)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_RTC_ALARM(ALARM)   (((ALARM) == \fBRTC_ALARM_A\fP) || ((ALARM) == \fBRTC_ALARM_B\fP))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 823 行定义\&.
.SS "#define IS_RTC_ALARM_DATE_WEEKDAY_DATE(DATE)   (((DATE) > 0U) && ((DATE) <= 31U))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 812 行定义\&.
.SS "#define IS_RTC_ALARM_DATE_WEEKDAY_SEL(SEL)"
\fB值:\fP
.PP
.nf
                                            (((SEL) == RTC_ALARMDATEWEEKDAYSEL_DATE) || \
                                            ((SEL) == RTC_ALARMDATEWEEKDAYSEL_WEEKDAY))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 820 行定义\&.
.SS "#define IS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY(WEEKDAY)"
\fB值:\fP
.PP
.nf
                                                    (((WEEKDAY) == RTC_WEEKDAY_MONDAY)    || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_TUESDAY)   || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_WEDNESDAY) || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_THURSDAY)  || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_FRIDAY)    || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_SATURDAY)  || \
                                                    ((WEEKDAY) == RTC_WEEKDAY_SUNDAY))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 813 行定义\&.
.SS "#define IS_RTC_ALARM_MASK(MASK)   (((MASK) & 0x7F7F7F7FU) == (uint32_t)RESET)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 822 行定义\&.
.SS "#define IS_RTC_ALARM_SUB_SECOND_MASK(MASK)"
\fB值:\fP
.PP
.nf
                                              (((MASK) == RTC_ALARMSUBSECONDMASK_ALL) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_1) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_2) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_3) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_4) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_5) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_6) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_7) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_8) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_9) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_10) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_11) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_12) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14_13) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_SS14) || \
                                              ((MASK) == RTC_ALARMSUBSECONDMASK_NONE))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 826 行定义\&.
.SS "#define IS_RTC_ALARM_SUB_SECOND_VALUE(VALUE)   ((VALUE) <= 0x00007FFFU)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 824 行定义\&.
.SS "#define IS_RTC_ASYNCH_PREDIV(PREDIV)   ((PREDIV) <= 0x7FU)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 790 行定义\&.
.SS "#define IS_RTC_DATE(DATE)   (((DATE) >= 1U) && ((DATE) <= 31U))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 804 行定义\&.
.SS "#define IS_RTC_DAYLIGHT_SAVING(SAVE)"
\fB值:\fP
.PP
.nf
                                      (((SAVE) == RTC_DAYLIGHTSAVING_SUB1H) || \
                                      ((SAVE) == RTC_DAYLIGHTSAVING_ADD1H) || \
                                      ((SAVE) == RTC_DAYLIGHTSAVING_NONE))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 796 行定义\&.
.SS "#define IS_RTC_FORMAT(FORMAT)   (((FORMAT) == \fBRTC_FORMAT_BIN\fP) || ((FORMAT) == \fBRTC_FORMAT_BCD\fP))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 801 行定义\&.
.SS "#define IS_RTC_HOUR12(HOUR)   (((HOUR) > 0U) && ((HOUR) <= 12U))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 788 行定义\&.
.SS "#define IS_RTC_HOUR24(HOUR)   ((HOUR) <= 23U)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 789 行定义\&.
.SS "#define IS_RTC_HOUR_FORMAT(FORMAT)"
\fB值:\fP
.PP
.nf
                                        (((FORMAT) == RTC_HOURFORMAT_12) || \
                                        ((FORMAT) == RTC_HOURFORMAT_24))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 778 行定义\&.
.SS "#define IS_RTC_HOURFORMAT12(PM)   (((PM) == \fBRTC_HOURFORMAT12_AM\fP) || ((PM) == \fBRTC_HOURFORMAT12_PM\fP))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 795 行定义\&.
.SS "#define IS_RTC_MINUTES(MINUTES)   ((MINUTES) <= 59U)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 792 行定义\&.
.SS "#define IS_RTC_MONTH(MONTH)   (((MONTH) >= 1U) && ((MONTH) <= 12U))"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 803 行定义\&.
.SS "#define IS_RTC_OUTPUT(OUTPUT)"
\fB值:\fP
.PP
.nf
                               (((OUTPUT) == RTC_OUTPUT_DISABLE) || \
                               ((OUTPUT) == RTC_OUTPUT_ALARMA)  || \
                               ((OUTPUT) == RTC_OUTPUT_ALARMB)  || \
                               ((OUTPUT) == RTC_OUTPUT_WAKEUP))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 780 行定义\&.
.SS "#define IS_RTC_OUTPUT_POL(POL)"
\fB值:\fP
.PP
.nf
                                (((POL) == RTC_OUTPUT_POLARITY_HIGH) || \
                                ((POL) == RTC_OUTPUT_POLARITY_LOW))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 784 行定义\&.
.SS "#define IS_RTC_OUTPUT_TYPE(TYPE)"
\fB值:\fP
.PP
.nf
                                  (((TYPE) == RTC_OUTPUT_TYPE_OPENDRAIN) || \
                                  ((TYPE) == RTC_OUTPUT_TYPE_PUSHPULL))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 786 行定义\&.
.SS "#define IS_RTC_SECONDS(SECONDS)   ((SECONDS) <= 59U)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 793 行定义\&.
.SS "#define IS_RTC_STORE_OPERATION(OPERATION)"
\fB值:\fP
.PP
.nf
                                           (((OPERATION) == RTC_STOREOPERATION_RESET) || \
                                           ((OPERATION) == RTC_STOREOPERATION_SET))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 799 行定义\&.
.SS "#define IS_RTC_SYNCH_PREDIV(PREDIV)   ((PREDIV) <= 0x7FFFU)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 791 行定义\&.
.SS "#define IS_RTC_WEEKDAY(WEEKDAY)"
\fB值:\fP
.PP
.nf
                                 (((WEEKDAY) == RTC_WEEKDAY_MONDAY)    || \
                                 ((WEEKDAY) == RTC_WEEKDAY_TUESDAY)   || \
                                 ((WEEKDAY) == RTC_WEEKDAY_WEDNESDAY) || \
                                 ((WEEKDAY) == RTC_WEEKDAY_THURSDAY)  || \
                                 ((WEEKDAY) == RTC_WEEKDAY_FRIDAY)    || \
                                 ((WEEKDAY) == RTC_WEEKDAY_SATURDAY)  || \
                                 ((WEEKDAY) == RTC_WEEKDAY_SUNDAY))
.fi
.PP
在文件 stm32f4xx_hal_rtc\&.h 第 805 行定义\&.
.SS "#define IS_RTC_YEAR(YEAR)   ((YEAR) <= 99U)"

.PP
在文件 stm32f4xx_hal_rtc\&.h 第 802 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
