.TH "RTC_Private_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBRTC_EnterInitMode\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "uint8_t \fBRTC_ByteToBcd2\fP (uint8_t Value)"
.br
.ti -1c
.RI "uint8_t \fBRTC_Bcd2ToByte\fP (uint8_t Value)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint8_t RTC_Bcd2ToByte (uint8_t Value)"

.SS "uint8_t RTC_ByteToBcd2 (uint8_t Value)"

.SS "\fBHAL_StatusTypeDef\fP RTC_EnterInitMode (\fBRTC_HandleTypeDef\fP * hrtc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
