.TH "RTC_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBRTC Hour Formats\fP"
.br
.ti -1c
.RI "\fBRTC Output Selection Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Output Polarity Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Output Type ALARM OUT\fP"
.br
.ti -1c
.RI "\fBRTC AM PM Definitions\fP"
.br
.ti -1c
.RI "\fBRTC DayLight Saving Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Store Operation Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Input Parameter Format Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Month Date Definitions\fP"
.br
.ti -1c
.RI "\fBRTC WeekDay Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Alarm Date WeekDay Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Alarm Mask Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Alarms Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Alarm Sub Seconds Masks Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Interrupts Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Flags Definitions\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
