.TH "RTCEx_Exported_Functions_Group4" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Exported_Functions_Group4
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_RTCEx_AlarmBEventCallback\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_PollForAlarmBEvent\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Timeout)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_RTCEx_AlarmBEventCallback (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_PollForAlarmBEvent (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Timeout)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
