.TH "RTCEx_Tamper_Pins_Selection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Pins_Selection
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_DEFAULT\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_POS1\fP   0x00010000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_TAMPERPIN_DEFAULT   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 135 行定义\&.
.SS "#define RTC_TAMPERPIN_POS1   0x00010000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 138 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
