.TH "RTCEx" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx \- RTC HAL module driver  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBRTCEx Exported Types\fP"
.br
.ti -1c
.RI "\fBRTCEx Exported Constants\fP"
.br
.ti -1c
.RI "\fBRTCEx Exported Macros\fP"
.br
.ti -1c
.RI "\fBRTCEx Exported Functions\fP"
.br
.ti -1c
.RI "\fBRTCEx Private Constants\fP"
.br
.ti -1c
.RI "\fBRTCEx Private Macros\fP"
.br
.in -1c
.SH "详细描述"
.PP 
RTC HAL module driver 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
