.TH "RTCEx_Backup_Registers_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Backup_Registers_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_BKP_DR0\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR1\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR2\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR3\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR4\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR5\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR6\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR7\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR8\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR9\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR10\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR11\fP   0x0000000BU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR12\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR13\fP   0x0000000DU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR14\fP   0x0000000EU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR15\fP   0x0000000FU"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR16\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR17\fP   0x00000011U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR18\fP   0x00000012U"
.br
.ti -1c
.RI "#define \fBRTC_BKP_DR19\fP   0x00000013U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_BKP_DR0   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 86 行定义\&.
.SS "#define RTC_BKP_DR1   0x00000001U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 87 行定义\&.
.SS "#define RTC_BKP_DR10   0x0000000AU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 96 行定义\&.
.SS "#define RTC_BKP_DR11   0x0000000BU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 97 行定义\&.
.SS "#define RTC_BKP_DR12   0x0000000CU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 98 行定义\&.
.SS "#define RTC_BKP_DR13   0x0000000DU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 99 行定义\&.
.SS "#define RTC_BKP_DR14   0x0000000EU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 100 行定义\&.
.SS "#define RTC_BKP_DR15   0x0000000FU"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 101 行定义\&.
.SS "#define RTC_BKP_DR16   0x00000010U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 102 行定义\&.
.SS "#define RTC_BKP_DR17   0x00000011U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 103 行定义\&.
.SS "#define RTC_BKP_DR18   0x00000012U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 104 行定义\&.
.SS "#define RTC_BKP_DR19   0x00000013U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 105 行定义\&.
.SS "#define RTC_BKP_DR2   0x00000002U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 88 行定义\&.
.SS "#define RTC_BKP_DR3   0x00000003U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 89 行定义\&.
.SS "#define RTC_BKP_DR4   0x00000004U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 90 行定义\&.
.SS "#define RTC_BKP_DR5   0x00000005U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 91 行定义\&.
.SS "#define RTC_BKP_DR6   0x00000006U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 92 行定义\&.
.SS "#define RTC_BKP_DR7   0x00000007U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 93 行定义\&.
.SS "#define RTC_BKP_DR8   0x00000008U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 94 行定义\&.
.SS "#define RTC_BKP_DR9   0x00000009U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 95 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
