.TH "RTCEx_Wakeup_Timer_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Wakeup_Timer_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_RTCCLK_DIV16\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_RTCCLK_DIV8\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_RTCCLK_DIV4\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_RTCCLK_DIV2\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_CK_SPRE_16BITS\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUPCLOCK_CK_SPRE_17BITS\fP   0x00000006U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_WAKEUPCLOCK_CK_SPRE_16BITS   0x00000004U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 245 行定义\&.
.SS "#define RTC_WAKEUPCLOCK_CK_SPRE_17BITS   0x00000006U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 246 行定义\&.
.SS "#define RTC_WAKEUPCLOCK_RTCCLK_DIV16   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 241 行定义\&.
.SS "#define RTC_WAKEUPCLOCK_RTCCLK_DIV2   0x00000003U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 244 行定义\&.
.SS "#define RTC_WAKEUPCLOCK_RTCCLK_DIV4   0x00000002U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 243 行定义\&.
.SS "#define RTC_WAKEUPCLOCK_RTCCLK_DIV8   0x00000001U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 242 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
