.TH "RTCEx_Tamper_Pins_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Pins_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TAMPER_1\fP   RTC_TAFCR_TAMP1E"
.br
.ti -1c
.RI "#define \fBRTC_TAMPER_2\fP   RTC_TAFCR_TAMP2E"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_TAMPER_1   RTC_TAFCR_TAMP1E"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 122 行定义\&.
.SS "#define RTC_TAMPER_2   RTC_TAFCR_TAMP2E"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 125 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
