.TH "RTCEx_Tamper_Sampling_Frequencies_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Sampling_Frequencies_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV32768\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV16384\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV8192\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV4096\fP   0x00000300U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV2048\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV1024\fP   0x00000500U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV512\fP   0x00000600U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV256\fP   0x00000700U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV1024   0x00000500U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 1024 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 196 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV16384   0x00000100U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 16384 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 188 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV2048   0x00000400U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 2048 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 194 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV256   0x00000700U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 256 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 200 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV32768   0x00000000U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 32768 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 186 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV4096   0x00000300U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 4096 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 192 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV512   0x00000600U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 512 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 198 行定义\&.
.SS "#define RTC_TAMPERSAMPLINGFREQ_RTCCLK_DIV8192   0x00000200U"
Each of the tamper inputs are sampled with a frequency = RTCCLK / 8192 
.br
 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 190 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
