.TH "RTCEx_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBRTC Backup Registers Definitions\fP"
.br
.ti -1c
.RI "\fBRTC TimeStamp Edges Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Pins Definitions\fP"
.br
.ti -1c
.RI "\fBRTC tamper Pins Selection\fP"
.br
.ti -1c
.RI "\fBRTC TimeStamp Pins Selection\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Triggers Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Filter Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Sampling Frequencies Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Pin Precharge Duration Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper TimeStamp On Tamper Detection Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Tamper Pull Up Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Wake\-up Timer Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Digital Calib Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Smooth Calib Period Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Smooth Calib Plus Pulses Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Add 1 Second Parameter Definitions\fP"
.br
.ti -1c
.RI "\fBRTC Calib Output Selection Definitions\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
