.TH "RTCEx_Tamper_Filter_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Filter_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TAMPERFILTER_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERFILTER_2SAMPLE\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERFILTER_4SAMPLE\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERFILTER_8SAMPLE\fP   0x00001800U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_TAMPERFILTER_2SAMPLE   0x00000800U"
Tamper is activated after 2 consecutive samples at the active level 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 173 行定义\&.
.SS "#define RTC_TAMPERFILTER_4SAMPLE   0x00001000U"
Tamper is activated after 4 consecutive samples at the active level 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 175 行定义\&.
.SS "#define RTC_TAMPERFILTER_8SAMPLE   0x00001800U"
Tamper is activated after 8 consecutive samples at the active level\&. 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 177 行定义\&.
.SS "#define RTC_TAMPERFILTER_DISABLE   0x00000000U"
Tamper filter is disabled 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 170 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
