.TH "RTCEx_Tamper_Pin_Precharge_Duration_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Pin_Precharge_Duration_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_TAMPERPRECHARGEDURATION_1RTCCLK\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPRECHARGEDURATION_2RTCCLK\fP   0x00002000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPRECHARGEDURATION_4RTCCLK\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPRECHARGEDURATION_8RTCCLK\fP   0x00006000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_TAMPERPRECHARGEDURATION_1RTCCLK   0x00000000U"
Tamper pins are pre-charged before sampling during 1 RTCCLK cycle 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 209 行定义\&.
.SS "#define RTC_TAMPERPRECHARGEDURATION_2RTCCLK   0x00002000U"
Tamper pins are pre-charged before sampling during 2 RTCCLK cycles 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 211 行定义\&.
.SS "#define RTC_TAMPERPRECHARGEDURATION_4RTCCLK   0x00004000U"
Tamper pins are pre-charged before sampling during 4 RTCCLK cycles 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 213 行定义\&.
.SS "#define RTC_TAMPERPRECHARGEDURATION_8RTCCLK   0x00006000U"
Tamper pins are pre-charged before sampling during 8 RTCCLK cycles 
.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 215 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
