.TH "RTCEx_Tamper_Timestamp" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Tamper_Timestamp
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_IT\fP()   (EXTI\->IMR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Enable interrupt on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_IT\fP()   (EXTI\->IMR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"
.br
.RI "Disable interrupt on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_EVENT\fP()   (EXTI\->EMR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Enable event on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_EVENT\fP()   (EXTI\->EMR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"
.br
.RI "Disable event on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_FALLING_EDGE\fP()   (EXTI\->FTSR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Enable falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_FALLING_EDGE\fP()   (EXTI\->FTSR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"
.br
.RI "Disable falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_RISING_EDGE\fP()   (EXTI\->RTSR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Enable rising edge trigger on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_RISING_EDGE\fP()   (EXTI\->RTSR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"
.br
.RI "Disable rising edge trigger on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_RISING_FALLING_EDGE\fP()"
.br
.RI "Enable rising & falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_RISING_FALLING_EDGE\fP()"
.br
.RI "Disable rising & falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. This parameter can be: "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_GET_FLAG\fP()   (EXTI\->PR & \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Check whether the RTC Tamper and Timestamp associated Exti line interrupt flag is set or not\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_CLEAR_FLAG\fP()   (EXTI\->PR = \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Clear the RTC Tamper and Timestamp associated Exti line flag\&. "
.ti -1c
.RI "#define \fB__HAL_RTC_TAMPER_TIMESTAMP_EXTI_GENERATE_SWIT\fP()   (EXTI\->SWIER |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"
.br
.RI "Generate a Software interrupt on the RTC Tamper and Timestamp associated Exti line "
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_CLEAR_FLAG()   (EXTI\->PR = \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Clear the RTC Tamper and Timestamp associated Exti line flag\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 725 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_EVENT()   (EXTI\->EMR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"

.PP
Disable event on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 672 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_FALLING_EDGE()   (EXTI\->FTSR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"

.PP
Disable falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 684 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_IT()   (EXTI\->IMR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"

.PP
Disable interrupt on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 660 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_RISING_EDGE()   (EXTI\->RTSR &= ~(\fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP))"

.PP
Disable rising edge trigger on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 696 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_RISING_FALLING_EDGE()"
\fB值:\fP
.PP
.nf
                                                                           do { __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_RISING_EDGE();\
                                                                           __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_FALLING_EDGE();\
                                                                         } while(0U)
.fi
.PP
Disable rising & falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. This parameter can be: 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 711 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_EVENT()   (EXTI\->EMR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Enable event on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 666 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_FALLING_EDGE()   (EXTI\->FTSR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Enable falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 678 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_IT()   (EXTI\->IMR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Enable interrupt on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 654 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_RISING_EDGE()   (EXTI\->RTSR |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Enable rising edge trigger on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 690 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_RISING_FALLING_EDGE()"
\fB值:\fP
.PP
.nf
                                                                          do { __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_RISING_EDGE();\
                                                                          __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_FALLING_EDGE(); \
                                                                        } while(0U)
.fi
.PP
Enable rising & falling edge trigger on the RTC Tamper and Timestamp associated Exti line\&. 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 702 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_GENERATE_SWIT()   (EXTI\->SWIER |= \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Generate a Software interrupt on the RTC Tamper and Timestamp associated Exti line 
.PP
\fB返回值\fP
.RS 4
\fINone\&.\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 731 行定义\&.
.SS "#define __HAL_RTC_TAMPER_TIMESTAMP_EXTI_GET_FLAG()   (EXTI\->PR & \fBRTC_EXTI_LINE_TAMPER_TIMESTAMP_EVENT\fP)"

.PP
Check whether the RTC Tamper and Timestamp associated Exti line interrupt flag is set or not\&. 
.PP
\fB返回值\fP
.RS 4
\fILine\fP Status\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 719 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
