.TH "RTCEx_Calib_Output_selection_Definitions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Calib_Output_selection_Definitions
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBRTC_CALIBOUTPUT_512HZ\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRTC_CALIBOUTPUT_1HZ\fP   0x00080000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define RTC_CALIBOUTPUT_1HZ   0x00080000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 299 行定义\&.
.SS "#define RTC_CALIBOUTPUT_512HZ   0x00000000U"

.PP
在文件 stm32f4xx_hal_rtc_ex\&.h 第 298 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
