.TH "RTCEx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTCEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_SetTimeStamp\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_SetTimeStamp_IT\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_DeactivateTimeStamp\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_GetTimeStamp\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_TimeTypeDef\fP *sTimeStamp, \fBRTC_DateTypeDef\fP *sTimeStampDate, uint32_t Format)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_SetTamper\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_TamperTypeDef\fP *sTamper)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_SetTamper_IT\fP (\fBRTC_HandleTypeDef\fP *hrtc, \fBRTC_TamperTypeDef\fP *sTamper)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_DeactivateTamper\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Tamper)"
.br
.ti -1c
.RI "void \fBHAL_RTCEx_TamperTimeStampIRQHandler\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "void \fBHAL_RTCEx_Tamper1EventCallback\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "void \fBHAL_RTCEx_Tamper2EventCallback\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "void \fBHAL_RTCEx_TimeStampEventCallback\fP (\fBRTC_HandleTypeDef\fP *hrtc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_PollForTimeStampEvent\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_PollForTamper1Event\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RTCEx_PollForTamper2Event\fP (\fBRTC_HandleTypeDef\fP *hrtc, uint32_t Timeout)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_DeactivateTamper (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Tamper)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_DeactivateTimeStamp (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_GetTimeStamp (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_TimeTypeDef\fP * sTimeStamp, \fBRTC_DateTypeDef\fP * sTimeStampDate, uint32_t Format)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_PollForTamper1Event (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_PollForTamper2Event (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_PollForTimeStampEvent (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_SetTamper (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_TamperTypeDef\fP * sTamper)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_SetTamper_IT (\fBRTC_HandleTypeDef\fP * hrtc, \fBRTC_TamperTypeDef\fP * sTamper)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_SetTimeStamp (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RTCEx_SetTimeStamp_IT (\fBRTC_HandleTypeDef\fP * hrtc, uint32_t TimeStampEdge, uint32_t RTC_TimeStampPin)"

.SS "void HAL_RTCEx_Tamper1EventCallback (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "void HAL_RTCEx_Tamper2EventCallback (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "void HAL_RTCEx_TamperTimeStampIRQHandler (\fBRTC_HandleTypeDef\fP * hrtc)"

.SS "void HAL_RTCEx_TimeStampEventCallback (\fBRTC_HandleTypeDef\fP * hrtc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
