.TH "SMARTCARD_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBSMARTCARD Error Code\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Word Length\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Number of Stop Bits\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Parity\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Mode\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Clock Polarity\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Clock Phase\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Last Bit\fP"
.br
.ti -1c
.RI "\fBSMARTCARD NACK State\fP"
.br
.ti -1c
.RI "\fBSMARTCARD DMA requests\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Prescaler\fP"
.br
.ti -1c
.RI "\fBSMARTCARD Flags\fP"
.br
.RI "Elements values convention: 0xXXXX "
.ti -1c
.RI "\fBSMARTCARD Interrupts Definition\fP"
.br
.RI "Elements values convention: 0xY000XXXX "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
