.TH "SMARTCARD_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_SMARTCARD_StateTypeDef\fP \fBHAL_SMARTCARD_GetState\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SMARTCARD_GetError\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_SMARTCARD_GetError (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SS "\fBHAL_SMARTCARD_StateTypeDef\fP HAL_SMARTCARD_GetState (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
