.TH "SMARTCARD_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Init\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_ReInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_DeInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_MspInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_MspDeInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_SMARTCARD_DeInit (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_SMARTCARD_Init (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SS "void HAL_SMARTCARD_MspDeInit (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SS "void HAL_SMARTCARD_MspInit (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_SMARTCARD_ReInit (\fBSMARTCARD_HandleTypeDef\fP * hsc)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
