.TH "SMARTCARD_Prescaler" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV4\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV6\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV8\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV10\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV12\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV14\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV16\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV18\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV20\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV22\fP   0x0000000BU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV24\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV26\fP   0x0000000DU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV28\fP   0x0000000EU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV30\fP   0x0000000FU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV32\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV34\fP   0x00000011U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV36\fP   0x00000012U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV38\fP   0x00000013U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV40\fP   0x00000014U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV42\fP   0x00000015U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV44\fP   0x00000016U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV46\fP   0x00000017U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV48\fP   0x00000018U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV50\fP   0x00000019U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV52\fP   0x0000001AU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV54\fP   0x0000001BU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV56\fP   0x0000001CU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV58\fP   0x0000001DU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV60\fP   0x0000001EU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV62\fP   0x0000001FU"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV10   0x00000005U"
SYSCLK divided by 10 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 346 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV12   0x00000006U"
SYSCLK divided by 12 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 347 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV14   0x00000007U"
SYSCLK divided by 14 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 348 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV16   0x00000008U"
SYSCLK divided by 16 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 349 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV18   0x00000009U"
SYSCLK divided by 18 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 350 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV2   0x00000001U"
SYSCLK divided by 2 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 342 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV20   0x0000000AU"
SYSCLK divided by 20 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 351 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV22   0x0000000BU"
SYSCLK divided by 22 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 352 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV24   0x0000000CU"
SYSCLK divided by 24 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 353 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV26   0x0000000DU"
SYSCLK divided by 26 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 354 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV28   0x0000000EU"
SYSCLK divided by 28 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 355 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV30   0x0000000FU"
SYSCLK divided by 30 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 356 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV32   0x00000010U"
SYSCLK divided by 32 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 357 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV34   0x00000011U"
SYSCLK divided by 34 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 358 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV36   0x00000012U"
SYSCLK divided by 36 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 359 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV38   0x00000013U"
SYSCLK divided by 38 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 360 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV4   0x00000002U"
SYSCLK divided by 4 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 343 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV40   0x00000014U"
SYSCLK divided by 40 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 361 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV42   0x00000015U"
SYSCLK divided by 42 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 362 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV44   0x00000016U"
SYSCLK divided by 44 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 363 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV46   0x00000017U"
SYSCLK divided by 46 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 364 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV48   0x00000018U"
SYSCLK divided by 48 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 365 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV50   0x00000019U"
SYSCLK divided by 50 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 366 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV52   0x0000001AU"
SYSCLK divided by 52 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 367 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV54   0x0000001BU"
SYSCLK divided by 54 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 368 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV56   0x0000001CU"
SYSCLK divided by 56 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 369 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV58   0x0000001DU"
SYSCLK divided by 58 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 370 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV6   0x00000003U"
SYSCLK divided by 6 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 344 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV60   0x0000001EU"
SYSCLK divided by 60 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 371 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV62   0x0000001FU"
SYSCLK divided by 62 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 372 行定义\&.
.SS "#define SMARTCARD_PRESCALER_SYSCLK_DIV8   0x00000004U"
SYSCLK divided by 8 
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 345 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
