.TH "SMARTCARD_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_SMARTCARD_WORD_LENGTH\fP(LENGTH)   ((LENGTH) == \fBSMARTCARD_WORDLENGTH_9B\fP)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_STOPBITS\fP(STOPBITS)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_PARITY\fP(PARITY)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_MODE\fP(MODE)   ((((MODE) & 0x0000FFF3U) == 0x00U) && ((MODE) != 0x000000U))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_POLARITY\fP(CPOL)   (((CPOL) == \fBSMARTCARD_POLARITY_LOW\fP) || ((CPOL) == \fBSMARTCARD_POLARITY_HIGH\fP))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_PHASE\fP(CPHA)   (((CPHA) == \fBSMARTCARD_PHASE_1EDGE\fP) || ((CPHA) == \fBSMARTCARD_PHASE_2EDGE\fP))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_LASTBIT\fP(LASTBIT)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_NACK_STATE\fP(NACK)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_BAUDRATE\fP(BAUDRATE)   ((BAUDRATE) < 10500001U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIV\fP(__PCLK__,  __BAUD__)   (((__PCLK__)*25U)/(4U*(__BAUD__)))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIVMANT\fP(__PCLK__,  __BAUD__)   (\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__))/100U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIVFRAQ\fP(__PCLK__,  __BAUD__)   (((\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__)) \- (\fBSMARTCARD_DIVMANT\fP((__PCLK__), (__BAUD__)) * 100U)) * 16U + 50U) / 100U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_BRR\fP(__PCLK__,  __BAUD__)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_SMARTCARD_BAUDRATE(BAUDRATE)   ((BAUDRATE) < 10500001U)"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 720 行定义\&.
.SS "#define IS_SMARTCARD_LASTBIT(LASTBIT)"
\fB值:\fP
.PP
.nf
                                             (((LASTBIT) == SMARTCARD_LASTBIT_DISABLE) || \
                                             ((LASTBIT) == SMARTCARD_LASTBIT_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 716 行定义\&.
.SS "#define IS_SMARTCARD_MODE(MODE)   ((((MODE) & 0x0000FFF3U) == 0x00U) && ((MODE) != 0x000000U))"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 713 行定义\&.
.SS "#define IS_SMARTCARD_NACK_STATE(NACK)"
\fB值:\fP
.PP
.nf
                                             (((NACK) == SMARTCARD_NACK_ENABLE) || \
                                             ((NACK) == SMARTCARD_NACK_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 718 行定义\&.
.SS "#define IS_SMARTCARD_PARITY(PARITY)"
\fB值:\fP
.PP
.nf
                                             (((PARITY) == SMARTCARD_PARITY_EVEN) || \
                                             ((PARITY) == SMARTCARD_PARITY_ODD))
.fi
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 711 行定义\&.
.SS "#define IS_SMARTCARD_PHASE(CPHA)   (((CPHA) == \fBSMARTCARD_PHASE_1EDGE\fP) || ((CPHA) == \fBSMARTCARD_PHASE_2EDGE\fP))"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 715 行定义\&.
.SS "#define IS_SMARTCARD_POLARITY(CPOL)   (((CPOL) == \fBSMARTCARD_POLARITY_LOW\fP) || ((CPOL) == \fBSMARTCARD_POLARITY_HIGH\fP))"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 714 行定义\&.
.SS "#define IS_SMARTCARD_STOPBITS(STOPBITS)"
\fB值:\fP
.PP
.nf
                                             (((STOPBITS) == SMARTCARD_STOPBITS_0_5) || \
                                             ((STOPBITS) == SMARTCARD_STOPBITS_1_5))
.fi
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 709 行定义\&.
.SS "#define IS_SMARTCARD_WORD_LENGTH(LENGTH)   ((LENGTH) == \fBSMARTCARD_WORDLENGTH_9B\fP)"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 708 行定义\&.
.SS "#define SMARTCARD_BRR(__PCLK__, __BAUD__)"
\fB值:\fP
.PP
.nf
                                                 (((SMARTCARD_DIVMANT((__PCLK__), (__BAUD__)) << 4U) + \
                                                 (SMARTCARD_DIVFRAQ((__PCLK__), (__BAUD__)) & 0xF0U)) + \
                                                 (SMARTCARD_DIVFRAQ((__PCLK__), (__BAUD__)) & 0x0FU))
.fi
.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 727 行定义\&.
.SS "#define SMARTCARD_DIV(__PCLK__, __BAUD__)   (((__PCLK__)*25U)/(4U*(__BAUD__)))"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 722 行定义\&.
.SS "#define SMARTCARD_DIVFRAQ(__PCLK__, __BAUD__)   (((\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__)) \- (\fBSMARTCARD_DIVMANT\fP((__PCLK__), (__BAUD__)) * 100U)) * 16U + 50U) / 100U)"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 724 行定义\&.
.SS "#define SMARTCARD_DIVMANT(__PCLK__, __BAUD__)   (\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__))/100U)"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 723 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
