.TH "SMARTCARD_NACK_State" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMARTCARD_NACK_State
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMARTCARD_NACK_ENABLE\fP   ((uint32_t)USART_CR3_NACK)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_NACK_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMARTCARD_NACK_DISABLE   0x00000000U"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 325 行定义\&.
.SS "#define SMARTCARD_NACK_ENABLE   ((uint32_t)USART_CR3_NACK)"

.PP
在文件 stm32f4xx_hal_smartcard\&.h 第 324 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
