.TH "SMBUS_IRQ_Handler_and_Callbacks" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_IRQ_Handler_and_Callbacks
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_SMBUS_EV_IRQHandler\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_ER_IRQHandler\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_MasterTxCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_MasterRxCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_SlaveTxCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_SlaveRxCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_AddrCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus, uint8_t TransferDirection, uint16_t AddrMatchCode)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_ListenCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_ErrorCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_AbortCpltCallback\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void HAL_SMBUS_AbortCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_AddrCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus, uint8_t TransferDirection, uint16_t AddrMatchCode)"

.SS "void HAL_SMBUS_ER_IRQHandler (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_ErrorCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_EV_IRQHandler (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_ListenCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_MasterRxCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_MasterTxCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_SlaveRxCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_SlaveTxCpltCallback (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
