.TH "SMBUS_Flag_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_Flag_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_FLAG_SMBALERT\fP   0x00018000U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_TIMEOUT\fP   0x00014000U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_PECERR\fP   0x00011000U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_OVR\fP   0x00010800U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_AF\fP   0x00010400U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_ARLO\fP   0x00010200U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_BERR\fP   0x00010100U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_TXE\fP   0x00010080U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_RXNE\fP   0x00010040U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_STOPF\fP   0x00010010U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_ADD10\fP   0x00010008U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_BTF\fP   0x00010004U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_ADDR\fP   0x00010002U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_SB\fP   0x00010001U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_DUALF\fP   0x00100080U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_SMBHOST\fP   0x00100040U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_SMBDEFAULT\fP   0x00100020U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_GENCALL\fP   0x00100010U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_TRA\fP   0x00100004U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_BUSY\fP   0x00100002U"
.br
.ti -1c
.RI "#define \fBSMBUS_FLAG_MSL\fP   0x00100001U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMBUS_FLAG_ADD10   0x00010008U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 366 行定义\&.
.SS "#define SMBUS_FLAG_ADDR   0x00010002U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 368 行定义\&.
.SS "#define SMBUS_FLAG_AF   0x00010400U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 360 行定义\&.
.SS "#define SMBUS_FLAG_ARLO   0x00010200U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 361 行定义\&.
.SS "#define SMBUS_FLAG_BERR   0x00010100U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 362 行定义\&.
.SS "#define SMBUS_FLAG_BTF   0x00010004U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 367 行定义\&.
.SS "#define SMBUS_FLAG_BUSY   0x00100002U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 375 行定义\&.
.SS "#define SMBUS_FLAG_DUALF   0x00100080U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 370 行定义\&.
.SS "#define SMBUS_FLAG_GENCALL   0x00100010U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 373 行定义\&.
.SS "#define SMBUS_FLAG_MSL   0x00100001U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 376 行定义\&.
.SS "#define SMBUS_FLAG_OVR   0x00010800U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 359 行定义\&.
.SS "#define SMBUS_FLAG_PECERR   0x00011000U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 358 行定义\&.
.SS "#define SMBUS_FLAG_RXNE   0x00010040U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 364 行定义\&.
.SS "#define SMBUS_FLAG_SB   0x00010001U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 369 行定义\&.
.SS "#define SMBUS_FLAG_SMBALERT   0x00018000U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 356 行定义\&.
.SS "#define SMBUS_FLAG_SMBDEFAULT   0x00100020U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 372 行定义\&.
.SS "#define SMBUS_FLAG_SMBHOST   0x00100040U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 371 行定义\&.
.SS "#define SMBUS_FLAG_STOPF   0x00010010U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 365 行定义\&.
.SS "#define SMBUS_FLAG_TIMEOUT   0x00014000U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 357 行定义\&.
.SS "#define SMBUS_FLAG_TRA   0x00100004U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 374 行定义\&.
.SS "#define SMBUS_FLAG_TXE   0x00010080U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 363 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
