.TH "SMBUS_Analog_Filter" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_Analog_Filter
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_ENABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_DISABLE\fP   I2C_FLTR_ANOFF"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMBUS_ANALOGFILTER_DISABLE   I2C_FLTR_ANOFF"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 261 行定义\&.
.SS "#define SMBUS_ANALOGFILTER_ENABLE   0x00000000U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 260 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
