.TH "SMBUS_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBSMBUS Error Code\fP"
.br
.RI "SMBUS Error Code "
.ti -1c
.RI "\fBSMBUS Analog Filter\fP"
.br
.ti -1c
.RI "\fBSMBUS addressing mode\fP"
.br
.ti -1c
.RI "\fBSMBUS dual addressing mode\fP"
.br
.ti -1c
.RI "\fBSMBUS general call addressing mode\fP"
.br
.ti -1c
.RI "\fBSMBUS nostretch mode\fP"
.br
.ti -1c
.RI "\fBSMBUS packet error check mode\fP"
.br
.ti -1c
.RI "\fBSMBUS peripheral mode\fP"
.br
.ti -1c
.RI "\fBSMBUS XferDirection definition\fP"
.br
.ti -1c
.RI "\fBSMBUS XferOptions definition\fP"
.br
.ti -1c
.RI "\fBSMBUS Interrupt configuration definition\fP"
.br
.ti -1c
.RI "\fBSMBUS Flag definition\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
