.TH "SMBUS_XferOptions_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_XferOptions_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_FIRST_FRAME\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBSMBUS_NEXT_FRAME\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBSMBUS_FIRST_AND_LAST_FRAME_NO_PEC\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBSMBUS_LAST_FRAME_NO_PEC\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBSMBUS_FIRST_AND_LAST_FRAME_WITH_PEC\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBSMBUS_LAST_FRAME_WITH_PEC\fP   0x00000006U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMBUS_FIRST_AND_LAST_FRAME_NO_PEC   0x00000003U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 335 行定义\&.
.SS "#define SMBUS_FIRST_AND_LAST_FRAME_WITH_PEC   0x00000005U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 337 行定义\&.
.SS "#define SMBUS_FIRST_FRAME   0x00000001U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 333 行定义\&.
.SS "#define SMBUS_LAST_FRAME_NO_PEC   0x00000004U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 336 行定义\&.
.SS "#define SMBUS_LAST_FRAME_WITH_PEC   0x00000006U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 338 行定义\&.
.SS "#define SMBUS_NEXT_FRAME   0x00000002U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 334 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
