.TH "SMBUS_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMBUS_Init\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMBUS_DeInit\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_MspInit\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "void \fBHAL_SMBUS_MspDeInit\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_SMBUS_DeInit (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "\fBHAL_StatusTypeDef\fP HAL_SMBUS_Init (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_MspDeInit (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "void HAL_SMBUS_MspInit (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
