.TH "SMBUS_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_InitTypeDef \- SMBUS Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_smbus\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBClockSpeed\fP"
.br
.ti -1c
.RI "uint32_t \fBAnalogFilter\fP"
.br
.ti -1c
.RI "uint32_t \fBOwnAddress1\fP"
.br
.ti -1c
.RI "uint32_t \fBAddressingMode\fP"
.br
.ti -1c
.RI "uint32_t \fBDualAddressMode\fP"
.br
.ti -1c
.RI "uint32_t \fBOwnAddress2\fP"
.br
.ti -1c
.RI "uint32_t \fBGeneralCallMode\fP"
.br
.ti -1c
.RI "uint32_t \fBNoStretchMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPacketErrorCheckMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPeripheralMode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
SMBUS Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AddressingMode"
Specifies if 7-bit or 10-bit addressing mode is selected\&. This parameter can be a value of \fBSMBUS addressing mode\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 58 行定义\&.
.SS "uint32_t AnalogFilter"
Specifies if Analog Filter is enable or not\&. This parameter can be a value of \fBSMBUS Analog Filter\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 52 行定义\&.
.SS "uint32_t ClockSpeed"
Specifies the clock frequency\&. This parameter must be set to a value lower than 100kHz 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 49 行定义\&.
.SS "uint32_t DualAddressMode"
Specifies if dual addressing mode is selected\&. This parameter can be a value of \fBSMBUS dual addressing mode\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 61 行定义\&.
.SS "uint32_t GeneralCallMode"
Specifies if general call mode is selected\&. This parameter can be a value of \fBSMBUS general call addressing mode\fP 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 67 行定义\&.
.SS "uint32_t NoStretchMode"
Specifies if nostretch mode is selected\&. This parameter can be a value of \fBSMBUS nostretch mode\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 70 行定义\&.
.SS "uint32_t OwnAddress1"
Specifies the first device own address\&. This parameter can be a 7-bit or 10-bit address\&. 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 55 行定义\&.
.SS "uint32_t OwnAddress2"
Specifies the second device own address if dual addressing mode is selected\&. This parameter can be a 7-bit address\&. 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 64 行定义\&.
.SS "uint32_t PacketErrorCheckMode"
Specifies if Packet Error Check mode is selected\&. This parameter can be a value of \fBSMBUS packet error check mode\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 73 行定义\&.
.SS "uint32_t PeripheralMode"
Specifies which mode of Periphal is selected\&. This parameter can be a value of \fBSMBUS peripheral mode\fP 
.br
 
.PP
在文件 stm32f4xx_hal_smbus\&.h 第 76 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
