.TH "SMBUS_addressing_mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_addressing_mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_ADDRESSINGMODE_7BIT\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBSMBUS_ADDRESSINGMODE_10BIT\fP   (I2C_OAR1_ADDMODE | 0x00004000U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SMBUS_ADDRESSINGMODE_10BIT   (I2C_OAR1_ADDMODE | 0x00004000U)"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 270 行定义\&.
.SS "#define SMBUS_ADDRESSINGMODE_7BIT   0x00004000U"

.PP
在文件 stm32f4xx_hal_smbus\&.h 第 269 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
