.TH "SMBUS_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMBUS_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_SMBUS_StateTypeDef\fP \fBHAL_SMBUS_GetState\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "\fBHAL_SMBUS_ModeTypeDef\fP \fBHAL_SMBUS_GetMode\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SMBUS_GetError\fP (\fBSMBUS_HandleTypeDef\fP *hsmbus)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_SMBUS_GetError (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "\fBHAL_SMBUS_ModeTypeDef\fP HAL_SMBUS_GetMode (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SS "\fBHAL_SMBUS_StateTypeDef\fP HAL_SMBUS_GetState (\fBSMBUS_HandleTypeDef\fP * hsmbus)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
