.TH "SPI_Error_Code" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Error_Code
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_NONE\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_MODF\fP   (0x00000001U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_CRC\fP   (0x00000002U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_OVR\fP   (0x00000004U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_FRE\fP   (0x00000008U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_DMA\fP   (0x00000010U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_FLAG\fP   (0x00000020U)"
.br
.ti -1c
.RI "#define \fBHAL_SPI_ERROR_ABORT\fP   (0x00000040U)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define HAL_SPI_ERROR_ABORT   (0x00000040U)"
Error during SPI Abort procedure 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 197 行定义\&.
.SS "#define HAL_SPI_ERROR_CRC   (0x00000002U)"
CRC error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 192 行定义\&.
.SS "#define HAL_SPI_ERROR_DMA   (0x00000010U)"
DMA transfer error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 195 行定义\&.
.SS "#define HAL_SPI_ERROR_FLAG   (0x00000020U)"
Error on RXNE/TXE/BSY Flag 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 196 行定义\&.
.SS "#define HAL_SPI_ERROR_FRE   (0x00000008U)"
FRE error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 194 行定义\&.
.SS "#define HAL_SPI_ERROR_MODF   (0x00000001U)"
MODF error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 191 行定义\&.
.SS "#define HAL_SPI_ERROR_NONE   (0x00000000U)"
No error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 190 行定义\&.
.SS "#define HAL_SPI_ERROR_OVR   (0x00000004U)"
OVR error 
.br
 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 193 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
