.TH "SPI_BaudRate_Prescaler" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_BaudRate_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_2\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_4\fP   (SPI_CR1_BR_0)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_8\fP   (SPI_CR1_BR_1)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_16\fP   (SPI_CR1_BR_1 | SPI_CR1_BR_0)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_32\fP   (SPI_CR1_BR_2)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_64\fP   (SPI_CR1_BR_2 | SPI_CR1_BR_0)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_128\fP   (SPI_CR1_BR_2 | SPI_CR1_BR_1)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_256\fP   (SPI_CR1_BR_2 | SPI_CR1_BR_1 | SPI_CR1_BR_0)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SPI_BAUDRATEPRESCALER_128   (SPI_CR1_BR_2 | SPI_CR1_BR_1)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 270 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_16   (SPI_CR1_BR_1 | SPI_CR1_BR_0)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 267 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_2   (0x00000000U)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 264 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_256   (SPI_CR1_BR_2 | SPI_CR1_BR_1 | SPI_CR1_BR_0)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 271 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_32   (SPI_CR1_BR_2)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 268 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_4   (SPI_CR1_BR_0)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 265 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_64   (SPI_CR1_BR_2 | SPI_CR1_BR_0)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 269 行定义\&.
.SS "#define SPI_BAUDRATEPRESCALER_8   (SPI_CR1_BR_1)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 266 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
