.TH "SPI_Interrupt_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Interrupt_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSPI_IT_TXE\fP   SPI_CR2_TXEIE"
.br
.ti -1c
.RI "#define \fBSPI_IT_RXNE\fP   SPI_CR2_RXNEIE"
.br
.ti -1c
.RI "#define \fBSPI_IT_ERR\fP   SPI_CR2_ERRIE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SPI_IT_ERR   SPI_CR2_ERRIE"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 308 行定义\&.
.SS "#define SPI_IT_RXNE   SPI_CR2_RXNEIE"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 307 行定义\&.
.SS "#define SPI_IT_TXE   SPI_CR2_TXEIE"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 306 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
