.TH "SPI_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_InitTypeDef \- SPI Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_spi\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBMode\fP"
.br
.ti -1c
.RI "uint32_t \fBDirection\fP"
.br
.ti -1c
.RI "uint32_t \fBDataSize\fP"
.br
.ti -1c
.RI "uint32_t \fBCLKPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBCLKPhase\fP"
.br
.ti -1c
.RI "uint32_t \fBNSS\fP"
.br
.ti -1c
.RI "uint32_t \fBBaudRatePrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBFirstBit\fP"
.br
.ti -1c
.RI "uint32_t \fBTIMode\fP"
.br
.ti -1c
.RI "uint32_t \fBCRCCalculation\fP"
.br
.ti -1c
.RI "uint32_t \fBCRCPolynomial\fP"
.br
.in -1c
.SH "详细描述"
.PP 
SPI Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t BaudRatePrescaler"
Specifies the Baud Rate prescaler value which will be used to configure the transmit and receive SCK clock\&. This parameter can be a value of \fBSPI BaudRate Prescaler\fP 
.PP
\fB注解\fP
.RS 4
The communication clock is derived from the master clock\&. The slave clock does not need to be set\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_spi\&.h 第 68 行定义\&.
.SS "uint32_t CLKPhase"
Specifies the clock active edge for the bit capture\&. This parameter can be a value of \fBSPI Clock Phase\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 61 行定义\&.
.SS "uint32_t CLKPolarity"
Specifies the serial clock steady state\&. This parameter can be a value of \fBSPI Clock Polarity\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 58 行定义\&.
.SS "uint32_t CRCCalculation"
Specifies if the CRC calculation is enabled or not\&. This parameter can be a value of \fBSPI CRC Calculation\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 80 行定义\&.
.SS "uint32_t CRCPolynomial"
Specifies the polynomial used for the CRC calculation\&. This parameter must be an odd number between Min_Data = 1 and Max_Data = 65535 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 83 行定义\&.
.SS "uint32_t DataSize"
Specifies the SPI data size\&. This parameter can be a value of \fBSPI Data Size\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 55 行定义\&.
.SS "uint32_t Direction"
Specifies the SPI bidirectional mode state\&. This parameter can be a value of \fBSPI Direction Mode\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 52 行定义\&.
.SS "uint32_t FirstBit"
Specifies whether data transfers start from MSB or LSB bit\&. This parameter can be a value of \fBSPI MSB LSB Transmission\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 74 行定义\&.
.SS "uint32_t Mode"
Specifies the SPI operating mode\&. This parameter can be a value of \fBSPI Mode\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 49 行定义\&.
.SS "uint32_t NSS"
Specifies whether the NSS signal is managed by hardware (NSS pin) or by software using the SSI bit\&. This parameter can be a value of \fBSPI Slave Select Management\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 64 行定义\&.
.SS "uint32_t TIMode"
Specifies if the TI mode is enabled or not\&. This parameter can be a value of \fBSPI TI Mode\fP 
.PP
在文件 stm32f4xx_hal_spi\&.h 第 77 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
