.TH "SPI_Direction" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Direction
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBSPI_DIRECTION_2LINES\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_DIRECTION_2LINES_RXONLY\fP   SPI_CR1_RXONLY"
.br
.ti -1c
.RI "#define \fBSPI_DIRECTION_1LINE\fP   SPI_CR1_BIDIMODE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define SPI_DIRECTION_1LINE   SPI_CR1_BIDIMODE"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 219 行定义\&.
.SS "#define SPI_DIRECTION_2LINES   (0x00000000U)"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 217 行定义\&.
.SS "#define SPI_DIRECTION_2LINES_RXONLY   SPI_CR1_RXONLY"

.PP
在文件 stm32f4xx_hal_spi\&.h 第 218 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
