.TH "inc/stm32f4xx_ll_utils.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_ll_utils.h \- Header file of UTILS LL module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBLL_UTILS_PLLInitTypeDef\fP"
.br
.RI "UTILS PLL structure definition "
.ti -1c
.RI "struct \fBLL_UTILS_ClkInitTypeDef\fP"
.br
.RI "UTILS System, AHB and APB buses clock configuration structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLL_MAX_DELAY\fP   0xFFFFFFFFU"
.br
.ti -1c
.RI "#define \fBUID_BASE_ADDRESS\fP   UID_BASE"
.br
.RI "Unique device ID register base address "
.ti -1c
.RI "#define \fBFLASHSIZE_BASE_ADDRESS\fP   FLASHSIZE_BASE"
.br
.RI "Flash size data register base address "
.ti -1c
.RI "#define \fBPACKAGE_BASE_ADDRESS\fP   PACKAGE_BASE"
.br
.RI "Package data register base address "
.ti -1c
.RI "#define \fBLL_UTILS_HSEBYPASS_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_HSEBYPASS_ON\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_WLCSP36_UFQFPN48_LQFP64\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_WLCSP168_FBGA169_LQFP100_LQFP64_UFQFPN48\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_WLCSP64_WLCSP81_LQFP176_UFBGA176\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_LQFP144_UFBGA144_UFBGA144_UFBGA100\fP   0x00000300U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_LQFP100_LQFP208_TFBGA216\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_LQFP208_TFBGA216\fP   0x00000500U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_PACKAGETYPE_TQFP64_UFBGA144_LQFP144\fP   0x00000700U"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_GetUID_Word0\fP (void)"
.br
.RI "Get Word0 of the unique device identifier (UID based on 96 bits) "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_GetUID_Word1\fP (void)"
.br
.RI "Get Word1 of the unique device identifier (UID based on 96 bits) "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_GetUID_Word2\fP (void)"
.br
.RI "Get Word2 of the unique device identifier (UID based on 96 bits) "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_GetFlashSize\fP (void)"
.br
.RI "Get Flash memory size "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fBLL_GetPackageType\fP (void)"
.br
.RI "Get Package type "
.ti -1c
.RI "__STATIC_INLINE void \fBLL_InitTick\fP (uint32_t HCLKFrequency, uint32_t Ticks)"
.br
.RI "This function configures the Cortex-M SysTick source of the time base\&. "
.ti -1c
.RI "void \fBLL_Init1msTick\fP (uint32_t HCLKFrequency)"
.br
.RI "This function configures the Cortex-M SysTick source to have 1ms time base\&. "
.ti -1c
.RI "void \fBLL_mDelay\fP (uint32_t Delay)"
.br
.RI "This function provides accurate delay (in milliseconds) based on SysTick counter flag "
.ti -1c
.RI "void \fBLL_SetSystemCoreClock\fP (uint32_t HCLKFrequency)"
.br
.RI "This function sets directly SystemCoreClock CMSIS variable\&. "
.ti -1c
.RI "ErrorStatus \fBLL_PLL_ConfigSystemClock_HSI\fP (\fBLL_UTILS_PLLInitTypeDef\fP *UTILS_PLLInitStruct, \fBLL_UTILS_ClkInitTypeDef\fP *UTILS_ClkInitStruct)"
.br
.RI "This function configures system clock at maximum frequency with HSI as clock source of the PLL "
.ti -1c
.RI "ErrorStatus \fBLL_PLL_ConfigSystemClock_HSE\fP (uint32_t HSEFrequency, uint32_t HSEBypass, \fBLL_UTILS_PLLInitTypeDef\fP *UTILS_PLLInitStruct, \fBLL_UTILS_ClkInitTypeDef\fP *UTILS_ClkInitStruct)"
.br
.RI "This function configures system clock with HSE as clock source of the PLL "
.in -1c
.SH "详细描述"
.PP 
Header file of UTILS LL module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.PP
.nf
==============================================================================
                   ##### How to use this driver #####
==============================================================================
  [..]
  The LL UTILS driver contains a set of generic APIs that can be
  used by user:
    (+) Device electronic signature
    (+) Timing functions
    (+) PLL configuration functions
.fi
.PP
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_ll_utils\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
