.TH "inc/stm32f4xx_hal_tim_ex.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_tim_ex.h \- Header file of TIM HAL Extended module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBTIM_HallSensor_InitTypeDef\fP"
.br
.RI "TIM Hall sensor Configuration Structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_TIM5_GPIO\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TIM5_LSI\fP   TIM_OR_TI4_RMP_0"
.br
.ti -1c
.RI "#define \fBTIM_TIM5_LSE\fP   TIM_OR_TI4_RMP_1"
.br
.ti -1c
.RI "#define \fBTIM_TIM5_RTC\fP   (TIM_OR_TI4_RMP_1 | TIM_OR_TI4_RMP_0)"
.br
.ti -1c
.RI "#define \fBTIM_TIM11_GPIO\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TIM11_HSE\fP   TIM_OR_TI1_RMP_1"
.br
.ti -1c
.RI "#define \fBIS_TIM_REMAP\fP(INSTANCE,  TIM_REMAP)"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Init\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_HallSensor_InitTypeDef\fP *sConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_DeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_HallSensor_MspInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_HallSensor_MspDeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_PWMN_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_MasterConfigSynchronization\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_MasterConfigTypeDef\fP *sMasterConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigBreakDeadTime\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_BreakDeadTimeConfigTypeDef\fP *sBreakDeadTimeConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_RemapConfig\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Remap)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_CommutCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_CommutHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_BreakCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIMEx_HallSensor_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBTIMEx_DMACommutationCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIMEx_DMACommutationHalfCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of TIM HAL Extended module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_tim_ex\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
