.TH "inc/stm32f4xx_hal_cortex.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_cortex.h \- Header file of CORTEX HAL module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_0\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_1\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_2\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_3\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBNVIC_PRIORITYGROUP_4\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBSYSTICK_CLKSOURCE_HCLK_DIV8\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSYSTICK_CLKSOURCE_HCLK\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBIS_NVIC_PRIORITY_GROUP\fP(GROUP)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_PREEMPTION_PRIORITY\fP(PRIORITY)   ((PRIORITY) < 0x10U)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_SUB_PRIORITY\fP(PRIORITY)   ((PRIORITY) < 0x10U)"
.br
.ti -1c
.RI "#define \fBIS_NVIC_DEVICE_IRQ\fP(IRQ)   ((IRQ) >= (IRQn_Type)0x00U)"
.br
.ti -1c
.RI "#define \fBIS_SYSTICK_CLK_SOURCE\fP(SOURCE)"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_NVIC_SetPriorityGrouping\fP (uint32_t PriorityGroup)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SetPriority\fP (IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_EnableIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_DisableIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SystemReset\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SYSTICK_Config\fP (uint32_t TicksNumb)"
.br
.ti -1c
.RI "uint32_t \fBHAL_NVIC_GetPriorityGrouping\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_GetPriority\fP (IRQn_Type IRQn, uint32_t PriorityGroup, uint32_t *pPreemptPriority, uint32_t *pSubPriority)"
.br
.ti -1c
.RI "uint32_t \fBHAL_NVIC_GetPendingIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SetPendingIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_ClearPendingIRQ\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "uint32_t \fBHAL_NVIC_GetActive\fP (IRQn_Type IRQn)"
.br
.ti -1c
.RI "void \fBHAL_SYSTICK_CLKSourceConfig\fP (uint32_t CLKSource)"
.br
.ti -1c
.RI "void \fBHAL_SYSTICK_IRQHandler\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SYSTICK_Callback\fP (void)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of CORTEX HAL module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_cortex\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
