.TH "inc/stm32f4xx_hal_smartcard.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_smartcard.h \- Header file of SMARTCARD HAL module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBSMARTCARD_InitTypeDef\fP"
.br
.RI "SMARTCARD Init Structure definition "
.ti -1c
.RI "struct \fB__SMARTCARD_HandleTypeDef\fP"
.br
.RI "SMARTCARD handle Structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_PE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_NE\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_FE\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_ORE\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBHAL_SMARTCARD_ERROR_DMA\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_WORDLENGTH_9B\fP   ((uint32_t)USART_CR1_M)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_STOPBITS_0_5\fP   ((uint32_t)USART_CR2_STOP_0)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_STOPBITS_1_5\fP   ((uint32_t)(USART_CR2_STOP_0 | USART_CR2_STOP_1))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PARITY_EVEN\fP   ((uint32_t)USART_CR1_PCE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PARITY_ODD\fP   ((uint32_t)(USART_CR1_PCE | USART_CR1_PS))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_MODE_RX\fP   ((uint32_t)USART_CR1_RE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_MODE_TX\fP   ((uint32_t)USART_CR1_TE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_MODE_TX_RX\fP   ((uint32_t)(USART_CR1_TE |USART_CR1_RE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_POLARITY_LOW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_POLARITY_HIGH\fP   ((uint32_t)USART_CR2_CPOL)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PHASE_1EDGE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PHASE_2EDGE\fP   ((uint32_t)USART_CR2_CPHA)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_ENABLE\fP   ((uint32_t)USART_CR2_LBCL)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_NACK_ENABLE\fP   ((uint32_t)USART_CR3_NACK)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_NACK_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DMAREQ_TX\fP   ((uint32_t)USART_CR3_DMAT)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DMAREQ_RX\fP   ((uint32_t)USART_CR3_DMAR)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV4\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV6\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV8\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV10\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV12\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV14\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV16\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV18\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV20\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV22\fP   0x0000000BU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV24\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV26\fP   0x0000000DU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV28\fP   0x0000000EU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV30\fP   0x0000000FU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV32\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV34\fP   0x00000011U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV36\fP   0x00000012U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV38\fP   0x00000013U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV40\fP   0x00000014U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV42\fP   0x00000015U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV44\fP   0x00000016U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV46\fP   0x00000017U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV48\fP   0x00000018U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV50\fP   0x00000019U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV52\fP   0x0000001AU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV54\fP   0x0000001BU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV56\fP   0x0000001CU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV58\fP   0x0000001DU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV60\fP   0x0000001EU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_PRESCALER_SYSCLK_DIV62\fP   0x0000001FU"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_TXE\fP   ((uint32_t)USART_SR_TXE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_TC\fP   ((uint32_t)USART_SR_TC)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_RXNE\fP   ((uint32_t)USART_SR_RXNE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_IDLE\fP   ((uint32_t)USART_SR_IDLE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_ORE\fP   ((uint32_t)USART_SR_ORE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_NE\fP   ((uint32_t)USART_SR_NE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_FE\fP   ((uint32_t)USART_SR_FE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_FLAG_PE\fP   ((uint32_t)USART_SR_PE)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_PE\fP   ((uint32_t)(\fBSMARTCARD_CR1_REG_INDEX\fP << 28U | USART_CR1_PEIE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_TXE\fP   ((uint32_t)(\fBSMARTCARD_CR1_REG_INDEX\fP << 28U | USART_CR1_TXEIE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_TC\fP   ((uint32_t)(\fBSMARTCARD_CR1_REG_INDEX\fP << 28U | USART_CR1_TCIE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_RXNE\fP   ((uint32_t)(\fBSMARTCARD_CR1_REG_INDEX\fP << 28U | USART_CR1_RXNEIE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_IDLE\fP   ((uint32_t)(\fBSMARTCARD_CR1_REG_INDEX\fP << 28U | USART_CR1_IDLEIE))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_IT_ERR\fP   ((uint32_t)(\fBSMARTCARD_CR3_REG_INDEX\fP << 28U | USART_CR3_EIE))"
.br
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_RESET_HANDLE_STATE\fP(__HANDLE__)"
.br
.RI "Reset SMARTCARD handle gstate & RxState "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_FLUSH_DRREGISTER\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->DR)"
.br
.RI "Flush the Smartcard DR register "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_GET_FLAG\fP(__HANDLE__,  __FLAG__)   (((__HANDLE__)\->Instance\->SR & (__FLAG__)) == (__FLAG__))"
.br
.RI "Check whether the specified Smartcard flag is set or not\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_FLAG\fP(__HANDLE__,  __FLAG__)   ((__HANDLE__)\->Instance\->SR = ~(__FLAG__))"
.br
.RI "Clear the specified Smartcard pending flags\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_PEFLAG\fP(__HANDLE__)"
.br
.RI "Clear the SMARTCARD PE pending flag\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_FEFLAG\fP(__HANDLE__)   \fB__HAL_SMARTCARD_CLEAR_PEFLAG\fP(__HANDLE__)"
.br
.RI "Clear the SMARTCARD FE pending flag\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_NEFLAG\fP(__HANDLE__)   \fB__HAL_SMARTCARD_CLEAR_PEFLAG\fP(__HANDLE__)"
.br
.RI "Clear the SMARTCARD NE pending flag\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_OREFLAG\fP(__HANDLE__)   \fB__HAL_SMARTCARD_CLEAR_PEFLAG\fP(__HANDLE__)"
.br
.RI "Clear the SMARTCARD ORE pending flag\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_CLEAR_IDLEFLAG\fP(__HANDLE__)   \fB__HAL_SMARTCARD_CLEAR_PEFLAG\fP(__HANDLE__)"
.br
.RI "Clear the SMARTCARD IDLE pending flag\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_ENABLE_IT\fP(__HANDLE__,  __INTERRUPT__)"
.br
.RI "Enable the specified SmartCard interrupt\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_DISABLE_IT\fP(__HANDLE__,  __INTERRUPT__)"
.br
.RI "Disable the specified SmartCard interrupt\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_GET_IT_SOURCE\fP(__HANDLE__,  __IT__)   (((((__IT__) >> 28U) == \fBSMARTCARD_CR1_REG_INDEX\fP)? (__HANDLE__)\->Instance\->CR1: (__HANDLE__)\->Instance\->CR3) & (((uint32_t)(__IT__)) & \fBSMARTCARD_IT_MASK\fP))"
.br
.RI "Checks whether the specified SmartCard interrupt has occurred or not\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_ONE_BIT_SAMPLE_ENABLE\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->CR3|= USART_CR3_ONEBIT)"
.br
.RI "Macro to enable the SMARTCARD's one bit sample method "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_ONE_BIT_SAMPLE_DISABLE\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->CR3 &= (uint16_t)~((uint16_t)USART_CR3_ONEBIT))"
.br
.RI "Macro to disable the SMARTCARD's one bit sample method "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_ENABLE\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->CR1 |=  USART_CR1_UE)"
.br
.RI "Enable the USART associated to the SMARTCARD Handle "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_DISABLE\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->CR1 &=  ~USART_CR1_UE)"
.br
.RI "Disable the USART associated to the SMARTCARD Handle "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_DMA_REQUEST_ENABLE\fP(__HANDLE__,  __REQUEST__)   ((__HANDLE__)\->Instance\->CR3 |=  (__REQUEST__))"
.br
.RI "Macros to enable the SmartCard DMA request\&. "
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_DMA_REQUEST_DISABLE\fP(__HANDLE__,  __REQUEST__)   ((__HANDLE__)\->Instance\->CR3 &=  ~(__REQUEST__))"
.br
.RI "Macros to disable the SmartCard DMA request\&. "
.ti -1c
.RI "#define \fBSMARTCARD_IT_MASK\fP"
.br
.RI "SMARTCARD interruptions flag mask "
.ti -1c
.RI "#define \fBSMARTCARD_CR1_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBSMARTCARD_CR3_REG_INDEX\fP   3U"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_WORD_LENGTH\fP(LENGTH)   ((LENGTH) == \fBSMARTCARD_WORDLENGTH_9B\fP)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_STOPBITS\fP(STOPBITS)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_PARITY\fP(PARITY)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_MODE\fP(MODE)   ((((MODE) & 0x0000FFF3U) == 0x00U) && ((MODE) != 0x000000U))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_POLARITY\fP(CPOL)   (((CPOL) == \fBSMARTCARD_POLARITY_LOW\fP) || ((CPOL) == \fBSMARTCARD_POLARITY_HIGH\fP))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_PHASE\fP(CPHA)   (((CPHA) == \fBSMARTCARD_PHASE_1EDGE\fP) || ((CPHA) == \fBSMARTCARD_PHASE_2EDGE\fP))"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_LASTBIT\fP(LASTBIT)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_NACK_STATE\fP(NACK)"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_BAUDRATE\fP(BAUDRATE)   ((BAUDRATE) < 10500001U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIV\fP(__PCLK__,  __BAUD__)   (((__PCLK__)*25U)/(4U*(__BAUD__)))"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIVMANT\fP(__PCLK__,  __BAUD__)   (\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__))/100U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_DIVFRAQ\fP(__PCLK__,  __BAUD__)   (((\fBSMARTCARD_DIV\fP((__PCLK__), (__BAUD__)) \- (\fBSMARTCARD_DIVMANT\fP((__PCLK__), (__BAUD__)) * 100U)) * 16U + 50U) / 100U)"
.br
.ti -1c
.RI "#define \fBSMARTCARD_BRR\fP(__PCLK__,  __BAUD__)"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "typedef struct \fB__SMARTCARD_HandleTypeDef\fP \fBSMARTCARD_HandleTypeDef\fP"
.br
.RI "SMARTCARD handle Structure definition "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHAL_SMARTCARD_StateTypeDef\fP { \fBHAL_SMARTCARD_STATE_RESET\fP = 0x00U, \fBHAL_SMARTCARD_STATE_READY\fP = 0x20U, \fBHAL_SMARTCARD_STATE_BUSY\fP = 0x24U, \fBHAL_SMARTCARD_STATE_BUSY_TX\fP = 0x21U, \fBHAL_SMARTCARD_STATE_BUSY_RX\fP = 0x22U, \fBHAL_SMARTCARD_STATE_BUSY_TX_RX\fP = 0x23U, \fBHAL_SMARTCARD_STATE_TIMEOUT\fP = 0xA0U, \fBHAL_SMARTCARD_STATE_ERROR\fP = 0xE0U }"
.br
.RI "HAL SMARTCARD State structures definition "
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Init\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_ReInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_DeInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_MspInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_MspDeInit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Transmit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Receive\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Transmit_IT\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Receive_IT\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Transmit_DMA\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Receive_DMA\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc, uint8_t *pData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Abort\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_AbortTransmit\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_AbortReceive\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_Abort_IT\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_AbortTransmit_IT\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SMARTCARD_AbortReceive_IT\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_IRQHandler\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_TxCpltCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_RxCpltCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_ErrorCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_AbortCpltCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_AbortTransmitCpltCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "void \fBHAL_SMARTCARD_AbortReceiveCpltCallback\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "\fBHAL_SMARTCARD_StateTypeDef\fP \fBHAL_SMARTCARD_GetState\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SMARTCARD_GetError\fP (\fBSMARTCARD_HandleTypeDef\fP *hsc)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of SMARTCARD HAL module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_smartcard\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
