.TH "inc/stm32_assert_template.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32_assert_template.h
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBassert_param\fP(expr)   ((void)0U)"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define assert_param(expr)   ((void)0U)"

.PP
在文件 stm32_assert_template\&.h 第 48 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
