.TH "inc/stm32f4xx_hal_flash_ex.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_flash_ex.h \- Header file of FLASH HAL Extension module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBFLASH_EraseInitTypeDef\fP"
.br
.RI "FLASH Erase structure definition "
.ti -1c
.RI "struct \fBFLASH_OBProgramInitTypeDef\fP"
.br
.RI "FLASH Option Bytes Program structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBFLASH_TYPEERASE_SECTORS\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBFLASH_TYPEERASE_MASSERASE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_3\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBFLASH_VOLTAGE_RANGE_4\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBOB_WRPSTATE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_WRPSTATE_ENABLE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_WRP\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_RDP\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_USER\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_BOR\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_0\fP   ((uint8_t)0xAA)"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_1\fP   ((uint8_t)0x55)"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_2\fP   ((uint8_t)0xCC)"
.br
.ti -1c
.RI "#define \fBOB_IWDG_SW\fP   ((uint8_t)0x20)"
.br
.ti -1c
.RI "#define \fBOB_IWDG_HW\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBOB_STOP_NO_RST\fP   ((uint8_t)0x40)"
.br
.ti -1c
.RI "#define \fBOB_STOP_RST\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBOB_STDBY_NO_RST\fP   ((uint8_t)0x80)"
.br
.ti -1c
.RI "#define \fBOB_STDBY_RST\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBOB_BOR_LEVEL3\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBOB_BOR_LEVEL2\fP   ((uint8_t)0x04)"
.br
.ti -1c
.RI "#define \fBOB_BOR_LEVEL1\fP   ((uint8_t)0x08)"
.br
.ti -1c
.RI "#define \fBOB_BOR_OFF\fP   ((uint8_t)0x0C)"
.br
.ti -1c
.RI "#define \fBIS_FLASH_TYPEERASE\fP(VALUE)"
.br
.ti -1c
.RI "#define \fBIS_VOLTAGERANGE\fP(RANGE)"
.br
.ti -1c
.RI "#define \fBIS_WRPSTATE\fP(VALUE)"
.br
.ti -1c
.RI "#define \fBIS_OPTIONBYTE\fP(VALUE)   (((VALUE) <= (\fBOPTIONBYTE_WRP\fP|\fBOPTIONBYTE_RDP\fP|\fBOPTIONBYTE_USER\fP|\fBOPTIONBYTE_BOR\fP)))"
.br
.ti -1c
.RI "#define \fBIS_OB_RDP_LEVEL\fP(LEVEL)"
.br
.ti -1c
.RI "#define \fBIS_OB_IWDG_SOURCE\fP(SOURCE)   (((SOURCE) == \fBOB_IWDG_SW\fP) || ((SOURCE) == \fBOB_IWDG_HW\fP))"
.br
.ti -1c
.RI "#define \fBIS_OB_STOP_SOURCE\fP(SOURCE)   (((SOURCE) == \fBOB_STOP_NO_RST\fP) || ((SOURCE) == \fBOB_STOP_RST\fP))"
.br
.ti -1c
.RI "#define \fBIS_OB_STDBY_SOURCE\fP(SOURCE)   (((SOURCE) == \fBOB_STDBY_NO_RST\fP) || ((SOURCE) == \fBOB_STDBY_RST\fP))"
.br
.ti -1c
.RI "#define \fBIS_OB_BOR_LEVEL\fP(LEVEL)"
.br
.ti -1c
.RI "#define \fBIS_FLASH_ADDRESS\fP(ADDRESS)"
.br
.ti -1c
.RI "#define \fBIS_FLASH_NBSECTORS\fP(NBSECTORS)   (((NBSECTORS) != 0) && ((NBSECTORS) <= FLASH_SECTOR_TOTAL))"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit, uint32_t *SectorError)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase_IT\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_OBProgram\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_OBGetConfig\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "void \fBFLASH_Erase_Sector\fP (uint32_t Sector, uint8_t VoltageRange)"
.br
.ti -1c
.RI "void \fBFLASH_FlushCaches\fP (void)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of FLASH HAL Extension module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_flash_ex\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
