.TH "src/stm32f4xx_hal_i2s_ex.c" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/stm32f4xx_hal_i2s_ex.c \- I2S HAL module driver\&. This file provides firmware functions to manage the following functionalities of I2S extension peripheral:  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SH "详细描述"
.PP 
I2S HAL module driver\&. This file provides firmware functions to manage the following functionalities of I2S extension peripheral: 


.PP
\fB作者\fP
.RS 4
MCD Application Team
.IP "\(bu" 2
Extension features Functions
.PP
.RE
.PP
.PP
.nf
 ==============================================================================
                   ##### I2S Extension features #####
 ==============================================================================
 [..]
    (#) In I2S full duplex mode, each SPI peripheral is able to manage sending and receiving
        data simultaneously using two data lines. Each SPI peripheral has an extended block
        called I2Sxext (i.e I2S2ext for SPI2 and I2S3ext for SPI3).
    (#) The extension block is not a full SPI IP, it is used only as I2S slave to
        implement full duplex mode. The extension block uses the same clock sources
        as its master.

    (#) Both I2Sx and I2Sx_ext can be configured as transmitters or receivers.

    [..]
      (@) Only I2Sx can deliver SCK and WS to I2Sx_ext in full duplex mode, where
        I2Sx can be I2S2 or I2S3.

                 ##### How to use this driver #####
===============================================================================
[..]
  Three operation modes are available within this driver :

  *** Polling mode IO operation ***
  =================================
  [..]
    (+) Send and receive in the same time an amount of data in blocking mode using HAL_I2SEx_TransmitReceive()

  *** Interrupt mode IO operation ***
  ===================================
  [..]
    (+) Send and receive in the same time an amount of data in non blocking mode using HAL_I2SEx_TransmitReceive_IT()
    (+) At transmission/reception end of transfer HAL_I2SEx_TxRxCpltCallback is executed and user can
        add his own code by customization of function pointer HAL_I2SEx_TxRxCpltCallback
    (+) In case of transfer Error, HAL_I2S_ErrorCallback() function is executed and user can
        add his own code by customization of function pointer HAL_I2S_ErrorCallback

  *** DMA mode IO operation ***
  ==============================
  [..]
    (+) Send and receive an amount of data in non blocking mode (DMA) using HAL_I2SEx_TransmitReceive_DMA()
    (+) At transmission/reception end of transfer HAL_I2SEx_TxRxCpltCallback is executed and user can
        add his own code by customization of function pointer HAL_I2S_TxRxCpltCallback
    (+) In case of transfer Error, HAL_I2S_ErrorCallback() function is executed and user can
        add his own code by customization of function pointer HAL_I2S_ErrorCallback.fi
.PP
.PP
Additional Figure: The Extended block uses the same clock sources as its master\&. 
.PP
.nf
           +-----------------------+

.fi
.PP
 I2Sx_SCK | | ----------+-->| I2Sx |------------------->I2Sx_SD(in/out) +--|-->| | | | +-----------------------+ | | I2S_WS | | ------>| | | | +-----------------------+ | +-->| | | | I2Sx_ext |------------------->I2Sx_extSD(in/out) +----->| | +-----------------------+
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_i2s_ex\&.c\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
