.TH "inc/stm32f4xx_hal_iwdg.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_iwdg.h \- Header file of IWDG HAL module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBIWDG_InitTypeDef\fP"
.br
.RI "IWDG Init structure definition "
.ti -1c
.RI "struct \fBIWDG_HandleTypeDef\fP"
.br
.RI "IWDG Handle Structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIWDG_PRESCALER_4\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_8\fP   IWDG_PR_PR_0"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_16\fP   IWDG_PR_PR_1"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_32\fP   (IWDG_PR_PR_1 | IWDG_PR_PR_0)"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_64\fP   IWDG_PR_PR_2"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_128\fP   (IWDG_PR_PR_2 | IWDG_PR_PR_0)"
.br
.ti -1c
.RI "#define \fBIWDG_PRESCALER_256\fP   (IWDG_PR_PR_2 | IWDG_PR_PR_1)"
.br
.ti -1c
.RI "#define \fB__HAL_IWDG_START\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_ENABLE\fP)"
.br
.RI "Enable the IWDG peripheral\&. "
.ti -1c
.RI "#define \fB__HAL_IWDG_RELOAD_COUNTER\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_RELOAD\fP)"
.br
.RI "Reload IWDG counter with value defined in the reload register (write access to IWDG_PR and IWDG_RLR registers disabled)\&. "
.ti -1c
.RI "#define \fBIWDG_KEY_RELOAD\fP   0x0000AAAAu"
.br
.RI "IWDG Key Register BitMask "
.ti -1c
.RI "#define \fBIWDG_KEY_ENABLE\fP   0x0000CCCCu"
.br
.ti -1c
.RI "#define \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP   0x00005555u"
.br
.ti -1c
.RI "#define \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBIWDG_ENABLE_WRITE_ACCESS\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_ENABLE\fP)"
.br
.RI "Enable write access to IWDG_PR and IWDG_RLR registers\&. "
.ti -1c
.RI "#define \fBIWDG_DISABLE_WRITE_ACCESS\fP(__HANDLE__)   WRITE_REG((__HANDLE__)\->Instance\->KR, \fBIWDG_KEY_WRITE_ACCESS_DISABLE\fP)"
.br
.RI "Disable write access to IWDG_PR and IWDG_RLR registers\&. "
.ti -1c
.RI "#define \fBIS_IWDG_PRESCALER\fP(__PRESCALER__)"
.br
.RI "Check IWDG prescaler value\&. "
.ti -1c
.RI "#define \fBIS_IWDG_RELOAD\fP(__RELOAD__)   ((__RELOAD__) <= IWDG_RLR_RL)"
.br
.RI "Check IWDG reload value\&. "
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_IWDG_Init\fP (\fBIWDG_HandleTypeDef\fP *hiwdg)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_IWDG_Refresh\fP (\fBIWDG_HandleTypeDef\fP *hiwdg)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of IWDG HAL module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_iwdg\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
