.TH "src/stm32f4xx_hal_crc.c" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/stm32f4xx_hal_crc.c \- CRC HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Cyclic Redundancy Check (CRC) peripheral:  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal\&.h'\fP
.br

.SH "详细描述"
.PP 
CRC HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Cyclic Redundancy Check (CRC) peripheral: 


.PP
\fB作者\fP
.RS 4
MCD Application Team
.IP "\(bu" 2
Initialization and de-initialization functions
.IP "\(bu" 2
Peripheral Control functions
.IP "\(bu" 2
Peripheral State functions
.PP
.RE
.PP
.PP
.nf
===============================================================================
                    ##### How to use this driver #####
===============================================================================
   [..]
        (+) Enable CRC AHB clock using __HAL_RCC_CRC_CLK_ENABLE();
        (+) Initialize CRC calculator
            (++) specify generating polynomial (peripheral default or non-default one)
            (++) specify initialization value (peripheral default or non-default one)
            (++) specify input data format
            (++) specify input or output data inversion mode if any
        (+) Use HAL_CRC_Accumulate() function to compute the CRC value of the
            input data buffer starting with the previously computed CRC as
            initialization value
        (+) Use HAL_CRC_Calculate() function to compute the CRC value of the
            input data buffer starting with the defined initialization value
            (default or non-default) to initiate CRC calculation.fi
.PP
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_crc\&.c\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
