.TH "inc/stm32f4xx_hal_crc.h" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/stm32f4xx_hal_crc.h \- Header file of CRC HAL module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f4xx_hal_def\&.h'\fP
.br

.SS "结构体"

.in +1c
.ti -1c
.RI "struct \fBCRC_HandleTypeDef\fP"
.br
.RI "CRC Handle Structure definition "
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fB__HAL_CRC_RESET_HANDLE_STATE\fP(__HANDLE__)   ((__HANDLE__)\->State = \fBHAL_CRC_STATE_RESET\fP)"
.br
.RI "Reset CRC handle state\&. "
.ti -1c
.RI "#define \fB__HAL_CRC_DR_RESET\fP(__HANDLE__)   ((__HANDLE__)\->Instance\->CR |= CRC_CR_RESET)"
.br
.RI "Reset CRC Data Register\&. "
.ti -1c
.RI "#define \fB__HAL_CRC_SET_IDR\fP(__HANDLE__,  __VALUE__)   (WRITE_REG((__HANDLE__)\->Instance\->IDR, (__VALUE__)))"
.br
.RI "Store data in the Independent Data (ID) register\&. "
.ti -1c
.RI "#define \fB__HAL_CRC_GET_IDR\fP(__HANDLE__)   (((__HANDLE__)\->Instance\->IDR) & CRC_IDR_IDR)"
.br
.RI "Return the data stored in the Independent Data (ID) register\&. "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum \fBHAL_CRC_StateTypeDef\fP { \fBHAL_CRC_STATE_RESET\fP = 0x00U, \fBHAL_CRC_STATE_READY\fP = 0x01U, \fBHAL_CRC_STATE_BUSY\fP = 0x02U, \fBHAL_CRC_STATE_TIMEOUT\fP = 0x03U, \fBHAL_CRC_STATE_ERROR\fP = 0x04U }"
.br
.RI "CRC HAL State Structure definition "
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_CRC_Init\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_CRC_DeInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "void \fBHAL_CRC_MspInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "void \fBHAL_CRC_MspDeInit\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.ti -1c
.RI "uint32_t \fBHAL_CRC_Accumulate\fP (\fBCRC_HandleTypeDef\fP *hcrc, uint32_t pBuffer[], uint32_t BufferLength)"
.br
.ti -1c
.RI "uint32_t \fBHAL_CRC_Calculate\fP (\fBCRC_HandleTypeDef\fP *hcrc, uint32_t pBuffer[], uint32_t BufferLength)"
.br
.ti -1c
.RI "\fBHAL_CRC_StateTypeDef\fP \fBHAL_CRC_GetState\fP (\fBCRC_HandleTypeDef\fP *hcrc)"
.br
.in -1c
.SH "详细描述"
.PP 
Header file of CRC HAL module\&. 


.PP
\fB作者\fP
.RS 4
MCD Application Team 
.RE
.PP
\fB注意\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.PP
在文件 \fBstm32f4xx_hal_crc\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
