.TH "TIM_Clock_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ETRMODE2\fP   TIM_SMCR_ETPS_1"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_INTERNAL\fP   TIM_SMCR_ETPS_0"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR0\fP   \fBTIM_TS_ITR0\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR1\fP   \fBTIM_TS_ITR1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR2\fP   \fBTIM_TS_ITR2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR3\fP   \fBTIM_TS_ITR3\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI1ED\fP   \fBTIM_TS_TI1F_ED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI1\fP   \fBTIM_TS_TI1FP1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI2\fP   \fBTIM_TS_TI2FP2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ETRMODE1\fP   \fBTIM_TS_ETRF\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_CLOCKSOURCE_ETRMODE1   \fBTIM_TS_ETRF\fP"
External clock source mode 1 (ETRF) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 715 行定义\&.
.SS "#define TIM_CLOCKSOURCE_ETRMODE2   TIM_SMCR_ETPS_1"
External clock source mode 2 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 706 行定义\&.
.SS "#define TIM_CLOCKSOURCE_INTERNAL   TIM_SMCR_ETPS_0"
Internal clock source 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 707 行定义\&.
.SS "#define TIM_CLOCKSOURCE_ITR0   \fBTIM_TS_ITR0\fP"
External clock source mode 1 (ITR0) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 708 行定义\&.
.SS "#define TIM_CLOCKSOURCE_ITR1   \fBTIM_TS_ITR1\fP"
External clock source mode 1 (ITR1) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 709 行定义\&.
.SS "#define TIM_CLOCKSOURCE_ITR2   \fBTIM_TS_ITR2\fP"
External clock source mode 1 (ITR2) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 710 行定义\&.
.SS "#define TIM_CLOCKSOURCE_ITR3   \fBTIM_TS_ITR3\fP"
External clock source mode 1 (ITR3) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 711 行定义\&.
.SS "#define TIM_CLOCKSOURCE_TI1   \fBTIM_TS_TI1FP1\fP"
External clock source mode 1 (TTI1FP1) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 713 行定义\&.
.SS "#define TIM_CLOCKSOURCE_TI1ED   \fBTIM_TS_TI1F_ED\fP"
External clock source mode 1 (TTI1FP1 + edge detect\&.) 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 712 行定义\&.
.SS "#define TIM_CLOCKSOURCE_TI2   \fBTIM_TS_TI2FP2\fP"
External clock source mode 1 (TTI2FP2) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 714 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
