.TH "TIM_Exported_Functions_Group10" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group10 \- Peripheral State functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Base_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OC_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_PWM_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_IC_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OnePulse_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Encoder_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "详细描述"
.PP 
Peripheral State functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Base_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Encoder_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_IC_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OC_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OnePulse_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_PWM_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
