.TH "TIM_DMA_Base_address" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_Base_address
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMABASE_CR1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CR2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_SMCR\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DIER\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_SR\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_EGR\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCMR1\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCMR2\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCER\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CNT\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_PSC\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_ARR\fP   0x0000000BU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_RCR\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR1\fP   0x0000000DU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR2\fP   0x0000000EU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR3\fP   0x0000000FU"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_CCR4\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_BDTR\fP   0x00000011U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DCR\fP   0x00000012U"
.br
.ti -1c
.RI "#define \fBTIM_DMABASE_DMAR\fP   0x00000013U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_DMABASE_ARR   0x0000000BU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 429 行定义\&.
.SS "#define TIM_DMABASE_BDTR   0x00000011U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 435 行定义\&.
.SS "#define TIM_DMABASE_CCER   0x00000008U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 426 行定义\&.
.SS "#define TIM_DMABASE_CCMR1   0x00000006U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 424 行定义\&.
.SS "#define TIM_DMABASE_CCMR2   0x00000007U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 425 行定义\&.
.SS "#define TIM_DMABASE_CCR1   0x0000000DU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 431 行定义\&.
.SS "#define TIM_DMABASE_CCR2   0x0000000EU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 432 行定义\&.
.SS "#define TIM_DMABASE_CCR3   0x0000000FU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 433 行定义\&.
.SS "#define TIM_DMABASE_CCR4   0x00000010U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 434 行定义\&.
.SS "#define TIM_DMABASE_CNT   0x00000009U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 427 行定义\&.
.SS "#define TIM_DMABASE_CR1   0x00000000U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 418 行定义\&.
.SS "#define TIM_DMABASE_CR2   0x00000001U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 419 行定义\&.
.SS "#define TIM_DMABASE_DCR   0x00000012U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 436 行定义\&.
.SS "#define TIM_DMABASE_DIER   0x00000003U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 421 行定义\&.
.SS "#define TIM_DMABASE_DMAR   0x00000013U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 437 行定义\&.
.SS "#define TIM_DMABASE_EGR   0x00000005U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 423 行定义\&.
.SS "#define TIM_DMABASE_PSC   0x0000000AU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 428 行定义\&.
.SS "#define TIM_DMABASE_RCR   0x0000000CU"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 430 行定义\&.
.SS "#define TIM_DMABASE_SMCR   0x00000002U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 420 行定义\&.
.SS "#define TIM_DMABASE_SR   0x00000004U"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 422 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
