.TH "TIM_ClearInput_Polarity" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInput_Polarity
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPOLARITY_INVERTED\fP   \fBTIM_ETRPOLARITY_INVERTED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPOLARITY_NONINVERTED\fP   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_CLEARINPUTPOLARITY_INVERTED   \fBTIM_ETRPOLARITY_INVERTED\fP"
Polarity for ETRx pin 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 746 行定义\&.
.SS "#define TIM_CLEARINPUTPOLARITY_NONINVERTED   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
Polarity for ETRx pin 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 747 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
