.TH "TIM_Clock_Polarity" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Polarity
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_INVERTED\fP   \fBTIM_ETRPOLARITY_INVERTED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_NONINVERTED\fP   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_RISING\fP   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_FALLING\fP   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_BOTHEDGE\fP   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_CLOCKPOLARITY_BOTHEDGE   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
Polarity for TIx clock sources 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 727 行定义\&.
.SS "#define TIM_CLOCKPOLARITY_FALLING   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
Polarity for TIx clock sources 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 726 行定义\&.
.SS "#define TIM_CLOCKPOLARITY_INVERTED   \fBTIM_ETRPOLARITY_INVERTED\fP"
Polarity for ETRx clock sources 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 723 行定义\&.
.SS "#define TIM_CLOCKPOLARITY_NONINVERTED   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
Polarity for ETRx clock sources 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 724 行定义\&.
.SS "#define TIM_CLOCKPOLARITY_RISING   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
Polarity for TIx clock sources 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 725 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
