.TH "TIM_DMA_sources" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_sources
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMA_UPDATE\fP   TIM_DIER_UDE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC1\fP   TIM_DIER_CC1DE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC2\fP   TIM_DIER_CC2DE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC3\fP   TIM_DIER_CC3DE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC4\fP   TIM_DIER_CC4DE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_COM\fP   TIM_DIER_COMDE"
.br
.ti -1c
.RI "#define \fBTIM_DMA_TRIGGER\fP   TIM_DIER_TDE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_DMA_CC1   TIM_DIER_CC1DE"
DMA request is triggered by the capture/compare macth 1 event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 662 行定义\&.
.SS "#define TIM_DMA_CC2   TIM_DIER_CC2DE"
DMA request is triggered by the capture/compare macth 2 event event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 663 行定义\&.
.SS "#define TIM_DMA_CC3   TIM_DIER_CC3DE"
DMA request is triggered by the capture/compare macth 3 event event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 664 行定义\&.
.SS "#define TIM_DMA_CC4   TIM_DIER_CC4DE"
DMA request is triggered by the capture/compare macth 4 event event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 665 行定义\&.
.SS "#define TIM_DMA_COM   TIM_DIER_COMDE"
DMA request is triggered by the commutation event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 666 行定义\&.
.SS "#define TIM_DMA_TRIGGER   TIM_DIER_TDE"
DMA request is triggered by the trigger event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 667 行定义\&.
.SS "#define TIM_DMA_UPDATE   TIM_DIER_UDE"
DMA request is triggered by the update event 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 661 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
