.TH "TIM_Lock_level" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Lock_level
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_LOCKLEVEL_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_LOCKLEVEL_1\fP   TIM_BDTR_LOCK_0"
.br
.ti -1c
.RI "#define \fBTIM_LOCKLEVEL_2\fP   TIM_BDTR_LOCK_1"
.br
.ti -1c
.RI "#define \fBTIM_LOCKLEVEL_3\fP   TIM_BDTR_LOCK"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_LOCKLEVEL_1   TIM_BDTR_LOCK_0"
LOCK Level 1 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 784 行定义\&.
.SS "#define TIM_LOCKLEVEL_2   TIM_BDTR_LOCK_1"
LOCK Level 2 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 785 行定义\&.
.SS "#define TIM_LOCKLEVEL_3   TIM_BDTR_LOCK"
LOCK Level 3 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 786 行定义\&.
.SS "#define TIM_LOCKLEVEL_OFF   0x00000000U"
LOCK OFF 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 783 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
