.TH "TIM_Master_Mode_Selection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Master_Mode_Selection
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_TRGO_RESET\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_ENABLE\fP   TIM_CR2_MMS_0"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_UPDATE\fP   TIM_CR2_MMS_1"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC1\fP   (TIM_CR2_MMS_1 | TIM_CR2_MMS_0)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC1REF\fP   TIM_CR2_MMS_2"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC2REF\fP   (TIM_CR2_MMS_2 | TIM_CR2_MMS_0)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC3REF\fP   (TIM_CR2_MMS_2 | TIM_CR2_MMS_1)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC4REF\fP   (TIM_CR2_MMS_2 | TIM_CR2_MMS_1 | TIM_CR2_MMS_0)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_TRGO_ENABLE   TIM_CR2_MMS_0"
TIMx_CR1\&.CEN bit is used as trigger output (TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 823 行定义\&.
.SS "#define TIM_TRGO_OC1   (TIM_CR2_MMS_1 | TIM_CR2_MMS_0)"
Capture or a compare match 1 is used as trigger output (TRGO) 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 825 行定义\&.
.SS "#define TIM_TRGO_OC1REF   TIM_CR2_MMS_2"
OC1REF signal is used as trigger output (TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 826 行定义\&.
.SS "#define TIM_TRGO_OC2REF   (TIM_CR2_MMS_2 | TIM_CR2_MMS_0)"
OC2REF signal is used as trigger output(TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 827 行定义\&.
.SS "#define TIM_TRGO_OC3REF   (TIM_CR2_MMS_2 | TIM_CR2_MMS_1)"
OC3REF signal is used as trigger output(TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 828 行定义\&.
.SS "#define TIM_TRGO_OC4REF   (TIM_CR2_MMS_2 | TIM_CR2_MMS_1 | TIM_CR2_MMS_0)"
OC4REF signal is used as trigger output(TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 829 行定义\&.
.SS "#define TIM_TRGO_RESET   0x00000000U"
TIMx_EGR\&.UG bit is used as trigger output (TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 822 行定义\&.
.SS "#define TIM_TRGO_UPDATE   TIM_CR2_MMS_1"
Update event is used as trigger output (TRGO) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 824 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
