.TH "TIM_SlaveConfigTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_SlaveConfigTypeDef \- TIM Slave configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBSlaveMode\fP"
.br
.ti -1c
.RI "uint32_t \fBInputTrigger\fP"
.br
.ti -1c
.RI "uint32_t \fBTriggerPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBTriggerPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBTriggerFilter\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Slave configuration Structure definition 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 240 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t InputTrigger"
Input Trigger source This parameter can be a value of \fBTIM Trigger Selection\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 244 行定义\&.
.SS "uint32_t SlaveMode"
Slave mode selection This parameter can be a value of \fBTIM Slave mode\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 242 行定义\&.
.SS "uint32_t TriggerFilter"
Input trigger filter This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 250 行定义\&.
.SS "uint32_t TriggerPolarity"
Input Trigger polarity This parameter can be a value of \fBTIM Trigger Polarity\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 246 行定义\&.
.SS "uint32_t TriggerPrescaler"
Input trigger prescaler This parameter can be a value of \fBTIM Trigger Prescaler\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 248 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
