.TH "TIM_TI1_Selection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_TI1_Selection
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_TI1SELECTION_CH1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TI1SELECTION_XORCOMBINATION\fP   TIM_CR2_TI1S"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_TI1SELECTION_CH1   0x00000000U"
The TIMx_CH1 pin is connected to TI1 input 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 912 行定义\&.
.SS "#define TIM_TI1SELECTION_XORCOMBINATION   TIM_CR2_TI1S"
The TIMx_CH1, CH2 and CH3 pins are connected to the TI1 input (XOR combination) 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 913 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
