.TH "TIM_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBTIM Clear Input Source\fP"
.br
.ti -1c
.RI "\fBTIM DMA Base Address\fP"
.br
.ti -1c
.RI "\fBTIM Event Source\fP"
.br
.ti -1c
.RI "\fBTIM Input Channel polarity\fP"
.br
.ti -1c
.RI "\fBTIM ETR Polarity\fP"
.br
.ti -1c
.RI "\fBTIM ETR Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM Counter Mode\fP"
.br
.ti -1c
.RI "\fBTIM Clock Division\fP"
.br
.ti -1c
.RI "\fBTIM Output Compare State\fP"
.br
.ti -1c
.RI "\fBTIM Auto\-Reload Preload\fP"
.br
.ti -1c
.RI "\fBTIM Output Fast State\fP"
.br
.ti -1c
.RI "\fBTIM Complementary Output Compare State\fP"
.br
.ti -1c
.RI "\fBTIM Output Compare Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Complementary Output Compare Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Output Compare Idle State\fP"
.br
.ti -1c
.RI "\fBTIM Complementary Output Compare Idle State\fP"
.br
.ti -1c
.RI "\fBTIM Input Capture Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Input Capture Selection\fP"
.br
.ti -1c
.RI "\fBTIM Input Capture Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM One Pulse Mode\fP"
.br
.ti -1c
.RI "\fBTIM Encoder Mode\fP"
.br
.ti -1c
.RI "\fBTIM interrupt Definition\fP"
.br
.ti -1c
.RI "\fBTIM Commutation Source\fP"
.br
.ti -1c
.RI "\fBTIM DMA Sources\fP"
.br
.ti -1c
.RI "\fBTIM Flag Definition\fP"
.br
.ti -1c
.RI "\fBTIM Channel\fP"
.br
.ti -1c
.RI "\fBTIM Clock Source\fP"
.br
.ti -1c
.RI "\fBTIM Clock Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Clock Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM Clear Input Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Clear Input Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM OSSR OffState Selection for Run mode state\fP"
.br
.ti -1c
.RI "\fBTIM OSSI OffState Selection for Idle mode state\fP"
.br
.ti -1c
.RI "\fBTIM Lock level\fP"
.br
.ti -1c
.RI "\fBTIM Break Input Enable\fP"
.br
.ti -1c
.RI "\fBTIM Break Input Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Automatic Output Enable\fP"
.br
.ti -1c
.RI "\fBTIM Master Mode Selection\fP"
.br
.ti -1c
.RI "\fBTIM Master/Slave Mode\fP"
.br
.ti -1c
.RI "\fBTIM Slave mode\fP"
.br
.ti -1c
.RI "\fBTIM Output Compare and PWM Modes\fP"
.br
.ti -1c
.RI "\fBTIM Trigger Selection\fP"
.br
.ti -1c
.RI "\fBTIM Trigger Polarity\fP"
.br
.ti -1c
.RI "\fBTIM Trigger Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM TI1 Input Selection\fP"
.br
.ti -1c
.RI "\fBTIM DMA Burst Length\fP"
.br
.ti -1c
.RI "\fBTIM DMA Handle Index\fP"
.br
.ti -1c
.RI "\fBTIM Capture/Compare Channel State\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
