.TH "TIM_Input_Capture_Polarity" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Input_Capture_Polarity
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_RISING\fP   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_FALLING\fP   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_BOTHEDGE\fP   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_ICPOLARITY_BOTHEDGE   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
Capture triggered by both rising and falling edges on timer input 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 587 行定义\&.
.SS "#define TIM_ICPOLARITY_FALLING   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
Capture triggered by falling edge on timer input 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 586 行定义\&.
.SS "#define TIM_ICPOLARITY_RISING   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
Capture triggered by rising edge on timer input 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 585 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
