.TH "TIM_AOE_Bit_Set_Reset" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_AOE_Bit_Set_Reset
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_AUTOMATICOUTPUT_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_AUTOMATICOUTPUT_ENABLE\fP   TIM_BDTR_AOE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_AUTOMATICOUTPUT_DISABLE   0x00000000U"
MOE can be set only by software 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 812 行定义\&.
.SS "#define TIM_AUTOMATICOUTPUT_ENABLE   TIM_BDTR_AOE"
MOE can be set by software or automatically at the next update event (if none of the break inputs BRK and BRK2 is active) 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 814 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
