.TH "TIM_Flag_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Flag_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_FLAG_UPDATE\fP   TIM_SR_UIF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1\fP   TIM_SR_CC1IF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2\fP   TIM_SR_CC2IF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3\fP   TIM_SR_CC3IF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4\fP   TIM_SR_CC4IF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_COM\fP   TIM_SR_COMIF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_TRIGGER\fP   TIM_SR_TIF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_BREAK\fP   TIM_SR_BIF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1OF\fP   TIM_SR_CC1OF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2OF\fP   TIM_SR_CC2OF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3OF\fP   TIM_SR_CC3OF"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4OF\fP   TIM_SR_CC4OF"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_FLAG_BREAK   TIM_SR_BIF"
Break interrupt flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 682 行定义\&.
.SS "#define TIM_FLAG_CC1   TIM_SR_CC1IF"
Capture/Compare 1 interrupt flag 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 676 行定义\&.
.SS "#define TIM_FLAG_CC1OF   TIM_SR_CC1OF"
Capture 1 overcapture flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 683 行定义\&.
.SS "#define TIM_FLAG_CC2   TIM_SR_CC2IF"
Capture/Compare 2 interrupt flag 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 677 行定义\&.
.SS "#define TIM_FLAG_CC2OF   TIM_SR_CC2OF"
Capture 2 overcapture flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 684 行定义\&.
.SS "#define TIM_FLAG_CC3   TIM_SR_CC3IF"
Capture/Compare 3 interrupt flag 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 678 行定义\&.
.SS "#define TIM_FLAG_CC3OF   TIM_SR_CC3OF"
Capture 3 overcapture flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 685 行定义\&.
.SS "#define TIM_FLAG_CC4   TIM_SR_CC4IF"
Capture/Compare 4 interrupt flag 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 679 行定义\&.
.SS "#define TIM_FLAG_CC4OF   TIM_SR_CC4OF"
Capture 4 overcapture flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 686 行定义\&.
.SS "#define TIM_FLAG_COM   TIM_SR_COMIF"
Commutation interrupt flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 680 行定义\&.
.SS "#define TIM_FLAG_TRIGGER   TIM_SR_TIF"
Trigger interrupt flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 681 行定义\&.
.SS "#define TIM_FLAG_UPDATE   TIM_SR_UIF"
Update interrupt flag 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 675 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
