.TH "TIM_Channel" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Channel
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_CHANNEL_1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_2\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_3\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_4\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_ALL\fP   0x0000003CU"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_CHANNEL_1   0x00000000U"
Capture/compare channel 1 identifier 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 694 行定义\&.
.SS "#define TIM_CHANNEL_2   0x00000004U"
Capture/compare channel 2 identifier 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 695 行定义\&.
.SS "#define TIM_CHANNEL_3   0x00000008U"
Capture/compare channel 3 identifier 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 696 行定义\&.
.SS "#define TIM_CHANNEL_4   0x0000000CU"
Capture/compare channel 4 identifier 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 697 行定义\&.
.SS "#define TIM_CHANNEL_ALL   0x0000003CU"
Global Capture/compare channel identifier 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 698 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
