.TH "TIM_Break_Input_enable_disable" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Break_Input_enable_disable
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAK_ENABLE\fP   TIM_BDTR_BKE"
.br
.ti -1c
.RI "#define \fBTIM_BREAK_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_BREAK_DISABLE   0x00000000U"
Break input BRK is disabled 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 795 行定义\&.
.SS "#define TIM_BREAK_ENABLE   TIM_BDTR_BKE"
Break input BRK is enabled 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 794 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
