.TH "TIM_Interrupt_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Interrupt_definition
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_IT_UPDATE\fP   TIM_DIER_UIE"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC1\fP   TIM_DIER_CC1IE"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC2\fP   TIM_DIER_CC2IE"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC3\fP   TIM_DIER_CC3IE"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC4\fP   TIM_DIER_CC4IE"
.br
.ti -1c
.RI "#define \fBTIM_IT_COM\fP   TIM_DIER_COMIE"
.br
.ti -1c
.RI "#define \fBTIM_IT_TRIGGER\fP   TIM_DIER_TIE"
.br
.ti -1c
.RI "#define \fBTIM_IT_BREAK\fP   TIM_DIER_BIE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_IT_BREAK   TIM_DIER_BIE"
Break interrupt 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 644 行定义\&.
.SS "#define TIM_IT_CC1   TIM_DIER_CC1IE"
Capture/Compare 1 interrupt 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 638 行定义\&.
.SS "#define TIM_IT_CC2   TIM_DIER_CC2IE"
Capture/Compare 2 interrupt 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 639 行定义\&.
.SS "#define TIM_IT_CC3   TIM_DIER_CC3IE"
Capture/Compare 3 interrupt 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 640 行定义\&.
.SS "#define TIM_IT_CC4   TIM_DIER_CC4IE"
Capture/Compare 4 interrupt 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 641 行定义\&.
.SS "#define TIM_IT_COM   TIM_DIER_COMIE"
Commutation interrupt 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 642 行定义\&.
.SS "#define TIM_IT_TRIGGER   TIM_DIER_TIE"
Trigger interrupt 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 643 行定义\&.
.SS "#define TIM_IT_UPDATE   TIM_DIER_UIE"
Update interrupt 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 637 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
