.TH "TIM_Encoder_Mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Encoder_Mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_ENCODERMODE_TI1\fP   TIM_SMCR_SMS_0"
.br
.ti -1c
.RI "#define \fBTIM_ENCODERMODE_TI2\fP   TIM_SMCR_SMS_1"
.br
.ti -1c
.RI "#define \fBTIM_ENCODERMODE_TI12\fP   (TIM_SMCR_SMS_1 | TIM_SMCR_SMS_0)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_ENCODERMODE_TI1   TIM_SMCR_SMS_0"
Quadrature encoder mode 1, x2 mode, counts up/down on TI1FP1 edge depending on TI2FP2 level 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 627 行定义\&.
.SS "#define TIM_ENCODERMODE_TI12   (TIM_SMCR_SMS_1 | TIM_SMCR_SMS_0)"
Quadrature encoder mode 3, x4 mode, counts up/down on both TI1FP1 and TI2FP2 edges depending on the level of the other input\&. 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 629 行定义\&.
.SS "#define TIM_ENCODERMODE_TI2   TIM_SMCR_SMS_1"
Quadrature encoder mode 2, x2 mode, counts up/down on TI2FP2 edge depending on TI1FP1 level\&. 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 628 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
