.TH "TIM_HallSensor_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_HallSensor_InitTypeDef \- TIM Hall sensor Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim_ex\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBIC1Polarity\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Prescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Filter\fP"
.br
.ti -1c
.RI "uint32_t \fBCommutation_Delay\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Hall sensor Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_tim_ex\&.h 第 48 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Commutation_Delay"
Specifies the pulse value to be loaded into the Capture Compare Register\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF 
.PP
在文件 stm32f4xx_hal_tim_ex\&.h 第 59 行定义\&.
.SS "uint32_t IC1Filter"
Specifies the input capture filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.PP
在文件 stm32f4xx_hal_tim_ex\&.h 第 56 行定义\&.
.SS "uint32_t IC1Polarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Input Capture Polarity\fP 
.PP
在文件 stm32f4xx_hal_tim_ex\&.h 第 50 行定义\&.
.SS "uint32_t IC1Prescaler"
Specifies the Input Capture Prescaler\&. This parameter can be a value of \fBTIM Input Capture Prescaler\fP 
.PP
在文件 stm32f4xx_hal_tim_ex\&.h 第 53 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
