.TH "TIM_MasterConfigTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_MasterConfigTypeDef \- TIM Master configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBMasterOutputTrigger\fP"
.br
.ti -1c
.RI "uint32_t \fBMasterSlaveMode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Master configuration Structure definition 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 229 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t MasterOutputTrigger"
Trigger output (TRGO) selection This parameter can be a value of \fBTIM Master Mode Selection\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 231 行定义\&.
.SS "uint32_t MasterSlaveMode"
Master/slave mode selection This parameter can be a value of \fBTIM Master/Slave Mode\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 233 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
