.TH "TIM_ClearInputConfigTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInputConfigTypeDef \- TIM Clear Input Configuration Handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBClearInputState\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputSource\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputFilter\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Clear Input Configuration Handle Structure definition 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 212 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t ClearInputFilter"
TIM Clear Input filter This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 222 行定义\&.
.SS "uint32_t ClearInputPolarity"
TIM Clear Input polarity This parameter can be a value of \fBTIM Clear Input Polarity\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 218 行定义\&.
.SS "uint32_t ClearInputPrescaler"
TIM Clear Input prescaler This parameter must be 0: When OCRef clear feature is used with ETR source, ETR prescaler must be off 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 220 行定义\&.
.SS "uint32_t ClearInputSource"
TIM clear Input sources This parameter can be a value of \fBTIM Clear Input Source\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 216 行定义\&.
.SS "uint32_t ClearInputState"
TIM clear Input state This parameter can be ENABLE or DISABLE 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 214 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
