.TH "TIM_Input_Channel_Polarity" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Input_Channel_Polarity
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_INPUTCHANNELPOLARITY_RISING\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP   TIM_CCER_CC1P"
.br
.ti -1c
.RI "#define \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP   (TIM_CCER_CC1P | TIM_CCER_CC1NP)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_INPUTCHANNELPOLARITY_BOTHEDGE   (TIM_CCER_CC1P | TIM_CCER_CC1NP)"
Polarity for TIx source 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 462 行定义\&.
.SS "#define TIM_INPUTCHANNELPOLARITY_FALLING   TIM_CCER_CC1P"
Polarity for TIx source 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 461 行定义\&.
.SS "#define TIM_INPUTCHANNELPOLARITY_RISING   0x00000000U"
Polarity for TIx source 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 460 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
