.TH "TIM_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group2 \- TIM Output Compare functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Init\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_DeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OC_MspInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OC_MspDeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Output Compare functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_DeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Init (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_OC_MspDeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_OC_MspInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Start (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Start_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel, uint32_t * pData, uint16_t Length)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Start_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Stop (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Stop_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_Stop_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
