.TH "TIM_Exported_Functions_Group9" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group9 \- TIM Callbacks functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.RI "Period elapsed callback in non blocking mode "
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OC_DelayElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_ErrorCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Callbacks functions 


.SH "函数说明"
.PP 
.SS "void HAL_TIM_ErrorCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_IC_CaptureCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_IC_CaptureHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_OC_DelayElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PeriodElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.PP
Period elapsed callback in non blocking mode 
.PP
\fB注解\fP
.RS 4
This function is called when TIM6 interrupt took place, inside \fBHAL_TIM_IRQHandler()\fP\&. It makes a direct call to \fBHAL_IncTick()\fP to increment a global variable 'uwTick' used as application time base\&. 
.RE
.PP
\fB参数\fP
.RS 4
\fIhtim\fP TIM handle 
.RE
.PP
\fB返回值\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
在文件 stm32f4xx_hal_timebase_tim_template\&.c 第 144 行定义\&.
.SS "void HAL_TIM_PeriodElapsedHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_PulseFinishedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_PulseFinishedHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_TriggerCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_TriggerHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
