.TH "TIM_Exported_Functions_Group8" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group8 \- Peripheral Control functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OC_ConfigChannel\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_OC_InitTypeDef\fP *sConfig, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_ConfigChannel\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_OC_InitTypeDef\fP *sConfig, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_IC_ConfigChannel\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_IC_InitTypeDef\fP *sConfig, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_ConfigChannel\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_OnePulse_InitTypeDef\fP *sConfig, uint32_t OutputChannel, uint32_t InputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_ConfigOCrefClear\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_ClearInputConfigTypeDef\fP *sClearInputConfig, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_ConfigClockSource\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_ClockConfigTypeDef\fP *sClockSourceConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_ConfigTI1Input\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t TI1_Selection)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_SlaveConfigSynchro\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_SlaveConfigTypeDef\fP *sSlaveConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_SlaveConfigSynchro_IT\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_SlaveConfigTypeDef\fP *sSlaveConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_DMABurst_WriteStart\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t BurstBaseAddress, uint32_t BurstRequestSrc, uint32_t *BurstBuffer, uint32_t BurstLength)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_DMABurst_WriteStop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t BurstRequestSrc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_DMABurst_ReadStart\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t BurstBaseAddress, uint32_t BurstRequestSrc, uint32_t *BurstBuffer, uint32_t BurstLength)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_DMABurst_ReadStop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t BurstRequestSrc)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_GenerateEvent\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t EventSource)"
.br
.ti -1c
.RI "uint32_t \fBHAL_TIM_ReadCapturedValue\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.in -1c
.SH "详细描述"
.PP 
Peripheral Control functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_ConfigClockSource (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_ClockConfigTypeDef\fP * sClockSourceConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_ConfigOCrefClear (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_ClearInputConfigTypeDef\fP * sClearInputConfig, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_ConfigTI1Input (\fBTIM_HandleTypeDef\fP * htim, uint32_t TI1_Selection)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_DMABurst_ReadStart (\fBTIM_HandleTypeDef\fP * htim, uint32_t BurstBaseAddress, uint32_t BurstRequestSrc, uint32_t * BurstBuffer, uint32_t BurstLength)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_DMABurst_ReadStop (\fBTIM_HandleTypeDef\fP * htim, uint32_t BurstRequestSrc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_DMABurst_WriteStart (\fBTIM_HandleTypeDef\fP * htim, uint32_t BurstBaseAddress, uint32_t BurstRequestSrc, uint32_t * BurstBuffer, uint32_t BurstLength)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_DMABurst_WriteStop (\fBTIM_HandleTypeDef\fP * htim, uint32_t BurstRequestSrc)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_GenerateEvent (\fBTIM_HandleTypeDef\fP * htim, uint32_t EventSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_IC_ConfigChannel (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_IC_InitTypeDef\fP * sConfig, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OC_ConfigChannel (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_OC_InitTypeDef\fP * sConfig, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_ConfigChannel (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_OnePulse_InitTypeDef\fP * sConfig, uint32_t OutputChannel, uint32_t InputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_ConfigChannel (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_OC_InitTypeDef\fP * sConfig, uint32_t Channel)"

.SS "uint32_t HAL_TIM_ReadCapturedValue (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_SlaveConfigSynchro (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_SlaveConfigTypeDef\fP * sSlaveConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_SlaveConfigSynchro_IT (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_SlaveConfigTypeDef\fP * sSlaveConfig)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
