.TH "TIM_Exported_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBTIM Peripheral Control functions\fP"
.br
.RI "Peripheral Control functions "
.ti -1c
.RI "\fBTIM Callbacks functions\fP"
.br
.RI "TIM Callbacks functions "
.ti -1c
.RI "\fBTIM Peripheral State functions\fP"
.br
.RI "Peripheral State functions "
.ti -1c
.RI "\fBTIM Time Base functions\fP"
.br
.RI "Time Base functions "
.ti -1c
.RI "\fBTIM Output Compare functions\fP"
.br
.RI "TIM Output Compare functions "
.ti -1c
.RI "\fBTIM PWM functions\fP"
.br
.RI "TIM PWM functions "
.ti -1c
.RI "\fBTIM Input Capture functions\fP"
.br
.RI "TIM Input Capture functions "
.ti -1c
.RI "\fBTIM One Pulse functions\fP"
.br
.RI "TIM One Pulse functions "
.ti -1c
.RI "\fBTIM Encoder functions\fP"
.br
.RI "TIM Encoder functions "
.ti -1c
.RI "\fBTIM IRQ handler management\fP"
.br
.RI "IRQ handler management "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
