.TH "TIM_Clock_Prescaler" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCKPRESCALER_DIV1\fP   \fBTIM_ETRPRESCALER_DIV1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPRESCALER_DIV2\fP   \fBTIM_ETRPRESCALER_DIV2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPRESCALER_DIV4\fP   \fBTIM_ETRPRESCALER_DIV4\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPRESCALER_DIV8\fP   \fBTIM_ETRPRESCALER_DIV8\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_CLOCKPRESCALER_DIV1   \fBTIM_ETRPRESCALER_DIV1\fP"
No prescaler is used 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 735 行定义\&.
.SS "#define TIM_CLOCKPRESCALER_DIV2   \fBTIM_ETRPRESCALER_DIV2\fP"
Prescaler for External ETR Clock: Capture performed once every 2 events\&. 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 736 行定义\&.
.SS "#define TIM_CLOCKPRESCALER_DIV4   \fBTIM_ETRPRESCALER_DIV4\fP"
Prescaler for External ETR Clock: Capture performed once every 4 events\&. 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 737 行定义\&.
.SS "#define TIM_CLOCKPRESCALER_DIV8   \fBTIM_ETRPRESCALER_DIV8\fP"
Prescaler for External ETR Clock: Capture performed once every 8 events\&. 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 738 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
