.TH "TIM_Output_Compare_N_Idle_State" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_N_Idle_State
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCNIDLESTATE_SET\fP   TIM_CR2_OIS1N"
.br
.ti -1c
.RI "#define \fBTIM_OCNIDLESTATE_RESET\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_OCNIDLESTATE_RESET   0x00000000U"
Complementary output Idle state: OCxN=0 when MOE=0 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 577 行定义\&.
.SS "#define TIM_OCNIDLESTATE_SET   TIM_CR2_OIS1N"
Complementary output Idle state: OCxN=1 when MOE=0 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 576 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
