.TH "TIM_AutoReloadPreload" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_AutoReloadPreload
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_AUTORELOAD_PRELOAD_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_AUTORELOAD_PRELOAD_ENABLE\fP   TIM_CR1_ARPE"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_AUTORELOAD_PRELOAD_DISABLE   0x00000000U"
TIMx_ARR register is not buffered 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 521 行定义\&.
.SS "#define TIM_AUTORELOAD_PRELOAD_ENABLE   TIM_CR1_ARPE"
TIMx_ARR register is buffered 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 522 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
