.TH "TIM_OC_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_OC_InitTypeDef \- TIM Output Compare Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBOCMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPulse\fP"
.br
.ti -1c
.RI "uint32_t \fBOCPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBOCNPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBOCFastMode\fP"
.br
.ti -1c
.RI "uint32_t \fBOCIdleState\fP"
.br
.ti -1c
.RI "uint32_t \fBOCNIdleState\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Output Compare Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 78 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t OCFastMode"
Specifies the Fast mode state\&. This parameter can be a value of \fBTIM Output Fast State\fP 
.PP
\fB注解\fP
.RS 4
This parameter is valid only in PWM1 and PWM2 mode\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 93 行定义\&.
.SS "uint32_t OCIdleState"
Specifies the TIM Output Compare pin state during Idle state\&. This parameter can be a value of \fBTIM Output Compare Idle State\fP 
.PP
\fB注解\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 98 行定义\&.
.SS "uint32_t OCMode"
Specifies the TIM mode\&. This parameter can be a value of \fBTIM Output Compare and PWM Modes\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 80 行定义\&.
.SS "uint32_t OCNIdleState"
Specifies the TIM Output Compare pin state during Idle state\&. This parameter can be a value of \fBTIM Complementary Output Compare Idle State\fP 
.PP
\fB注解\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 102 行定义\&.
.SS "uint32_t OCNPolarity"
Specifies the complementary output polarity\&. This parameter can be a value of \fBTIM Complementary Output Compare Polarity\fP 
.PP
\fB注解\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 89 行定义\&.
.SS "uint32_t OCPolarity"
Specifies the output polarity\&. This parameter can be a value of \fBTIM Output Compare Polarity\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 86 行定义\&.
.SS "uint32_t Pulse"
Specifies the pulse value to be loaded into the Capture Compare Register\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 83 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
