.TH "TIM_Trigger_Selection" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Trigger_Selection
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_TS_ITR0\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TS_ITR1\fP   TIM_SMCR_TS_0"
.br
.ti -1c
.RI "#define \fBTIM_TS_ITR2\fP   TIM_SMCR_TS_1"
.br
.ti -1c
.RI "#define \fBTIM_TS_ITR3\fP   (TIM_SMCR_TS_0 | TIM_SMCR_TS_1)"
.br
.ti -1c
.RI "#define \fBTIM_TS_TI1F_ED\fP   TIM_SMCR_TS_2"
.br
.ti -1c
.RI "#define \fBTIM_TS_TI1FP1\fP   (TIM_SMCR_TS_0 | TIM_SMCR_TS_2)"
.br
.ti -1c
.RI "#define \fBTIM_TS_TI2FP2\fP   (TIM_SMCR_TS_1 | TIM_SMCR_TS_2)"
.br
.ti -1c
.RI "#define \fBTIM_TS_ETRF\fP   (TIM_SMCR_TS_0 | TIM_SMCR_TS_1 | TIM_SMCR_TS_2)"
.br
.ti -1c
.RI "#define \fBTIM_TS_NONE\fP   0x0000FFFFU"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_TS_ETRF   (TIM_SMCR_TS_0 | TIM_SMCR_TS_1 | TIM_SMCR_TS_2)"
Filtered External Trigger input (ETRF) 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 880 行定义\&.
.SS "#define TIM_TS_ITR0   0x00000000U"
Internal Trigger 0 (ITR0) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 873 行定义\&.
.SS "#define TIM_TS_ITR1   TIM_SMCR_TS_0"
Internal Trigger 1 (ITR1) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 874 行定义\&.
.SS "#define TIM_TS_ITR2   TIM_SMCR_TS_1"
Internal Trigger 2 (ITR2) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 875 行定义\&.
.SS "#define TIM_TS_ITR3   (TIM_SMCR_TS_0 | TIM_SMCR_TS_1)"
Internal Trigger 3 (ITR3) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 876 行定义\&.
.SS "#define TIM_TS_NONE   0x0000FFFFU"
No trigger selected 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 881 行定义\&.
.SS "#define TIM_TS_TI1F_ED   TIM_SMCR_TS_2"
TI1 Edge Detector (TI1F_ED) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 877 行定义\&.
.SS "#define TIM_TS_TI1FP1   (TIM_SMCR_TS_0 | TIM_SMCR_TS_2)"
Filtered Timer Input 1 (TI1FP1) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 878 行定义\&.
.SS "#define TIM_TS_TI2FP2   (TIM_SMCR_TS_1 | TIM_SMCR_TS_2)"
Filtered Timer Input 2 (TI2FP2) 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 879 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
