.TH "TIM_Master_Slave_Mode" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Master_Slave_Mode
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_MASTERSLAVEMODE_ENABLE\fP   TIM_SMCR_MSM"
.br
.ti -1c
.RI "#define \fBTIM_MASTERSLAVEMODE_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_MASTERSLAVEMODE_DISABLE   0x00000000U"
Master/slave mode is selected 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 838 行定义\&.
.SS "#define TIM_MASTERSLAVEMODE_ENABLE   TIM_SMCR_MSM"
No action 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 837 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
