.TH "TIM_Event_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Event_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_UPDATE\fP   TIM_EGR_UG"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC1\fP   TIM_EGR_CC1G"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC2\fP   TIM_EGR_CC2G"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC3\fP   TIM_EGR_CC3G"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC4\fP   TIM_EGR_CC4G"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_COM\fP   TIM_EGR_COMG"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_TRIGGER\fP   TIM_EGR_TG"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_BREAK\fP   TIM_EGR_BG"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_EVENTSOURCE_BREAK   TIM_EGR_BG"
A break event is generated 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 452 行定义\&.
.SS "#define TIM_EVENTSOURCE_CC1   TIM_EGR_CC1G"
A capture/compare event is generated on channel 1 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 446 行定义\&.
.SS "#define TIM_EVENTSOURCE_CC2   TIM_EGR_CC2G"
A capture/compare event is generated on channel 2 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 447 行定义\&.
.SS "#define TIM_EVENTSOURCE_CC3   TIM_EGR_CC3G"
A capture/compare event is generated on channel 3 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 448 行定义\&.
.SS "#define TIM_EVENTSOURCE_CC4   TIM_EGR_CC4G"
A capture/compare event is generated on channel 4 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 449 行定义\&.
.SS "#define TIM_EVENTSOURCE_COM   TIM_EGR_COMG"
A commutation event is generated 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 450 行定义\&.
.SS "#define TIM_EVENTSOURCE_TRIGGER   TIM_EGR_TG"
A trigger event is generated 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 451 行定义\&.
.SS "#define TIM_EVENTSOURCE_UPDATE   TIM_EGR_UG"
Reinitialize the counter and generates an update of the registers 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 445 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
