.TH "TIM_BreakDeadTimeConfigTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_BreakDeadTimeConfigTypeDef \- TIM Break input(s) and Dead time configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBOffStateRunMode\fP"
.br
.ti -1c
.RI "uint32_t \fBOffStateIDLEMode\fP"
.br
.ti -1c
.RI "uint32_t \fBLockLevel\fP"
.br
.ti -1c
.RI "uint32_t \fBDeadTime\fP"
.br
.ti -1c
.RI "uint32_t \fBBreakState\fP"
.br
.ti -1c
.RI "uint32_t \fBBreakPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBBreakFilter\fP"
.br
.ti -1c
.RI "uint32_t \fBAutomaticOutput\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Break input(s) and Dead time configuration Structure definition 


.PP
\fB注解\fP
.RS 4
2 break inputs can be configured (BKIN and BKIN2) with configurable filter and polarity\&. 
.RE
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 260 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AutomaticOutput"
TIM Automatic Output Enable state This parameter can be a value of \fBTIM Automatic Output Enable\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 276 行定义\&.
.SS "uint32_t BreakFilter"
Specifies the break input filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 274 行定义\&.
.SS "uint32_t BreakPolarity"
TIM Break input polarity This parameter can be a value of \fBTIM Break Input Polarity\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 272 行定义\&.
.SS "uint32_t BreakState"
TIM Break State This parameter can be a value of \fBTIM Break Input Enable\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 270 行定义\&.
.SS "uint32_t DeadTime"
TIM dead Time This parameter can be a number between Min_Data = 0x00 and Max_Data = 0xFF 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 268 行定义\&.
.SS "uint32_t LockLevel"
TIM Lock level This parameter can be a value of \fBTIM Lock level\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 266 行定义\&.
.SS "uint32_t OffStateIDLEMode"
TIM off state in IDLE mode This parameter can be a value of \fBTIM OSSI OffState Selection for Idle mode state\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 264 行定义\&.
.SS "uint32_t OffStateRunMode"
TIM off state in run mode This parameter can be a value of \fBTIM OSSR OffState Selection for Run mode state\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 262 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
