.TH "TIM_Base_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Base_InitTypeDef \- TIM Time base Configuration Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_tim\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBCounterMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPeriod\fP"
.br
.ti -1c
.RI "uint32_t \fBClockDivision\fP"
.br
.ti -1c
.RI "uint32_t \fBRepetitionCounter\fP"
.br
.ti -1c
.RI "uint32_t \fBAutoReloadPreload\fP"
.br
.in -1c
.SH "详细描述"
.PP 
TIM Time base Configuration Structure definition 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 47 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t AutoReloadPreload"
Specifies the auto-reload preload\&. This parameter can be a value of \fBTIM Auto-Reload Preload\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 71 行定义\&.
.SS "uint32_t ClockDivision"
Specifies the clock division\&. This parameter can be a value of \fBTIM Clock Division\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 59 行定义\&.
.SS "uint32_t CounterMode"
Specifies the counter mode\&. This parameter can be a value of \fBTIM Counter Mode\fP 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 52 行定义\&.
.SS "uint32_t Period"
Specifies the period value to be loaded into the active Auto-Reload Register at the next update event\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF\&. 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 55 行定义\&.
.SS "uint32_t Prescaler"
Specifies the prescaler value used to divide the TIM clock\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 49 行定义\&.
.SS "uint32_t RepetitionCounter"
Specifies the repetition counter value\&. Each time the RCR downcounter reaches zero, an update event is generated and counting restarts from the RCR value (N)\&. This means in PWM mode that (N+1) corresponds to:
.IP "\(bu" 2
the number of PWM periods in edge-aligned mode
.IP "\(bu" 2
the number of half PWM period in center-aligned mode GP timers: this parameter must be a number between Min_Data = 0x00 and Max_Data = 0xFF\&. Advanced timers: this parameter must be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF\&. 
.PP

.PP
在文件 stm32f4xx_hal_tim\&.h 第 62 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
