.TH "TIM_Commutation_Source" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Commutation_Source
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_COMMUTATION_TRGI\fP   TIM_CR2_CCUS"
.br
.ti -1c
.RI "#define \fBTIM_COMMUTATION_SOFTWARE\fP   0x00000000U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_COMMUTATION_SOFTWARE   0x00000000U"
When Capture/compare control bits are preloaded, they are updated by setting the COMG bit 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 653 行定义\&.
.SS "#define TIM_COMMUTATION_TRGI   TIM_CR2_CCUS"
When Capture/compare control bits are preloaded, they are updated by setting the COMG bit or when an rising edge occurs on trigger input 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 652 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
