.TH "TIM_DMA_Burst_Length" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_Burst_Length
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_1TRANSFER\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_2TRANSFERS\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_3TRANSFERS\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_4TRANSFERS\fP   0x00000300U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_5TRANSFERS\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_6TRANSFERS\fP   0x00000500U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_7TRANSFERS\fP   0x00000600U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_8TRANSFERS\fP   0x00000700U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_9TRANSFERS\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_10TRANSFERS\fP   0x00000900U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_11TRANSFERS\fP   0x00000A00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_12TRANSFERS\fP   0x00000B00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_13TRANSFERS\fP   0x00000C00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_14TRANSFERS\fP   0x00000D00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_15TRANSFERS\fP   0x00000E00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_16TRANSFERS\fP   0x00000F00U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_17TRANSFERS\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBTIM_DMABURSTLENGTH_18TRANSFERS\fP   0x00001100U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define TIM_DMABURSTLENGTH_10TRANSFERS   0x00000900U"
The transfer is done to 10 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 930 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_11TRANSFERS   0x00000A00U"
The transfer is done to 11 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 931 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_12TRANSFERS   0x00000B00U"
The transfer is done to 12 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 932 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_13TRANSFERS   0x00000C00U"
The transfer is done to 13 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 933 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_14TRANSFERS   0x00000D00U"
The transfer is done to 14 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 934 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_15TRANSFERS   0x00000E00U"
The transfer is done to 15 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 935 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_16TRANSFERS   0x00000F00U"
The transfer is done to 16 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 936 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_17TRANSFERS   0x00001000U"
The transfer is done to 17 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 937 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_18TRANSFERS   0x00001100U"
The transfer is done to 18 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 938 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_1TRANSFER   0x00000000U"
The transfer is done to 1 register starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 921 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_2TRANSFERS   0x00000100U"
The transfer is done to 2 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 922 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_3TRANSFERS   0x00000200U"
The transfer is done to 3 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 923 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_4TRANSFERS   0x00000300U"
The transfer is done to 4 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 924 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_5TRANSFERS   0x00000400U"
The transfer is done to 5 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 925 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_6TRANSFERS   0x00000500U"
The transfer is done to 6 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 926 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_7TRANSFERS   0x00000600U"
The transfer is done to 7 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 927 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_8TRANSFERS   0x00000700U"
The transfer is done to 8 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 928 行定义\&.
.SS "#define TIM_DMABURSTLENGTH_9TRANSFERS   0x00000800U"
The transfer is done to 9 registers starting trom TIMx_CR1 + TIMx_DCR\&.DBA 
.br
 
.PP
在文件 stm32f4xx_hal_tim\&.h 第 929 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
