.TH "TIM_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_TIM_CLEARINPUT_SOURCE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_BASE\fP(__BASE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_EVENT_SOURCE\fP(__SOURCE__)   ((((__SOURCE__) & 0xFFFFFF00U) == 0x00000000U) && ((__SOURCE__) != 0x00000000U))"
.br
.ti -1c
.RI "#define \fBIS_TIM_COUNTER_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKDIVISION_DIV\fP(__DIV__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_AUTORELOAD_PRELOAD\fP(PRELOAD)"
.br
.ti -1c
.RI "#define \fBIS_TIM_FAST_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OC_POLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCN_POLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCIDLE_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCNIDLE_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_IC_POLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_IC_SELECTION\fP(__SELECTION__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_IC_PRESCALER\fP(__PRESCALER__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OPM_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_ENCODER_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_SOURCE\fP(__SOURCE__)   ((((__SOURCE__) & 0xFFFF80FFU) == 0x00000000U) && ((__SOURCE__) != 0x00000000U))"
.br
.ti -1c
.RI "#define \fBIS_TIM_CHANNELS\fP(__CHANNEL__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OPM_CHANNELS\fP(__CHANNEL__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_COMPLEMENTARY_CHANNELS\fP(__CHANNEL__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKSOURCE\fP(__CLOCK__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKPOLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKPRESCALER\fP(__PRESCALER__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLOCKFILTER\fP(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLEARINPUT_POLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLEARINPUT_PRESCALER\fP(__PRESCALER__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLEARINPUT_FILTER\fP(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OSSR_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OSSI_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LOCK_LEVEL\fP(__LEVEL__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_BREAK_FILTER\fP(__BRKFILTER__)   ((__BRKFILTER__) <= 0xFUL)"
.br
.ti -1c
.RI "#define \fBIS_TIM_BREAK_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_BREAK_POLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_AUTOMATIC_OUTPUT_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRGO_SOURCE\fP(__SOURCE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_MSM_STATE\fP(__STATE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_SLAVE_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_PWM_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OC_MODE\fP(__MODE__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRIGGER_SELECTION\fP(__SELECTION__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_INTERNAL_TRIGGEREVENT_SELECTION\fP(__SELECTION__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRIGGERPOLARITY\fP(__POLARITY__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRIGGERPRESCALER\fP(__PRESCALER__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRIGGERFILTER\fP(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TI1SELECTION\fP(__TI1SELECTION__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_LENGTH\fP(__LENGTH__)"
.br
.ti -1c
.RI "#define \fBIS_TIM_IC_FILTER\fP(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DEADTIME\fP(__DEADTIME__)   ((__DEADTIME__) <= 0xFFU)"
.br
.ti -1c
.RI "#define \fBIS_TIM_SLAVEMODE_TRIGGER_ENABLED\fP(__TRIGGER__)   ((__TRIGGER__) == \fBTIM_SLAVEMODE_TRIGGER\fP)"
.br
.ti -1c
.RI "#define \fBTIM_SET_ICPRESCALERVALUE\fP(__HANDLE__,  __CHANNEL__,  __ICPSC__)"
.br
.ti -1c
.RI "#define \fBTIM_RESET_ICPRESCALERVALUE\fP(__HANDLE__,  __CHANNEL__)"
.br
.ti -1c
.RI "#define \fBTIM_SET_CAPTUREPOLARITY\fP(__HANDLE__,  __CHANNEL__,  __POLARITY__)"
.br
.ti -1c
.RI "#define \fBTIM_RESET_CAPTUREPOLARITY\fP(__HANDLE__,  __CHANNEL__)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_TIM_AUTOMATIC_OUTPUT_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                                  (((__STATE__) == TIM_AUTOMATICOUTPUT_ENABLE) || \
                                                  ((__STATE__) == TIM_AUTOMATICOUTPUT_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1597 行定义\&.
.SS "#define IS_TIM_AUTORELOAD_PRELOAD(PRELOAD)"
\fB值:\fP
.PP
.nf
                                            (((PRELOAD) == TIM_AUTORELOAD_PRELOAD_DISABLE) || \
                                            ((PRELOAD) == TIM_AUTORELOAD_PRELOAD_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1490 行定义\&.
.SS "#define IS_TIM_BREAK_FILTER(__BRKFILTER__)   ((__BRKFILTER__) <= 0xFUL)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1588 行定义\&.
.SS "#define IS_TIM_BREAK_POLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                             (((__POLARITY__) == TIM_BREAKPOLARITY_LOW) || \
                                             ((__POLARITY__) == TIM_BREAKPOLARITY_HIGH))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1594 行定义\&.
.SS "#define IS_TIM_BREAK_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_BREAK_ENABLE) || \
                                            ((__STATE__) == TIM_BREAK_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1591 行定义\&.
.SS "#define IS_TIM_CHANNELS(__CHANNEL__)"
\fB值:\fP
.PP
.nf
                                            (((__CHANNEL__) == TIM_CHANNEL_1) || \
                                            ((__CHANNEL__) == TIM_CHANNEL_2) || \
                                            ((__CHANNEL__) == TIM_CHANNEL_3) || \
                                            ((__CHANNEL__) == TIM_CHANNEL_4) || \
                                            ((__CHANNEL__) == TIM_CHANNEL_ALL))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1530 行定义\&.
.SS "#define IS_TIM_CLEARINPUT_FILTER(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1575 行定义\&.
.SS "#define IS_TIM_CLEARINPUT_POLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                                  (((__POLARITY__) == TIM_CLEARINPUTPOLARITY_INVERTED) || \
                                                  ((__POLARITY__) == TIM_CLEARINPUTPOLARITY_NONINVERTED))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1567 行定义\&.
.SS "#define IS_TIM_CLEARINPUT_PRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                                    (((__PRESCALER__) == TIM_CLEARINPUTPRESCALER_DIV1) || \
                                                    ((__PRESCALER__) == TIM_CLEARINPUTPRESCALER_DIV2) || \
                                                    ((__PRESCALER__) == TIM_CLEARINPUTPRESCALER_DIV4) || \
                                                    ((__PRESCALER__) == TIM_CLEARINPUTPRESCALER_DIV8))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1570 行定义\&.
.SS "#define IS_TIM_CLEARINPUT_SOURCE(__MODE__)"
\fB值:\fP
.PP
.nf
                                             (((__MODE__) == TIM_CLEARINPUTSOURCE_NONE)      || \
                                             ((__MODE__) == TIM_CLEARINPUTSOURCE_ETR))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1456 行定义\&.
.SS "#define IS_TIM_CLOCKDIVISION_DIV(__DIV__)"
\fB值:\fP
.PP
.nf
                                            (((__DIV__) == TIM_CLOCKDIVISION_DIV1) || \
                                            ((__DIV__) == TIM_CLOCKDIVISION_DIV2) || \
                                            ((__DIV__) == TIM_CLOCKDIVISION_DIV4))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1486 行定义\&.
.SS "#define IS_TIM_CLOCKFILTER(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1565 行定义\&.
.SS "#define IS_TIM_CLOCKPOLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                            (((__POLARITY__) == TIM_CLOCKPOLARITY_INVERTED)    || \
                                            ((__POLARITY__) == TIM_CLOCKPOLARITY_NONINVERTED) || \
                                            ((__POLARITY__) == TIM_CLOCKPOLARITY_RISING)      || \
                                            ((__POLARITY__) == TIM_CLOCKPOLARITY_FALLING)     || \
                                            ((__POLARITY__) == TIM_CLOCKPOLARITY_BOTHEDGE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1554 行定义\&.
.SS "#define IS_TIM_CLOCKPRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                              (((__PRESCALER__) == TIM_CLOCKPRESCALER_DIV1) || \
                                              ((__PRESCALER__) == TIM_CLOCKPRESCALER_DIV2) || \
                                              ((__PRESCALER__) == TIM_CLOCKPRESCALER_DIV4) || \
                                              ((__PRESCALER__) == TIM_CLOCKPRESCALER_DIV8))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1560 行定义\&.
.SS "#define IS_TIM_CLOCKSOURCE(__CLOCK__)"
\fB值:\fP
.PP
.nf
                                       (((__CLOCK__) == TIM_CLOCKSOURCE_INTERNAL) || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ETRMODE2) || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ITR0)     || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ITR1)     || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ITR2)     || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ITR3)     || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_TI1ED)    || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_TI1)      || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_TI2)      || \
                                       ((__CLOCK__) == TIM_CLOCKSOURCE_ETRMODE1))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1543 行定义\&.
.SS "#define IS_TIM_COMPLEMENTARY_CHANNELS(__CHANNEL__)"
\fB值:\fP
.PP
.nf
                                                    (((__CHANNEL__) == TIM_CHANNEL_1) || \
                                                    ((__CHANNEL__) == TIM_CHANNEL_2) || \
                                                    ((__CHANNEL__) == TIM_CHANNEL_3))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1539 行定义\&.
.SS "#define IS_TIM_COUNTER_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                            (((__MODE__) == TIM_COUNTERMODE_UP)              || \
                                            ((__MODE__) == TIM_COUNTERMODE_DOWN)            || \
                                            ((__MODE__) == TIM_COUNTERMODE_CENTERALIGNED1)  || \
                                            ((__MODE__) == TIM_COUNTERMODE_CENTERALIGNED2)  || \
                                            ((__MODE__) == TIM_COUNTERMODE_CENTERALIGNED3))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1480 行定义\&.
.SS "#define IS_TIM_DEADTIME(__DEADTIME__)   ((__DEADTIME__) <= 0xFFU)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1680 行定义\&.
.SS "#define IS_TIM_DMA_BASE(__BASE__)"
\fB值:\fP
.PP
.nf
                                   (((__BASE__) == TIM_DMABASE_CR1)   || \
                                   ((__BASE__) == TIM_DMABASE_CR2)   || \
                                   ((__BASE__) == TIM_DMABASE_SMCR)  || \
                                   ((__BASE__) == TIM_DMABASE_DIER)  || \
                                   ((__BASE__) == TIM_DMABASE_SR)    || \
                                   ((__BASE__) == TIM_DMABASE_EGR)   || \
                                   ((__BASE__) == TIM_DMABASE_CCMR1) || \
                                   ((__BASE__) == TIM_DMABASE_CCMR2) || \
                                   ((__BASE__) == TIM_DMABASE_CCER)  || \
                                   ((__BASE__) == TIM_DMABASE_CNT)   || \
                                   ((__BASE__) == TIM_DMABASE_PSC)   || \
                                   ((__BASE__) == TIM_DMABASE_ARR)   || \
                                   ((__BASE__) == TIM_DMABASE_RCR)   || \
                                   ((__BASE__) == TIM_DMABASE_CCR1)  || \
                                   ((__BASE__) == TIM_DMABASE_CCR2)  || \
                                   ((__BASE__) == TIM_DMABASE_CCR3)  || \
                                   ((__BASE__) == TIM_DMABASE_CCR4)  || \
                                   ((__BASE__) == TIM_DMABASE_BDTR))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1459 行定义\&.
.SS "#define IS_TIM_DMA_LENGTH(__LENGTH__)"
\fB值:\fP
.PP
.nf
                                            (((__LENGTH__) == TIM_DMABURSTLENGTH_1TRANSFER) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_2TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_3TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_4TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_5TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_6TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_7TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_8TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_9TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_10TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_11TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_12TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_13TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_14TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_15TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_16TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_17TRANSFERS) || \
                                            ((__LENGTH__) == TIM_DMABURSTLENGTH_18TRANSFERS))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1659 行定义\&.
.SS "#define IS_TIM_DMA_SOURCE(__SOURCE__)   ((((__SOURCE__) & 0xFFFF80FFU) == 0x00000000U) && ((__SOURCE__) != 0x00000000U))"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1528 行定义\&.
.SS "#define IS_TIM_ENCODER_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                            (((__MODE__) == TIM_ENCODERMODE_TI1) || \
                                            ((__MODE__) == TIM_ENCODERMODE_TI2) || \
                                            ((__MODE__) == TIM_ENCODERMODE_TI12))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1524 行定义\&.
.SS "#define IS_TIM_EVENT_SOURCE(__SOURCE__)   ((((__SOURCE__) & 0xFFFFFF00U) == 0x00000000U) && ((__SOURCE__) != 0x00000000U))"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1478 行定义\&.
.SS "#define IS_TIM_FAST_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_OCFAST_DISABLE) || \
                                            ((__STATE__) == TIM_OCFAST_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1493 行定义\&.
.SS "#define IS_TIM_IC_FILTER(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1678 行定义\&.
.SS "#define IS_TIM_IC_POLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                            (((__POLARITY__) == TIM_ICPOLARITY_RISING)   || \
                                            ((__POLARITY__) == TIM_ICPOLARITY_FALLING)  || \
                                            ((__POLARITY__) == TIM_ICPOLARITY_BOTHEDGE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1508 行定义\&.
.SS "#define IS_TIM_IC_PRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                            (((__PRESCALER__) == TIM_ICPSC_DIV1) || \
                                            ((__PRESCALER__) == TIM_ICPSC_DIV2) || \
                                            ((__PRESCALER__) == TIM_ICPSC_DIV4) || \
                                            ((__PRESCALER__) == TIM_ICPSC_DIV8))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1516 行定义\&.
.SS "#define IS_TIM_IC_SELECTION(__SELECTION__)"
\fB值:\fP
.PP
.nf
                                            (((__SELECTION__) == TIM_ICSELECTION_DIRECTTI) || \
                                            ((__SELECTION__) == TIM_ICSELECTION_INDIRECTTI) || \
                                            ((__SELECTION__) == TIM_ICSELECTION_TRC))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1512 行定义\&.
.SS "#define IS_TIM_INTERNAL_TRIGGEREVENT_SELECTION(__SELECTION__)"
\fB值:\fP
.PP
.nf
                                                               (((__SELECTION__) == TIM_TS_ITR0) || \
                                                               ((__SELECTION__) == TIM_TS_ITR1) || \
                                                               ((__SELECTION__) == TIM_TS_ITR2) || \
                                                               ((__SELECTION__) == TIM_TS_ITR3) || \
                                                               ((__SELECTION__) == TIM_TS_NONE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1637 行定义\&.
.SS "#define IS_TIM_LOCK_LEVEL(__LEVEL__)"
\fB值:\fP
.PP
.nf
                                            (((__LEVEL__) == TIM_LOCKLEVEL_OFF) || \
                                            ((__LEVEL__) == TIM_LOCKLEVEL_1)   || \
                                            ((__LEVEL__) == TIM_LOCKLEVEL_2)   || \
                                            ((__LEVEL__) == TIM_LOCKLEVEL_3))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1583 行定义\&.
.SS "#define IS_TIM_MSM_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                          (((__STATE__) == TIM_MASTERSLAVEMODE_ENABLE) || \
                                          ((__STATE__) == TIM_MASTERSLAVEMODE_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1609 行定义\&.
.SS "#define IS_TIM_OC_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                   (((__MODE__) == TIM_OCMODE_TIMING)             || \
                                   ((__MODE__) == TIM_OCMODE_ACTIVE)             || \
                                   ((__MODE__) == TIM_OCMODE_INACTIVE)           || \
                                   ((__MODE__) == TIM_OCMODE_TOGGLE)             || \
                                   ((__MODE__) == TIM_OCMODE_FORCED_ACTIVE)      || \
                                   ((__MODE__) == TIM_OCMODE_FORCED_INACTIVE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1621 行定义\&.
.SS "#define IS_TIM_OC_POLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                            (((__POLARITY__) == TIM_OCPOLARITY_HIGH) || \
                                            ((__POLARITY__) == TIM_OCPOLARITY_LOW))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1496 行定义\&.
.SS "#define IS_TIM_OCIDLE_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_OCIDLESTATE_SET) || \
                                            ((__STATE__) == TIM_OCIDLESTATE_RESET))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1502 行定义\&.
.SS "#define IS_TIM_OCN_POLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                            (((__POLARITY__) == TIM_OCNPOLARITY_HIGH) || \
                                            ((__POLARITY__) == TIM_OCNPOLARITY_LOW))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1499 行定义\&.
.SS "#define IS_TIM_OCNIDLE_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_OCNIDLESTATE_SET) || \
                                            ((__STATE__) == TIM_OCNIDLESTATE_RESET))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1505 行定义\&.
.SS "#define IS_TIM_OPM_CHANNELS(__CHANNEL__)"
\fB值:\fP
.PP
.nf
                                            (((__CHANNEL__) == TIM_CHANNEL_1) || \
                                            ((__CHANNEL__) == TIM_CHANNEL_2))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1536 行定义\&.
.SS "#define IS_TIM_OPM_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                            (((__MODE__) == TIM_OPMODE_SINGLE) || \
                                            ((__MODE__) == TIM_OPMODE_REPETITIVE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1521 行定义\&.
.SS "#define IS_TIM_OSSI_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_OSSI_ENABLE) || \
                                            ((__STATE__) == TIM_OSSI_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1580 行定义\&.
.SS "#define IS_TIM_OSSR_STATE(__STATE__)"
\fB值:\fP
.PP
.nf
                                            (((__STATE__) == TIM_OSSR_ENABLE) || \
                                            ((__STATE__) == TIM_OSSR_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1577 行定义\&.
.SS "#define IS_TIM_PWM_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                   (((__MODE__) == TIM_OCMODE_PWM1)               || \
                                   ((__MODE__) == TIM_OCMODE_PWM2))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1618 行定义\&.
.SS "#define IS_TIM_SLAVE_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                     (((__MODE__) == TIM_SLAVEMODE_DISABLE)   || \
                                     ((__MODE__) == TIM_SLAVEMODE_RESET)     || \
                                     ((__MODE__) == TIM_SLAVEMODE_GATED)     || \
                                     ((__MODE__) == TIM_SLAVEMODE_TRIGGER)   || \
                                     ((__MODE__) == TIM_SLAVEMODE_EXTERNAL1))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1612 行定义\&.
.SS "#define IS_TIM_SLAVEMODE_TRIGGER_ENABLED(__TRIGGER__)   ((__TRIGGER__) == \fBTIM_SLAVEMODE_TRIGGER\fP)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1682 行定义\&.
.SS "#define IS_TIM_TI1SELECTION(__TI1SELECTION__)"
\fB值:\fP
.PP
.nf
                                                (((__TI1SELECTION__) == TIM_TI1SELECTION_CH1) || \
                                                ((__TI1SELECTION__) == TIM_TI1SELECTION_XORCOMBINATION))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1656 行定义\&.
.SS "#define IS_TIM_TRGO_SOURCE(__SOURCE__)"
\fB值:\fP
.PP
.nf
                                        (((__SOURCE__) == TIM_TRGO_RESET)  || \
                                        ((__SOURCE__) == TIM_TRGO_ENABLE) || \
                                        ((__SOURCE__) == TIM_TRGO_UPDATE) || \
                                        ((__SOURCE__) == TIM_TRGO_OC1)    || \
                                        ((__SOURCE__) == TIM_TRGO_OC1REF) || \
                                        ((__SOURCE__) == TIM_TRGO_OC2REF) || \
                                        ((__SOURCE__) == TIM_TRGO_OC3REF) || \
                                        ((__SOURCE__) == TIM_TRGO_OC4REF))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1600 行定义\&.
.SS "#define IS_TIM_TRIGGER_SELECTION(__SELECTION__)"
\fB值:\fP
.PP
.nf
                                                 (((__SELECTION__) == TIM_TS_ITR0) || \
                                                 ((__SELECTION__) == TIM_TS_ITR1) || \
                                                 ((__SELECTION__) == TIM_TS_ITR2) || \
                                                 ((__SELECTION__) == TIM_TS_ITR3) || \
                                                 ((__SELECTION__) == TIM_TS_TI1F_ED) || \
                                                 ((__SELECTION__) == TIM_TS_TI1FP1) || \
                                                 ((__SELECTION__) == TIM_TS_TI2FP2) || \
                                                 ((__SELECTION__) == TIM_TS_ETRF))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1628 行定义\&.
.SS "#define IS_TIM_TRIGGERFILTER(__ICFILTER__)   ((__ICFILTER__) <= 0xFU)"

.PP
在文件 stm32f4xx_hal_tim\&.h 第 1654 行定义\&.
.SS "#define IS_TIM_TRIGGERPOLARITY(__POLARITY__)"
\fB值:\fP
.PP
.nf
                                                (((__POLARITY__) == TIM_TRIGGERPOLARITY_INVERTED   ) || \
                                                ((__POLARITY__) == TIM_TRIGGERPOLARITY_NONINVERTED) || \
                                                ((__POLARITY__) == TIM_TRIGGERPOLARITY_RISING     ) || \
                                                ((__POLARITY__) == TIM_TRIGGERPOLARITY_FALLING    ) || \
                                                ((__POLARITY__) == TIM_TRIGGERPOLARITY_BOTHEDGE   ))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1643 行定义\&.
.SS "#define IS_TIM_TRIGGERPRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                                (((__PRESCALER__) == TIM_TRIGGERPRESCALER_DIV1) || \
                                                ((__PRESCALER__) == TIM_TRIGGERPRESCALER_DIV2) || \
                                                ((__PRESCALER__) == TIM_TRIGGERPRESCALER_DIV4) || \
                                                ((__PRESCALER__) == TIM_TRIGGERPRESCALER_DIV8))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1649 行定义\&.
.SS "#define TIM_RESET_CAPTUREPOLARITY(__HANDLE__, __CHANNEL__)"
\fB值:\fP
.PP
.nf
(((__CHANNEL__) == TIM_CHANNEL_1) ? ((__HANDLE__)->Instance->CCER &= (uint16_t)~(TIM_CCER_CC1P | TIM_CCER_CC1NP)) :\
 ((__CHANNEL__) == TIM_CHANNEL_2) ? ((__HANDLE__)->Instance->CCER &= (uint16_t)~(TIM_CCER_CC2P | TIM_CCER_CC2NP)) :\
 ((__CHANNEL__) == TIM_CHANNEL_3) ? ((__HANDLE__)->Instance->CCER &= (uint16_t)~(TIM_CCER_CC3P | TIM_CCER_CC3NP)) :\
 ((__HANDLE__)->Instance->CCER &= (uint16_t)~(TIM_CCER_CC4P | TIM_CCER_CC4NP)))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1702 行定义\&.
.SS "#define TIM_RESET_ICPRESCALERVALUE(__HANDLE__, __CHANNEL__)"
\fB值:\fP
.PP
.nf
(((__CHANNEL__) == TIM_CHANNEL_1) ? ((__HANDLE__)->Instance->CCMR1 &= (uint16_t)~TIM_CCMR1_IC1PSC) :\
 ((__CHANNEL__) == TIM_CHANNEL_2) ? ((__HANDLE__)->Instance->CCMR1 &= (uint16_t)~TIM_CCMR1_IC2PSC) :\
 ((__CHANNEL__) == TIM_CHANNEL_3) ? ((__HANDLE__)->Instance->CCMR2 &= (uint16_t)~TIM_CCMR2_IC3PSC) :\
 ((__HANDLE__)->Instance->CCMR2 &= (uint16_t)~TIM_CCMR2_IC4PSC))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1690 行定义\&.
.SS "#define TIM_SET_CAPTUREPOLARITY(__HANDLE__, __CHANNEL__, __POLARITY__)"
\fB值:\fP
.PP
.nf
(((__CHANNEL__) == TIM_CHANNEL_1) ? ((__HANDLE__)->Instance->CCER |= (__POLARITY__)) :\
 ((__CHANNEL__) == TIM_CHANNEL_2) ? ((__HANDLE__)->Instance->CCER |= ((__POLARITY__) << 4U)) :\
 ((__CHANNEL__) == TIM_CHANNEL_3) ? ((__HANDLE__)->Instance->CCER |= ((__POLARITY__) << 8U)) :\
 ((__HANDLE__)->Instance->CCER |= (((__POLARITY__) << 12U))))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1696 行定义\&.
.SS "#define TIM_SET_ICPRESCALERVALUE(__HANDLE__, __CHANNEL__, __ICPSC__)"
\fB值:\fP
.PP
.nf
(((__CHANNEL__) == TIM_CHANNEL_1) ? ((__HANDLE__)->Instance->CCMR1 |= (__ICPSC__)) :\
 ((__CHANNEL__) == TIM_CHANNEL_2) ? ((__HANDLE__)->Instance->CCMR1 |= ((__ICPSC__) << 8U)) :\
 ((__CHANNEL__) == TIM_CHANNEL_3) ? ((__HANDLE__)->Instance->CCMR2 |= (__ICPSC__)) :\
 ((__HANDLE__)->Instance->CCMR2 |= ((__ICPSC__) << 8U)))
.fi
.PP
在文件 stm32f4xx_hal_tim\&.h 第 1684 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
