.TH "TIMEx_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group2 \- Timer Complementary Output Compare functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OCN_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.in -1c
.SH "详细描述"
.PP 
Timer Complementary Output Compare functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Start (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Start_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel, uint32_t * pData, uint16_t Length)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Start_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Stop (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Stop_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OCN_Stop_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
