.TH "TIMEx_Private_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBTIMEx_DMACommutationCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIMEx_DMACommutationHalfCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "void TIMEx_DMACommutationCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIMEx_DMACommutationHalfCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
