.TH "TIMEx_Exported_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBExtended Timer Hall Sensor functions\fP"
.br
.RI "Timer Hall Sensor functions "
.ti -1c
.RI "\fBExtended Timer Complementary Output Compare functions\fP"
.br
.RI "Timer Complementary Output Compare functions "
.ti -1c
.RI "\fBExtended Timer Complementary PWM functions\fP"
.br
.RI "Timer Complementary PWM functions "
.ti -1c
.RI "\fBExtended Timer Complementary One Pulse functions\fP"
.br
.RI "Timer Complementary One Pulse functions "
.ti -1c
.RI "\fBExtended Peripheral Control functions\fP"
.br
.RI "Peripheral Control functions "
.ti -1c
.RI "\fBExtended Callbacks functions\fP"
.br
.RI "Extended Callbacks functions "
.ti -1c
.RI "\fBExtended Peripheral State functions\fP"
.br
.RI "Extended Peripheral State functions "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
