.TH "TIMEx_Exported_Functions_Group6" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group6 \- Extended Callbacks functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBHAL_TIMEx_CommutCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_CommutHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_BreakCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "详细描述"
.PP 
Extended Callbacks functions 


.SH "函数说明"
.PP 
.SS "void HAL_TIMEx_BreakCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIMEx_CommutCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIMEx_CommutHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
