.TH "TIMEx_Exported_Functions_Group5" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group5 \- Peripheral Control functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_MasterConfigSynchronization\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_MasterConfigTypeDef\fP *sMasterConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigBreakDeadTime\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_BreakDeadTimeConfigTypeDef\fP *sBreakDeadTimeConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_RemapConfig\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Remap)"
.br
.in -1c
.SH "详细描述"
.PP 
Peripheral Control functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigBreakDeadTime (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_BreakDeadTimeConfigTypeDef\fP * sBreakDeadTimeConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_MasterConfigSynchronization (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_MasterConfigTypeDef\fP * sMasterConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_RemapConfig (\fBTIM_HandleTypeDef\fP * htim, uint32_t Remap)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
