.TH "TIMEx_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group1 \- Timer Hall Sensor functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Init\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_HallSensor_InitTypeDef\fP *sConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_DeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_HallSensor_MspInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIMEx_HallSensor_MspDeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_HallSensor_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "详细描述"
.PP 
Timer Hall Sensor functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_DeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Init (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_HallSensor_InitTypeDef\fP * sConfig)"

.SS "void HAL_TIMEx_HallSensor_MspDeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIMEx_HallSensor_MspInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Start (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Start_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t * pData, uint16_t Length)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Start_IT (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Stop (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Stop_DMA (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_HallSensor_Stop_IT (\fBTIM_HandleTypeDef\fP * htim)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
