.TH "TIMEx_Exported_Functions_Group4" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group4 \- Timer Complementary One Pulse functions  

.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_OnePulseN_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.in -1c
.SH "详细描述"
.PP 
Timer Complementary One Pulse functions 


.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OnePulseN_Start (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OnePulseN_Start_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OnePulseN_Stop (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_OnePulseN_Stop_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
