.TH "UART_Private_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUART_IT_MASK\fP   0x0000FFFFU"
.br
.RI "UART interruptions flag mask "
.ti -1c
.RI "#define \fBUART_CR1_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBUART_CR2_REG_INDEX\fP   2U"
.br
.ti -1c
.RI "#define \fBUART_CR3_REG_INDEX\fP   3U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define UART_CR1_REG_INDEX   1U"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 765 行定义\&.
.SS "#define UART_CR2_REG_INDEX   2U"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 766 行定义\&.
.SS "#define UART_CR3_REG_INDEX   3U"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 767 行定义\&.
.SS "#define UART_IT_MASK   0x0000FFFFU"

.PP
UART interruptions flag mask 
.PP
在文件 stm32f4xx_hal_uart\&.h 第 763 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
