.TH "UART_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_UART_Init\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_HalfDuplex_Init\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_LIN_Init\fP (\fBUART_HandleTypeDef\fP *huart, uint32_t BreakDetectLength)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_MultiProcessor_Init\fP (\fBUART_HandleTypeDef\fP *huart, uint8_t Address, uint32_t WakeUpMethod)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_UART_DeInit\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "void \fBHAL_UART_MspInit\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "void \fBHAL_UART_MspDeInit\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_HalfDuplex_Init (\fBUART_HandleTypeDef\fP * huart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_LIN_Init (\fBUART_HandleTypeDef\fP * huart, uint32_t BreakDetectLength)"

.SS "\fBHAL_StatusTypeDef\fP HAL_MultiProcessor_Init (\fBUART_HandleTypeDef\fP * huart, uint8_t Address, uint32_t WakeUpMethod)"

.SS "\fBHAL_StatusTypeDef\fP HAL_UART_DeInit (\fBUART_HandleTypeDef\fP * huart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_UART_Init (\fBUART_HandleTypeDef\fP * huart)"

.SS "void HAL_UART_MspDeInit (\fBUART_HandleTypeDef\fP * huart)"

.SS "void HAL_UART_MspInit (\fBUART_HandleTypeDef\fP * huart)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
