.TH "UART_Exported_Functions_Group4" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Exported_Functions_Group4
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_UART_StateTypeDef\fP \fBHAL_UART_GetState\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "uint32_t \fBHAL_UART_GetError\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_UART_GetError (\fBUART_HandleTypeDef\fP * huart)"

.SS "\fBHAL_UART_StateTypeDef\fP HAL_UART_GetState (\fBUART_HandleTypeDef\fP * huart)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
