.TH "UART_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBUART Error Code\fP"
.br
.ti -1c
.RI "\fBUART Word Length\fP"
.br
.ti -1c
.RI "\fBUART Number of Stop Bits\fP"
.br
.ti -1c
.RI "\fBUART Parity\fP"
.br
.ti -1c
.RI "\fBUART Hardware Flow Control\fP"
.br
.ti -1c
.RI "\fBUART Transfer Mode\fP"
.br
.ti -1c
.RI "\fBUART State\fP"
.br
.ti -1c
.RI "\fBUART Over Sampling\fP"
.br
.ti -1c
.RI "\fBUART LIN Break Detection Length\fP"
.br
.ti -1c
.RI "\fBUART Wakeup Functions\fP"
.br
.ti -1c
.RI "\fBUART FLags\fP"
.br
.RI "Elements values convention: 0xXXXX "
.ti -1c
.RI "\fBUART Interrupt Definitions\fP"
.br
.RI "Elements values convention: 0xY000XXXX "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
