.TH "UART_Hardware_Flow_Control" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Hardware_Flow_Control
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUART_HWCONTROL_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_HWCONTROL_RTS\fP   ((uint32_t)USART_CR3_RTSE)"
.br
.ti -1c
.RI "#define \fBUART_HWCONTROL_CTS\fP   ((uint32_t)USART_CR3_CTSE)"
.br
.ti -1c
.RI "#define \fBUART_HWCONTROL_RTS_CTS\fP   ((uint32_t)(USART_CR3_RTSE | USART_CR3_CTSE))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define UART_HWCONTROL_CTS   ((uint32_t)USART_CR3_CTSE)"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 278 行定义\&.
.SS "#define UART_HWCONTROL_NONE   0x00000000U"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 276 行定义\&.
.SS "#define UART_HWCONTROL_RTS   ((uint32_t)USART_CR3_RTSE)"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 277 行定义\&.
.SS "#define UART_HWCONTROL_RTS_CTS   ((uint32_t)(USART_CR3_RTSE | USART_CR3_CTSE))"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 279 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
