.TH "UART_LIN_Break_Detection_Length" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_LIN_Break_Detection_Length
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUART_LINBREAKDETECTLENGTH_10B\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_LINBREAKDETECTLENGTH_11B\fP   ((uint32_t)USART_CR2_LBDL)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define UART_LINBREAKDETECTLENGTH_10B   0x00000000U"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 315 行定义\&.
.SS "#define UART_LINBREAKDETECTLENGTH_11B   ((uint32_t)USART_CR2_LBDL)"

.PP
在文件 stm32f4xx_hal_uart\&.h 第 316 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
