.TH "USART" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART \- HAL USART Synchronous module driver  

.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBUSART Exported Types\fP"
.br
.ti -1c
.RI "\fBUSART Exported Constants\fP"
.br
.ti -1c
.RI "\fBUSART Exported Macros\fP"
.br
.ti -1c
.RI "\fBUSART Private Constants\fP"
.br
.ti -1c
.RI "\fBUSART Private Macros\fP"
.br
.ti -1c
.RI "\fBUSART Private Functions\fP"
.br
.ti -1c
.RI "\fBUSART_Exported_Functions\fP"
.br
.in -1c
.SH "详细描述"
.PP 
HAL USART Synchronous module driver 


.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
