.TH "USART_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_USART_NACK_STATE\fP(NACK)"
.br
.ti -1c
.RI "#define \fBIS_USART_LASTBIT\fP(LASTBIT)"
.br
.ti -1c
.RI "#define \fBIS_USART_PHASE\fP(CPHA)"
.br
.ti -1c
.RI "#define \fBIS_USART_POLARITY\fP(CPOL)"
.br
.ti -1c
.RI "#define \fBIS_USART_CLOCK\fP(CLOCK)"
.br
.ti -1c
.RI "#define \fBIS_USART_WORD_LENGTH\fP(LENGTH)"
.br
.ti -1c
.RI "#define \fBIS_USART_STOPBITS\fP(STOPBITS)"
.br
.ti -1c
.RI "#define \fBIS_USART_PARITY\fP(PARITY)"
.br
.ti -1c
.RI "#define \fBIS_USART_MODE\fP(MODE)   ((((MODE) & (~((uint32_t)\fBUSART_MODE_TX_RX\fP))) == 0x00U) && ((MODE) != 0x00U))"
.br
.ti -1c
.RI "#define \fBIS_USART_BAUDRATE\fP(BAUDRATE)   ((BAUDRATE) <= 12500000U)"
.br
.ti -1c
.RI "#define \fBUSART_DIV\fP(_PCLK_,  _BAUD_)   (((_PCLK_)*25U)/(2U*(_BAUD_)))"
.br
.ti -1c
.RI "#define \fBUSART_DIVMANT\fP(_PCLK_,  _BAUD_)   (\fBUSART_DIV\fP((_PCLK_), (_BAUD_))/100U)"
.br
.ti -1c
.RI "#define \fBUSART_DIVFRAQ\fP(_PCLK_,  _BAUD_)   (((\fBUSART_DIV\fP((_PCLK_), (_BAUD_)) \- (\fBUSART_DIVMANT\fP((_PCLK_), (_BAUD_)) * 100U)) * 16U + 50U) / 100U)"
.br
.ti -1c
.RI "#define \fBUSART_BRR\fP(_PCLK_,  _BAUD_)   ((\fBUSART_DIVMANT\fP((_PCLK_), (_BAUD_)) << 4U)|(\fBUSART_DIVFRAQ\fP((_PCLK_), (_BAUD_)) & 0x0FU))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_USART_BAUDRATE(BAUDRATE)   ((BAUDRATE) <= 12500000U)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 605 行定义\&.
.SS "#define IS_USART_CLOCK(CLOCK)"
\fB值:\fP
.PP
.nf
                                      (((CLOCK) == USART_CLOCK_DISABLE) || \
                                      ((CLOCK) == USART_CLOCK_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 588 行定义\&.
.SS "#define IS_USART_LASTBIT(LASTBIT)"
\fB值:\fP
.PP
.nf
                                      (((LASTBIT) == USART_LASTBIT_DISABLE) || \
                                      ((LASTBIT) == USART_LASTBIT_ENABLE))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 579 行定义\&.
.SS "#define IS_USART_MODE(MODE)   ((((MODE) & (~((uint32_t)\fBUSART_MODE_TX_RX\fP))) == 0x00U) && ((MODE) != 0x00U))"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 603 行定义\&.
.SS "#define IS_USART_NACK_STATE(NACK)"
\fB值:\fP
.PP
.nf
                                      (((NACK) == USART_NACK_ENABLE) || \
                                      ((NACK) == USART_NACK_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 576 行定义\&.
.SS "#define IS_USART_PARITY(PARITY)"
\fB值:\fP
.PP
.nf
                                      (((PARITY) == USART_PARITY_NONE) || \
                                      ((PARITY) == USART_PARITY_EVEN) || \
                                      ((PARITY) == USART_PARITY_ODD))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 599 行定义\&.
.SS "#define IS_USART_PHASE(CPHA)"
\fB值:\fP
.PP
.nf
                                      (((CPHA) == USART_PHASE_1EDGE) || \
                                      ((CPHA) == USART_PHASE_2EDGE))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 582 行定义\&.
.SS "#define IS_USART_POLARITY(CPOL)"
\fB值:\fP
.PP
.nf
                                      (((CPOL) == USART_POLARITY_LOW) || \
                                      ((CPOL) == USART_POLARITY_HIGH))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 585 行定义\&.
.SS "#define IS_USART_STOPBITS(STOPBITS)"
\fB值:\fP
.PP
.nf
                                      (((STOPBITS) == USART_STOPBITS_1) || \
                                      ((STOPBITS) == USART_STOPBITS_0_5) || \
                                      ((STOPBITS) == USART_STOPBITS_1_5) || \
                                      ((STOPBITS) == USART_STOPBITS_2))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 594 行定义\&.
.SS "#define IS_USART_WORD_LENGTH(LENGTH)"
\fB值:\fP
.PP
.nf
                                      (((LENGTH) == USART_WORDLENGTH_8B) || \
                                      ((LENGTH) == USART_WORDLENGTH_9B))
.fi
.PP
在文件 stm32f4xx_hal_usart\&.h 第 591 行定义\&.
.SS "#define USART_BRR(_PCLK_, _BAUD_)   ((\fBUSART_DIVMANT\fP((_PCLK_), (_BAUD_)) << 4U)|(\fBUSART_DIVFRAQ\fP((_PCLK_), (_BAUD_)) & 0x0FU))"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 613 行定义\&.
.SS "#define USART_DIV(_PCLK_, _BAUD_)   (((_PCLK_)*25U)/(2U*(_BAUD_)))"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 607 行定义\&.
.SS "#define USART_DIVFRAQ(_PCLK_, _BAUD_)   (((\fBUSART_DIV\fP((_PCLK_), (_BAUD_)) \- (\fBUSART_DIVMANT\fP((_PCLK_), (_BAUD_)) * 100U)) * 16U + 50U) / 100U)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 611 行定义\&.
.SS "#define USART_DIVMANT(_PCLK_, _BAUD_)   (\fBUSART_DIV\fP((_PCLK_), (_BAUD_))/100U)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 609 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
