.TH "USART_Error_Code" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Error_Code \- USART Error Code  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBHAL_USART_ERROR_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_USART_ERROR_PE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBHAL_USART_ERROR_NE\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBHAL_USART_ERROR_FE\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBHAL_USART_ERROR_ORE\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBHAL_USART_ERROR_DMA\fP   0x00000010U"
.br
.in -1c
.SH "详细描述"
.PP 
USART Error Code 


.SH "宏定义说明"
.PP 
.SS "#define HAL_USART_ERROR_DMA   0x00000010U"
DMA transfer error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 187 行定义\&.
.SS "#define HAL_USART_ERROR_FE   0x00000004U"
Frame error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 185 行定义\&.
.SS "#define HAL_USART_ERROR_NE   0x00000002U"
Noise error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 184 行定义\&.
.SS "#define HAL_USART_ERROR_NONE   0x00000000U"
No error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 182 行定义\&.
.SS "#define HAL_USART_ERROR_ORE   0x00000008U"
Overrun error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 186 行定义\&.
.SS "#define HAL_USART_ERROR_PE   0x00000001U"
Parity error 
.br
 
.PP
在文件 stm32f4xx_hal_usart\&.h 第 183 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
