.TH "USART_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBUSART Error Code\fP"
.br
.RI "USART Error Code "
.ti -1c
.RI "\fBUSART Word Length\fP"
.br
.ti -1c
.RI "\fBUSART Number of Stop Bits\fP"
.br
.ti -1c
.RI "\fBUSART Parity\fP"
.br
.ti -1c
.RI "\fBUSART Mode\fP"
.br
.ti -1c
.RI "\fBUSART Clock\fP"
.br
.ti -1c
.RI "\fBUSART Clock Polarity\fP"
.br
.ti -1c
.RI "\fBUSART Clock Phase\fP"
.br
.ti -1c
.RI "\fBUSART Last Bit\fP"
.br
.ti -1c
.RI "\fBUSART NACK State\fP"
.br
.ti -1c
.RI "\fBUSART Flags\fP"
.br
.RI "Elements values convention: 0xXXXX "
.ti -1c
.RI "\fBUSART Interrupts Definition\fP"
.br
.RI "Elements values convention: 0xY000XXXX "
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
