.TH "USART_Exported_Functions_Group1" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Init\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_DeInit\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_MspInit\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_MspDeInit\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_USART_DeInit (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Init (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_MspDeInit (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_MspInit (\fBUSART_HandleTypeDef\fP * husart)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
