.TH "USART_Exported_Functions_Group2" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Transmit\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Receive\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pRxData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_TransmitReceive\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size, uint32_t Timeout)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Transmit_IT\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Receive_IT\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pRxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_TransmitReceive_IT\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Transmit_DMA\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Receive_DMA\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pRxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_TransmitReceive_DMA\fP (\fBUSART_HandleTypeDef\fP *husart, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_DMAPause\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_DMAResume\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_DMAStop\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Abort\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_USART_Abort_IT\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_IRQHandler\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_TxCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_TxHalfCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_RxCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_RxHalfCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_TxRxCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_ErrorCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "void \fBHAL_USART_AbortCpltCallback\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Abort (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Abort_IT (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_AbortCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_DMAPause (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_DMAResume (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_DMAStop (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_ErrorCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_IRQHandler (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Receive (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pRxData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Receive_DMA (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pRxData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Receive_IT (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pRxData, uint16_t Size)"

.SS "void HAL_USART_RxCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_RxHalfCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Transmit (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Transmit_DMA (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_Transmit_IT (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_TransmitReceive (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size, uint32_t Timeout)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_TransmitReceive_DMA (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size)"

.SS "\fBHAL_StatusTypeDef\fP HAL_USART_TransmitReceive_IT (\fBUSART_HandleTypeDef\fP * husart, uint8_t * pTxData, uint8_t * pRxData, uint16_t Size)"

.SS "void HAL_USART_TxCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_TxHalfCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SS "void HAL_USART_TxRxCpltCallback (\fBUSART_HandleTypeDef\fP * husart)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
