.TH "USART_Exported_Functions_Group3" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBHAL_USART_StateTypeDef\fP \fBHAL_USART_GetState\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.ti -1c
.RI "uint32_t \fBHAL_USART_GetError\fP (\fBUSART_HandleTypeDef\fP *husart)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "uint32_t HAL_USART_GetError (\fBUSART_HandleTypeDef\fP * husart)"

.SS "\fBHAL_USART_StateTypeDef\fP HAL_USART_GetState (\fBUSART_HandleTypeDef\fP * husart)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
