.TH "USART_Stop_Bits" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Stop_Bits
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUSART_STOPBITS_1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUSART_STOPBITS_0_5\fP   ((uint32_t)USART_CR2_STOP_0)"
.br
.ti -1c
.RI "#define \fBUSART_STOPBITS_2\fP   ((uint32_t)USART_CR2_STOP_1)"
.br
.ti -1c
.RI "#define \fBUSART_STOPBITS_1_5\fP   ((uint32_t)(USART_CR2_STOP_0 | USART_CR2_STOP_1))"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define USART_STOPBITS_0_5   ((uint32_t)USART_CR2_STOP_0)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 208 行定义\&.
.SS "#define USART_STOPBITS_1   0x00000000U"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 207 行定义\&.
.SS "#define USART_STOPBITS_1_5   ((uint32_t)(USART_CR2_STOP_0 | USART_CR2_STOP_1))"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 210 行定义\&.
.SS "#define USART_STOPBITS_2   ((uint32_t)USART_CR2_STOP_1)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 209 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
