.TH "USART_Word_Length" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_Word_Length
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBUSART_WORDLENGTH_8B\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUSART_WORDLENGTH_9B\fP   ((uint32_t)USART_CR1_M)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define USART_WORDLENGTH_8B   0x00000000U"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 198 行定义\&.
.SS "#define USART_WORDLENGTH_9B   ((uint32_t)USART_CR1_M)"

.PP
在文件 stm32f4xx_hal_usart\&.h 第 199 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
