.TH "UTILS_LL_Private_Functions" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILS_LL_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "static uint32_t \fBUTILS_GetPLLOutputFrequency\fP (uint32_t PLL_InputFrequency, \fBLL_UTILS_PLLInitTypeDef\fP *UTILS_PLLInitStruct)"
.br
.RI "Function to check that PLL can be modified "
.ti -1c
.RI "static ErrorStatus \fBUTILS_SetFlashLatency\fP (uint32_t HCLK_Frequency)"
.br
.RI "Update number of Flash wait states in line with new frequency and current voltage range\&. "
.ti -1c
.RI "static ErrorStatus \fBUTILS_EnablePLLAndSwitchSystem\fP (uint32_t SYSCLK_Frequency, \fBLL_UTILS_ClkInitTypeDef\fP *UTILS_ClkInitStruct)"
.br
.RI "Function to enable PLL and switch system clock to PLL "
.ti -1c
.RI "static ErrorStatus \fBUTILS_PLL_IsBusy\fP (void)"
.br
.RI "Function to check that PLL can be modified "
.in -1c
.SH "详细描述"
.PP 

.SH "函数说明"
.PP 
.SS "static ErrorStatus UTILS_EnablePLLAndSwitchSystem (uint32_t SYSCLK_Frequency, \fBLL_UTILS_ClkInitTypeDef\fP * UTILS_ClkInitStruct)\fC [static]\fP"

.PP
Function to enable PLL and switch system clock to PLL 
.PP
\fB参数\fP
.RS 4
\fISYSCLK_Frequency\fP SYSCLK frequency 
.br
\fIUTILS_ClkInitStruct\fP pointer to a \fBLL_UTILS_ClkInitTypeDef\fP structure that contains the configuration information for the BUS prescalers\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fIAn\fP ErrorStatus enumeration value:
.IP "\(bu" 2
SUCCESS: No problem to switch system to PLL
.IP "\(bu" 2
ERROR: Problem to switch system to PLL 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_ll_utils\&.c 第 670 行定义\&.
.SS "static uint32_t UTILS_GetPLLOutputFrequency (uint32_t PLL_InputFrequency, \fBLL_UTILS_PLLInitTypeDef\fP * UTILS_PLLInitStruct)\fC [static]\fP"

.PP
Function to check that PLL can be modified 
.PP
\fB参数\fP
.RS 4
\fIPLL_InputFrequency\fP PLL input frequency (in Hz) 
.br
\fIUTILS_PLLInitStruct\fP pointer to a \fBLL_UTILS_PLLInitTypeDef\fP structure that contains the configuration information for the PLL\&. 
.RE
.PP
\fB返回值\fP
.RS 4
\fIPLL\fP output frequency (in Hz) 
.RE
.PP

.PP
在文件 stm32f4xx_ll_utils\&.c 第 600 行定义\&.
.SS "static ErrorStatus UTILS_PLL_IsBusy (void)\fC [static]\fP"

.PP
Function to check that PLL can be modified 
.PP
\fB返回值\fP
.RS 4
\fIAn\fP ErrorStatus enumeration value:
.IP "\(bu" 2
SUCCESS: PLL modification can be done
.IP "\(bu" 2
ERROR: PLL is busy 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_ll_utils\&.c 第 631 行定义\&.
.SS "static ErrorStatus UTILS_SetFlashLatency (uint32_t HCLK_Frequency)\fC [static]\fP"

.PP
Update number of Flash wait states in line with new frequency and current voltage range\&. 
.PP
\fB注解\fP
.RS 4
This Function support ONLY devices with supply voltage (voltage range) between 2\&.7V and 3\&.6V 
.RE
.PP
\fB参数\fP
.RS 4
\fIHCLK_Frequency\fP HCLK frequency 
.RE
.PP
\fB返回值\fP
.RS 4
\fIAn\fP ErrorStatus enumeration value:
.IP "\(bu" 2
SUCCESS: Latency has been modified
.IP "\(bu" 2
ERROR: Latency cannot be modified 
.PP
.RE
.PP

.PP
在文件 stm32f4xx_ll_utils\&.c 第 477 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
