.TH "UTILS_EC_HSE_BYPASS" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILS_EC_HSE_BYPASS
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBLL_UTILS_HSEBYPASS_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBLL_UTILS_HSEBYPASS_ON\fP   0x00000001U"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define LL_UTILS_HSEBYPASS_OFF   0x00000000U"
HSE Bypass is not enabled 
.br
 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 155 行定义\&.
.SS "#define LL_UTILS_HSEBYPASS_ON   0x00000001U"
HSE Bypass is enabled 
.br
 
.PP
在文件 stm32f4xx_ll_utils\&.h 第 156 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
