.TH "WWDG_Flag_definition" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_Flag_definition \- WWDG Flag definition  

.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBWWDG_FLAG_EWIF\fP   WWDG_SR_EWIF"
.br
.in -1c
.SH "详细描述"
.PP 
WWDG Flag definition 


.SH "宏定义说明"
.PP 
.SS "#define WWDG_FLAG_EWIF   WWDG_SR_EWIF"
Early wakeup interrupt flag 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 123 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
