.TH "WWDG_Private_Macros" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBIS_WWDG_PRESCALER\fP(__PRESCALER__)"
.br
.ti -1c
.RI "#define \fBIS_WWDG_WINDOW\fP(__WINDOW__)   (((__WINDOW__) >= WWDG_CFR_W_6) && ((__WINDOW__) <= WWDG_CFR_W))"
.br
.ti -1c
.RI "#define \fBIS_WWDG_COUNTER\fP(__COUNTER__)   (((__COUNTER__) >= WWDG_CR_T_6) && ((__COUNTER__) <= WWDG_CR_T))"
.br
.ti -1c
.RI "#define \fBIS_WWDG_EWI_MODE\fP(__MODE__)"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "宏定义说明"
.PP 
.SS "#define IS_WWDG_COUNTER(__COUNTER__)   (((__COUNTER__) >= WWDG_CR_T_6) && ((__COUNTER__) <= WWDG_CR_T))"

.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 164 行定义\&.
.SS "#define IS_WWDG_EWI_MODE(__MODE__)"
\fB值:\fP
.PP
.nf
                                             (((__MODE__) == WWDG_EWI_ENABLE) || \
                                             ((__MODE__) == WWDG_EWI_DISABLE))
.fi
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 166 行定义\&.
.SS "#define IS_WWDG_PRESCALER(__PRESCALER__)"
\fB值:\fP
.PP
.nf
                                             (((__PRESCALER__) == WWDG_PRESCALER_1)  || \
                                             ((__PRESCALER__) == WWDG_PRESCALER_2)  || \
                                             ((__PRESCALER__) == WWDG_PRESCALER_4)  || \
                                             ((__PRESCALER__) == WWDG_PRESCALER_8))
.fi
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 157 行定义\&.
.SS "#define IS_WWDG_WINDOW(__WINDOW__)   (((__WINDOW__) >= WWDG_CFR_W_6) && ((__WINDOW__) <= WWDG_CFR_W))"

.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 162 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
