.TH "WWDG_Exported_Constants" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "模块"

.in +1c
.ti -1c
.RI "\fBWWDG Interrupt definition\fP"
.br
.ti -1c
.RI "\fBWWDG Flag definition\fP"
.br
.RI "WWDG Flag definition "
.ti -1c
.RI "\fBWWDG Prescaler\fP"
.br
.ti -1c
.RI "\fBWWDG Early Wakeup Interrupt Mode\fP"
.br
.in -1c
.SH "详细描述"
.PP 

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
