.TH "WWDG_HandleTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_HandleTypeDef \- WWDG handle Structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_wwdg\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "WWDG_TypeDef * \fBInstance\fP"
.br
.ti -1c
.RI "\fBWWDG_InitTypeDef\fP \fBInit\fP"
.br
.in -1c
.SH "详细描述"
.PP 
WWDG handle Structure definition 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 70 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBWWDG_InitTypeDef\fP Init"
WWDG required parameters 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 75 行定义\&.
.SS "WWDG_TypeDef* Instance"
Register base address 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 73 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
