.TH "WWDG_InitTypeDef" 3 "2020年 八月 7日 星期五" "Version 1.24.0" "STM32F4_HAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_InitTypeDef \- WWDG Init structure definition  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f4xx_hal_wwdg\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "uint32_t \fBPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBWindow\fP"
.br
.ti -1c
.RI "uint32_t \fBCounter\fP"
.br
.ti -1c
.RI "uint32_t \fBEWIMode\fP"
.br
.in -1c
.SH "详细描述"
.PP 
WWDG Init structure definition 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 48 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "uint32_t Counter"
Specifies the WWDG free-running downcounter value\&. This parameter must be a number between Min_Data = 0x40 and Max_Data = 0x7F 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 56 行定义\&.
.SS "uint32_t EWIMode"
Specifies if WWDG Early Wakeup Interupt is enable or not\&. This parameter can be a value of \fBWWDG Early Wakeup Interrupt Mode\fP 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 59 行定义\&.
.SS "uint32_t Prescaler"
Specifies the prescaler value of the WWDG\&. This parameter can be a value of \fBWWDG Prescaler\fP 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 50 行定义\&.
.SS "uint32_t Window"
Specifies the WWDG window value to be compared to the downcounter\&. This parameter must be a number Min_Data = 0x40 and Max_Data = 0x7F 
.PP
在文件 stm32f4xx_hal_wwdg\&.h 第 53 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 STM32F4_HAL 的 源代码自动生成\&.
